### ISSUE TITLE
save index error on hg38.fa

### ISSUE THREAD

**Issue by zhaoyanswill** [seqan/seqan#1006]
Hi,

I tried to build FMIndex on hg38.fa and crashed after about 8 hours. The code worked well on chr21.fa. The error message is show below:

```
./a.out hg38.fa > haha 
Asynchronous I/O operation failed (waitFor with timeOut=0ms): "Success"
fildes:  4
buffer:  7fd34449c000
offset:  ae0000000
nbytes:  4000000
event:   1
Raddr:   0x1492458
/u/yongzhao/include/seqan/file/file_page.h:842 FAILED!  (WRITING operation could not be completed: "Success")
Aborted (core dumped)
```

My code is here

```c++
#include <iostream>
#include <chrono>

#include <seqan/seq_io.h>
#include <seqan/sequence.h>
#include <seqan/file.h>
#include <seqan/index.h>
#include <seqan/find.h>


using namespace std;
using namespace std::chrono;
using namespace seqan;


int build(string s)
{
	cout << "beg of build" << endl;

	auto t1 = high_resolution_clock::now();
	SeqFileIn seqIn;
	if (!open(seqIn, s.c_str(), OPEN_RDONLY))
	{
		cerr << "ERROR: could not open the file" << endl;
		return 1;
	}

	StringSet<CharString> ids;
	StringSet<Dna5String> seqs;
	try
	{
		readRecords(ids, seqs, seqIn);
	}
	catch (const Exception& e)
	{
		cerr << "ERROR: " << e.what() << endl;
		return 1;
	}
	close(seqIn);
	cout << "read in " << duration_cast<chrono::seconds>(high_resolution_clock::now()-t1).count() << endl;

	t1 = high_resolution_clock::now();
	Index<StringSet<Dna5String>, FMIndex<> > index(seqs);
	indexCreate(index);
	cout << "index in " << duration_cast<chrono::seconds>(high_resolution_clock::now()-t1).count() << endl;

	t1 = high_resolution_clock::now();
	s += ".fm";
	save(index, s.c_str());
	cout << "save in " << duration_cast<chrono::seconds>(high_resolution_clock::now()-t1).count() << endl;

	reverseComplement(seqs);

	t1 = high_resolution_clock::now();
	Index<StringSet<Dna5String>, FMIndex<> > indexRc(seqs);
	indexCreate(indexRc);
	cout << "rc index in " << duration_cast<chrono::seconds>(high_resolution_clock::now()-t1).count() << endl;

	t1 = high_resolution_clock::now();
	s += ".rc";
	save(indexRc, s.c_str());
	cout << "rc save in " << duration_cast<chrono::seconds>(high_resolution_clock::now()-t1).count() << endl;

	cout << "end of build" << endl;

	return 0;
}


int load(string s)
{
	cout << "beg of load" << endl;

	auto t1 = high_resolution_clock::now();
	s += ".fm";
	Index<StringSet<Dna5String>, FMIndex<> > index;
	open(index, s.c_str());
	cout << "load in " << duration_cast<chrono::seconds>(high_resolution_clock::now()-t1).count() << endl;

	Finder<Index<StringSet<Dna5String>, FMIndex<> > > finder(index);
	while (find(finder, "AAAAAAAAAAAAAAAAAAAAA"))
	{
		cout << position(finder) << endl;
	}

	t1 = high_resolution_clock::now();
	s += ".rc";
	Index<StringSet<Dna5String>, FMIndex<> > indexRc;
	open(indexRc, s.c_str());
	cout << "rc load in " << duration_cast<chrono::seconds>(high_resolution_clock::now()-t1).count() << endl;

	Finder<Index<StringSet<Dna5String>, FMIndex<> > > finderRc(indexRc);
	while (find(finderRc, "AAAAAAAAAAAAAAAAAAAAA"))
	{
		cout << position(finderRc) << endl;
	}

	cout << "end of load" << endl;

	return 0;
}

int main(int argc, char** argv)
{
	build(argv[1]);
	load(argv[1]);
}
```

**Comment by esiragusa** [comment]
Hi,

The error means that you are running out of space. You need to set the environment variable TMPDIR to a folder that can hold a lot of temporary data (up to ~20x the size of the input sequence). For example you can use the same folder of the output file argv[1].

Enrico

**Comment by zhaoyanswill** [comment]
Hi Enrico,

I tried to export TMPDIR=/tmp and still got the error:

$ ./index chr21.fa > haha
$ vi haha
$ time ./index hg38.fa > haha
Asynchronous I/O operation failed (waitFor with timeOut=0ms): "Success"
fildes:  4
buffer:  7f34e54f8000
offset:  adc000000
nbytes:  4000000
event:   1
Raddr:   0x10337b0
/u/yongzhao/include/seqan/file/file_page.h:842 FAILED!  (WRITING 
operation could not be completed: "Success")
Aborted (core dumped)

real    158m29.793s
user    150m0.509s
sys    15m4.599s
$ echo $TMPDIR
/tmp


Please let me know how to fix it! Thanks!

Sincerely,
Y. Z.

**Comment by zhaoyanswill** [comment]
Hi,

BTW, there is 2.4T available on our server. Thanks!

Sincerely,
Y. Z.

**Comment by esiragusa** [comment]
Do you have 2.4T on the /tmp folder? Could you please check with ```df -h```?

**Comment by zhaoyanswill** [comment]
$ df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/sda4             366G  174G  174G  51% /
tmpfs                 127G  4.0K  127G   1% /dev/shm
/dev/sda2             194M  111M   73M  61% /boot
/dev/sda1              50M  260K   50M   1% /boot/efi
/dev/sdb1              27T   25T  2.4T  92% /home

Sincerely,
Y. Z.

**Comment by esiragusa** [comment]
You only have 174G...

**Comment by zhaoyanswill** [comment]
I firstly tried it in my working directory which has 2.4T. It failed.

Sincerely,
Y. Z.

**Comment by zhaoyanswill** [comment]
The size of hg38.fa is 3.1G bytes. So if the size of temp file is 20X 
than that of the input file, it's less 70G. The /tmp has enough space 
for the temp file as well.

Sincerely,
Y. Z.

**Comment by h-2** [comment]
The factor for required disk space might actually be a lot bigger. more like 30x and this only if you are using 32bit position types. By default you will be using 64bit position types, which could double the factor. Please see http://seqan.readthedocs.org/en/master/Tutorial/Indices.html?highlight=index#sa-fibre on how to change the size of the position type and/or use a temporary directory with more free space, e.g. create ``$HOME/tmp`` and use that.
There are also other suffix array / fm-index construction algorithms (that require no disk space but more RAM instead), but they are not trivial to use.

**Comment by zhaoyanswill** [comment]
Hi,

Even 30X for the factor and 2X for the overhead of 64bits, hg38.fa 
results in less than 200G. I'm able to write files of that size. Is 
there any other reasons I might miss? Thanks!

Sincerely,
Y. Z.

**Comment by h-2** [comment]
Hm, if we assume `3.1G * 30 * 2 = 186GB`, so /tmp wouldn't be enough, but you said you tried in /home... 
Can you try monitoring all disks while running your application, e.g. run `df` in a loop every second until the program crashes? Then we could exclude disk problems...

**Comment by rrahn** [comment]
I close this for now.
@zhaoyanswill if you still have some problems or any updates on this problem please reopen.
