### ISSUE TITLE
BAM IO test failure

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1008]
One of the BAM IO tests fails with:
`Uncaught exception of type std::ios_base::failure: BGZF block too short.` (gcc)
and 
`Terminating due to uncaught exception 0x805c10020 of type std::__1::ios_base::failure
Attempting to rethrow an exception that doesn't exist!
Attempting to rethrow an exception that doesn't exist!
...` (clang)

This happes **always** on FreeBSD and randomly (not often) on Linux (especially on Travis). See current cdash for more details.

**Comment by esiragusa** [comment]
Fixed by #1053 #1054.

**Comment by rrahn** [comment]
This is not completely

**Comment by rrahn** [comment]
I postpone this to when we have actual freeBSD support.

**Comment by h-2** [comment]
we do have actual freebsd support, this is the only remaining os-specific problem and I want to update the offical FreeBSD port to 2.x (http://www.freshports.org/biology/seqan).

**Comment by h-2** [comment]
@rrahn if possible change the file in the nightlies before 2.1.1 and move fixing the real problem to later. Thanks!

**Comment by h-2** [comment]
fixed via #1791
