### ISSUE TITLE
save infix of const String to infix variable

### ISSUE THREAD

**Issue by kaktus42** [seqan/seqan#1009]
on dev branch.

```
seqan::Infix<TBarcodeString>::Type referenceIfx =
         infix(representative(indexIt),
               parentRepLength(indexIt) + 1,
               endPos);
```

throws compiling error:

```
--------- shortened ---------
/opt/seqan/seqan-src/include/seqan/sequence/segment_infix.h:135:42:
error: invalid conversion from
‘seqan::Pointer_<const TBarcodeString::Type {aka const TBarcodeString*}’ to
‘seqan::Pointer_<TBarcodeString>::Type {aka TBarcodeString*}’
[-fpermissive]
         data_host(_toPointer(host(_other))),

--------- original ---------
/opt/seqan/seqan-src/include/seqan/sequence/segment_infix.h:135:42: error: invalid conversion from ‘seqan::Pointer_<const seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<> > >::Type {aka const seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<> >*}’ to ‘seqan::Pointer_<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<> > >::Type {aka seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<> >*}’ [-fpermissive]
         data_host(_toPointer(host(_other))),
```

with

```
typedef seqan::Dna5String TBarcodeString
typedef seqan::StringSet<TBarcodeString> TBarcodeSet
typedef seqan::Index<TBarcodeSet> TBarcodeIndex
seqan::Iterator<TBarcodeIndex, seqan::TopDown<ParentLinks<> > >::Type indexIt
unsigned endPos
```

Shouldn't this work properly?

**Comment by esiragusa** [comment]
Should be:
```
seqan::Infix<TBarcodeString const>::Type referenceIfx = ...
```

If you have C++11 you can do:
```
auto referenceIfx = ...
```

**Comment by kaktus42** [comment]
That indeed works...
Thank you!

A question to this auto feature:
What is better style? Write out the Type or use auto?

**Comment by esiragusa** [comment]
Hmm hard to say in general. In this case I would prefer auto. Seems to me that auto is always convenient whenever a return type is generic, as you spare computing it through a metafunction.

**Comment by h-2** [comment]
> A question to this auto feature:
> What is better style? Write out the Type or use auto?

We don't have a policy on this in SeqAn, yet. I recommend to never use auto, unless
  * the inferred type is obvious **and**
  * it improves readability of the code

So in your example it would be ok, because it is clear that the `infix()` function returns an infix and the Metafunction just makes it harder to read.

**Comment by esiragusa** [comment]
Hmm what's your definition of obvious?

Wouldn't you do:
```
auto repr = representative(indexIt)
```

This also returns an infix but it's not so obvious (infix of the const text on which the iterator's index is based on). Indeed that's why @kaktus42 got a problem.

**Comment by h-2** [comment]
> Hmm what's your definition of obvious?

There is a trade-off between verbosity and readability, and there are benefits to both, it's definitely something we should discuss. It also depends on the documentation of said function...

For function return values this will also be relevant. And since cxx14, there is also `decltype(auto)`.
