### ISSUE TITLE
install target for headers?

### ISSUE THREAD

**Issue by kotoroshinoto** [seqan/seqan#1015]
I noticed that tophat is packaging an old version of seqan (1.3), which now has a problem compiling under gcc 5.1.

I was hoping to see if I could attempt to develop a pull request for tophat that would find seqan installed or staged through its makefile to either a system prefix or custom prefix (make instlal prefix=/path etc), and update it to use seqan 2.0 properly as I did so.

I noted that seqan's makefile doesn't install ANY headers. Was tophat actually following recommended procedure by packaging their copy of seqan-1.3 in with their source tree, or was this just overlooked as a possibility?

(it'd be nice if there was a pkg-config setup as well, for easier discovery using configure scripts, but it'd probably be sufficient to add the include paths to environmental variables and let the compilers find them, since your project doesn't seem to create shared libraries.)

**Comment by h-2** [comment]
There are different targets for installing the headers and the apps, please see #954.

**Comment by kotoroshinoto** [comment]
thank you for the response. I suspected something like that might be the case.

**Comment by rrahn** [comment]
I close this as it seems to be resolved.
@kotoroshinoto please reopen if something is missing.
