### ISSUE TITLE
Razers3 segmentation fault in 'estimatePigeonholeLosses()'

### ISSUE THREAD

**Issue by gui11aume** [seqan/seqan#1016]
To reproduce the bug, create a file called seq.fasta containing the following sequence.

<pre>
>seq
GATGTAGCGCGATTAGCCTGAAAATGCGAGTACGGCGCGAAT
</pre>

Then call razers3 with `./razers3 -i 69 dummy.fasta seq.fasta` where `dummy.fasta` can be anything. For instance

<pre>
>genome
ACTGTGATGCTGATCGAGCT
</pre>

The error occurs in the function `estimatePigeonholeLosses()` in file `razers.h` at line 2645, most likely because the value of `stepSize` is 4294967295.

**Comment by h-2** [comment]
we recommend to use the yara read mapper instead.
