### ISSUE TITLE
Razers3 segmentation fault in 'windowFindBegin()'

### ISSUE THREAD

**Issue by gui11aume** [seqan/seqan#1017]
To reproduce the bug, create a file called seq.fasta containing the following sequence.

<pre>
>seq
GATGTAGCGCGATTAGCCTGAAAATGCGAGTACGGCGCGAAT
</pre>

Then call razers3 with `./razers3 -i 66 seq.fasta seq.fasta`. Razers3 crashes with the error message below.
<pre>
ERROR: windowFindBegin() failed in thread 0
*** Error in `./razers3': free(): invalid pointer: 0x0000000002c05350 ***
Aborted (core dumped)
</pre>

**Comment by h-2** [comment]
we recommend to use the yara read mapper instead.
