### ISSUE TITLE
use SeqAn for a project

### ISSUE THREAD

**Issue by Ccile13** [seqan/seqan#1031]
Hi
Sorry if I'm in the wrong place and my poor English.

I want to use SeqAn and I followed the instructions of Getting Started and Integration with your own Build System. But when I want to try the example, I have a huge message with four errors as "seqan/seqan-src/include/seqan/sequence/string_base.h:2009: error: 'directionIterator' was not declared in this scope"
 
What can I do ? Is the problem come from me ?
Thanks a lot !

**Comment by Ccile13** [comment]
Sorry I forgot to tell that the computer I used is Linux Ubuntu 32bits (and I don't know how to edit the question)
Thanks again

**Comment by Ccile13** [comment]
Sorry I found the solution here https://github.com/seqan/seqan/issues/926

**Comment by esiragusa** [comment]
Hi. I created a hotfix in #1032. Thanks for reporting the problem and for resurrecting #926 too!
