### ISSUE TITLE
Language entity type "int x" should be named "var"

### ISSUE THREAD

**Issue by bkahlert** [seqan/seqan#1034]
In the documentation, so called language entity types are prefixed with an ideogramm. E.g. classes are prefixed with "Class" and interface meta functions are prefixed with "#Fn".
The current prefix for variables is "int x", which can be misleading if a text is about a variable with a different name. Therefore variables should use the ideogram/prefix "var".

**Comment by h-2** [comment]
Can you create a pull request for this? You probably know best...
