### ISSUE TITLE
VirtualStream adds wrong file extensions like .fasta.bam

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1037]
I am confused about our file extensions. getFileExtensions actually generates `.fasta.bam` for me, just because there is bz2 on the system. Obviously I do want `.fasta.bz2`, but I don't want `.fasta.bam`.
`.bam` should be part of the BAM definition -- which it also is. Why is this the case and how can we change it?

Also, why are the other fasta extensions deactivated? They are quite common.

**Comment by h-2** [comment]
Also `.z` is the extension for compress (LZW) and not for Gzip, and `.bz` ist the first bzip version which is patented and not compatible with bzip2. IMHO the only valid gzip extension should be `.gz` and the only valid bzip2 extension should be `.bz2`. If for some reason we want to read tarballs we can also add `.tgz` and `.tbz`, but I don't see the necessity right now.

**Comment by h-2** [comment]
If no one objects until tomorrow noon, I will create a pull that 
  * removes extensions from gzip and bzip2 that are not used normally; and
  * adds the fasta extensions back again

**Comment by esiragusa** [comment]
:+1: for removing extensions:
* .z https://github.com/seqan/seqan/blob/aedd69b4507649ef17fa8381442efe31d2d17c6f/include/seqan/stream/stream_base.h#L131
* .bz https://github.com/seqan/seqan/blob/aedd69b4507649ef17fa8381442efe31d2d17c6f/include/seqan/stream/stream_base.h#L161

To remove fasta.bam and fasta.bzgf you should remove BgzfFile from the list CompressedFileTypes used by SeqFile's VirtualStream. See:
* CompressedFileTypes https://github.com/seqan/seqan/blob/aedd69b4507649ef17fa8381442efe31d2d17c6f/include/seqan/stream/virtual_stream.h#L71
* FileFormat https://github.com/seqan/seqan/blob/aedd69b4507649ef17fa8381442efe31d2d17c6f/include/seqan/stream/virtual_stream.h#L318

What do you mean by "adds the fasta extensions back again"?

**Comment by h-2** [comment]
@esiragusa Please review the pull request once tests pass, thanks!

> What do you mean by "adds the fasta extensions back again"?
see b5c27b00d636517789b9428402f920f9cbf4f7b8

**Comment by h-2** [comment]
@temehi  we can discuss this together..
