### ISSUE TITLE
Support pkg-config for build dependency discovery

### ISSUE THREAD

**Issue by SoapZA** [seqan/seqan#1042]
Dear Seqan maintainers,
being aware of your support for CMake and integration of Seqan into CMake-based build systems, I would like to suggest adding pkg-config .pc files as a more general way to discover dependencies. While I am fully aware of your FindSeqAn.cmake module, this only works in conjunction with CMake and not other build systems such as the Autotools or plain Makefiles, whereas pkg-config based dependency discovery is build system agnostic. A good example of a clean .pc file is given by x265:
https://bitbucket.org/multicoreware/x265/src/46152345eb6ff261fd90272f7a0712300d6324c0/source/x265.pc.in?at=default
Thanks for considering my proposal

**Comment by wookietreiber** [comment]
:+1:

**Comment by rrahn** [comment]
Thanks for suggesting this enhancement. We are planning to apply some structural changes to the library in the future and will consider and discuss additional ways to include SeqAn in your own build system.

**Comment by SoapZA** [comment]
I have now integrated pkg-config support myself, please see whether you can merge my changes at
https://github.com/seqan/seqan/pull/1069

**Comment by h-2** [comment]
implemented in #1316

**Comment by g-braeunlich** [comment]
Ok, I will have a look at this.
Could you close the corresponding bug: https://bugs.gentoo.org/show_bug.cgi?id=588148 ?
