### ISSUE TITLE
SeqAn version macros in branches

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1048]
should be adapted always immediately after branching and not before release, i.e. SEQAN_VERSION_STRING in current master should be `2.0.1` and in develop it should be `2.1.0` (or something like `2.0.90`. Right now they are all 2.0.0.

This should both be fixed in the current trees and we should add a note to our release manual (..cough..).

**Comment by esiragusa** [comment]
That's listed in our Trello card for SeqAn Releases: https://trello.com/c/1xQjpev1/30-seqan-release

**Comment by esiragusa** [comment]
Done in bfe6e83 and 6af9c5a.
