### ISSUE TITLE
Build jobs on travis

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1059]
Right now we are using 6 / 4 threads on travis for building:
https://github.com/seqan/seqan/blob/master/util/travis/linux-cibuild.cmake
But since we only have two cores anyway...
http://docs.travis-ci.com/user/ci-environment/
... we might as well only use two threads. Maybe then we don't run out of RAM so often as well.

**Comment by esiragusa** [comment]
Build times exceeded 50 minutes and run out of memory anyway. See #1086.

**Comment by hannespetur** [comment]
Perhaps moving to container-based infrastructure would solve the issues. Builds usually run faster and Travis provides 4 GB memory vs 3 GB we are getting now. See: http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by rrahn** [comment]
@hannespetur  thanks for pointing this out, but it seems as we cannot directly use it while we install packages using sudo command. However, we plan to restructure the library anyway such that it will reduce the workload for the builds.

**Comment by hannespetur** [comment]
Yes, it would require changing the build script so no root access is needed. Unless you have a strong opinion against going container-based, I plan to do a PR for this to see how much of an improvement it would be.

**Comment by esiragusa** [comment]
:+1:
