### ISSUE TITLE
PackedString relies on allocated memory to be zero-initialized

### ISSUE THREAD

**Issue by catkira** [seqan/seqan#1074]
I experienced strange behaviour and test_sequence unit test failing on visual studio 2015. I could isolate the problem to uninitialized memory that PackedString uses somehow.
The problems in visual studio 2015 disappeared when I added 
     memset((void*)data, 0, count * sizeof(TValue));
in include/seqan/basic/allocator_interface.h
Furthermore I could reproduce the failing unit test in GCC and Clang by doing
     memset((void*)data, 0xFFFFFFFF, count * sizeof(TValue));

I think actually PackedString is supposed not to rely on zero-initialized memory. However the details are quite complex, so that I think its best that somebody who knows this code better than me fixes this. For now I add this memset 0 workaround (could be a little performance penalty though,if the allocator function is called very often)

**Comment by esiragusa** [comment]
Great job! :+1:

If I recall correctly, during the SeqAn 2.0.0 release, I saw something related in Valgrind reports...

**Comment by esiragusa** [comment]
@catkira did you solve this issue? :sweat_smile:

**Comment by catkira** [comment]
@SRR1175698.5 AdapterXX length=51
GGGGGCTGAAGATCGGAAGAGCACACGTCTGGATCCACGACGCTCTTCCGA
+SRR1175698.5 SEB9BZKS1:84:D1F78ACXX:4:1101:2363:2237 length=51
CCCFFFFFHHHHHHIIHIIIJHHIIIFHGGFEFF>FGGGGIEEIDHAHGHC
@SRR1175698.1 Adapter1 length=51
NCTGACTGAGATCGGAAGAGCACACGTCCGTCTGAACTCCAGTCACTTAAA
+SRR1175698.1 SEB9BZKS1:84:D1F78ACXX:4:1101:1969:2170 length=51
#1=DDFFFHHGHHJJHIIIIHIIJJJIJJIIJJIJJJJGHIJJJJJJJGHF
@SRR1175698.2 Adapter2 length=51
NGGGTCTGACATTTTGGAGGCACATCTGCGATCGGAAGAGCACACGTCTGAAA
+SRR1175698.2 SEB9BZKS1:84:D1F78ACXX:4:1101:2216:2128 length=51
#1=DADEFGHHHHJJJJHIIGIJJIJJJIJJJDIJJJJGHIIIJIIIFGHI
@SRR1175698.3 Adapter3 length=51
NCAGCCTGAAACAGATCGGAAGAGCACACGTCTGGATCCACGACGCTCTTC
+SRR1175698.3 SEB9BZKS1:84:D1F78ACXX:4:1101:2091:2173 length=51
#1=DDFFFHHHHHIJJIIJJJJJJJEHJJGGIIJJJJJJFHIJIJJGIIJI
@SRR1175698.4 Adapter6 length=51
NCTTGCTGAGCCTTCGGAAGAGCACACGTCTGGATCCACGACGCTCTTCCC
+SRR1175698.4 SEB9BZKS1:84:D1F78ACXX:4:1101:2237:2190 length=51
#4:ADD>?DDD>2AC:EEDE<FDEAC<DCEDD066D@AD98?DB>9BBD=B
@SRR1175698.6 SEB9BZKS1:84:D1F78ACXX:4:1101:2595:2166 length=51
NATGTCTGATCCACAAGGTAGTGTCCTCGGCCCCCTGCTCTACTGCCTGTA
+SRR1175698.6 SEB9BZKS1:84:D1F78ACXX:4:1101:2595:2166 length=51
#1:DDDBDDDHHHIIGGEAFCFHHGAGGIBGEHIIGIIFIDBBFHIGHCCE
@SRR1175698.6 SEB9BZKS1:84:D1F78ACXX:4:1101:2595:2166 length=51
CATTTGGGATCCACAAGGTAGTGTCCTCGGCCCCCTGCTCTACTGCCTGTA
+SRR1175698.6 SEB9BZKS1:84:D1F78ACXX:4:1101:2595:2166 length=51
#1:DDDBDDDHHHIIGGEAFCFHHGAGGIBGEHIIGIIFIDBBFHIGHCCE

**Comment by catkira** [comment]
its a very strange bug, i also dont get this behaviour with every file. But when I change line 10 to 
NGGGTCTGACATTTTGGAGGCACATCTGCGATCGGAAGAGCACACGTCTGAA
then  I get 7 reads. With the above file I get 6 reads.

**Comment by catkira** [comment]
yes I could solve it by adding memset((void*)data, 0x00, count * sizeof(TValue));
But thats only a quick fix and creates extra overhead. See https://github.com/catkira/seqan/commit/f0836434c2ee38cf820912959e700064164263e6

**Comment by h-2** [comment]
@catkira are there any news on this item? Did I understand correctly that it only happens on windows, and that gcc and clang initialize properly?

Can you sum up
  - how large the impact of the error is 
  - how large the overhead of your fix is
  - make a pull request?

Thanks a lot!

**Comment by esiragusa** [comment]
@h2 please read the thread above: do not apply this fix, rather investigate the issue further.

**Comment by h-2** [comment]
@esiragusa well if the memory is unitialized and it need to be initialized, what's the problem with memset?

**Comment by esiragusa** [comment]
As @catkira wrote, PackedString is supposed not to rely on zero-initialized memory. This is true for all other SeqAn containers.

Initialization does not happen at allocation time. If you place a memset there, all properly implemented containers will imply that memory is initialized twice, while PackedString will rely on zero-initialized memory which is wrong.

**Comment by h-2** [comment]
@esiragusa Thanks for the explanation! So the memset should be in the PackedString's constructor + resize?

**Comment by esiragusa** [comment]
To reproduce the error on GCC or Clang, @catkira suggested to do:

```memset((void)data, 0xFFFFFFFF, count * sizeof(TValue));```

You should check if PackedString is correctly implemented.

**Comment by catkira** [comment]
I think the correct way would be to make sure that packet_string initializes newly allocated memory when it uses it for the first time. Its more efficient than doing a memset.
I guess that is what the author of packet_string had in mind, because its "almost" working, just some bits dont get initialized correctly.

**Comment by rrahn** [comment]
In our nightly builds we now see the problems: http://cdash.seqan.de/viewTest.php?onlyfailed&buildid=163427
Only 32 windows causes the packed string to break. So something related to the word width I guess.
And only on master. On develop this problem, does not occur anymore. 
Second the test_sequence_v2 breaks when calling the reverse test on std::list. I think it should work though, but I open another issue for this. :grin: 
@catkira can you verify that the problem on develop is not present anymore? Did you use 32 bit Windows?

**Comment by h-2** [comment]
fixed by #1429
