### ISSUE TITLE
Warning C4800: 'BOOL': forcing value to bool 'true' or 'false' (performance warning)

### ISSUE THREAD

**Issue by catkira** [seqan/seqan#1085]
In minwindef.h line 157 is: typedef int                 BOOL;

Is this really neccessary?
It generates a warning (that sounds reasonable):
warning C4800: 'BOOL': forcing value to bool 'true' or 'false' (performance warning)

**Comment by esiragusa** [comment]
Hi @catkira, is this related to mingw?

**Comment by catkira** [comment]
no, visual studio 2015 with -W3.

**Comment by h-2** [comment]
Hm, I think we build with /W2 right now, right @cpockrandt ?
We can try to move to W3 or even W4 for 2.3.0, but not for 2.2

**Comment by h-2** [comment]
We will move to W3 for SeqAn3, but not anymore for SeqAn2.

**Comment by cpockrandt** [comment]
@h-2 We can close this issue, right?

**Comment by catkira** [comment]
yes

Am 20. Juni 2017 01:04:14 MESZ, schrieb cpockrandt <notifications@github.com>:
>@h-2 We can close this issue, right?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/seqan/seqan/issues/1085#issuecomment-309597643

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
