### ISSUE TITLE
Group Language Entity Type not documented

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#1127]
The group entity is missing in the description and has no icon associated in the dox.
See:
<img width="1350" alt="screen shot 2015-08-14 at 22 41 46" src="https://cloud.githubusercontent.com/assets/1529364/9283663/c1108018-42d5-11e5-834a-2f1a27fd32bc.png">

**Comment by xenigmax** [comment]
Hmm. What should I do for this exactly? 
@rrahn Can you explain it more? :)
