### ISSUE TITLE
G++-4.7 and clang++-3.3 missing in nightly builds on larix

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#1144]
Look here:
![screen shot 2015-08-19 at 12 05 09](https://cloud.githubusercontent.com/assets/1529364/9353695/9741e87e-466a-11e5-843d-175b762d988d.png)

**Comment by h-2** [comment]
@rrahn they are not available on debian stable as packages anymore... Someone could build them from source of course...

**Comment by esiragusa** [comment]
@h-2 if they are not available even on debian stable then we should drop them :-1:

BTW gcc47 had some problems with C++11...

**Comment by h-2** [comment]
@esiragusa:
I agree and propose the policy:
Support the *three* most recent releases of clang, gcc, the *single* most recent release of MSVC (with a small grace period for conversion) and whatever is used by debian stable. What do you think?

**Comment by esiragusa** [comment]
Let's discuss it on monday okay?

**Comment by h-2** [comment]
Yes!
