### ISSUE TITLE
Windows Master builds produce tons of warnings.

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#1149]
@catkira Can you please have a look at this: http://cdash.seqan.de/index.php?project=SeqAn
The nightly master builds for windows seem to be broken after merging this change: #1142
The master now produces tons of warning messages.

**Comment by catkira** [comment]
I created another hotfix and did a pull request

Am 20.08.2015 16:51, schrieb rrahn:

**Comment by rrahn** [comment]
Ok I'll have a look. Thanks.

**Comment by rrahn** [comment]
Problem with the demos is fixed in https://github.com/rrahn/seqan/tree/hotfix/win_build_warnings.
Apparently, this causes the demos to produce a lot of warnings on GNU and clang due to some unused variables and typedefs. This can first be fixed after #1197 is merged.

**Comment by esiragusa** [comment]
@rrahn can you please open a PR?

**Comment by rrahn** [comment]
ok

**Comment by rrahn** [comment]
Fixed by #1214
