### ISSUE TITLE
Compiling with W2 on Visual C++

### ISSUE THREAD

**Issue by catkira** [seqan/seqan#1155]
using W2 is very problematic, because many useful warnings are suppressed

**Comment by catkira** [comment]
All projects that use seqan have to use W2 in order not to get flooded with warnings. This is not usable.

**Comment by esiragusa** [comment]
Isn't this equal to Issue #1149?

**Comment by catkira** [comment]
yes

**Comment by esiragusa** [comment]
Ok thanks, we'll try to work on #1149. Sorry for the inconvenient...
