### ISSUE TITLE
Alignment algorithms accept unsupported scoring schemes

### ISSUE THREAD

**Issue by esiragusa** [seqan/seqan#1161]
Right now it is possible to call a restricted alignment algorithm with an unsupported general scoring scheme. The result is then undefined.

For instance, one can do the following:
```globalAlignment(align, Score<int, Simple>(3, -2, 0, -5), Hirschberg());```

We should:
* If possible, restrict the scoring scheme type at compile time;
* Otherwise, assert the scoring scheme parameters with ```SEQAN_ASSERT```.

**Comment by rrahn** [comment]
Fixed by #1361
