### ISSUE TITLE
inconsistency in writing index over modstring

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1165]
writing an index over a modstring to disk results in a `.txt.concat` and `.txt.limits` being written, although none should be. In fact the limits are empty, but the concat contains 16byte, of which at least one is random.

**Comment by h-2** [comment]
https://github.com/seqan/seqan/blob/master/include/seqan/modifier/modifier_string.h#L848 shows that is writing should be deactivated for mod-strings.

**Comment by esiragusa** [comment]
There's a const missing...

**Comment by h-2** [comment]
cool :)

**Comment by h-2** [comment]
should be fixed by #1168 / #1169
