### ISSUE TITLE
erase is not working with iterators

### ISSUE THREAD

**Issue by catkira** [seqan/seqan#1171]
this gives errors when I try to compile it:
    String<char> strA = "abc";
    erase(strA, begin(strA), end(strA));

P:\git\seqan\include\seqan/sequence/string_base.h(924): error C2440: 'static_cast': cannot convert from 'seqan::Iter<T,seqan::AdaptorIterator<char *,seqan::Default>>' to 'TPos_'
          with
          [
              T=seqan::CharString
          ]

**Comment by h-2** [comment]
according to the dox this is not supposed to work (only positions allowed as argument). You could make a wrapper that calls position on the iterator and make a pull request though ;)
