### ISSUE TITLE
KNIME YaraIndexer node fails

### ISSUE THREAD

**Issue by esiragusa** [seqan/seqan#1172]
Description
------------------------------
KNIME YaraIndexer node produces a "Configure failed (ArrayIndexOutOfBoundsException): 0" error when connected to an input. The problem seems related to the IPrefixURIPortObject output.

How to reproduce the issue
------------------------------------
* Make the prepare_workflow_plugins target in SeqAn and use the output "workflow_plugin_dir" with the GenericKnimeNodes tools to produce the SeqAn KNIME nodes and input them in KNIME.
* Then connect YaraIndexer (Community Nodes->SeqAn->Read Mapping->YaraIndexer) to an input node (Community Nodes->GenericKnimeNodes->IO->Input File) with any fasta sequence.
* The error "Configure failed (ArrayIndexOutOfBoundsException): 0".

Explanation 
---------------

The latest Yara versions are tagged from develop, while KNIME builds use old master version. This fact should explain the issue.

**Comment by rrahn** [comment]
@temehi is this still a problem?

**Comment by esiragusa** [comment]
@rrahn this issue will be solved when our KNIME nodes will be built for 2.1.0 (see the explanation above). You can close the issue now or perhaps wait until it's solved...

**Comment by rrahn** [comment]
@esiragusa Ah I see. Thanks for the update.

**Comment by temehi** [comment]
@esiragusa @rrahn I was looking more into it. Sorry to say this but I don't think the YaraIndexer KNIME node of the new release  2.1.0 will work! The problem is related to the fact that the indexer doesn't output a single known file_type. The GenericKnimeNodes has a way to deal output-prefixes but yet it expects a common ending/extension for all the resulting files. Which is not the case for YaraIndexer.

**Comment by rrahn** [comment]
@temehi don't be sorry. Fix it! :stuck_out_tongue_winking_eye:
What do you mean with common? Can we not just put some ending to it like: file.index something?
I mean I don't know which files are output by the indexer at the end, but it would be ok to just give it some extension, or am I overseeing something here?

**Comment by h-2** [comment]
Our indexes consist of a bunch of files with all sorts of endings. This a bad design anyway, and in the future we should find some way to stuff the files into one, like `.tar`. Then we could arbitrarily compress this, as well. But for the short term we need a different soluation.
@temehi can we not hack around this some way? This effects all SeqAn tools that save indexes to disk, also Lambda (which I haven't had time to put into KNIME, but plan to do so in the future).

**Comment by esiragusa** [comment]
Yara usees ```ArgParseOption::OUTPUT_PREFIX``` See https://github.com/seqan/seqan/blob/develop/apps/yara/indexer.cpp#L139.

This thing enforces all index files to have have a common prefix but, as far as I can see, not a common extension. Is that the problem? Do you know what's the correct way of using the argparse?

@h-2 Keep in mind that one wants to memory map the index. With tar it will be impossible. One could concatenate the files and keep a directory of cumulated lengths (as in our Concat String). Then the MMap String must be able to map a slice of the file... easy solution: use a directory :smile:

**Comment by h-2** [comment]
@esiragusa yes, I have thought about all these things, tar'ing without compression would still allow to memory map regions from the file. OTOH tar is overkill...
Ideally we would have an (endianess-independent) concatenation of files with a small index that has length and plainstring identifiers for the files contained. Then we could make our `open()` and `save()` plug into that.

**Comment by esiragusa** [comment]
@temehi I don't get what's the problem with ```ArgParseOption::OUTPUT_PREFIX```. Am I misusing it?

**Comment by esiragusa** [comment]
@temehi I guess lambda has the same issue... @h-2 I know you :heart: KNIME

**Comment by temehi** [comment]
@esiragusa  I don't think the problem is from yara side. All we can do is set the argument type to "ArgParseOption::OUTPUT_PREFIX". I think GenericKnimeNodes is not handling the situation properly. I am going to write an issue on their repository, though the repo don't seem to be active

**Comment by temehi** [comment]
@h-2 , @rrahn  This issue can be closed.
