### ISSUE TITLE
Link broken at seqan.readthedocs.org

### ISSUE THREAD

**Issue by Grahack** [seqan/seqan#1179]
The Github link in the top right corner of this page:  
<http://seqan.readthedocs.org/en/latest/Tutorial/IndexIterators.html>  
is broken.

**Comment by rrahn** [comment]
Thanks for reporting this. 
Seems we need to make sure to set the slashes for some of the variables to generate the link?
It works for master and the release versions though.
Here the generated URL from the rtd engine.
```html
<a href="https://{{ github_host|default("github.com") }}/{{ github_user }}/{{ github_repo }}/blob/{{ github_version }}{{ conf_py_path }}{{ pagename }}{{ source_suffix }}" class="fa fa-github"> Edit on GitHub</a>
```

**Comment by rrahn** [comment]
Mhmm, it must have been a temporary problem.
After rebuilding the manual the problem didn't occur anymore.
If this should break again, we need to investigate if this is not an error on rtd site.
At least I couldn't find where we could possibly influence these parameters. 
They are automatically detected by the rtd system.
