### ISSUE TITLE
Documentation error in the PairwiseSequenceAlignment tutorial

### ISSUE THREAD

**Issue by marehr** [seqan/seqan#1188]
In assignment 3 there is a wrong text pasage.
http://seqan.readthedocs.org/en/master/Tutorial/PairwiseSequenceAlignment.html#assignment-3

> In the next step we initialize our input StringSet `strings` and pass it as argument to the constructor of the AlignmentGraph `alignG`.

But in this example you don't use an AlignmentGraph.

-----

Also in the assignment 3. The following text doen't seem to match with the code snippet.

> Now we compute the alignment using the levenshtein distance and a AlignConfig object to set the correct free end-gaps. In this example we put the shorter sequence on the vertical axis of our alignment matrix. Hence, we have to use free end-gaps in the first and last row, which corresponds to the first and the last parameter in the AlignConfig object. If you add the shorter sequence at first to strings, then you simply have to flip the bool values of the AlignConfig object.

There is no alignment config, because the MyersHirschberg method is used.

From the assignment text, I also don't find it clear, that you should use the MyersHirschberg method. Maybe you should include a hint.

------

Another small typo is in the hint of the second assignment.
http://seqan.readthedocs.org/en/master/Tutorial/PairwiseSequenceAlignment.html#assignment-2

> Here we only allow free free end-gaps at the beginning and the end of the shorter sequence

The `free` is repeated.

**Comment by esiragusa** [comment]
@rrahn It's probably wise to wait for #1173 #1174.

**Comment by rrahn** [comment]
Well, yes I agree.
