### ISSUE TITLE
Unexpected character found.

### ISSUE THREAD

**Issue by martinjvickers** [seqan/seqan#1196]
I'm getting the following error when trying to open a fasta file;

alfsc-c-version/seqan-src/include/seqan/basic/basic_exception.h:368 FAILED!  (Uncaught exception of type seqan::ParseError: Unexpected character 'R' found. )

The code I'm using to open the file is from the tutorial;

        StringSet<CharString> ids;
        StringSet<Dna5String> seqs;
        CharString referenceFileName;
        getOptionValue(referenceFileName, parser, "reference-file");
        SeqFileIn seqFileIn(toCString(referenceFileName));
        readRecords(ids, seqs, seqFileIn);

The fasta file contains the following sequence which contains an R (NB I've tried this with other letters and it fails on all of them);

>gi|15807672|ref|NC_001264.1| Deinococcus radiodurans R1 chromosome 2, complete sequence:101000;102000
GACGGGTCCCATCGGTCTGGCGATCGCGGCCATTGGCCTCCTGGRTCGGTGCGGGCGTGGCGCTCTACCGCAACTGGGATGAGGTCGTCTCCTGGGCGCACAAGACGTGGAACCAGATCAAGGGCATCGTCGAGAACGCTATCAATGGGGCCATGTCCTACCTGCGCGGTGTGGACATGAAAGGCGTGGGCCTCGACATCGTGCAGGGCCTGGTAAACGGCATCCTGGCCGGGCCGCGCCTGGTGCTCGCCGCCGCCCGCAACCTGGGCAGCAAGGTCATTGAGGGTGTCAAGGGTGTCCTCAACATCCAGTCACCCTCCCGCGTGATGAAAGAGCTGGGCGAGTTCACGGGTCAGGGCTTCGTGATGGGCCTGGAATCTGAGGTGCCGAGCGTTCGCAAGGCCGCCGAAGCGACAGCCAAAGCGTTTCTGGATTCGTTCAGCGACCTGAAGCTGGAACGGTCGGTGGGCAACGTGGACCTCACCACCTACACCCGCACGCTGGAGCAGGCCGCCGCGCAGCTGCGCAGCAAGCTCAAGACAGTGCAGGAGGGCACCCCTGCCTATGTTGCCTGGCTCAAGGCGCTCCAGACCGTGACGAGCGAGCTGGACGCGGTCAAGAGCAAGAGCAGCGGCGCTCAGGCATCAGCCAAGGGTCTCGCCGACGAGCTGACCCGCAACCGTCAACAGATCGAGCGCGGCGAGGCGATGGAGCAGTACGTGGGGAGCCTGCGCTCGGCCACCTCGGCGCAACTGGCCTCGGCGCTCGAAACGGCCAGAGCCAGGGGCGAAACCGAGAAATACAACGCGATTCGTGACGAGCAGCGCCGCCGCACCGACGCGGCCACCGCTGCCCAGAACAAGGCCACCGACTCGGTGCGCCGGCACCAGGAACAGGTGGCGGACACCCGTTCCCAAATCGCTGCCAACGAGGCACAAGAACGCTATGTTCTCGGACTGCGTTCAGCCACCGACGCTCAGCTCCGCTCGGCGCTCGAAACC

I'm led to believe that the Dna5String would convert any unknown characters to an 'N' as described in the API docs and here;
https://lists.fu-berlin.de/htdig/seqan-dev/2012-April/msg00026.html

Is this a bug or am I doing something wrong?

**Comment by h-2** [comment]
The behaviour has changed to where unknown characters are not converted implicitly. You can use a `StringSet<String<Iupac> >` to have support for the other characters.
If you want the old behaviour, read to Iupac first and then assign it to a Dna5String. This will do the proper conversions on assignment.

The new behaviour might seem more inconvenient, but it protects you from reading protein sequences as dna sequences and all sorts of other minor issues.

**Comment by h-2** [comment]
Where exactly do the API docs suggest the old behaviour? Maybe we need to fix that...

**Comment by martinjvickers** [comment]
I think I may have misunderstood the API docs. In the spec for Dna5 it states;

"The ValueSize of Dna5 is 5. The nucleotides are enumerated this way: 'A' = 0, 'C' = 1, 'G' = 2, 'T' = 3. The 'N' character ("unkown nucleotide") is encoded by 4. Objects of type Dna5 can be converted to various other types and vice versa. An object that has a value not in {'A', 'C', 'G', 'T'} is converted to 'N'."

...which led me to the conclusion that Dna5String would act the same way as it was mentioned in the dev-list archive.

I think the new behaviour does make good sense, maybe it could be made a little clearer in a tutorial, .e.g. dealing with odd characters in fasta's, maybe not the api docs.

**Comment by martinjvickers** [comment]
I can however read the same file in as follows;

        CharString testids;
        Dna5String testseqs;
        SeqFileIn seqFileIntest("test.fasta");
        readRecord(testids, testseqs, seqFileIntest);

which to me seems a little odd when it doesn't work as a StringSet.

**Comment by h-2** [comment]
> I think the new behaviour does make good sense, maybe it could be made a little clearer in a tutorial, .e.g. dealing with odd characters in fasta's, maybe not the api docs.

Yes, this should be covered in a tutorial somewhere...

> which to me seems a little odd when it doesn't work as a StringSet.

This should definitely not work and I can't see why it does. `readRecords()` only calls `readRecord()`...

Can you double-check that?

**Comment by martinjvickers** [comment]
Sure, here is my test of both;

        cout << "Test1" << endl;
        CharString test1ids;
        Dna5String test1seqs;
        SeqFileIn seqFileIntest1("test.fasta");
        readRecord(test1ids, test1seqs, seqFileIntest1);
        cout << "Test1 - complete" << endl;

        cout << "Test2" << endl;
        StringSet<CharString> test2ids;
        StringSet<Dna5String> test2seqs;
        SeqFileIn seqFileIntest2("test.fasta");
        readRecords(test2ids, test2seqs, seqFileIntest2);
        cout << "Test2 - complete" << endl;

and here is the result;

Test1
Test1 - complete
Test2
~/Desktop/alfsc-c-version/seqan-src/include/seqan/basic/basic_exception.h:368 FAILED!  (Uncaught exception of type seqan::ParseError: Unexpected character 'R' found. )
...
long stacktrace

**Comment by esiragusa** [comment]
```readRecors``` (note the plural form) uses an internal buffer which has the same type of the StringSet to be filled in with sequences (Dna5 String in your case). See here: 
* https://github.com/seqan/seqan/blob/master/include/seqan/seq_io/sequence_file.h#L257
* https://github.com/seqan/seqan/blob/master/include/seqan/seq_io/sequence_file.h#L122

One solution is to overload the private metafunction ```SeqFileBuffer_``` as I did in https://github.com/seqan/seqan/blob/develop/apps/yara/misc_types.h#L136 to use a Iupac String. In this way the input file is checked against Iupac and any non-A/C/G/T is silently converted into a N.

Concerning ```readRecor```, I don't know why it behaves that way... does it implicitly convert to Dna5?

**Comment by martinjvickers** [comment]
@esiragusa. Thanks for the pointer to the overloading SeqFileBuffer_, that just worked!

@h-2 thanks for taking a look into this. I was unsure if it was a bug, an error on my part or a misunderstanding, I guess it's a little of all three.

**Comment by esiragusa** [comment]
OK! We now have to investigate why ```readRecord(Dna5String, ...)``` does not throw the same ParseError exception...

**Comment by esiragusa** [comment]
@martinjvickers I am on seqan/master and run your test on the file that you pasted in your first comment. As expected, ```readRecord(Dna5String, ...)``` throws a ParseError exception. See below:

```
$ bin/demo_seq_io_test /tmp/test.fa 
Test1
/Users/esiragusa/Code/seqan/include/seqan/basic/basic_exception.h:368 FAILED!  (Uncaught exception of type seqan::ParseError: Unexpected character 'R' found. )

stack trace:
  0  0x000000010b03ad4b  seqan::globalExceptionHandler() + 123
  1  0x00007fff8a1a019e  std::__terminate(void (*)()) + 8
  2  0x00007fff8a19fc12  __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 0
  3  0x000000010b0473f0  bool seqan::AssertFunctor<seqan::IsInAlphabet<seqan::SimpleType<unsigned char, seqan::Dna5_> >, seqan::ParseError, seqan::Tag<seqan::TagFasta_>, false>::operator()<char>(char const&) + 496
  4  0x000000010b047e80  void seqan::_readUntil<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Iter<seqan::VirtualStream<char, seqan::Tag<seqan::Input_>, std::__1::char_traits<char> >, seqan::StreamIterator<seqan::Tag<seqan::Input_> > >, seqan::EqualsChar<(char)62>, seqan::OrFunctor<seqan::OrFunctor<seqan::OrFunctor<seqan::EqualsChar<(char)32>, seqan::EqualsChar<(char)9> >, seqan::OrFunctor<seqan::EqualsChar<(char)10>, seqan::EqualsChar<(char)13> > >, seqan::AssertFunctor<seqan::IsInAlphabet<seqan::SimpleType<unsigned char, seqan::Dna5_> >, seqan::ParseError, seqan::Tag<seqan::TagFasta_>, false> >, char, seqan::SimpleType<unsigned char, seqan::Dna5_> >(seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >&, seqan::Iter<seqan::VirtualStream<char, seqan::Tag<seqan::Input_>, std::__1::char_traits<char> >, seqan::StreamIterator<seqan::Tag<seqan::Input_> > >&, seqan::EqualsChar<(char)62>&, seqan::OrFunctor<seqan::OrFunctor<seqan::OrFunctor<seqan::EqualsChar<(char)32>, seqan::EqualsChar<(char)9> >, seqan::OrFunctor<seqan::EqualsChar<(char)10>, seqan::EqualsChar<(char)13> > >, seqan::AssertFunctor<seqan::IsInAlphabet<seqan::SimpleType<unsigned char, seqan::Dna5_> >, seqan::ParseError, seqan::Tag<seqan::TagFasta_>, false> >&, seqan::Range<char*>*, seqan::Range<seqan::SimpleType<unsigned char, seqan::Dna5_>*>*) + 656
  5  0x000000010b047b70  void seqan::readRecord<seqan::String<char, seqan::Alloc<void> >, seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Iter<seqan::VirtualStream<char, seqan::Tag<seqan::Input_>, std::__1::char_traits<char> >, seqan::StreamIterator<seqan::Tag<seqan::Input_> > > >(seqan::String<char, seqan::Alloc<void> >&, seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >&, seqan::Iter<seqan::VirtualStream<char, seqan::Tag<seqan::Input_>, std::__1::char_traits<char> >, seqan::StreamIterator<seqan::Tag<seqan::Input_> > >&, seqan::Tag<seqan::TagFasta_>) + 720
  6  0x000000010b03af5e  main + 430
  7  0x00007fff8a6ed5ad  start + 1

Abort trap: 6
```
I close the issue for now. Please let me know whether it works for you!
