### ISSUE TITLE
readRecord allocates too much memory when reading into vector

### ISSUE THREAD

**Issue by catkira** [seqan/seqan#1238]
When I read many record directly into a vector, it allocates too much memory. For mode 1 and 2 the program needs around 18mb memory, for mode 3 and 4 around 300mb. Does anybody have an idea why this is?
If I calculate it, lets say 50 bytes for the sequence and 50 bytes for the qualities per read, then I get 100*100000 = 10.000.000 bytess = 10mb which is about the 18 mb that i can measure for mode 1 and 2.

    seqan::SeqFileIn seqFile("P:\\data\\fastq\\xxx.fastq");  // any fastq file with a read length of about 50

    seqan::CharString id;
    seqan::Dna5QString seq;
    const auto len = 100000;
    seqan::String<seqan::Dna5QString> seqVector(len);
    std::vector<seqan::Dna5QString> seqStdVector(len);
    resize(seqVector, len);
    unsigned int i = 0;
    constexpr int mode = 4;
    while (!atEnd(seqFile) && i < len)
    {
        if (mode == 1)
        {
            seqan::readRecord(seq, id, seqFile);
            seqVector[i] = seq;
        }
        else if (mode == 2)
        {
            seqan::readRecord(seq, id, seqFile);
            seqStdVector[i] = seq;
        }
        else if(mode == 3)
            seqan::readRecord(seqVector[i], id, seqFile);
        else if (mode == 4)
            seqan::readRecord(seqStdVector[i], id, seqFile);
        ++i;
    }
    close(seqFile);
    std::cout << "read done" << std::endl;
    while (1) {};
    return 0;

**Comment by catkira** [comment]
I looked a bit more into it, when i change case 1 to
 seqVector[i] = std::move(seq);
I also get the high memory usage. I think its because unused allocated memory gets moved into the new destination.

With move(seq) the program uses about 300 MB ram, without move(seq) 16 MB.

**Comment by temehi** [comment]
>  I think its because unused allocated memory gets moved into the new destination.

Yes! and the reason is if you pass `seqVector[i]` to `readRecord()` it will be reserved with the stream buffer size (which is usually bigger) and stays as it is, where as the intermediate variable is overwritten for every iteration. To avoid this one should use (it's also recommended) readRecords() to read a block of records, and use   `StringSet<CharString, Owner<ConcatDirect<> > >` to store them.
something like this 
```
   seqan::StringSet<seqan::Dna5QString, seqan::Owner<seqan::ConcatDirect<> > > seqVector;
   seqan::StringSet<seqan::CharString, seqan::Owner<seqan::ConcatDirect<> > > idVector;
   seqan::readRecords(idVector, seqVector, seqFile, 100000);
```
@h-2 can you please close the issue?

**Comment by h-2** [comment]
@catkira can you confirm this fixes your issue?

**Comment by catkira** [comment]
yes, its solved now. Thank you!

**Comment by h-2** [comment]
Although it is true that `readRecords()` is recommended, I still think there is a bug somewhere. 
I am not convinced the reserved space should grow, if the saved strings are always the same size. @temehi can we discuss this again sometime?
