### ISSUE TITLE
Changing a BamTagsDict to a BamAlignmentRecord.tags object

### ISSUE THREAD

**Issue by snaedis88** [seqan/seqan#1246]
Hello.

I have been using the BamTagsDict to access/modify/erase tags in a BamAlignmentRecord.
When I have finished modifying the record I would like to be able to use it to create a tags CharString for my BamAlignmentRecord, something like the following: 

BamAlignmentRecord record; //my record
BamTagsDict tagsDict(record.tags);
//Edit the tagsDict
tagsDictToBam(tagsDict, record.tags);

Currently, I am using a work around with the function appendTagsSamToBam(record.tags, tagString) where tagString = "MQ:i:27" for example.

Thank you,
Snædís

**Comment by rrahn** [comment]
Hey Snædís,

so I took a look into the BamTagsDict implementation. As far as I could see it, the host of the BamTagsDict is already in the Bam-Tags format. 
Moreover, if you call the constructor with ```records.tags``` the dictionary will store a reference to the record's tags member. Hence modifying the tags via the BamTagDict should be transparently applied to the record.tags field. I documented this behaviour. 
However, if your record was somehow copied at some place (or maybe const) this would not work anymore. So I added the function ```tagsToBamRecord``` which is semantically the same as:
```record.tags = host(bamTagDict);```
In case the host is pointing to ```record.tags``` it would be merely a self-assignment.

Could you please verify, whether this works for you? 
See #1362.

**Comment by snaedis88** [comment]
Hey René.

I tried both of your suggestions and they work very well.
I am not sure why this didn't work for me earlier, although I suspect it might have been a copy issue like you suggested.
Thank you for your reply and the "new" function.

/Snædís
