### ISSUE TITLE
bam io does not support custom tags with floats

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1272]
i.e. this does not work:
```c++
appendTagValue(bamR.tags, "ZE", mIt->eValue, 'f');
```
There are multiple overloads for integers:
https://github.com/seqan/seqan/blob/master/include/seqan/bam_io/bam_tags_dict.h#L675

and for sequences:
https://github.com/seqan/seqan/blob/master/include/seqan/bam_io/bam_tags_dict.h#L691

(same is true for `extractValue()`).

I am not completely sure how the internals work,  @esiragusa can you have a look?

**Comment by esiragusa** [comment]
Is eValue a float? See https://github.com/seqan/seqan/blob/master/include/seqan/bam_io/bam_tags_dict.h#L637

**Comment by esiragusa** [comment]
Or should https://github.com/seqan/seqan/blob/master/include/seqan/bam_io/bam_tags_dict.h#L675 be enabled for ```NumberConcept```?

**Comment by h-2** [comment]
fixed by #1285
