### ISSUE TITLE
getAbsolutePath and leading /

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1275]
in the new tutorials we have `getAbsolutePath("/path/in/seqan/") which is confusing. getAbsolutePath should add a slash if missing and the leading slash in the demos should be removed.

**Comment by esiragusa** [comment]
Without the leading slash the path becomes ambiguous: The leading slash indicates the project root.

**Comment by esiragusa** [comment]
Apart from the fact that this is really :nail_care:

**Comment by h-2** [comment]
> Without the leading slash the path becomes ambiguous: The leading slash indicates the project root.

A leading slash indicates file-system root and is always an indicator that a path is already absolute, so I agree with Johannes that it is a little confusing. And that its good to change.

**Comment by jtroehr** [comment]
Exactly, thought without slash one indicates a path relative to the project (root). But could also live with dropping this change ;)

**Comment by esiragusa** [comment]
FYI I would close this issue rather than spending time on it. It does not improve anything objectively... that's really :nail_care:

**Comment by h-2** [comment]
I disagree, the issue is basically already fiyed and it improves the quality of our tutorials which is good. even though it may not be essential I don't see any harm in the fix, so why not do it?

**Comment by h-2** [comment]
fixed by #1295
