### ISSUE TITLE
use ModifiedString in FM-Index construction to save space+time

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1277]
@cpockrandt we discussed this before... could you have a look at it? For a regular String it is basically just using the positiion modifier with the SA as positions-String. For a StringSet one would have to create a custom ModString...

**Comment by cpockrandt** [comment]
I implemented it using ModPos but iterating over the modified string was much slower than constructing the bwt and iterating over it, probably because of cache misses (as @marehr pointed out).

**Comment by h-2** [comment]
We will have to think of other strategies to make BWT construction faster...
