### ISSUE TITLE
CONDITION_VARIABLE does not name a type - when using Seqan library

### ISSUE THREAD

**Issue by AOIST** [seqan/seqan#1284]
I am trying to make use of the Seqan library but whenever I try and compile I get the error CONDITION_VARIABLE does not name a type. Would you be able to help me find a solution for this?
Thanks!
[capture](https://cloud.githubusercontent.com/assets/15818999/11122068/47995fee-8951-11e5-9bc4-5397d3ee9978.JPG)

**Comment by esiragusa** [comment]
Hi @AOIST, on Windows you should build with Visual Studio. Are you using cygwin?

**Comment by AOIST** [comment]
I am quite new to all this, I have just been using Code Blocks

**Comment by h-2** [comment]
@AOIST on windows we only support MSVC++ right now, not gcc. So we can't help you with the problem.  However we do accept patches, so if you manage to fix it, we will integrate the fix.
