### ISSUE TITLE
deprecate Dependent<Tight> StringSets

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1289]
... and also undocument `valueById()` `removeValueById()` as no one knows exactly what they are good for, their interfaces don't align with SequenceConcept, there are currently no tests being run and no app uses them.
Also redo StringSets Tutorial.

**Comment by esiragusa** [comment]
If you plan to keep these functions, you better mark them as deprecated in the dox! Or do you want to remove these functions?

**Comment by h-2** [comment]
@esiragusa deprecating would probably be enough. But they need to be removed from the tutorial, too.

**Comment by h-2** [comment]
"The Dependent-Tight StringSet is deprecated and will likely be removed within the SeqAn-2.x lifecycle."

  - [ ] add above  notice to the dox entry of `Spec Tight Dependent StringSet`
  - [ ] add notice to the `[set|get|remove][vV]alueById()` that they are deprecated and that one should use  version without `ById()` instead
  - [ ] add above notice the StringSets manual, just below `Specialization Dependent<Tight>`

**Comment by h-2** [comment]
fixed by #1467
