### ISSUE TITLE
Documentation error with CIGAR format in Pairwise Sequence Alignment Tutorial 

### ISSUE THREAD

**Issue by NG0S** [seqan/seqan#1309]
In this tutorial, and in particular in the Assignment 5, the author considers "S" operations in CIGAR means substitutions. This is not true.
In accordance to SAM format specifications (http://samtools.github.io/hts-specs/SAMv1.pdf), "S" operations should mean soft-clipping, which is widely used with local aligners like bowtie --local, or even BLAST. The "M" operation means both match and mismatch.
This is not the first time I see problems with soft-clipping in Seqan, which is not correctly implemented in the Fragment Store for example (see https://github.com/seqan/seqan/issues/535). I dont have the technical abilities to debug this pb, but as a user I can tell you that this is not an unfrequent pb. In local alignments you can have up to 80% of soft-clipped sequences in your sam file, which means that we cannot treat it with high level structures in seqan.

**Comment by h-2** [comment]
Can you point me to the tutorial? I couldn't find Assignment 5...
Also all internal functions that I just checked treat 'H' and 'S' as clipping.

**Comment by NG0S** [comment]
This is the tutorial i'm talking about:
http://seqan.readthedocs.org/en/master/Tutorial/PairwiseSequenceAlignment.html#tutorial-pairwise-sequence-alignment
and there:
https://github.com/seqan/seqan/blob/master/manual/source/Tutorial/PairwiseSequenceAlignment.rst#assignment-5

If I'm remembering correctly the bug with the Fragment Store and the soft-clipping (https://github.com/seqan/seqan/issues/535), when I loaded reads locally aligned with "S" in the cigar into the Fragment Store, the soft-clipped bases where not considered when computing the positions of the read against the ref, and the whole read was shifted. But since the Fragment Store doesnt store the Cigar, there where no way to correct the pb a-posteriori.
