### ISSUE TITLE
make C++11 formal requirement for 2.1.0 and remove old code

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1320]
- [x] make FindCXX11 a requirement for any build, as all supported 2.1 compilers support the required C++11 features
  - [x] include the std= parameter in SEQAN_CXX_FLAGS and get rid of CX11_CXX_FLAGS
  - [ ] find all occurences of `SEQAN_CXX11_STANDARD`, `SEQAN_CXX11_STL` and `SEQAN_CXX11_COMPLETE` and remove the outdated code and checks

see also #1349

**Comment by mr-c** [comment]
Great to hear, :+1:

**Comment by h-2** [comment]
fixed by #1382
