### ISSUE TITLE
v1.4.1: please make the build reproducible

### ISSUE THREAD

**Issue by mr-c** [seqan/seqan#1344]
FYI: another issue found in Debian

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=809058

```
diff --git a/docs/dddoc_html.py b/docs/dddoc_html.py
index 52e5de1..26101a8 100644
--- a/docs/dddoc_html.py
+++ b/docs/dddoc_html.py
@@ -1,5 +1,6 @@
 # coding: latin-1
 import os
+import time
 import datetime
 import dddoc
 import dddoc_html_trans
@@ -13,6 +14,7 @@ from os import F_OK
 # Number of warnings.
 WARNING_COUNT = 0
 OUT_PATH = 'html'
+BUILD_DATE = datetime.datetime.utcfromtimestamp(int(os.environ.get('SOURCE_DATE_EPOCH', time.time())))
 
 ################################################################################
 
@@ -663,7 +665,7 @@ def pageIndexpage(fl, cat):
     fl.write('</td></tr>')
     fl.write('</table>')
     fl.write('<p style="font-size:50%%; color: #909090">Page built @%s</p>' %
-             datetime.datetime.now().strftime('%Y/%m/%d %H:%M:%S'))
+             BUILD_DATE.strftime('%Y/%m/%d %H:%M:%S'))
     fl.write('</body>')
     fl.write('</html>')
 
@@ -760,7 +762,7 @@ def pageContent(fl, data):
     fl.write('</td></tr>')
     fl.write('</table>')
     fl.write('<p style="font-size:50%%; color: #909090">Page built @%s</p>' %
-             datetime.datetime.now().strftime('%Y/%m/%d %H:%M:%S'))
+             BUILD_DATE.strftime('%Y/%m/%d %H:%M:%S'))
     fl.write('</body>')
     fl.write('</html>')
```

**Comment by h-2** [comment]
There are no further updates for seqan-1.*
But can you point us to documents that explain how ensure this for seqan2?

**Comment by h-2** [comment]
Is the dddoc issue the only problem for reproducability? Because if yes, I can assure you the entire dddoc system has been removed :)

**Comment by mr-c** [comment]
That was the only problem for reproducibility; thanks!

Mie, 20 ian. 2016, 12:35, Hannes Hauswedell <notifications@github.com> a
scris:

> Is the dddoc issue the only problem for reproducability? Because if yes, I
> can assure you the entire dddoc system has been removed :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seqan/seqan/issues/1344#issuecomment-173178561>.
>
-- 
Michael R. Crusoe     CWL Community Engineer     crusoe@ucdavis.edu
<mcrusoe@msu.edu>
Common Workflow Language project    University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe
