### ISSUE TITLE
Replace SeqAn threads and atomic wrappers by C++11 STL 

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#1355]
- [x] replace seqan threads with std::thread
- [x] fix static linking against pthread lib
- ~~replace atomic intrinsics with std::atomic~~ (moved to SeqAn3)
- [x] update manual
- [x] add note to changelog

**Comment by rrahn** [comment]
Apparently, we still might need the intrinsics in order to allow atomic operations on standard integral and pointer types. See the following function: https://github.com/seqan/seqan/blob/develop/include/seqan/parallel/parallel_sequence.h#L116.
However, the __sync builtins could be replaced by __atomic builtins for gcc and clang, which support memory order settings like STL does: http://en.cppreference.com/w/cpp/atomic/memory_order.
I think with VS 14 we also have some updated intrinsics.

**Comment by h-2** [comment]
@rrahn can this be done for 2.2.0? Would be really cool, especially since it might finally resolve #1008

**Comment by rrahn** [comment]
@h-2 We need some more internal changes in the library that need to be tested thoroughly. I will postpone it to 2.3.0.
