### ISSUE TITLE
many unit and/or app tests don't cleanup /tmp

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1387]
Many tests create temporary files that are not deleted. This should be fixed.

**Comment by cpockrandt** [comment]
I would like to re-open this ticket :grimacing: 

There are still many folders in /tmp that are not deleted. There are currently 78 folders left from tonights nightly builds on ``larex`` (and also quite a few on Windows as well). I think we missed some unit/app tests :see_no_evil:

**Comment by cpockrandt** [comment]
hopefully fixed by #1588 and #1587

**Comment by cpockrandt** [comment]
@smehringer: Larix lgtm, but on Windows there were 2*13 folders left from the nightly builds.

**Comment by smehringer** [comment]
windows doesn't like me it seems... :disappointed:  can we look into windows together?

**Comment by cpockrandt** [comment]
@smehringer Sure, just drop by my office :wink:

**Comment by xenigmax** [comment]
It's related to #1557 . Removal does not work for Windows.

**Comment by h-2** [comment]
fixed except for #1557
