### ISSUE TITLE
Dox color scheme for sample commands is hard to read

### ISSUE THREAD

**Issue by ryan-williams** [seqan/seqan#1427]
e.g. [Prerequisites](http://seqan.readthedocs.org/en/master/Tutorial/GettingStarted/MacMakefiles.html#prerequisites)

![](http://cl.ly/0O2m2R412z0B/Screen%20Shot%202016-02-04%20at%204.11.04%20PM.png)

**Comment by h-2** [comment]
@ryan-williams indeed... @xenigmax can you have a look at it sometime?
