### ISSUE TITLE
Problem making an FM-Index from a StringSet

### ISSUE THREAD

**Issue by ryan-williams** [seqan/seqan#1439]
I'm trying to FM-Index the reads from a `.bam` file.

I iterate over each read and added its `seq` to a `StringSet`, then build an `FMIndex` from that `StringSet`.

When I `save` the index, I end up with N small files with names of the form `*.txt.[0-9]+`, where N is the number of reads in the `.bam` file, so I must be doing something incorrectly; I assume the FM-index's on-disk representation should not include thousands/millions of little files.

Can you help me understand how to correct my usage of the relevant APIs? Here is my sample program:

```
#include <seqan/bam_io.h>
#include <seqan/index.h>
#include <seqan/sequence.h>

using namespace seqan;
using std::string;

typedef Index<StringSet<String<Dna5> >, FMIndex<> > FMI;

int main(int argc, char** argv) {

	char* inPath = argv[1];
	string outPath = string(inPath) + ".fmi";

	printf("Building %s from %s\n", outPath.c_str(), inPath);

	BamFileIn bamFileIn(toCString(inPath));
	StringSet<String<Dna5> > reads;

	BamHeader header;
	readHeader(header, bamFileIn);

	BamAlignmentRecord record;
	int cur = 0;
	while (!atEnd(bamFileIn)) {
		readRecord(record, bamFileIn);
		appendValue(reads, record.seq);
		cur++;
	}

	printf("Built StringSet from %d reads\n", cur);

	FMI index(reads);
	indexCreate(index, FibreSA());
	save(index, outPath.c_str());

	printf("Wrote index to disk\n");

	return 0;
```

Sample output when run on a small BAM (1000 lines including header; 897 reads):

```
$ ./sample normal-1000.bam
Building normal-1000.bam.fmi from normal-1000.bam
Built StringSet from 897 reads
Wrote index to disk
```

After this I see files:

```
normal-1000.bam.fmi.lf.drp
normal-1000.bam.fmi.lf.drs
normal-1000.bam.fmi.lf.drv.wtc.0
normal-1000.bam.fmi.lf.drv.wtc.1
normal-1000.bam.fmi.lf.drv.wtc.2
normal-1000.bam.fmi.lf.drv.wtc.3
normal-1000.bam.fmi.lf.drv.wts.rtm
normal-1000.bam.fmi.lf.drv.wts.rtv
normal-1000.bam.fmi.lf.pst
normal-1000.bam.fmi.sa.ind
normal-1000.bam.fmi.sa.len
normal-1000.bam.fmi.sa.val
```

as well as 897 files of the form `normal-1000.bam.fmi.txt.N` for `N` in [0, 897).

Thanks!

**Comment by esiragusa** [comment]
Hi @ryan-williams, to remove the 897 files you have to load your reads in a ConcatDirect StringSet.

In addition, I suggest you to use a Levels FMIndex instead of the default WaveletTree FMIndex because it's more efficient for the Dna Alphabet. See doc at http://docs.seqan.de/seqan/develop/class_FMIndexConfig.html and a complex example at https://github.com/seqan/seqan/blob/develop/apps/yara/misc_types.h#L148.

**Comment by ryan-williams** [comment]
Thanks @esiragusa! I've built it now with updated types:

```
typedef StringSet<String<Dna5>, Owner<ConcatDirect<String<Dna5> > > > ReadSet;
typedef Index<ReadSet, FMIndex<> > FMI;
```

Indeed the many small files are gone, and instead there is a `normal.bam.fmi.txt.concat` that has all the read sequences concatenated.

One question I still have: typically an FM-index can avoid storing the entire indexed sequence; is there another tweak that will enable that?

Sorry if these questions are already answered in the (comprehensive!) docs; I'm not really grokking all of the template-type trickery yet. For example, I can't figure out how to "use a Levels FMIndex instead of the default WaveletTree FMIndex", any help with that would also be appreciated.

**Comment by cpockrandt** [comment]
Hi @ryan-williams,

indeed he FM-index is a self-index and does not need to store the text itself. This is not solved very well in SeqAn (yet) :smile:  and but you can avoid storing it by

    clear(getFibre(index, FibreText()));

The FMIndex can be specialized by two template parameters (by default it is ``FMIndex<void, FMIndexConfig<void> >``). The struct ``FMIndexConfig`` defines the data structures used by the FMIndex (e.g. WaveletTree or Levels, see https://github.com/seqan/seqan/blob/master/include/seqan/index/index_fm.h#L78). esiragusa changed among others the data structures to Levels for the LF-table in ``YaraFMConfig`` (so you can basically replace ``FMIndexConfig<...>`` by ``YaraFMConfig<...>`` or something different in your typedef declaration)

**Comment by h-2** [comment]
Are there still open questions, or can this be closed?

**Comment by h-2** [comment]
Please reopen if there are remaining issues.
