### ISSUE TITLE
Debug some cmake issues

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1448]
- activate SEQAN_FIND_DEBUG and SEQAN_STATIC_APPS
- run cmake on the directory
- see that e.g. yara has

`SEQAN_LIBRARIES            pthread;execinfo;elf;/usr/lib/libz.so;/usr/lib/libbz2.so`
- configure the build to only build yara, i.e. `SEQAN_BUILD_SYSTEM="APP:yara"`
- do the same, see that it prints:

`SEQAN_LIBRARIES            pthread;execinfo;elf;/usr/lib/libz.a;/usr/lib/libbz2.a`

→ in one case the static libraries are selected, in the other case not. Note that the apps is still built statically, but that some obscure workarounds are required (see seqan_register_apps in SeqAnBuildSystem.cmake) .

Possibly related:
https://cmake.org/cmake/help/v3.3/policy/CMP0060.html

**Comment by rrahn** [comment]
@h-2 Do we need to take care of this? If so please reopen, but I think the current version works for us as we need it and no one has time to dig into the cmake configs to fix this.
