### ISSUE TITLE
Massive performance problems in BAM reader

### ISSUE THREAD

**Issue by greenify** [seqan/seqan#1476]
Hey all,

Last week I tested the performance of multiple libraries to read BAM and your BAM reader is 14x slower than htslib and even 7x slower than SeqAn - so I don't know what's going on there, but you might want to have a look at it ;-)

For 70m reads (2.4G) it takes:

```
htslib 31s
bamtools 39s
pysam 59s
SeqAn 7m08s
```

You can find the test here:

https://github.com/greenify/bam-perf-test

**Comment by h-2** [comment]
Since you are not using SeqAn's build system, did you turn on optimizations yourself? i.e. for SeqAn you should use -03

@esiragusa can you have a look at this? Thank you!

**Comment by esiragusa** [comment]
@h-2 probably not before end next week. You might want to have a look yourself if it's important...

**Comment by h-2** [comment]
@esiragusa I won't have time in the next days... @rrahn if you have half an hour and want to get away from other things, feel free to checkout the benchmark!

**Comment by h-2** [comment]
@temehi since you work with the IO stuff a lot, can you have a look?

**Comment by esiragusa** [comment]
Yesterday I investigated this a bit.

I cloned the repo bam-perf-test, went into folder seqan and did ```cmake``` followed by ```make VERBOSE=1```:

```/usr/bin/c++    -DSEQAN_HAS_ZLIB=1 -std=c++11   -o CMakeFiles/prun_seqan.dir/main.cpp.o -c /home/esiragusa/Code/bam-perf-test/seqan/main.cpp```

I compared that with standard flags, e.g., compiling app samcat:
```
cd /Users/esiragu/Code/seqan-builds/Release-Gcc/apps/samcat && /opt/local/bin/g++-mp-4.9   -DSEQAN_APP_VERSION=\"0.3.2\" -DSEQAN_DATE=\"2016-02-17_16:36:09_+0100\" -DSEQAN_ENABLE_TESTING=0 -DSEQAN_HAS_EXECINFO=1 -DSEQAN_HAS_OPENMP=1 -DSEQAN_HAS_ZLIB=1 -DSEQAN_REVISION=\"f36ffd4\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/Users/esiragu/Code/seqan/include  -std=c++14  -W -Wall -Wno-long-long -fstrict-aliasing -Wstrict-aliasing -pedantic -Wno-variadic-macros -fopenmp -O3 -DNDEBUG -DSEQAN_ENABLE_DEBUG=0    -DSEQAN_GLOBAL_EXCEPTION_HANDLER -o CMakeFiles/samcat.dir/samcat.cpp.o -c /Users/esiragu/Code/seqan/apps/samcat/samcat.cpp
```

@greenify **You might want to add these flags: ```-O3 -DNDEBUG -DSEQAN_ENABLE_DEBUG=0```**

@h-2 do you know how to tell cmake where seqan sources are? I did ```cmake  . -DCMAKE_MODULE_PATH=~/Code/seqan/util/cmake``` but finds only FindSeqAn.cmake, not the headers.

**Comment by h-2** [comment]
> @greenify You are missing these flags/defines: -O3 -DNDEBUG -DSEQAN_ENABLE_DEBUG=0 -DSEQAN_ENABLE_TESTING=0

I would really good to know if this makes a difference. If yes we should definitely change the default behaviour...

> @h-2 do you know how to tell cmake where seqan sources are?

Thats what `FindSeqan.cmake` is for. It sets `SEQAN_INCLUDE_DIRS`.

**Comment by esiragusa** [comment]
@h-2 cmake with ```-DCMAKE_MODULE_PATH=~/Code/seqan/util/cmake``` did find FindSeqAn but it didn't set the includes folder... I've never tried this before so I am unsure whether that is the correct way of doing it.

**Comment by esiragusa** [comment]
I am unsure about the effect of ```-DSEQAN_ENABLE_DEBUG=0 -DSEQAN_ENABLE_TESTING=0``` but ```-O3 -DNDEBUG``` is definitely required.

**Comment by h-2** [comment]
@esiragusa we will investigate the flags in general and the include behaviour

@greenify can you tell us whether setting the flags changes your numbers? That would be very helpful. Also please give us the specs of the system the test was run on and whether multi-threading was available. Thank you very much!

**Comment by greenify** [comment]
@ all: thanks a lot for your interest and help. I didn't expect to cause such an active discussion :)

Actually `-O3` brings it down to 30s

And with `-DNDEBUG` enabled too it get down to `17s` and yes with that it's nr. 1 on my simple benchmark ;-)
(the other mentioned flags had to impact)
FYI I also checked whether `-O3` just removes the serialization, but it doesn't - so no worries there. 

Do you have any idea(s) why a non-optimized build is so slow?
(I just verified the runtime again)

I guess one major difference might be that with the optimized build all my eight cores are used with nearly 100% and without `-O3` it doesn't use multi-threading?
(at least that's what I see in my resource manager)

> Also please give us the specs of the system the test was run on and whether multi-threading was available. Thank you very much!

i7 4700MQ (8 cores, 16GB RAM, SSD) - Arch Linux.

Thanks again!

**Comment by greenify** [comment]
@esiragusa 

> @greenify you should add find_package (SeqAn REQUIRED) to seqan/CMakeLists.txt. That might add SEQAN_* missing defines.

Hmm I installed seqan via [seqan-git](https://aur.archlinux.org/packages/seqan-git) - it roughly equals doing a `make install` (on the git repo), but installed as a package.

I am not an expert with cmake any case, but as far as I understood it, because SeqAn is in my header files (=`/usr/include/seqan/`) I compile it into my program, whereas Zlib is linked as a dependency library. Therefore `find_package` and `target_link_libraries` for ZLib.

**Comment by esiragusa** [comment]
@greenify we are proud of SeqAn's speed :smile: Did you add ```-DSEQAN_ENABLE_DEBUG=0 -DSEQAN_ENABLE_TESTING=0``` as well? Time ago we had measured a 4x speedup over htslib. Optimization doesn't affect multithreading. The speedup is partially due to inlining. The defines remove debug assertions.

**Comment by h-2** [comment]
@greenify To be fair, I think you should build the other tests with `-O3` as well, although I think it won't make a big difference because it is calling the functions in the installed libraries anyway.
It would be interesting to also see write-speeds and maybe a bam→sam conversion as a real world example. What do you think?

Concerning the finding of paths, that is completely unrelated and we will resolve that in different tickets...

**Comment by marehr** [comment]
@greenify I would like to rerun your benchmark and make the ```-DNDEBUG``` default behaviour, for that I need the used bam file.

Could you provide me the link to the used bam file?

**Comment by greenify** [comment]
> maybe a bam→sam conversion as a real world example. What do you think?

Yep I thought about this too - I will do this once I have a bit of time.

@marehr - it's just randomly simulated from chr1, but feel free to use it ;-)
https://drive.google.com/file/d/0BwdiZp7qSaBhU2RQb2hTaGtFRGc/view?usp=sharing

**Comment by marehr** [comment]
@greenify I ran your benchmark with different compiler flags and took the median out of three runs.
specs: i7-3770K CPU @ 3.50GHz (8 cores), 32GB RAM, SSD

@h-2 As you can see, seqan performs best by only setting `-O3` after pr #1493. There was only a 15% performance increase, not 100% like @greenify had.

@greenify Maybe you could rerun the benchmark with my fix and verify my results?
```
git clone git@github.com:marehr/seqan.git -b task/cleanup_debug_flags-1486
```

### current master 26b9af47dd11e9344e896d46e578c8356187deec VS pull request 1aa3d6b6a1b7ce548bc4ace905640d4e11da8a3d:

```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DSEQAN_HAS_ZLIB=1 -std=c++11")
```

current | master |  | after fix
---|---|---|---
real | 3m14.370s | | 3m9.999s
user| 4m19.084s | | 4m13.000s
sys | 0m9.320s | | 0m9.432s

```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DSEQAN_HAS_ZLIB=1 -std=c++11 -O3")
```

current | master |  | after fix
---|---|---|---
real |	**0m12.068s** | | **0m10.288s**
user |	1m9.224s | | 1m8.520s
sys |	0m1.528s | | 0m1.236s

```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DSEQAN_HAS_ZLIB=1 -std=c++11 -O3 -DNDEBUG")
```

current | master |  | after fix
---|---|---|---
real | 0m10.029s | | 0m10.035s
user | 1m8.296s | | 1m8.448s
sys | 0m1.180s | | 0m1.100s

```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DSEQAN_HAS_ZLIB=1 -std=c++11 -O3 -DSEQAN_ENABLE_DEBUG=0 -DSEQAN_ENABLE_TESTING=0")
```

current | master |  | after fix
---|---|---|---
real |	0m10.029s | | 0m10.261s
user |	1m8.384s | | 1m8.664s
sys |	0m1.012s | | 0m1.116s

```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DSEQAN_HAS_ZLIB=1 -std=c++11 -O3 -DNDEBUG -DSEQAN_ENABLE_DEBUG=0 -DSEQAN_ENABLE_TESTING=0")
```

current | master |  | after fix
---|---|---|---
real |	0m10.055s | | 0m10.038s
user |	1m8.552s | | 1m8.420s
sys |	0m1.016s | | 0m1.100s

**Comment by h-2** [comment]
@marehr thanks for the extensive analysis, I will merge your PR.

**Comment by h-2** [comment]
@greenify I will now also close this issue, although, I would still be interested in rread/write or bam->sam tests, so if you do make them, please let us now!
