### ISSUE TITLE
investigate using precompiled headers

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1485]
https://lists.fu-berlin.de/pipermail/seqan-dev/2016-February/msg00000.html

@xenigmax could you have a look at this in the next two weeks? Thanks!

**Comment by xenigmax** [comment]
I can make precompiled header without any problem (g++ 4.9, Debian). 
So it's another compatibility problem I think.
He is using mac I'm going to ask him more information.

**Comment by h-2** [comment]
Can you figure out how this interacts with cmake? It would be great if we could change our build system so that it automatically pre-compiles all headers, before doing a full build of SeqAn. It could possibly speed up our nightly builds and continuous integration significantly!

Thanks!

**Comment by xenigmax** [comment]
OK. I will resolve the user's situation first. And then I will check it.

**Comment by h-2** [comment]
> OK. I will resolve the user's situation first. And then I will check it.

:+1: 

> However, "seq_io.h.pch" is about 120 MB.
> We may need more space for other headers.

Yep, I was expecting that.

> Let's consider it before make it "default"

That's true. It would only befault for nightly or travis anyway I think, but it would be good to have it as a build option!

**Comment by xenigmax** [comment]
I reassign this to backlog. Refer to #1477

**Comment by h-2** [comment]
Closed because inactivity.
