### ISSUE TITLE
fix FindSeqAn.cmake

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1487]
it doesn't set include-paths correctly :facepunch:

**Comment by h-2** [comment]
@esiragusa I had initially installed SeqAn with wrong permissions. After fixing that stand-alone tools and `find_package(SeqAn)` work correctly.
Can you clarify in which situations you are running into problems?

**Comment by esiragusa** [comment]
@h-2 I didn't want to install seqan. I wanted to let it use my git sources.

**Comment by h-2** [comment]
@esiragusa Then you always need to give the path as SEQAN_INCLUDE_PATH, sorry about the confusion.

**Comment by h-2** [comment]
Does this work for you?  Can we close the issue?

**Comment by esiragusa** [comment]
I thought it was enough to find FindSeqAn.cmake so it would set SEQAN_INCLUDE_PATH to ../../include/seqan (assuming util/cmake/FindSeqAn.cmake).

**Comment by h-2** [comment]
I don't think cmake files know where they are in the filesystem. In fact this is quite hard to find out, also for shell scripts or even c-programs. But if you have a solution, I would gladly integrate it.

**Comment by esiragusa** [comment]
Don't you know ```-DCMAKE_MODULE_PATH=<seqan-root>/util/cmake```? How do other cmake modules solve that?

**Comment by h-2** [comment]
What does the MODULE_PATH have to do with the INCLUDE_PATH? I don't think the FindModule.cmake files are supposed to work if the project is not installed... also because the relative position of the cmake file towards the includes can change arbitrarily between "source tree" and "installed state".
But maybe I still don't understand what you are trying to do :confused:

**Comment by esiragusa** [comment]
Ok never mind, maybe I expected too much magic from cmake...
