### ISSUE TITLE
Cannot use Seqan in eclipse

### ISSUE THREAD

**Issue by Patg13** [seqan/seqan#1496]
Hello

I'm trying to use the seqan library in eclipse but I can't make it work

Eclipse detect seqan files (includes work), but when I use seqan:: or using namespace seqan, it give me this error message : Symbol seqan could not be resolve

I didn't import seqan as a project in eclipse, I just install the libraries using the seqan tutorial

Do I have to add something to GCC C++ Linker ?

Can you help me please ?

**Comment by Patg13** [comment]
Ohh my bad, I just make it work...

I was missing the -pedantic and the -lrt flag

Sorry for that...

**Comment by marehr** [comment]
@Patg13  Since you solved your problem, I close the issue.
