### ISSUE TITLE
update/fix dox website

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1501]
@xenigmax can you 
  - [x] add dox for 2.0.2 and 2.1.0 on our website
  - [x] check why the current dox for 2.0.1 is broken? There are a lot (null) logos where there should be (Class) or (Enum), also functions don't seem to be listed at all...

Thank you!

**Comment by xenigmax** [comment]
1. 2.0.2, 2.1.0 => done.
2. I tried to change this using http://packages.seqan.de/seqan-library/seqan-library-2.0.1.zip but it shows the same result (http://docs.seqan.de/seqan/2.0.1-2/). @h-2  How can we handle this properly?

**Comment by xenigmax** [comment]
All the versions after 2.0.0 can't produce correct dox using "make package". 
- I will open an issue about this.

I made dox for 2.0.1 from the source and it's updated.
Maybe we can close this issue.

**Comment by xenigmax** [comment]
I've updated library releases from 2.0.0 to 2.1.0 at http://packages.seqan.de using #1514 
You can find old versions(which contain incorrect dox) at http://packages.seqan.de/seqan-library/backup_010316/
