### ISSUE TITLE
Mason2 download links on packages.seqan.de 403 forbidden

### ISSUE THREAD

**Issue by kdmurray91** [seqan/seqan#1518]
Hi,

The download links for mason2 version > 2.0.1 seem broken. Both 2.0.2 & 2.0.3 fail with a 403 forbidden error code. I'm just using wget:

    wget http://packages.seqan.de/mason2/mason2-2.0.3-Linux-x86_64.tar.xz

Thanks in advance,
Kevin

**Comment by h-2** [comment]
sorry about that, should be fixed now!
