### ISSUE TITLE
seqan-2.1.0.tar.xz checksum changed

### ISSUE THREAD

**Issue by tdsmith** [seqan/seqan#1519]
Hello, it appears that the checksum of seqan-2.1.0.tar.xz (accessible from https://github.com/seqan/seqan/releases/download/seqan-v2.1.0/seqan-library-2.1.0.tar.xz) has changed since February 16.

On the 16th, the sha256 checksum was 97bbeffcb059d650e4bdf6ffcd3d585910a382525a1a5054941eb080df0c88d2. Today, it is 986a55d028fb08e0befc538af927cbcfb880e7d4402f9b008d09f76abe63f86e. Was this change intentional?

Thanks!

**Comment by xenigmax** [comment]
Yes. It was intentional. The old version contained incorrect documents in /share/dox.
That's the only change. Please let us know if you find any problem.

**Comment by h-2** [comment]
We know changing the package after the release isn't great, but the we were pretty sure downstream packages hadn't yet picked up the tarballs (also we know that e.g. debian uses the "full" tarballs, which are unchanged, not the library tarballs).
What is your usecase / how did you notice? If more people rely on this we can make a policy to always bump version in the future.

**Comment by tdsmith** [comment]
Brilliant; thanks for the explanation. Please feel free to close this issue. :)

Homebrew is a rolling-release package manager for OS X which uses checksums to verify download integrity; homebrew-science builds its `seqan` package from seqan-library tarballs. Our fast-fingered maintainer @sjackman updated our formula and captured the checksum on the 16th. I noticed because our CI was complaining about a checksum mismatch when seqan was used as a dependency of another package under test.

**Comment by h-2** [comment]
> Homebrew is a rolling-release package manager for OS X

Ah, great to see we are on homebrew, thanks! The MacPorts are maintained by us and unfortunately still outdated.

> homebrew-science builds its seqan package from seqan-library tarballs

That is very much how we intend it. We will try to make sure these packages are not changed 'in-place' in the future.
