### ISSUE TITLE
Add SeqAn apps to Bioconda

### ISSUE THREAD

**Issue by esiragusa** [seqan/seqan#1547]
See https://bioconda.github.io/

**Comment by esiragusa** [comment]
@h-2 FYI

**Comment by h-2** [comment]
Looks interesting but won't be done for 2.2.0

**Comment by esiragusa** [comment]
@h-2 FYI somebody added [yara](https://anaconda.org/bioconda/yara) and [razers3](https://anaconda.org/bioconda/razers3).

**Comment by h-2** [comment]
Blocked by ContinuumIO/anaconda-recipes#67

**Comment by h-2** [comment]
@esiragusa @weese On a more general note: I will not add SeqAn apps to other package management systems if these apps are not maintained any longer. We have many open issues for both Yara and RazerS. Increasing the visibility of these apps will just increase the amount of reports we get.
Unless you make an effort to react to issues regarding the apps or find new maintainers, Yara and RazerS will be marked as legacy apps with the other apps (probably at the end of this year).

**Comment by h-2** [comment]
Closed because inactivity.
