### ISSUE TITLE
a test failed on win32/64 

### ISSUE THREAD

**Issue by xenigmax** [seqan/seqan#1557]
This should be fixed before the release.

http://cdash.seqan.de/viewTest.php?onlyfailed&buildid=168955

test_demo_tutorial_indices_base	Failed	340ms	Completed (Failed)

**Comment by cpockrandt** [comment]
We didn't manage to fix it yet :sweat: but @smehringer and me figured out in which cases the tests fails.

The following example works:

    const char * tmpFilename = SEQAN_TEMP_FILENAME();
    Index<String<Dna>, IndexEsa<> > index("ACGT");

    save(index, tmpFilename);
    open_index, tmpFilename);

    ClassTest::_deleteTempFile(ClassTest::_stripFileName(tmpFilename));

As soon as we use an ``FMIndex`` or an external string such as ``String<Dna, External<>>`` the directory cannot be deleted anymore.

**Comment by cpockrandt** [comment]
I think I narrowed it down. As expected, the problem occurs, when an external string is stored in the directory (which happens if the index is built on an external string or the FM index is built, since it is built in external memory).

Who is responsible for external strings? :trollface:

**Comment by xenigmax** [comment]
>Who is responsible for external strings? :trollface:

You know the answer. :cry:

**Comment by xenigmax** [comment]
@cpockrandt 
Does #1574 close this issue as well?

**Comment by xenigmax** [comment]
I think it's a problem of Windows.

I tried this and found that all the files are actually not deleted right after "DeleteFile" call.
So the RemoveDirecroy returns "error code145" always which means "not empty".

It seems DeleteFile just marks files to "to be deleted".

**Comment by cpockrandt** [comment]
We did some research about it as well, and I think you're right, that the directories are not removed immediately. However I think that directories that contained an external String cannot and will not be removed at all.

**Comment by xenigmax** [comment]
There should be an additional effort for that, especially with close function.
http://docs.seqan.de/seqan/master/?p=ExternalString#ExternalString%23close

However, for this issue, let's find a way to delete temporary files anyway (which is working on linux)..

**Comment by smehringer** [comment]
Maybe this could be an alternative to `DeleteFile` when deleting temporary files:

> To recursively delete the files in a directory, use the [SHFileOperation](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762164%28v=vs.85%29.aspx) function.

**Comment by smehringer** [comment]
The second answer to this StackOverflow question gives an example

http://stackoverflow.com/questions/213392/what-is-the-win32-api-function-to-use-to-delete-a-folder

**Comment by cpockrandt** [comment]
We checked it, doesn't work either :wink:

**Comment by xenigmax** [comment]
OK.. We have spent enough time to make a decision for this.
I think there are 2 solutions for this.

1) 
By using Win32 API, investigate all the handles that are attached to specific files and unlock them. (and delete them..)

2)
Fix/add "close" function for data structures that use external storage (external string, indices with external strings..) and modify every line to use it.

I think none of them is possible within 1~2 days. So I would like to turn off the warning messages just like before(to make it pass the test) and wish to move this issues to another milestone.

@h-2, @rrahn What do you think?

**Comment by xenigmax** [comment]
We will try to fix it today. But we have to change the milestone if we can't make it.

**Comment by marehr** [comment]
@h-2 should be resolved
