### ISSUE TITLE
nightly-built doc

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1566]
the current documentation at docs.seqan.de/seqan/master is actually older than docs.seqan.de/seqan/2.1.0 .
This is really confusing, can we get dox nightly builds for the server?

**Comment by xenigmax** [comment]
> the current documentation at docs.seqan.de/seqan/master is actually older than docs.seqan.de/seqan/2.1.0 
Maybe it's related to #1501. But the content is OK. Is this right?

> This is really confusing, can we get dox nightly builds for the server?
I will do that if you tell me where it is.

**Comment by h-2** [comment]
> But the content is OK. Is this right?

Yes, its just outdated, I think.

> I will do that if you tell me where it is.

Where what is? :smile: The dox? In /web/docs.seqan.de

**Comment by xenigmax** [comment]
@h-2 I thought that you asked me to do something about nightly build as well.
If it's not. That's fine. I will update it. :)

**Comment by cpockrandt** [comment]
I think we should automatize it in the long run, but not for Release 2.1.1

**Comment by h-2** [comment]
I agree, please update it manually, and then we can switch to nightlies later.

**Comment by rrahn** [comment]
I reenabled the hourly update of the dox for master and develop.
Let's see if it works.
