### ISSUE TITLE
Strange behaviour of indexed fasta I/O when building an index twice

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan#1573]
This issue occurs in the following demo file:
> demos/tutorial/indexed_fasta_io/base.cpp

The function `getIdByName()` raises the error, that it cannot find "chr1". The _example.fasta_ file does contain a sequence named "chr1" though.

If you try out `std::cout << empty(faiIndex) << std::endl;`, it returns `1`. 

Strangely, after `getIdByName()` fails, `sequenceLength()` successfully fetches the length of the sequence. But `empty(faiIndex)` still returns `1`...

This is not a problem for the tutorials, since the file is not included in any assignment.
@temehi can you take a look at it? Maybe some time after the release.

**Comment by smehringer** [comment]
@cpockrandt can you please add labels, Milestone and Assignee.

**Comment by temehi** [comment]
@cpockrandt you may close this issue now

**Comment by cpockrandt** [comment]
Oops, forgot it. Thanks!
