### ISSUE TITLE
test of demo file passes even when the stdout was not as expected.

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan#1576]
I found the following two tests which passed, even if the stdout was not as expected.

http://cdash.seqan.de/testDetails.php?test=27779920&build=169398
http://cdash.seqan.de/testDetails.php?test=27779935&build=169398

They both have in common that the stored .stdout file was empty. 

This shoud not happen, should it?
Or is there some special case where a test is allowed to have different standard output?

@xenigmax can you assign someone who might know this?

**Comment by xenigmax** [comment]
@h-2  
What is the behind story about this?

**Comment by h-2** [comment]
I habe no clue to be honest...

**Comment by temehi** [comment]
I have some clue,

 <a href="https://github.com/seqan/seqan/blob/master/util/bin/demo_checker.py#L88">Here</a>  The python code 

    return not (**expected_out == expected_out** and expected_err == actual_err)

It should have been 

    return not (expected_out == actual_out and expected_err == actual_err)

**Comment by temehi** [comment]
I will make a pull request, Let's hope this won't reveal a lot of reds at cdash :pray:

**Comment by h-2** [comment]
@temehi good catch! this could actually reveal some more errors in demos...

**Comment by temehi** [comment]
@h-2 it did, 19 of them. see my comment at #1579.
