### ISSUE TITLE
Adjust members to naming scheme

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#158]
There are still some member variables that do not follow the naming scheme:
- `BamAlignmentRecord::rNextId` -> `BamAlignmentRecord::rNextID`
- `GenomicRegion::seqId` -> `GenomicRegion::seqID`

Also, all fragment store members and related types should be rechecked.

**Comment by h-2** [comment]
Ok, I did some regular expression voodoo to find stuff with too many CAPs first and I have made this list of conversions:
```
LCPcopy          -> lcpCopy
SAQSort          -> SaqSort
SVGFile          -> SvgFile
WTRDConfig       -> WtRdConfig (?)
checkDBIds       -> checkDbIds (?)
countCHG         -> countChg
countCHH         -> countChh
counterTMP       -> counterTmp
createSABTree    -> createSaBTree (?)
currRID          -> currRId (?)
isLCPTable       -> isLcpTable
localTVD         -> localTvd
maxLCP           -> maxLcp
outputCNV        -> outputCnv
outputSNP        -> output SNP
pdfCHG           -> pdfChg
pdfCHH           -> pdfChh
similarBPId      -> similarBpId (?)
sizeofSABTree    -> sizeofSaBTree (?)
statsCHGMethylated -> statsChgMethylated
statsCHHMethylated -> statsChhMethylated
streamEOF        ->  streamEof
testCSPImpl      -> testCspImpl
testMPMCQueue    -> testMpmcQueue
wTMP             -> wTmp
writeCLIElement  -> writeCliElement
writeCTD         -> writeCtd
```
For some composite abbreviations I was really unsure, e.g. WaveletTree is abbreviated WT and RankDictionary is abbreviated RD, so is WaveletTreeRankDictionary abbreviated WTRD, Wtrd, or WtRd? I think the last one is the most readable, so thats what I used. 
What about DatabaseIdentifiers? Is that DBID, Dbid, DbID, oder DbId?

Btw: I neither think `getIDByName` is more readable than `getIdByName` nor `rNextID` than `rNextId`. Can't we just agree on `Id` for `Identifier`, the two letter don't even represent two words :weary: 

Altogether this PR seems like a lot of :nail_care: to me, I think we have bigger issues and should just use common sense and readability for these kind of things...

**Comment by rrahn** [comment]
Let us first get the nightly/continues builds green. These are no compelling changes for the release.
We can discuss adaptions of some naming schemes after the release.

**Comment by esiragusa** [comment]
I move this to the backlog. Now that all builds are green, making such a change seems to me like a suicide... @h-2 @rrahn agreed?

**Comment by holtgrewe** [comment]
Hm, I think we at least have to deal with the identifiers containing `Id`/`ID`. In the `BamAlignmentRecord` class, we have `rID` but `rNextId` which makes the class itself inconsistent.

**Comment by rrahn** [comment]
Is taken care of in SeqAn 3
