### ISSUE TITLE
app_test_razers/app_test_stellar timeouts after 600s (performance degrade)

### ISSUE THREAD

**Issue by xenigmax** [seqan/seqan#1586]
http://cdash.seqan.de/testDetails.php?test=31266148&build=169958

**Comment by xenigmax** [comment]
@marehr 
I'm not sure whether it's related to #1577 or not.
But.. can you take a look? Thanks!

**Comment by marehr** [comment]
There is a performance degrade on windows for app_test_razers and app_test_stellar (master & nightly)
15.03. 907a7a4c06ee50dd7309a081db4cffa3b618fe8e (master) (~34s)
16.03. f98f8a9eb67ebd1aaf834d8c0c8ce4c75a92c67d (master) (~480s)

I will try to find out which commit is the cause.

**Comment by xenigmax** [comment]
Now it's getting worse.. But we have to fix this 

flag test_test_store	Failed	10m 30ms	Completed (Timeout)
flag test_demo_tutorial_fragment_store_access_aligned_reads	Failed	10m 590ms	Completed (Timeout)
flag test_demo_tutorial_fragment_store_access_aligned_reads2	Failed	10m 630ms	Completed (Timeout)
flag test_demo_tutorial_fragment_store_display_aligned_reads	Failed	10m 330ms	Completed (Timeout)
test_demo_tutorial_indices_base	Failed	550ms	Completed (Failed)
flag app_test_micro_razers	Failed	10m 260ms	Completed (Timeout)
flag app_test_rabema	Failed	10m 50ms	Completed (Timeout)
flag app_test_razers	Failed	10m 60ms	Completed (Timeout)
flag app_test_snp_store	Failed	10m 260ms	Completed (Timeout)
flag app_test_stellar	Failed	10m 340ms	Completed (Timeout)

**Comment by marehr** [comment]
I (possibly) found the culprit. This seems to be a windows-only problem, on the other platforms I couldn't measure/see a performance degrade in cdash. The pull request #1594 reverts some commits that @h-2 hannes introduced. I hope this solves the problem temporarily.

I think it has to do something with the different code generator used for Visual Studio.
