### ISSUE TITLE
Different gapOpen/Extension cost in seed extension

### ISSUE THREAD

**Issue by xenigmax** [seqan/seqan#1596]
This line prevents a use of different gapOpen/Extension cost.
https://github.com/seqan/seqan/blob/master/include/seqan/seeds/seeds_extension.h#L799

**Comment by rrahn** [comment]
There is a another extension implementation in align_extend which allows to use affine gap costs as well. 
We need to unify the extension module and make use of the dp code for the 3.0 release.

**Comment by h-2** [comment]
@xenigmax unless you want to implement this for the seed extension I will close this for now. align_extend can be used instead.
