### ISSUE TITLE
Amino acid alphabet size: doc and source files disagree

### ISSUE THREAD

**Issue by simon-m** [seqan/seqan#1622]
The amino-acid alphabet size as in the documentation for seqan 2.0 is 27 ("The ValueSize of AminoAcid is 27"), whereas it is 26 in /basic/alphabet_residue.h
The reason is that "O" is mentioned in the doc but not included in the source code.

**Comment by marehr** [comment]
Thank you for your report. We have this week the Seqan UGM. Therefore, there might be a slight delay to answer your question.

@rrahn I think you know a bit more about this than me :wink:

**Comment by rrahn** [comment]
@simon-m can you please give me the line, where the implementation only has 26 residues?
In ```basic/alphabet_residue.h``` the ```ValueSize``` is 27.
See here https://github.com/seqan/seqan/blob/master/include/seqan/basic/alphabet_residue.h#L555.

I double checked the scoring matrix implementations. They all feature 27 residues.
Thanks a lot.

**Comment by simon-m** [comment]
Hi,
OK, I just checked the following archive http://packages.seqan.de/seqan-src/seqan-src-2.0.0.tar.gz which I am using and I have the following (line 555):
```
struct AminoAcid_ {};
typedef SimpleType<unsigned char, AminoAcid_> AminoAcid;

template <> struct ValueSize<AminoAcid>
{
    typedef __uint8 Type;
    static const Type VALUE = 26;
};
```
Also, all my matrices are 26x26 and have no "O". 

However the docs at http://docs.seqan.de/seqan/2.0.0/ tell me that "The ValueSize of AminoAcid is 27".

Perhaps I should move to a more recent version.
Thanks,

Simon

**Comment by rrahn** [comment]
Oh, I am sorry for this bug.
Yes the most current version is 2.1.1. 
There it should be fixed.
