### ISSUE TITLE
[DOX] No documentation for the constructor of the LocalAlignmentEnumerator class 

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan#1638]
If you take a look, there is no documentation of the constructor:
http://docs.seqan.de/seqan/master/index.html?p=LocalAlignmentEnumerator

same here:
class Score http://docs.seqan.de/seqan/master/index.html?p=Score
class Index http://docs.seqan.de/seqan/master/index.html?p=Index

**Comment by smehringer** [comment]
@rrahn I just took a look into the files and I now think this issue is not an issue

All of the mentioned classes above are superior to several subclasses and only the subclasses do have a constructor (which is documented). So there is no need for a constructor documentation.

**Comment by rrahn** [comment]
I see, the class is more like a abstract class.
It says in the description that one should look into the specialisations for more information, but I think it would be good to also point out, that this is an abstract class which is not instantiated, but one of it's subclasses. Can you add a short sentence to the description?

**Comment by smehringer** [comment]
Sure, but can you tell me where exactly I should put the sentence or what you mean by the "description". Is there an optional parameter like *@description* ? Or do you mean the *@brief* tag that appears right under the class name?

**Comment by smehringer** [comment]
Or further down in the Detailed Description part? Maybe It's better so state this at the beginning of the page..

**Comment by rrahn** [comment]
I think in the description will suffice.
We actually would need something like a tag or so for our dox to differentiate abstract classes from others.

**Comment by smehringer** [comment]
ok

**Comment by rrahn** [comment]
@smehringer Can you make a PR for the updated descriptions?
