### ISSUE TITLE
Outdated contribs for Windows

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan#1664]
Our manual links to contrib packages from 2013, not the latest from 2016. See http://seqan.readthedocs.org/en/master/Infrastructure/Use/InstallDependencies.html

We should link instead to the ones from 2016, check http://ftp.seqan.de/contribs/ for the latest version.

**Comment by rrahn** [comment]
There is already a PR, waiting for updates #1618 to be merged.
