### ISSUE TITLE
Better packages

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1667]
CPack can generate `.dmg` for Mac; `.deb` and `.rpm` for Linux and proper installers for Windows. Why aren't we doing this? Also we should have optimized builds and unoptimized.

i.e.

**Yara**

Version  | Linux                                          | Mac                              | FreeBSD          | Windows
----------  | ----------------------------------------- | -------------------------------| -------------------- | -------------
0.9.6      | 32bit: [tar.xz]() [deb]() [rpm]()     | 32bit: [tar.xz]() [dmg]() | 32bit: [tar.xz]()  | 32bit: [zip]() [exe]()
              | 64bit: [tar.xz]() [deb]() [rpm]()     | 64bit: [tar.xz]() [dmg]() | 64bit: [tar.xz]()  | 64bit: [zip]() [exe]()
              | sse4: [tar.xz]() [deb]() [rpm]()     | sse4: [tar.xz]() [dmg]() | sse4: [tar.xz]()  | sse4: [zip]() [exe]()
0.9.5      | 32bit: [tar.xz]() [deb]() [rpm]()     | 32bit: [tar.xz]() [dmg]() | 32bit: [tar.xz]()  | 32bit: [zip]() [exe]()
              | 64bit: [tar.xz]() [deb]() [rpm]()     | 64bit: [tar.xz]() [dmg]() | 64bit: [tar.xz]()  | 64bit: [zip]() [exe]()
              | sse4: [tar.xz]() [deb]() [rpm]()     | sse4: [tar.xz]() [dmg]() | sse4: [tar.xz]()  | sse4: [zip]() [exe]()

**Comment by h-2** [comment]
@xenigmax can you look at this?

**Comment by h-2** [comment]
One part of this would be to add something like
```cmake
if ((CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")  AND (SEQAN_ARCH_SSE4))
    set (CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64_sse4") 
endif()
```
to https://github.com/seqan/seqan/blob/master/util/cmake/SetCPackSystemName.cmake#L46

This will guarantee that the files have different names. Than you can also check for `x86_64_sse4` in the web-site generation.

For the different package types it *should be* enough to add the extensions to 
https://github.com/seqan/seqan/blob/master/util/cmake/package.cmake#L52 and
https://github.com/seqan/seqan/blob/develop/util/cmake/SeqAnBuildSystem.cmake#L411

**Comment by xenigmax** [comment]
@h-2 @esiragusa @rrahn 
I think the optimization option described in #1668 should be seprated from this.
I will be working on packaging(deb, rpm) and necessary changes for release prcoess.

Assign me #1668 if you want. But I'm not sure whether you guys made a consensus about this.

**Comment by h-2** [comment]
Well @esiragusa was in favor of sse4 vs sse3 and I am convinced that this is right, too, now, especially with popcnt. But we should have unoptimized builds, as well, thats why 64bit+sse4.
Since you have to edit the files anyway, I think doing this in one go would be good.

**Comment by xenigmax** [comment]
@h-2 . OK. Then I will do it.
I have another concern. :)
Cpack uses NSIS for windows installation binaries and it follows zlib license. 
https://en.wikipedia.org/wiki/Zlib_License
Is this OK?

**Comment by h-2** [comment]
> (1) license
> Cpack uses NSIS for windows installation binaries and it follows zlib license. 
> https://en.wikipedia.org/wiki/Zlib_License
> Is this OK?

Yes.

> (2) dependency
> And to use this feature, one have to install several files from NSIS and this will make another dependency to the project. Is this OK?

It wouldnt be a deoendency of "the project" just of the RPM, thats no problem.

> [...]
> If it's true, we can't generate .dmg in unix/linux enviroment which is our standard in general.
> Is this OK as well?

Binaries and packages for macOS have to be built on macOS anyway so its no additional dependency.

**Comment by xenigmax** [comment]
OK. Then I will talk about window-build with Chris and mac-build with Themesgen or Rene.

**Comment by xenigmax** [comment]
closed by 

1) https://github.com/seqan/seqan/issues/1781
2) https://github.com/seqan/packages.seqan.de/pull/2
