### ISSUE TITLE
Optimization level of app packages

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1668]
I'd like to reopen this. Right now we are specifying `-msse4`. I thought this was the intersection of SSE4 extension supported by AMD and Intel, but apparently it means `-msse4.1 -msse4.2` which is not supported by AMD barcelona (which e.g. I have at home so it is not extremely old).
I propose removing `-msse4` again so that we have `-mmmx -msse -msse2 -msse3 -mpopcnt`.
 Although not listed on  https://gcc.gnu.org/onlinedocs/gcc-4.9.0/gcc/i386-and-x86-64-Options.html POPCNT is actually supported on AMDs >= barcelona.

@esiragusa @rrahn what do you think?

**Comment by esiragusa** [comment]
I have a great idea :bulb: Why don't you sell your AMD processor on ebay? :trollface: 

Ok seriously, I don't know how much we would loose without -msse4. I can try Yara. Did you try Lambda?

**Comment by h-2** [comment]
> Why don't you sell your AMD processor on ebay? :trollface:

I think they would only give me 5$ :sob: 

> Did you try Lambda?

I am checking...

**Comment by h-2** [comment]
Hmmm, it seems to be the important factor:

| flags                                                                                               | time           |
|-----------------------------------------------------------------------------------|---------------|
|  (none)                                                                                           | 118.4s       |
|`-mmmx -msse -msse2 -msse3`                                                       | 117.3s       |
|`-mmmx -msse -msse2 -msse3 -mssse3 -msse4 -mpopcnt`             | 104.1s      |
|`-mmmx -msse -msse2 -msse3 -mssse3 -msse4 -mpopcnt -mavx`   | 103.4s      |

**Comment by esiragusa** [comment]
Interesting, thanks! Then I think we should keep -msse4. Do you agree?

**Comment by h-2** [comment]
Not sure, maybe we should add sse4 as an extra architecture besides 32bit and 64bit?

**Comment by esiragusa** [comment]
Only for AMD barcelona? Then I would distribute legacy binaries that work for any i686.

**Comment by h-2** [comment]
> Only for AMD barcelona?

No, it affects intel core and core 2, as well, including some series of Macbooks...

**Comment by esiragusa** [comment]
Well all that is not HPC... :wink:

**Comment by h-2** [comment]
will be resolved by #1667

**Comment by h-2** [comment]
This will be resolved by #1667. There will be both unoptimized x86_64 builds and x_86_64_sse4 which also include popcnt.
