### ISSUE TITLE
softcode fasta file extension in Mason

### ISSUE THREAD

**Issue by tseemann** [seqan/seqan#1670]
It appears the apps only support `.fa` and `.fasta`.

NCBI has a pseudo-standard of 
- `.fna` for genomic contigs
- `.faa` for protein sequences
- `.frn` for nucleotide RNA features
- `.ffn` for nuceotide DNA features (or just CDS)

**Comment by h-2** [comment]
Thanks for the feedback!

As you can see here:
https://github.com/seqan/seqan/blob/master/include/seqan/seq_io/fasta_fastq.h#L109
all of the extensions are actually supported.

But maybe some apps hard-code the extensions to be only a subset... which apps were your referring to?

**Comment by h-2** [comment]
Are you reffering to Mason? I see that it hardcodes the extensions:
https://github.com/seqan/seqan/blob/master/apps/mason2/mason_genome.cpp#L118
It should instead be "softcoded", as described in #838

**Comment by h-2** [comment]
I am marking this as a duplicate of #838

**Comment by tseemann** [comment]
Yes I did mean `mason`  thanks for digging into the problem!

**Comment by Funatiq** [comment]
The problem still consists in the mason apps. There were some suggestions in #838 to fix this, but it got closed without resolving this issue here.

**Comment by h-2** [comment]
Renaming and re-opening. 

The abovementioned line in mason needs to be changed from
```diff
-setValidValues(parser, "out-file", "fa fasta");
+setValidValues(parser, "out-file", toCString(concat(getFileExtensions(SeqFileOut()), ' ')));
```
This is now tagged for milestone 2.4.0, but if  you could make a PR for this it would certainly be fixed faster 😃

**Comment by Funatiq** [comment]
Well I'm a little confused about how you handle those things. I've seen something like
`setValidValues(parser, "seq", getFileExtensions(Fasta()));`
or 
`setValidValues(parser, "o", SeqFileOut::getFileExtensions());`
in the other apps. There are many apps like mason that still have hardcoded file extensions for parsing.
Is there a difference between those code lines?

**Comment by h-2** [comment]
Yes, there is. The SeqFileOut's getFileExtensions also add extensions based on supported compression formats, e.g. `.faa.gz`. The line I posted above is how other apps like Lambda do it so I am sure that will work.

**Comment by rrahn** [comment]
is this issue resolved?
