### ISSUE TITLE
mason_variator: invalid FORMAT column in VCF output

### ISSUE THREAD

**Issue by tseemann** [seqan/seqan#1671]
Thanks for writing this tool - it's exactly what I was looking for!

I don't think the VCF is valid however. The sample column 'simulated' has a `1` in it, but there is no corresponding metadata in the `FORMAT` column (or header) to explain what that `1` is:

```
#CHROM          POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  simulated
NC_018143       7006    .       T       TG      .       PASS    .       .       1
```

I suspect it is the genotype, so `FORMAT` should have `GT` in it, and the header have the GT description like this:

```
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM          POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  simulated
NC_018143       7006    .       T       TG      .       PASS    .       GT      1
```

This is the version I am using:

```
    mason_variator version: 2.0.4 [6217cce]
    SeqAn version: 2.1.1
```

@holtgrewe

**Comment by h-2** [comment]
@holtgrewe is this a bug and if yes in mason or in SeqAn's vcf support?

**Comment by h-2** [comment]
Closed because inactivity.

**Comment by rohan-ibn-tariq** [comment]
I was facing the same issue in my microsatellite instability quantification workflow, and your suggestion solves the issue.


> Thanks for writing this tool - it's exactly what I was looking for!
> 
> I don't think the VCF is valid however. The sample column 'simulated' has a `1` in it, but there is no corresponding metadata in the `FORMAT` column (or header) to explain what that `1` is:
> 
> ```
> #CHROM          POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  simulated
> NC_018143       7006    .       T       TG      .       PASS    .       .       1
> ```
> 
> I suspect it is the genotype, so `FORMAT` should have `GT` in it, and the header have the GT description like this:
> 
> ```
> ##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
> #CHROM          POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  simulated
> NC_018143       7006    .       T       TG      .       PASS    .       GT      1
> ```
> 
> This is the version I am using:
> 
> ```
>     mason_variator version: 2.0.4 [6217cce]
>     SeqAn version: 2.1.1
> ```
> 
> [@holtgrewe](https://github.com/holtgrewe)

**Comment by eseiler** [comment]
I'll have a look next week.
