### ISSUE TITLE
mason_variator: left align indels instead of right align

### ISSUE THREAD

**Issue by tseemann** [seqan/seqan#1672]
When `mason_variator` creates an indel variant, the VCF output file seems to right-align the `REF`/`ALT` calls. 

Although VCF annoyingly allows either, the convention is to left-align them.
https://www.biostars.org/p/66843/

```
NC_018143       12305   .       CAC     C                     # mason
NC_018143       12304   .       TCA     T                     # most other tools
```

This makes it much simpler to compare VCFs, which is what simulating sequences is generally used for.

@holtgrewe

**Comment by esiragusa** [comment]
@h-2 @rrahn do our DP alignment algorithms produce left-aligned gaps? IIRC this was configurable but it doesn't seem to be mentioned in the dox/tutorials.

**Comment by rrahn** [comment]
Our gaps are by default left-aligned.They can be configured to be right-aligned, but this is not yet exposed by the public interface. (Hence not documented)
However, I am not aware of the implementation details in Mason.
If @holtgrewe can not maintain it, we need to reassign a maintainer to it.

**Comment by h-2** [comment]
Closed because inactivity.
