### ISSUE TITLE
BamHeader

### ISSUE THREAD

**Issue by snaedis88** [seqan/seqan#1674]
The documentation describes the BamHeader as a class but if you look into the source code it it a typedef: 
`seqan-library/2.1.0/include/seqan/bam_io/bam_header_record.h: typedef String<BamHeaderRecord> BamHeader`
I think it would be a good idea to make this clear in the documentation.

/snædís

**Comment by h-2** [comment]
Hm, the documentation at 
http://docs.seqan.de/seqan/develop/class_BamHeader.html
says:
```c++
typedef String<BamHeaderRecord> BamHeader;
```
And in the tutorial
http://seqan.readthedocs.org/en/master/Tutorial/InputOutput/SamAndBamIO.html
we also say
> The header consists of multiple lines, starting with an '@' character, each line is a record. 

How would you change the documentation to be more clear?

Please note that "Class" is used in the documentation in a broader sense, as "something you might want to create an object from". As can be seen from the examples, `BamHeader` is used in this way:
```c++
BamHeader header;
readHeader(header, bamFileIn);
```

So I think the actual technical details are less important, or not?

In which way did you encounter problems when trying to use BAM I/O?

**Comment by h-2** [comment]
If you have further questions or suggestions, please feel free to re-open this issue, but I will close it for now.
