### ISSUE TITLE
Reading a genbank file introduces empty sequences

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1675]
Calling `readRecords()` on the attached file creates two sequences in the set although there is only one. The second sequence is empty.
[exophiala_dermatitidis_mitochondrion.gbk.txt](https://github.com/seqan/seqan/files/225963/exophiala_dermatitidis_mitochondrion.gbk.txt)

**Comment by temehi** [comment]
@h-2 If I am not mistaken a genbank flat file should have only a single ORIGIN element. 

The file you uploaded has 2 trailing newline chars and that is the reason for the empty record. This is basically not a valid. Nevertheless we can fix it by skipping until the next non-white-character after reading a recored. 

basically by adding the line: 
`skipUntil(iter, NotFunctor<IsWhitespace>());`
at the end of  `readRecord(TSeqString & seq, TFwdIterator & iter, GenBankSequence)` function.

What do you think?

**Comment by h-2** [comment]
:+1: 

In the case of empty lines we should be lenient with errors!

**Comment by h-2** [comment]
fixed via #1756
