### ISSUE TITLE
indexRequire() doesn't work for FMIndex

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1676]
I thought the usual interface for creating an index quickly was:

``` c++
Index<StringSet<String<Iupac>, Owner<ConcatDirect<>>>, IndexSa<> > ix(seqs);
indexRequire(ix, EsaSa());
```

This works. But when I do:

``` c++
Index<StringSet<String<Iupac>, Owner<ConcatDirect<>>>, FMIndex<> > ix(seqs);
indexRequire(ix, FibreLF());
```

I get all sorts of errors. Instead I have to use `indexCreate(ix)` (no further arguments!) for creating the FMIndex. OTOH when doing the same for an SA-Index you need to specify more arguments. Is there a reason for this inconsistency?

Do you know anything about this @esiragusa ? Could you discuss with @cpockrandt how to improve this for the future?

**Comment by cpockrandt** [comment]
I cannot test it right now but I think for the FMIndex the following should work:

    indexRequire(ix, FibreSALF());

**Comment by cpockrandt** [comment]
@h-2 ``indexRequire(ix)`` does not work for me, instead you should use ``FibreSALF()`` as suggested above.

``indexRequire(ix, FibreLF());`` doesn't make sense for the FM index since you need to create the SA before you can create the LF table. That's probably why they introduced the ``FibreSALF`` tag.

**Comment by h-2** [comment]
Ah, ok. I think we should look for some unified interface that makes sure the index is instantiated, but I'll move it to 3.0.

**Comment by cpockrandt** [comment]
I close this issue now, it doesn't make sense to keep this issue open for 3.0. @h-2 Please reopen if you feel differently about it.
