### ISSUE TITLE
New STL_* and COMPILER_* macros

### ISSUE THREAD

**Issue by marehr** [seqan/seqan#1681]
Use the following macros

Before checking include `<cstddef>` and `<ciso646>`

| SEQAN MACRO      | SYSTEM MACRO
|------------------|------------------------------------
|STDLIB_VS            | `_msc_ver`
|STDLIB_GNU           | `__GLIBCXX__`
|STDLIB_LLVM          | `_LIBCPP_VERSION`
|                  |
|COMPILER_MSVC     | `_msc_ver && ! __ICC && ! __clang__`
|COMPILER_GCC      | `__gcc__ && ! __ICC && ! __clang__`
|COMPILER_INTEL    | `__ICC`
|COMPILER_CLANG    | `__clang__`

and replace the old ones

| SEQAN MACRO        | SYSTEM MACRO
|--------------------|------------------------------------
|PLATFORM_WINDOWS    | 
|PLATFORM_WINDOWS_VS | `_msc_ver`
|PLATFORM_GCC        | `__gcc__` (also set by icc and clang on unix)
|PLATFORM_GNU        | `__gcc__ && ! __ICC && ! __clang__`
|PLATFORM_INTEL      | `__ICC` (not sed on windows because PLATFORM_WINDOWS_VS was checked before)
|PLATFORM_CLANG      | `__clang__`  (not sed on windows because PLATFORM_WINDOWS_VS was checked before)

**Comment by marehr** [comment]
fixed by #1696

**Comment by marehr** [comment]
[Cdash](http://cdash.seqan.de/viewBuildError.php?type=1&onlydeltap&buildid=180657) complains a lot about [C4503](https://msdn.microsoft.com/en-us/library/074af4b6%28v=vs.140%29.aspx), e.g.

>  warning C4503: 'seqan::_skew7Extend': decorated name length exceeded, name was truncated

We [removed](https://github.com/seqan/seqan/pull/1696/files#diff-12d0468e15242109aacd13c5a9cf16ecL54) this suppressed warning, but the pr #1731 brings it back.

**Comment by marehr** [comment]
Another new error on [cdash](http://cdash.seqan.de/viewBuildError.php?onlydeltap&buildid=180678):

```
/.../Linux-3.16.0-4-amd64_clang++-3.5_32/tests/blast/test_blast_misc.h:81:19: error: static_assert expression is not an integral constant expression

    static_assert(strcmp(_programTagToString(n), "BLASTN") == 0,       "static assertion failed!");
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

After a quick check, it seems that `strcmp` isn't required to be `constexpr`. And the older version of stdlib in `clang++3.5` doesn't support it.

We [changed](https://github.com/seqan/seqan/pull/1696/files#diff-6908e7988572747d37d5e58e2630ab81L80) `PLATFORM_GNU` to `STDLIB_GNU`, but the `STDLIB_GNU` in `clang++3.5` doesn't support this.

@h-2 What should we do?

**Comment by h-2** [comment]
@marehr this one is tricky, because (a) strcmp is part of the stnadard c library, not the standard c++ library (thus the macro is wrong); and (b) in gcc this function is "builtin" so the constexpr version seems to  be a compiler feature rather than a library feature.

Can you
1. try to use `std::strcmp` instead of `strcmp` to see if that makes a difference? (probably will not)
2. change the macro to `COMPILER_GCC` and add a comment to the source code that the constexpr strcmp function is a non-standard compiler builtin of gcc?

Thanks!

**Comment by marehr** [comment]
@h-2, but icc, clang >3.5 and gcc support it. I'll check `std::strcmp`.

**Comment by rrahn** [comment]
Have you seen this here: http://stackoverflow.com/questions/5721813/compile-time-assert-for-string-equality?
Could this solve the issue independent of compiler and/or stdlib version?

**Comment by h-2** [comment]
I think this is solved!
