### ISSUE TITLE
The seqan tarball is missing any reference to seqan_setup_install_vars

### ISSUE THREAD

**Issue by laserson** [seqan/seqan#1682]
This breaks the install of imseq.

```
$ cmake . -DCMAKE_MODULE_PATH=/Users/laserson/Downloads/seqan-library-2.1.1/share/cmake/Modules
-- Configuring apps/imseq
-- Configuring apps/imseq/src
-- Performing Test CXX11_DETECTED
-- Performing Test CXX11_DETECTED - Success
-- Looking for C++ include execinfo.h
-- Looking for C++ include execinfo.h - found
--   Determined version is 2.1.0
-- Found Git: /usr/local/bin/git (found version "2.8.1") 
CMake Error at src/CMakeLists.txt:101 (seqan_setup_install_vars):
  Unknown CMake command "seqan_setup_install_vars".
```

**Comment by laserson** [comment]
This is true for other macros as well.  Does `SeqAnBuildSystem.cmake` need to be included in the tarball in some way?

**Comment by marehr** [comment]
Hi @laserson,
thank you for your issue. When was the last time this exact command worked for you? What SeqAn Version did you use before?

As I can see form the download page, we never shipped `share/cmake` until 2.1.0.

The `SeqAnBuildSystem.cmake` is actually for our own build process. You can use that of course, but when your missing CMakeFiles that are not included in the packaged version on github. You may want to clone the repository directly from github.

The reason for that is simple, we don't want to enforce our users to use our way to build the library. If you want to use cmake you can also only use our FindSeqan.cmake.

This [tutorials](http://seqan.readthedocs.org/en/master/Infrastructure/Use/FindSeqAnCMake.html) describes how to setup a cmake project for seqan, that uses FindSeqan.cmake. 

----

I looked at http://www.imtools.org/ and the download link of `IMSEQ 1.1.0 Sourcecode` actually includes a minimal version of SeqAn 2.0.1. Maybe you want to use that, or replace the content of the `seqan_minimal` folder with a clone of the github repository.

**Comment by laserson** [comment]
Ok, it sounds like maybe the IMSEQ developer is using your "internal" build tools that you never intend to release.  I'll follow up there...thanks for the help!

**Comment by marehr** [comment]
It's not that we never intended it. We actually had tutorials that described how to use our build system, but since 2.1.0 we wanted to decouple that and updated the docs. So using our build system should still work, but there is now an easier way to include our library. I hope I could help you :smiley:
