### ISSUE TITLE
Finder on an index sometimes allows to search Dna5 and sometimes not.

### ISSUE THREAD

**Issue by marehr** [seqan/seqan#1683]
This code snippet works:

``` c++
Dna5String genome = "ACGTGCTAGCGATGACGATGCAGACTGACTGGACAGGCATGA";

Index<Dna5String, IndexEsa<> > index(genome);
Finder<Index<Dna5String, IndexEsa<> > > finder(index);
Dna5 needle(0);
find(finder, needle);
```

This doesn't:

``` c++
Dna5String genome = "ACGTGCTAGCGATGACGATGCAGACTGACTGGACAGGCATGA";

Index<Dna5String, FMIndex<> > index(genome);
Finder<Index<Dna5String, FMIndex<> > > finder(index);
Dna5 needle(0);
find(finder, needle);
```

I know that `needle` should be `Dna5String needle = "A"`. But I think it should be either allowed or disallowed in both cases.

**Comment by rrahn** [comment]
It should be not allowed in both cases. 
The pattern must be a text not a character.

**Comment by beekalam** [comment]
@rrahn but 

` Dna5 needle('A');`

is allowed and it is okay. and also

` Dna5 needle((char)97);    // (char)97 ==> 'A' `

but

` Dna5 needle(97);`

doesn't make sense and shouldn't be allowed. Am I right?

**Comment by rrahn** [comment]
Well, I was not referring to the construction of a <tt>SimpleType</tt>, but to the index find interface.
Here the needle should always fulfil the <tt>ContainerConcept</tt>, which a character is not.

**Comment by cpockrandt** [comment]
@marehr Can you give me some more information? I tried it with master and develop branch and both code snippets compile ...

**Comment by h-2** [comment]
what is the state here?

**Comment by h-2** [comment]
@cpockrandt can you add static_asserts that fail with reasable error messages?
