### ISSUE TITLE
SeqAn in MacPorts does not install crucial buildsystem files

### ISSUE THREAD

**Issue by SoapZA** [seqan/seqan#1694]
Dear SeqAn,
thank you for getting the latest SeqAn release into the tree. Unfortunately, do install SeqAn in MacPorts, you just use your prepackaged release, which is suboptimal. This package misses the CMake + pkg-config files that are so important for people developing against the library. The only way to consume this library is to hard-code against the MacPorts paths, which I hope you will agree with me, is cumbersome at best. Could you update the Portfile such that it runs cmake and produces all the required build system files? Take for instance the approach we take in Gentoo:

https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-biology/seqan/seqan-2.1.1.ebuild

Here, we run the full cmake and add documentation depending on whether a user flag is set (ignore all the noise with sed, this is for making seqan installable in parallel with the older 1.4.2 release). To make SeqAn fully integrated, I believe you want to install the *.cmake and pkg-config .pc files too.

Thanks
David

**Comment by h-2** [comment]
Indeed, the MacPorts port file doesnt install those files. It will be fixed.
However the files *are* present in our library releases, and we still strongly suggest using those in favor of using an ebuild that requires python to build the documentation et cetera.

**Comment by SoapZA** [comment]
In Gentoo this is not a problem, as python is ubiquitous on any Gentoo system (portage runs on python). On MacPorts, this is a bit trickier. With the `-DSEQAN_NO_DOX=YES` flag, python is not required. If users want documentation, then asking for python + sphinx is not too much asked, given how involved some of the MacPorts builds are (Clang + OpenMP anyone?)

**Comment by h-2** [comment]
Still, the situation is that the documentation is "static at distribution time", why would you want to add complexity and waste cpu-cycles building on it? [I know one could ask this any source based packaging system, but the implications of software source code and documentation source code are different ones from my POV]

**Comment by SoapZA** [comment]
I would be willing to entertain installing just the documentation as is. But let us not kid ourselves: most of our CPU cycles will go into instantiating SeqAn templates. It has been a paradigm of Gentoo to produce documentation from raw sources ever since. Sphinx is a very light-weight package, and most Gentoo users don't even want documentation, hence Sphinx would even be pulled in.

**Comment by h-2** [comment]
OK, well you are free to package however you want to of course :)

We will adapt the MacPort to include the additional files, as that it less trouble for us. Thanks for letting us now about it.

**Comment by h-2** [comment]
btw: @SoapZA I see that SeqAn is now available as 2.1.1 in Portgage, thanks a lot! What would be the command we can add to http://seqan.readthedocs.io/en/master/Infrastructure/Use/Install.html for Gentoo?
`emerge seqan` ?
`emerge sci-biology/seqan` ?
Or do you need to append the version number to get 2.x ?

**Comment by SoapZA** [comment]
`emerge sci-biology/seqan`
should suffice. The build system has been hacked a bit to allow for parallel installations with otehr major versions, as we still require seqan-1.4.2 for TopHat and bowtie 1. Still, all of the changes are transparent to the user, that is, if they use the `FindSeqan.cmake` module or `pkg-config` file, all their seqan developed programs will work unchanged.

**Comment by h-2** [comment]
Ok, so `emerge sci-biology/seqan` will install both versions or in any case include the new one? Then I will add that to our documentation (although I suspect most Gentoo users will not require our documentation).

**Comment by SoapZA** [comment]
`emerge sci-biology/seqan` will only ever install the latest version (i.e. 2.1.1 currently). Installation of documentation is controlled by the `USE="doc"` flag, which I would guess 95% of Gentoo users disable.

Regardless, we discourage people from using 1.4.2 and also have a reminder that it's just a "support library" intended for compiling other applications and not for primary use. In any way, people would have to go out of their way to consume 1.4.2 from their applications, as all the files have been renamed (and the `FindSeqan.cmake` module has been deleted anyways).

**Comment by rrahn** [comment]
@SoapZA I updated the portfile patch. It will now install SeqAn.config into ${prefix}/share/seqan. I tested it with a little project and cmake finds the package successfully. Once the patch has been accepted I'll close this issue. I will also add one for 2.2 and 2.3.

**Comment by SoapZA** [comment]
@rrahn thanks for your time

**Comment by rrahn** [comment]
Fixed for SeqAn 2.1.1 (https://trac.macports.org/ticket/51344)
I will add ports for 2.2 and 2.3
