### ISSUE TITLE
Assertion failure on banded chain alignment: no glue point available

### ISSUE THREAD

**Issue by rrwick** [seqan/seqan#1700]
Hi, I ran into a crash when doing a banded chain alignment in Seqan. It seems similar to [issue 1357](https://github.com/seqan/seqan/issues/1357), and I get the crash on the current master branch.

Here's a small program I made which reproduces the issue:
[seqan_crash.cpp.txt](https://github.com/seqan/seqan/files/258514/seqan_crash.cpp.txt)
(Sorry about the '.txt', GitHub needed that for me to attach the file.)

I'm building the program like this:
`g++-5 -Iseqan/include seqan_crash.cpp -o seqan_crash -std=c++11 -DSEQAN_ENABLE_DEBUG=1`
Though I also tried with `clang++` (I'm using a Mac) and got the same issue, so I don't think it's specific to the compiler.

This test script takes the band size as a parameter, and the alignment crashes when the band size is 77 or more.  So this works: `./seqan_crash 75`, but this crashes: `./seqan_crash 80`.

It's also sensitive to the scores - if I change them it tends to no longer crash. I know the scores are a bit on the large side, but since I'm using `int` I don't suspect an overflow (as was the issue [here](https://github.com/seqan/seqan/issues/699)).

Let me know if I can provide anything else that would be helpful.

**Comment by rrahn** [comment]
Ok, I'll have a look.
Thanks for reporting.

**Comment by rrahn** [comment]
@rrwick sorry, that it took so long. 
It seems you are using wrong orientation of the positions when  adding the seed.
It should be:
```cpp
Seed(beginPosH, beginPosV, endPosH, endPosV)
```
But also at least the first and the second seed overlap, which is not allowed for the banded chain alignment. You should run ```alignSeedsGlobally()``` before. 
This requires a ```SeedSet```. Please see the documentation here: http://seqan.readthedocs.io/en/master/Tutorial/Algorithms/SeedExtension.html.
I will update the APIN documentation for the ```bandedChainAlingment```, to emphasise the colinarity-requirement of the seeds.
Please let me know if this solves your problem.

**Comment by rrahn** [comment]
@rrwick please reopen if the issue is not solved for you yet.
