### ISSUE TITLE
RABEMA not working and documentation missing

### ISSUE THREAD

**Issue by JakobSch** [seqan/seqan#1702]
I was looking for the RABEMA benchmarking suite as proposed in the Bioinformatics paper Holtgrewe et al. from 2011.
The availability link http://www.seqan.de/projects/rabema.html is broken and I also could not find any documentation about this using the search function of the seqan homepage.

Finally I found linux x64 executables in http://packages.seqan.de/rabema/ but on my system they are not working. (see also attached log)
[errorlog.txt](https://github.com/seqan/seqan/files/260867/errorlog.txt)

I would like to use the suite in my masters thesis.
Bests,
Jakob

**Comment by holtgrewe** [comment]
@h-2 Where is the old page done? Did you do a backup?

**Comment by h-2** [comment]
@holtgrewe yes, but I don't know where... @smehringer transferred the existing apps and made the new app template. @smehringer , do you know where they are and can you assist Manuel in transferring the Rabema data?

**Comment by marehr** [comment]
A redirect from the old url to the new one would be helpful.

**Comment by h-2** [comment]
there is no new one, thats the point :wink:

**Comment by smehringer** [comment]
When I transferred the (part of the) apps, the old seqan website was still online. I don't know where the backups are, but I'll ask Knut.

**Comment by JakobSch** [comment]
Any progress here?

**Comment by h-2** [comment]
The homepage will be reacreated and Rabema will be moved outside of the main repository soon.

Concerning the error, please rebuild the application in debug mode and provide a traceback of the crash and/or provide all input files to @holtgrewe

**Comment by JakobSch** [comment]
[Human_immunodeficiency_virus_1_uid15476.txt](https://github.com/seqan/seqan/files/270660/Human_immunodeficiency_virus_1_uid15476.txt)
Attached file is a fasta file renamed to .txt in order to upload it here. Rebuilding is not that easy since I only tried the precompiled executable.

**Comment by holtgrewe** [comment]
@JakobSch 

- this looks like the code was compiled on a machine that has instructions not available to yours
- please try version 1.2.0 (I think the bumps afterwards are just seqan upgrades and seqan releases)
- the old homepage can be viewed through the [wayback machine](https://web.archive.org/web/20160110192720/http://www.seqan.de/)
- the files are still missing and I'm in contact with the guys from @seqan/all to restore it

**Comment by rrahn** [comment]
To build the program on your own, follow the following steps assuming linux based OS: 

```
cd ~
mkdir workspace; cd workspace
git clone https://github.com/seqan/seqan.git
mkdir -p build/debu; cd build/debug
cmake ../../seqan -DCMAKE_BUILD_TYPE=Debug
make rabema
./bin/rabema --help
```
If it is really just an architectural problem, then your compiled rabema should run.
If not, please submit the stack trace and any diagnostic output of the program.

**Comment by JakobSch** [comment]
thank you both for your quick responses. Both methods work. I will prefer the approach from @rrahn .
However, when running rabema_build_gold_standard I still get an error when running it with --max-error 8.
It works like a charm when using --max-error 26. Does this depend on my input-sam-file and did I miss something conceptional here?

The sam-file might not be a perfect gold standard.

```
#$ ./workspace/build/debug/bin/rabema_build_gold_standard --max-error 8 --distance-metric edit -o gold-standard.gsi -r HIV.fasta -b manualHIVreads.sam
==============================================================================
                RABEMA - Read Alignment BEnchMArk
==============================================================================
                      Building Gold Standard
==============================================================================

____OPTIONS___________________________________________________________________

Max error rate [%]    8
Oracle mode           no
Distance measure      edit
Match Ns              no
GSI Output File       gold-standard.gsi
SAM/BAM Input File    manualHIVreads.sam
Reference File        HIV.fasta
Verbosity             1

____LOADING FILES_____________________________________________________________

Reference Index       HIV.fasta.fai ... OK (1 seqs)
 OK

Took 0.000581375s

____EXTENDING INTERVALS_______________________________________________________

Each dot represents work for 100k nucleotides in the genome.

gi|9629357|ref|NC_001802.1| (1/1) ./home/schulzeja/masterthesis/workDir/testScripts4HiLive/hiLiveRegressionTests/tests/rabematest/workspace/seqan/apps/rabema/rabema_build_gold_standard.cpp:470 Assertion failed : getScore(pattern) >= -maxError was: -16 < -8

stack trace:
  0          [0x4ad788]  seqan::ClassTest::fail() + 0xe
  1          [0x4d5294]  void buildErrorCurvePoints<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Tag<seqan::MyersUkkonenReads_>, seqan::StringSet<seqan::String<char, seqan::Alloc<void> >, seqan::Owner<seqan::Tag<seqan::Default_> > > >(seqan::String<WeightedMatch, seqan::Alloc<void> >&, int&, seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >&, unsigned long, bool, seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >&, unsigned long, unsigned long, seqan::StringSet<seqan::String<char, seqan::Alloc<void> >, seqan::Owner<seqan::Tag<seqan::Default_> > > const&, bool, seqan::Tag<seqan::MyersUkkonenReads_> const&) + 0x37e
  2          [0x4c6c69]  int matchesToErrorFunction<seqan::Tag<seqan::MyersUkkonenReads_> >(std::map<int, seqan::String<WeightedMatch, seqan::Alloc<void> >, std::less<int>, std::allocator<std::pair<int const, seqan::String<WeightedMatch, seqan::Alloc<void> > > > >&, seqan::String<int, seqan::Alloc<void> >&, seqan::FormattedFile<seqan::Tag<seqan::Bam_>, seqan::Tag<seqan::Input_>, void>&, seqan::StringSet<seqan::String<char, seqan::Alloc<void> >, seqan::Owner<seqan::Tag<seqan::Default_> > >&, seqan::StringSet<seqan::String<char, seqan::Alloc<void> >, seqan::Owner<seqan::Tag<seqan::Default_> > > const&, seqan::FaiIndex const&, BuildGoldStandardOptions const&, seqan::Tag<seqan::MyersUkkonenReads_> const&) + 0x7d9
  3          [0x4aca5a]  main + 0x65e
  4    [0x7f08661c0a40]  __libc_start_main + 0xf0
  5          [0x4a89a9]  _start + 0x29

Aborted (core dumped)
```

**Comment by h-2** [comment]
@holtgrewe what is the state here?

**Comment by holtgrewe** [comment]
worksforme?

**Comment by h-2** [comment]
why is it a question? does it work for you or not?

**Comment by h-2** [comment]
@JakobSch if this is still an issue, please reopen
