### ISSUE TITLE
move RABEMA out of seqan before 2.2.0

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1716]
will resolve #1702 for us at least :)

@holtgrewe can you do this in time, i.e. within the next four weeks? Thx!

Would you thinka bout moving mason out as well?

**Comment by h-2** [comment]
@holtgrewe we are approaching the last week before the release, can you please look into this? Thanks!

**Comment by holtgrewe** [comment]
I will not get to it, I guess. More like Q3

**Comment by h-2** [comment]
@holtgrewe reopen if you have a PR.
