### ISSUE TITLE
Constructor of AminoAcid / SimpleType has unexpected behaviour for uint8_t

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan#1721]
typedef typename ValueSize<AminoAcid>::Type TValueSize;
    TValueSize c = 26; // TValueSize is uint8_t
    std::cout << (int) c << AminoAcid(c) << AminoAcid(26) << std::endl;

Expected output: ``26 * *``
Actual output: ``26 X *``

It works if ``TValueSize`` is ``uint16_t``

This affects rank queries and string indices and thus would be nice if someone could fix it soon :)

**Comment by h-2** [comment]
This is "expected" because uint8_t translates to `unsigned char` and an unsigned char constructed from the value 26 is the "substitute character" and an aminoacid initialized with the "substitute character" gets the "unknown value" of X

**Comment by h-2** [comment]
If we did away with the constructors and just used `{c}` to initialize we wouldn't have this problem -> SeqAn3 alphabets :)

**Comment by h-2** [comment]
Of course we could also create an extra constructor overload for the char types, but then Dna5('C') wouldnt convert to the letter C but to 'N' which we also don't want.
