### ISSUE TITLE
Segfault when saving a char-RankDictionary to disk

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan#1728]
The following code snippet is not working:

```
String<char> str("abcde");
RankDictionary<char, Levels<> > dict(str);
save(dict, "/home/chris/testFM/dict");
```

I get a segfault in `file/string_external.h`. When I replace `char` by `Dna` or `AminoAcid`, it works fine. Is there a reason why `char` might not be supported or is it a bug?

**Comment by esiragusa** [comment]
FYI Levels RD make sense only for very small alphabets like bool or Dna. The naive implementation for char was only meant for debugging purposes.

**Comment by cpockrandt** [comment]
The reason why I'm bringing this up is because we will put the Levels RD for the next release into the documentation. We should either make it fully generic (and thus support char) or limit it only to certain alphabets in the docs. @h-2 What do you think?

**Comment by esiragusa** [comment]
@cpockrandt char is not meant to be used...

**Comment by cpockrandt** [comment]
Since it will most likely not be included in SeqAn3 anymore, I will include it only in the docs when I rewrite them for the FM and BiFM index.

**Comment by h-2** [comment]
document the (lack of) functionality
