### ISSUE TITLE
benchmark seqan versions

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1733]
run the benchmark suite with
- [ ] seqan-1.4.2
- [ ] seqan-2.0.1
- [ ] seqan-2.1.1
- [ ] seqan-2.2.0
- [ ] seqan-2.3.0

and compare the run-time

**Comment by h-2** [comment]
maybe this is more important for the release than #1411

**Comment by smehringer** [comment]
@h-2 The benchmark app does not compile with seqan-1.4.2 and seqan-2.0.1
I don't know if I may do something wrong though. @marehr should it be able to compile?

**Comment by marehr** [comment]
The benchmarks weren't written for 1.4.2, so they shouldn't. I never tried to compile the benchmarks with 2.0. So it could be that I used 2.1 API that wasn't available in 2.0. Which benchmarks aren't compiling? Index?

**Comment by h-2** [comment]
@xp3i4  what is the state here? Even if it doesn't build on 1.4, please try to make it run and 2.0 and compare all tests that work.

**Comment by h-2** [comment]
@xp3i4 *ping* please respond what the state is

**Comment by temehi** [comment]
benchmarks do not compile for seqan versions earlier than 2.1.0. Probably due  [changes in the build system](https://github.com/seqan/seqan/blob/seqan-v2.1.0/CHANGELOG.rst#infrastructure-updates-1).  So I will be doing the benchmarks for only

- [ ] 2.1.0
- [ ] 2.1.1
- [ ] develop

**Comment by h-2** [comment]
will have to happen after the release

**Comment by h-2** [comment]
Closed because inactivity.
