### ISSUE TITLE
System requirements in CHANGELOG for 2.1.0 wrong

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1737]
someone put in the old requirements for some reason... needs to be fixed.

**Comment by h-2** [comment]
see confusion in #1679

**Comment by h-2** [comment]
do we need to do a 2.1.1 release for this?

**Comment by rrahn** [comment]
It should be a hot fix.

**Comment by h-2** [comment]
assigning the issue and the release management of 2.1.1 to @cpockrandt since he wrote the wring CHANGELOG in the first place :point_right:

**Comment by h-2** [comment]
@cpockrandt did you fix this?

**Comment by cpockrandt** [comment]
@h-2 I planned to include it into the PR for Changelog 2.2.0 or do you prefer a separate PR?

**Comment by h-2** [comment]
@cpockrandt Same PR, different commit :)

But, sooner would be better than later! We wanted to have all commits in before 1am, so that no commits come after the nightlies!

**Comment by h-2** [comment]
[but if you don't make it until 1 thats life. I for one need to go to bed now :sleeping: ]

**Comment by cpockrandt** [comment]
@h-2 Sure, different commits ;)

Changelog won't be done before 1am, Knut and I are currently discussing the paper with Enrico

**Comment by h-2** [comment]
@cpockrandt ok, regards, to the two of them!
