### ISSUE TITLE
Do c++ version macro checks in platform.h

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1739]
... and warn user about lacking c++11/c++14 support and/or outdated compilers. We need this since many people apparently don't use cmake. While we are there we should also add proper auto-detection for  SEQAN_HAS_OPENMP (i.e. if not set, initialize it to `!!_OPENMP`).

**Comment by h-2** [comment]
This should be just a few lines and could be done with the other PR, @marehr ? If you think it doesn't fit, I can also take the issue...

**Comment by marehr** [comment]
Which other pull request?

**Comment by h-2** [comment]
All the other compiler and macro stuff you are involved in? :laughing: 

I can do it, too, if you want to.

**Comment by h-2** [comment]
implemented via #1740
