### ISSUE TITLE
Warnings by GCC6

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1763]
> align/dp_formula_affine.h:280:5: warning: this 'else' clause does not guard... [-Wmisleading-indentation]

see also:
http://cdash.seqan.de/viewBuildError.php?type=1&buildid=182726
http://cdash.seqan.de/viewBuildError.php?type=1&buildid=182719

**Comment by rrahn** [comment]
I am currently fixing this already.

**Comment by rrahn** [comment]
Fixed by #1772
