### ISSUE TITLE
Different travis compilers

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1766]
Since GCC6 is much stricter than previous versions and clang-3.8 is the first clang with openmp we support, I think they should be included in travis. I would propose:
- [x] gcc-4.9
- [x] gcc-5
- [x] gcc-6
- [x] clang-3.5
- [x] clang-3.9

→ GCC is still the main target platform, for clang take newest and oldest of the supported ones

@rrahn Since you worked on that recently, could you change it?

**Comment by rrahn** [comment]
@h2 ok

**Comment by h-2** [comment]
Moving this post 2.2.0

**Comment by rrahn** [comment]
for clang-3.9 we have to wait for the apt resources to become whitelisted. For the moment we have to deal with clang-3.8
