### ISSUE TITLE
Segfault when reading AnnotationTree with unknown feature type

### ISSUE THREAD

**Issue by martinjvickers** [seqan/seqan#1787]
The TAIR10 Arabidopsis gene GFF file has a feature type that is not in the annotationKeyStoreCache;

`Chr1    TAIR10  protein 6915    8666    .       -       .  ID=AT1G01020.1=protein;Name=AT1G01020.1;Derives_from=AT1G01020.1
`

which when you read causes the program to segfault. 

Is there functionality to either ignore it, or better still add the feature type at run time?

My code is simply;

```
        GffFileIn gffIn(toCString(queryFileName));
        TStore store;
        readRecords(store, gffIn);

        Iterator<FragmentStore<>, AnnotationTree<> >::Type it;
        it = begin(store, AnnotationTree<>());
        unsigned count = 0;

        while (!atEnd(it))
        {
                if(getType(it) == "exon"){
                        cout <<  "We have an exon!" << endl;
                }       
                //make it go next
                goNext(it);
        }
```

**Comment by h-2** [comment]
@temehi can you check if this is easily fixable? If not, please change the milestone to 2.3.0

**Comment by temehi** [comment]
The problem occurred due to the fact that an annotation can have multiple parents as it is the case in the GFF file in question. see the segment bellow. 
```
Chr1	TAIR10	CDS	3760	3913	.	+	0	Parent=AT1G01010.1,AT1G01010.1-Protein;
Chr1	TAIR10	exon	3996	4276	.	+	.	Parent=AT1G01010.1
Chr1	TAIR10	CDS	3996	4276	.	+	2	Parent=AT1G01010.1,AT1G01010.1-Protein;
Chr1	TAIR10	exon	4486	4605	.	+	.	Parent=AT1G01010.1
Chr1	TAIR10	CDS	4486	4605	.	+	0	Parent=AT1G01010.1,AT1G01010.1-Protein;
```

I am no GFF file expert but I can see two ways to go, one is to consider just the first parent and ignore the rest, the other is to handle the case of multiple parents properly and change from  `parentName` to `parentNames`. 
The first way is an easy fix. instead of 
```
        if (ctx._key == "Parent" || ctx._key == "ParentID")
        {
            ctx.parentKey = ctx._key;
            ctx.parentName = ctx._value;
        }
```
we do:
```
        if (ctx._key == "Parent" || ctx._key == "ParentID")
        {
            ctx.parentKey = ctx._key;

            typedef Iterator<CharString>::Type TStringIterator;
            TStringIterator it = begin(ctx._value);
            readUntil(ctx.parentName, it, EqualsChar<','>());
        }
```
The later might affect the whole design of `IOContextGff` as we are going to have multiple parents for an annotation.  @h-2 @rrahn what  do you think?

**Comment by h-2** [comment]
> I am no GFF file expert but I can see two ways to go, one is to consider just the first parent and ignore the rest, the other is to handle the case of multiple parents properly and change from parentName to parentNames. 

Yes, I would propose to the "easy fix" for the release and make an issue for seqan3 that we consider this situation when modernizing the module. Losing information is not ideal, but a lot better than crashing :smile: 

For your proposed fix, note that you can use `auto` instead of the typedef.

**Comment by temehi** [comment]
Then I will create a pull request!
