### ISSUE TITLE
The key field of an attribute is empty! when reading example GTF Mus_musculus.NCBIM37.61.gtf file

### ISSUE THREAD

**Issue by martinjvickers** [seqan/seqan#1789]
I downloaded the Mus_musculus.NCBIM37.61.gtf file after resolving the download link #1788 and I'm unable to read in the file.

```
martin@x250:~/development/app-build/release$ ./app -q Mus_musculus.NCBIM37.61.gtf
terminate called after throwing an instance of 'seqan::ParseError'
  what():  The key field of an attribute is empty!
Aborted (core dumped)
```

The code is simply this;

```
    GffFileIn gffIn(toCString(queryFileName));
    FragmentStore<> store;
    readRecords(store, gffIn);
    cout << "I've read the file." << endl;
```

and works fine for the `assignment_annotations.gtf` file. I took just the first line of the `Mus_musculus.NCBIM37.61.gtf` file;

`NT_166433  protein_coding  exon    11955   12166   .   +   .    gene_id "ENSMUSG00000000702"; transcript_id "ENSMUST00000105216"; exon_number "1"; gene_name "AC007307.1"; transcript_name "AC007307.1-201";`

and after playing around with it noticed that there is an extra space between the tab after column 8 and the first character of column 9.

**Comment by martinjvickers** [comment]
Just to confirm that I've tried this again with the latest v2.2.0 release and the same error occurs 

I'm just wondering if this example dataset did work once with a previous release, i.e. that the GTF file was being successfully parsed despite the extra space and in a subsequent release the GTF parsing is more stringent. If that's so should we update the Mus_musculus.NCBIM37.61.gtf file so that it works? (I have a copy of the file without the extra space if you want me to send it for FTP upload)

If the above isn't the case and GTF parsing shouldn't be this stringent, could there be another underlying issue?

**Comment by rrahn** [comment]
@martinjvickers Thanks for reporting this. We'll investigate this.

**Comment by temehi** [comment]
@martinjvickers thanks again for reporting and also for finding out what causes the error. 

Since there are many gff/gtf files available for download with an extra space at the beginning of attributes column (col 9) we should accommodate these files and ignore the extra space. I will create a PR with a fix soon.
