### ISSUE TITLE
Proper deprecation

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1794]
Search the codebase for things that are deprecated and mark them with `[[deprecated]]` so that we actually get warnings when they are used.

**Comment by rrahn** [comment]
@h-2 I propose to put this to 2.4, since I am afraid, that it will break a lot in the nightlies, which we won't be able to fix until tomorrow.

**Comment by h-2** [comment]
postponed to 2.4

**Comment by smehringer** [comment]
This was fixed in #1870
