### ISSUE TITLE
Razers3 -- differences between serial and parallel mode

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1797]
Razers3 has two different codepaths, one serial, one parallel. Selected a thread count of 0 (`-tc 0`) chooses the serial one, and choosing a thread count of 1 (`-tc 1`) , chooses the parallel codepath, but with exactly one thread (also serial execution).

If run with `-rr 100` (full sensitivity) they produce the same results, but if the recognition rate is lowered to 99, than the parallel codepath misses results that the serial one finds. Unless the serial codepath actually ignores the rr setting, this hints at a bug in the parallel codepath.

**Comment by h-2** [comment]
This example reproduces the problem:
`bin/razers3 adeno-genome.fa adeno-reads36_1.fa adeno-reads36_2.fa -i 98 -rr 99`
Depending on whether `-tc 0` or `-tc 1` is specified, the results will differ.

[adeno-genome.fa.txt](https://github.com/seqan/seqan/files/357365/adeno-genome.fa.txt)
[adeno-reads36_1.fa.txt](https://github.com/seqan/seqan/files/357367/adeno-reads36_1.fa.txt)
[adeno-reads36_2.fa.txt](https://github.com/seqan/seqan/files/357368/adeno-reads36_2.fa.txt)

**Comment by holtgrewe** [comment]
I don't think that this is a bug.

The sequential and the parallel code path both only guarantee that at least one match per equivalence class is returned. As the parallel processing comes from window-wise processing, different matches are generated and thus different results are generated.

**Comment by h-2** [comment]
This is not about equivalence classes, but about number of mapped reads which is approximately half in parallel mode VS sequential. 
But maybe I misunderstood something?

**Comment by holtgrewe** [comment]
I see.

Maybe @weese can comment here?

**Comment by h-2** [comment]
Closed because inactivity.
