### ISSUE TITLE
Improve/fix native packaging

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1809]
In https://github.com/seqan/seqan/blob/master/util/cmake/SeqAnBuildSystem.cmake#L528 add:
- correct `CPACK_DEBIAN_PACKAGE_ARCHITECTURE` and `CPACK_RPM_PACKAGE_ARCHITECTURE` depending on target platform
- other DEBIAN and RPM specfifc flags?
- CPACK_WIX instead of CPACK_NSIS for windows installers?

**Comment by xenigmax** [comment]
I don't think there are many difficulties regarding this.
But I'm just curious. :)

(1) For deb/rpm (CPACK options, DEBIAN/REDHAT specific flags)
You mentioned that generation of deb/rpm/exe/dmg packages is just for our own apps.
So, do we need this? May I ask you why?

(2) For CPACK_WIX (windows)
May I ask what is the benefit of this change?

**Comment by h-2** [comment]
> (1) For deb/rpm (CPACK options, DEBIAN/REDHAT specific flags)
> You mentioned that generation of deb/rpm/exe/dmg packages is just for our own apps.
> So, do we need this? May I ask you why?

We overwrite the system architecture from `amd64` to `x86_64` in https://github.com/seqan/seqan/blob/master/util/cmake/SetCPackSystemName.cmake . This breaks the packaging, because the .deb and .rpm generator don't "know" which architecture is used anymore. To make sure that the packages are correctly detected as "64bit amd/intel", we need to manually also set the flags mentioned above.

> (2) For CPACK_WIX (windows)
> May I ask what is the benefit of this change? 

This will generate an `.msi` file which I think is the recommend thing nowadays on Windows? I really am not an expert for windows, but heard they are better / integrate with the system settings or some such...

**Comment by xenigmax** [comment]
@h-2, I will make a pull-request after merging #1900 .

I understand that architectural part. I will do that.  

However, for other DEB/RPM specific tags, would you let me know which tags do you want to add? 
I found several tags in here : https://cmake.org/Wiki/CMake:CPackPackageGenerators

.DEB, for example, these are already set.
CPACK_DEBIAN_PACKAGE_MAINTAINER
CPACK_PACKAGE_DESCRIPTION_SUMMARY
CPACK_DEBIAN_PACKAGE_VERSION

while these are not.
CPACK_PACKAGE_DESCRIPTION
CPACK_DEBIAN_PACKAGE_SECTION
CPACK_DEBIAN_PACKAGE_DEPENDS 

If you think these are important information, please provide me some official content for filling out them.
- In my opinion, I don't have such authority in the team.

**Comment by rrahn** [comment]
@h-2 what's the state about the PR? Can it be merged and this ticket closed?

**Comment by h-2** [comment]
done
