### ISSUE TITLE
DFS crash - recursion depth

### ISSUE THREAD

**Issue by rrwick** [seqan/seqan#1821]
I encountered a Seqan crash which I traced to the `depthFirstSearch` function in a large graph. Since this DFS is implemented recursively, it crashed when it reached a depth of 10s of thousands of recursive calls.

I was able to solve the problem by re-writing the function in a non-recursive manner:
[depth_first_search.h.txt](https://github.com/seqan/seqan/files/380257/depth_first_search.h.txt) (Sorry about the `.txt` - GitHub wouldn't attach the file without it)

I also wrote this program to test my new implementation and compare it against the previous one:
[dfs_test.cpp.txt](https://github.com/seqan/seqan/files/380258/dfs_test.cpp.txt)

This test program can show that my new implementation seems to produce the exact same DFS result as the previous implementation. It's only a tiny bit slower (only noticeable on huge graphs). And importantly, it doesn't crash on very large, very connected graphs, where the DFS search can get very deep.

You're more than welcome to use my new implementation in a future version of Seqan, if you would like!

**Comment by h-2** [comment]
@rrahn can you investigate this? Or does anyone else work with the graph module right now?

**Comment by rrahn** [comment]
@rrwick can you submit the crash report? 
In general, iterative or recursive function might not have a big influence on the runtime at all. So changing it should be fine in general. 
Can you make a PR, for the iterative DFS? I will than have a look at the code.

**Comment by rrwick** [comment]
@rrahn, I've made the PR: https://github.com/seqan/seqan/pull/1823

And while I tried to do the contributor license agreement described [here](https://github.com/seqan/seqan/blob/master/CONTRIBUTING.rst), it just said, 'We're sorry, but something went wrong.'

Let me know if there's anything else I can do!

**Comment by rrahn** [comment]
@h-2 can you check the CLA plugin. It seems to be broken again?!

**Comment by rrahn** [comment]
Fixed by #1828
