### ISSUE TITLE
guessFormatFromFilename issue

### ISSUE THREAD

**Issue by jwalabroad** [seqan/seqan#1831]
I am trying to read a BAM file as follows, but it is failing:

```
std::string bam="small.bam";
seqan::BamFileIn bamFileIn;
if(!open(bamFileIn, bam.c_str(), seqan::OPEN_RDONLY)) { 
std::cerr << "ERROR: could not open input file " << bamFileInName << ".\n";
return 1;
}
```

I have tried this for multiple BAMs, all of which are well-behaved with other APIs. This does work if I input a SAM file instead. I used gdb to find where ```open``` is failing, and traced it to ```!guessFormatFromFilename(basename, file.format)``` on line 698 of ```formatted_file.h```. The ```guessFormatFromFilename``` is returning 0, even though I am confirming that ```basename``` is indeed "small.bam"

Am I missing something here, or is this a bug?

**Comment by rrahn** [comment]
For reading bam you need to have the zlib library installed on your platform and enabled in Seqan.
I think the former requirement is matched but for the latter you need to make sure that the macro ```SEQAN_HAS_ZLIB``` is set to 1. (It is 0 by default).
Can you confirm that the macro SEQAN_HAS_ZLIB is set to 1. 
Do you use a cmake or make-file based project? In cmake based project you need to call
```
find_package (ZLIB)
```
before
```
find_package (SeqAn REQUIRED)
```
.
For integration into your own build system please read: http://seqan.readthedocs.io/en/master/Infrastructure/Use/CustomBuildSystem.html

**Comment by jwalabroad** [comment]
Thank you for the info, this was indeed my issue! I had compiled with -DSEQAN_HAS_BZIP2 but not with the -DSEQAN_HAS_ZLIB. I had seen in other issues that not compiling with -DSEQAN_HAS_BZIP2 would emit an error message when trying to access its functionality, perhaps the same could be done for zlib to make the failure more clear? At any rate, thank you so much for the quick response.

**Comment by rrahn** [comment]
Hi, 'glad it worked. 
Well, the problem with the open function is, that it does not throw an exception. I think, when passing the file name to the BamFile constructor, an exception is thrown if the file could not be opened. 
But I am not sure what the error message of that exception looks like. 
In any case, we will consider a more verbose error message for the future. 
Thanks for reporting.
