### ISSUE TITLE
extracting floating point array tag from BAM

### ISSUE THREAD

**Issue by bayolau** [seqan/seqan#1833]
Hi all,

what's the best way to extracting a floating point array (of type B,f) from the TAG of a BAM record? I tried `extractTagValue` with `BamTagsDict`, but don't know what floating point datatype to use.

Thank you

**Comment by rrahn** [comment]
Hi, 

it seems this functionality is not yet implemented. 
```extractTagValue``` only works for _Z_ fields or atomic types such as ```int``` not for arrays I am afraid.

**Comment by h-2** [comment]
@temehi can you look into this for 2.3.0?

**Comment by temehi** [comment]
@h-2  will do!

**Comment by temehi** [comment]
@bayolau could you please provide us with a small example BAM file with floating point array in a tag? 

Cheers!

**Comment by rrahn** [comment]
Maybe we reconsider the entire BamTagDicts for 3.0

**Comment by h-2** [comment]
> Maybe we reconsider the entire BamTagDicts for 3.0

Yes, we will definitely do somthing else, probably a vector of std::variant or some such.
