### ISSUE TITLE
"isOpen" function for FormattedFile

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#1834]
This would be super useful.

**Comment by smehringer** [comment]
I gave it a try. Works with a little example for me. @holtgrewe @rrahn can you take a look at it?

**Comment by holtgrewe** [comment]
What about adding a unit test?

**Comment by smehringer** [comment]
Sure. Any suggestions to which existing tests this might fit?
Since ```formattedfile.h``` belongs to ```include/seqan/stream/```, I looked into the stream tests but I'm having a little trouble to understand all the test cases and figure out where to best place an isOpen-test.

**Comment by smehringer** [comment]
I added unit tests for each of the formatted file IO's. (See PR)

**Comment by h-2** [comment]
fixed by #1844
