### ISSUE TITLE
Generate cigar [Question]

### ISSUE THREAD

**Issue by ganyfml** [seqan/seqan#1836]
Hi All,

I am trying to do the global alignment among two Dna5Strings (ref, query) and generate the SAM file using the following code.

```
  typedef Gaps<Dna5String, ArrayGaps> TGaps;

  TGaps gap_query;
  TGaps gap_ref;
  assignSource(gap_query, query);
  assignSource(gap_ref, ref);
  globalAlignment(gap_query, gap_ref, Score<int>(0, -1, -1)
, AlignConfig<false, false, false, false>(), -2, 2);

```

I have read the document that in order to generate the SAM, I need the cigar which is in the following format:

```
    String<CigarElement<> > cigar;  // CIGAR string
```

Is there any function which helps to generate cigar from gap_ref and gap_query? I see there is one function called "getCigarString(...)" in seqan source code, but there is no document in it (or I can not find it...), is "getCigarString(...)" useful in this situation?

Thanks,
Yue

**Comment by holtgrewe** [comment]
Hi @ganyfml yes, `getCigarString` is the way to go. Something like the following should work.

```c++
getCigarString(cigar, gap_ref, gap_query, 9999999);
```

**Comment by ganyfml** [comment]
Hi @holtgrewe Thank you! Could you explain what the 9999999 means?.....

**Comment by holtgrewe** [comment]
Ah, this is the threshold to make a deletion (of the read with relation to the reference) count as a splicing event (being encoded as `N`). This is more or less just a quick hack, though.

**Comment by ganyfml** [comment]
That is a clear explanation, thank you very much!
I suggest you add getCigarString() to document/tutorial, since it is a really useful function.....
