### ISSUE TITLE
_printBinary() function in myers_hirschberg pollutes stdout [ Question ]

### ISSUE THREAD

**Issue by eik-dahms** [seqan/seqan#1840]
Since seqan-v2.2.0 the function _printBinary() in global_alignment_myers_hirschberg_impl.h is writing directly to the stdout. (and therefore polluting the output of my program)

Is this an intended behaviour ?

@rrahn

**Comment by rrahn** [comment]
Hi, sorry it's not intended.
It must be a leftover. We'll remove it soon.
Thanks for reporting.
