### ISSUE TITLE
zip archive for seqan-library release

### ISSUE THREAD

**Issue by aseyboldt** [seqan/seqan#1856]
Since the 2.2.0 release [packages.seqan.de](http://packages.seqan.de) does not list zip archives for the `seqan-library` release any more. On linux using the `tar.xz` release is straightforward, but not so much on windows. I think this was introduced in #1667. Unless this was an intentional change (in the pull request only the binary releases are mentioned) it would be great to get zip archives again.

**Comment by h-2** [comment]
@xenigmax can you create a zip file for 2.2.0 and update our TODOs in case creating a zip file is missing?

**Comment by xenigmax** [comment]
@h-2  
We don't need to change TODOs.  
Our python script can handle the situation if .zip exists.
