### ISSUE TITLE
Write output to SAM/BAM format [ Question ]

### ISSUE THREAD

**Issue by ganyfml** [seqan/seqan#1862]
Hi,

I am currently developing a pipeline which contains two programs:

1. The **program 1** will build the index for the reference genome and save them to files.
2. The **program 2** will then load the index file and file contains query reads and do the search for each query read, and output results to SAM/BAM format.

I get two questions:

1. When I building the index using the **program 1**, is there any way to store the reference genome name/id along with the seqs in the index file? In this case, when my **program 2** write the SAM/BAM file, it will know reference sequence name.  

2. When to output the  SAM/BAM file, how should I link the BamAlignmentRecord::rID with the actual reference genome name?

Thanks

**Comment by h-2** [comment]
@temehi can you reply to this?

**Comment by h-2** [comment]
> When I building the index using the program 1, is there any way to store the reference genome name/id along with the seqs in the index file? In this case, when my program 2 write the SAM/BAM file, it will know reference sequence name.

The same way you save your index to disk, you can also save the reference IDs' StringSet with `save()`:
```c++
StringSet<CharString, Owner<ConcatDirect<>>> myIDs;
// ... readRecords or whatever

save(myIDs, "/tmp/idfile");
```

In the second program you should be able to do:
```c++
BamFileOut of;
//  ...
StringSet<CharString, Owner<ConcatDirect<>>> myIDs;
open(myIDs, "/tmp/idfile");
setContigNames(context(of)), myIDs);
```

> When to output the SAM/BAM file, how should I link the BamAlignmentRecord::rID with the actual reference genome name?

They should just be in the same order...

**Comment by h-2** [comment]
@ganyfml I hope the explanations could help you, if you still have questions, please feel free to re-open this issue.
