### ISSUE TITLE
Print the help at will

### ISSUE THREAD

**Issue by martinjvickers** [seqan/seqan#1863]
Is there a method to print the help whenever I want to, not just when parsing the command line arguments?

**Comment by smehringer** [comment]
Hi @martinjvickers,

there is a function called ```void printHelp(parser[, stream, format, showAdvancedOptions])``` that lets you print out the help. Please take a look at our [API](http://docs.seqan.de/seqan/master/) for further details. 

A minimal working example could be:
```
#include <iostream>
#include<seqan/arg_parse.h>

int main(int argc, char const ** argv)
{
    // Setup ArgumentParser.
    seqan::ArgumentParser parser("modify_string");

    addArgument(parser, seqan::ArgParseArgument(
        seqan::ArgParseArgument::STRING, "TEXT"));

    // print help to std::cerr
    printHelp(parser);

    return 0;
}
```
which prints the help to the standard error output.

I hope this answers your question. If there is anything else you would like to know feel free to ask.

**Comment by martinjvickers** [comment]
Hi @smehringer,

That's fantastic, exactly what I needed. 

Thank you very much for your help and swift response.

Cheers,

Martin
