### ISSUE TITLE
Typos in Manual

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#1864]
http://seqan.readthedocs.io/en/master/Tutorial/GettingStarted/BackgroundAndMotivation.html
1. "You might already have get in touch with global function interfaces while working with the STL" replace "get in touch" with "seen"
2. "The rationale behind is the following observation." add "this"
3. "Such task can be performed by metafunctions" -> tasks

http://seqan.readthedocs.io/en/master/Tutorial/Workflows/UseSeqAnNodesInKnime.html
1."After the installation is don" -> done
2. "with the newly installed SeqAn nodes will be" -> drop "will be"
3. "In this way we will we can identify SNP’s more clearly." drop "we will"
4. "Give your workflow an approprate name" -> appropriate
5. "The node name it the text bellow the node." -> "is" and "below"
6. "has quite few workflows ready to run" -> several workflows
7. "With the help of the GenericWorkflowNodes one" drop "the"
8. "These file contain the command line description of an application in XML format" -> files
9. "For application developed in SeqAn or applications using" -> applications
10. "Below is an example of a CTD file for SortBam tool for sorting BAM files." -> "a SortBam"
11. "Also, we always call the program with view -f as the first two command line arguments since we do not provide a mapping for these arguments." Maybe I misunderstand but it seems to me you are calling samtools with "sort -f"
12. "/toll@category The path to the tool’s category." -> tool
13. "In this tutorial you will learn how to write a SeqAn app, which can be, easly converted into a KNIME node." ", easly" -> easily
14. "Later, when building workflows, you can only connect an output-port of a node to the input-port of the next one if only they have a compatible file endings." drop second "only"

**Comment by smehringer** [comment]
fixed by #1919
