### ISSUE TITLE
check implicit fallthroughs

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1865]
New compilers now warn if one has an implicit fallthrough, i.e.
```c++
switch(i)
{
    case 0:
        cout << "foo\n";
        break;
    case 1:
        cout << "bar\n";
        // falls through to case 2
        // generates warning on gcc7
    case 2:
        cout << "bax\n";
        break;
}
```
This is often a bug, so to explicitly state that this is desired behaviour, you can now add:
```c++
switch(i)
{
    case 0:
        cout << "foo\n";
        break;
    case 1:
        cout << "bar\n";
        [[fallthrough]]
        // falls through to case 2
        // generates no warning on gcc7
    case 2:
        cout << "bax\n";
        break;
}
```
This is formally a c++17 feature, but unknown attributes should be ignored on older versions so it should work anyway on c++14, too.

We need to 
* [x] check that the is the case for all our platforms (i.e. every supported compiler must not complain about the attribute)
* [x] add the attribute to our implicit fallthroughs in the library that currently produce warnings / investigate if the fallthrough is actually intended or maybe a bug

These are the current warnings:
http://cdash.seqan.de/viewBuildError.php?type=1&buildid=195900

**Comment by joergi-w** [comment]
Issue was solved with Pull Request #1882 and can be closed.

**Comment by h-2** [comment]
@joergi-w  Even the second pull request introduced new warnings. Please resolve them and in the future always check the cdash after one of your PRs has been merged to see its effect on other platforms! Thanks!

**Comment by joergi-w** [comment]
Now the warnings are gone, so we can close this issue.
