### ISSUE TITLE
windows nightlies broken

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1866]
* [x] klette seems to down
* [x] margerite/icpc seems to be broken
* [x] Change builds of master to weekly

PS: we can change the builds for the master branch to be weekly instead of nightly since there are no changes to master anyway.

**Comment by marehr** [comment]
@h-2 I deleted 33gb of temporary files and restarted the builds on klette. The HDD was full.

**Comment by marehr** [comment]
@h-2 I changed the builds of the master branch to weekly on klette and margerite. They will trigger in the night from sunday to monday.

**Comment by marehr** [comment]
@h-2 margerite/icpc seemed to build this night. I restarted all nightlies to see if they all work again.
