### ISSUE TITLE
Get Intel 2017 stuff installed

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1868]
While I don't _expect_ anything to have broken, it is quite important that we verify before the enxt release. Also the new compiler brings in KNL support.

For 2.3 @marehr 
- [x] ask staff to install Linux ICPC 17 and
- [x] ping @h-2 to add it to the nightlies
- [x] see if there are any issues and fix them

For 2.4 @rrahn 
- [x] setup windows VM with new intel windows compiler

**Comment by marehr** [comment]
@h-2 I wrote the `technik` an email.

**Comment by h-2** [comment]
@marehr what is the status here? Can you please keep bugging the staff until they do it?

**Comment by marehr** [comment]
Intel compiler 2017 is setup and running on linux. No issues with icpc17, this is now @rrahn's issue.
