### ISSUE TITLE
Open an empty FASTA file fails

### ISSUE THREAD

**Issue by bjpop** [seqan/seqan#1873]
Using seqAn 2.1.1. When I try to open an empty FASTA file (zero bytes), the open function returns false.

This behaviour makes it difficult to distinguish between file I/O errors and an empty file. We might like to handle these cases differently.

Example code below demonstrates the problem:

```
#include <seqan/seq_io.h>

using namespace seqan;
using namespace std;

int main(int argc, const char **argv)
{
    SeqFileIn seq_file;
    if (!open(seq_file, argv[1]))
    {
        cout << "Could not open the file.\n";
    }
    else
    {
        cout << "open worked\n";
    }
}
```

**Comment by bjpop** [comment]
This is fixable if we open ifstream first, and construct a SeqFileIn from that.

This behaviour is different than the code mentioned above. Is that intentional?

```
ifstream input_file(argv[1]);
if (!input_file)
{
     cout << "Could not open the file.\n";
}
SeqFileIn seq_file(input_file);
```

**Comment by rrahn** [comment]
If you open the file using the ```SeqFileIn``` using it's constructor like so:
```cpp SeqFileIn file(argv[1])``` it will throw an exception instead. 
It can throw an ```FileOpenError``` if it cannot open the file, or an ```UnknownFileFormat``` or ```UnknownExtensionError``` exception. In the last two cases the file had to be parsed, to read the magic number. If it is 0 bytes or an format that does not fit the file extension, than those exceptions are thrown. 
This way you can check, if the file couldn't be opened or if the format of the fiel is odd.
Does that help you?

**Comment by bjpop** [comment]
Yes, that is helpful. Thanks for the information.

**Comment by smehringer** [comment]
Feel free to re-open the issue.
