### ISSUE TITLE
"Git Workflow" tutorial outdated

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1877]
http://seqan.readthedocs.io/en/master/Infrastructure/Contribute/GitWorkflow.html#infra-contribute-git
doesn't correctly describe our current git workflow, also some things should maybe be stated in CONTRIBUTING.rst more prominently.

Change the tutorial:
- [x] all bug-fixes, feature and other PRs go to the develop branch
- [x] only severe issues, such as packaging mistakes, regression and interface breakages shall results in PRs to master and an immediate patch-level release

**Comment by rrahn** [comment]
fixed by #1965
