### ISSUE TITLE
Make it possible to turn individual apps off

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1891]
Here we add our individual apps to the build:
https://github.com/seqan/seqan/blob/master/util/cmake/SeqAnBuildSystem.cmake#L182

It would be good if we add another check to the if-clause, something like:
```
(NOT ${${APP}_NO_BUILD})
```
that enables you to selectively block certain apps from being built. NOTE that I am not sure this syntax is supported by cmake. If it doesn't work, one might need to add a `SKIP_APP_LIST` and then check if the app-name is a member of the list.

@joergi-w can you look into this?

**Comment by joergi-w** [comment]
see PR #1894
