### ISSUE TITLE
rna_io errors with Windows

### ISSUE THREAD

**Issue by joergi-w** [seqan/seqan#1921]
cdash reports some errors from the rna_io module
- [x] read_ebpseq test fails on icpc compiler
- [x] build errors occur in bracket2graph function in dot_bracket_read_write.h

**Comment by joergi-w** [comment]
Tested successfully on icpc (ICC) 16.0.3, so read_ebpseq is fixed now.

**Comment by joergi-w** [comment]
Probably, the Windows errors in bracket2graph were caused by the auto-Type variable elem. The resulting iterators of the std::find function are not of equal types, because the arrays have varying lengths. In the recent commit I use three separate variables to avoid the ambiguity. Sadly, I could not yet test the result in a Windows environment. 

What do you think of this solution @h-2 ?

**Comment by rrahn** [comment]
You can run windows in a VM to test it locally. Here https://www.zedat.fu-berlin.de/Benutzerservice/DreamSpark you can get access to Win OS.
You can log into klette.imp.fu-berlin.de with your zedat account and use VS there.

**Comment by joergi-w** [comment]
Thank you for the suggestions! I have tested successfully, so I start a pull request now.

**Comment by joergi-w** [comment]
The errors and warnings on cdash have been patched with PR #1940, so I close this.
