### ISSUE TITLE
A rare deadlock case in bam file loading

### ISSUE THREAD

**Issue by xenigmax** [seqan/seqan#1927]
I tried to read 100G bam file, and it couldn't finish the job.
I think it's about event management of multiple thread in bgzf stream since CPU usage became 0.

Since # of threads is fixed in bgzf stream(#1899), I manually changed this to 1 thread / 1 job.
And now it's not working with relatively small file( < 10GB).

I'm working on this.

**Comment by xenigmax** [comment]
Sometimes our decompression function for bgzf stream got 0 here.
https://github.com/seqan/seqan/blob/master/include/seqan/stream/iostream_bgzf.h#L588-L591

And in some situation, this cause a **deadlock** between the parent and child threads like below.
< Parent thread >
```
func readRecord :
    push(Q1)
    while (true) :        
        pop(Q2) # wait if empty
        parent_job_1(..)

func main :
    push(Q1)
    spawnChildThead(..)

    while (!EOF)
        readRecord(..)
        parent_job_2(..)
```

< Child thread >
```
func main :
    while (true) :
        pop(Q1) # wait if empty
        child_job(..)
        push(Q2)
```

(1) Normal case
```
Parent : push(Q1)          -> wait for pop(Q2)             -> parent_job_1        -> parent_job_2 -> push(Q1) ...
Child  : wait for pop(Q1)  -> child_job        -> push(Q2) -> wait for pop(Q1) ..
```

(2) Deadlock
```
Parent : push(Q1)          -> wait for pop(Q2)             -> parent_job_1        -> parent_job_1 -> wait for pop(Q2)
Child  : wait for pop(Q1)  -> child_job        -> push(Q2) -> wait for pop(Q1) ...
```

Since we are running 16 threads in parallel for I/O, Q1 and Q2 are not empty in most of the time.
Therefore, it's very rare.

If you wish to reproduce the situation 
1) modify below as numThreads=1, jobsPerThread=1 (or hard to reproduce the situation..)
https://github.com/seqan/seqan/blob/master/include/seqan/stream/iostream_bgzf.h#L496-L498

2) and try this code with the attached bam file.

```
#include <seqan/bam_io.h>

using namespace seqan;

int main(int argc, char *argv[])
{
    // bam
    CharString bamFileName = argv[1]; 
    BamFileIn bamFileIn;
    if (!open(bamFileIn, toCString(bamFileName)))
    {   
        std::cerr << "bam loading err : " << bamFileName << " \n";
        return false;
    }   

    int i=0;
    BamHeader header;
    readHeader(header, bamFileIn);
    while(!atEnd(bamFileIn))
    {   
        BamAlignmentRecord record;
        readRecord(record, bamFileIn);
        std::cerr << i++ << "th record\t" << record.qName << "\t" << record.flag << "\n";
    }   
}
```

**< Compile & run >**
g++ test.cpp -std=c++14 -g -ggdb -I YOUR_SEQAN_INCLUDE_DIR -DSEQAN_HAS_ZLIB=1 -lz -lpthread
./a.out ./1927.bam 
[1927.bam.gz](https://github.com/seqan/seqan/files/595822/1927.bam.gz)

I think it's related with correct usage of inflate function of zlib but I'm not sure..
zlib : http://zlib.net/zpipe.c
ours : https://github.com/seqan/seqan/blob/master/include/seqan/stream/stream_compressor.h#L425:L483

I will make a temporary PR that can avoid this deadlock situation.

**Comment by h-2** [comment]
assigning to @rrahn because of the threading and @temehi because of bam io

**Comment by temehi** [comment]
@xenigmax what is the status here? Should I start working on this?

**Comment by xenigmax** [comment]
@temehi  
I'm using this temporary fix for Vaquita.
- But I don't think it's the right solution for sure. :)

https://github.com/seqan/vaquita/blob/master/seqan-library-2.2.0/include/seqan/stream/iostream_bgzf.h#L588-L600

**Comment by temehi** [comment]
@rrahn  are you working on this? 😄 👍

**Comment by rrahn** [comment]
Yes, I can look at it.
Seems like an interesting bug.

**Comment by h-2** [comment]
What is the status here?

**Comment by rrahn** [comment]
Temesgen, can I play the ball back to you? We can also look into it together. But my plate is full with other stuff right now.
