### ISSUE TITLE
User question: Using input file format for output file

### ISSUE THREAD

**Issue by kdmurray91** [seqan/seqan#1935]
Hi all,

Firstly sorry if this isn't a good place to ask such questions, or if my confusion is the result of not reading the docs closely enough.

I'm attempting to write a tiny tool using seqan that reads either fasta or fastq records, does a tiny transformation, and write either fasta or fastq records, depending on the format of the input.

In short, I use

```
using namespace seqan;
const char *filename = "test.fastq"; // actually from argv
SeqFileIn instream(filename);
SeqFileOut outstream(std::cout, seqan::format(instream));
std::string id, seq, qual;
size_t nrecs = 0;
while (!seqan::atEnd(instream)) {
        nrecs++;
        readRecord(id, seq, qual, instream);
        writeRecord(outstream, id, seq, qual);
}
std::cerr << "Read " << nrecs << " records\n";
```

The correct number of records are printed, however no records are output. Manually specifying `seqan::Fasta()` (or fastq) to the outstream constructor works.

Thanks in advance for your help.

Cheers,
K

**Comment by h-2** [comment]
Hm, I haven't used our streaming with cout, yet, but in theory it should work :sweat_smile: 
Have you tried using user-specified names for both input and output? Then it should work, I think. 

In any case it should work with cout, as well. @temehi can you ahve a look?

**Comment by kdmurray91** [comment]
Thanks for the prompt response @h-2. I tried setting the input format with:

```c++
SeqFileIn instream(filename);
setFormat(instream, Fasta());
```

and nothing changed.

Cheers,
K

**Comment by temehi** [comment]
at the moment formats of `SeqFileIn` are not compatable with those of `SeqFileOut`. So there is no way to set the format of your `outstream` based on `seqan::format(instream)`.

A silly workaround would be to get your `SeqFileIn` extension and create a dummy `SeqFileOut` with a temp_file of the same extension and set the format of the actual  `SeqFileOut` based on that.

example:

```
    std::string filename = "/Users/dadi/workspace/example_data/simulated_reads.fa"; // actually from argv
    SeqFileIn instream(toCString(filename));

    std::string temp_filename = SEQAN_TEMP_FILENAME() + getFileExtensions(instream)[0];
    SeqFileOut temp_outstream(toCString(temp_filename));
    SeqFileOut outstream(std::cout, format(temp_outstream));
    close(temp_outstream);

    CharString id, seq, qual;
    size_t nrecs = 0;
    while (!seqan::atEnd(instream)) {
        nrecs++;
        readRecord(id, seq, qual, instream);
        writeRecord(outstream, id, seq, qual);
    }
    std::cerr << "Read " << nrecs << " records\n";
```

**Comment by h-2** [comment]
@temehi can you write a function that does this? should be somthing along the lines
```c++
bool tagSelectIntersect(TOutTagSelector & out, TInTagSelector const & in)
{
    // tag dispatch on in
    // then tag dispatch on out and set the tagId when both tags are identical
}
```

**Comment by rrahn** [comment]
@temehi can this be closed now?

**Comment by temehi** [comment]
Sure! @kdmurray91 With the next release (2.3.0) you can do 
`result = tagSelectIntersect(outstream.format, instream.format);` 

`result` is a boolean which will be true after successful assignment and false otherwise.

**Comment by kdmurray91** [comment]
@temehi Did that make it into the docs/tutorial somewhere?
