### ISSUE TITLE
Error while installing only header files

### ISSUE THREAD

**Issue by lemogras** [seqan/seqan#1943]
I followed the instructions in User Library Installation (http://xenigmaxseqan.readthedocs.io/en/fix-1043/BuildManual/UsingTheSeqAnBuildSystem.html). However I get this error when I run "make dox".

```
Baki-MacBook-Pro:library_only baki$ make install
Traceback (most recent call last):
  File "/Users/baki/seqan-src/dox/../util/bin/dox.py", line 14, in <module>
    sys.exit(main())
  File "/Users/baki/seqan-src/dox/../util/bin/dox.py", line 10, in main
    import seqan.dox.pure
  File "/Users/baki/seqan-src/util/py_lib/seqan/dox/pure.py", line 152
    except dox_parser.ParserError, e:
                                 ^
SyntaxError: invalid syntax
make[2]: *** [dox/CMakeFiles/dox] Error 1
make[1]: *** [dox/CMakeFiles/dox.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by xenigmax** [comment]
The link is not official SeqAn documentation.
Many contents in the link are out-of-date.
You can refer here instead.
http://seqan.readthedocs.io/en/master/Infrastructure/Use/Install.html#library-package

May I ask how did you get the link?

**Comment by lemogras** [comment]
Thanks for answering. I will review the link you provided.

The link I provided was shown on google search, not hard to find actually.

**Comment by xenigmax** [comment]
I deactivated the link. That was made for a testing :)
Thank you for letting me know.
