### ISSUE TITLE
[QGramIndex] indexRequire() does not work with simple Strings instead of StringSets

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan#1952]
When an index is required, it calls the function createCountsArray() which is only implemented for StringSets [here](https://github.com/seqan/seqan/blob/develop/include/seqan/index/index_qgram.h#L1696)

**Comment by rrahn** [comment]
Well, this might be by design, not documented well. I currently don't know if certain functionality of the Stringset is supported by strings. Not always they can be used interchangeably. 
Where do you need it?

**Comment by smehringer** [comment]
Umm, sorry. It's been too long for me to remember.. I'll reopen it if I come across it again.
