### ISSUE TITLE
Introduce parallel interface for index-based find module

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan#1954]

**Comment by esiragusa** [comment]
Hey @cpockrandt, the parallel interface is here: 
* https://github.com/seqan/seqan/blob/master/include/seqan/find/find_lambda.h
* https://github.com/seqan/seqan/blob/master/include/seqan/index/find_index_lambda.h

At best, indexed find interface should be consistent with online find. See also #545, #1403.

**Comment by cpockrandt** [comment]
Done with #2162
