### ISSUE TITLE
INPUT_DIRECTORY and OUTPUT_DIRECTORY don't accept trailing /

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1988]
The arg parser now explicitly supports directories. However, if I specify `.lambda` as directory extension, this does not include `.lambda/`.
This is unintuitive and some shells automatically add this with auto-completion.

**Comment by smehringer** [comment]
@h-2 
Does seqan have file path manipulation (stripping the last `/`) ? If not where should I add this functionality because I'll need it to conveniently fix this issue.

**Comment by rrahn** [comment]
We have tokenisation functions that do something like `readUntil(...);`
It is not documented,  but you can find it here: https://github.com/seqan/seqan/blob/master/include/seqan/stream/tokenization.h

**Comment by smehringer** [comment]
Thank you. Can you direct me to a (example) structure of the `functor` that is needed for the stop criterion?
