### ISSUE TITLE
cmake edits files that are under version control

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#1992]
#1969 changes existing files that are under version control. This is not good practice, because it causes files locally to change again and again, making it very likely that someone commits them by mistake. If the files really need to be system dependent, than the should be generated completely by cmake, not edited in place.
This could be done by tracking a `dox/dox_only.sh.in` in the repo (but not without the `.in`) and copy-rewriting that to `dox/dox_only.sh`. Or the code could be completely contained in the cmake script and generated upon execution.

@xenigmax can you look into this, as you did the original changes, too? Thx!

**Comment by h-2** [comment]
This effectively breaks out-of-source builds and might be rejected by down-stream package systems for this reason. Possibly we need to make a 2.3.2 release for this. @rrahn what is your opinion as the person who merged #1969 ?

**Comment by xenigmax** [comment]
Hmm.. As far as I remember, we had some discussion about this.
But I totally ignored the possibility of changing run.sh to run.sh.in.
I made a PR for this.
