### ISSUE TITLE
We need to forward mail seqan@support.de to sedan-team...

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#2016]
Please write the IT.

**Comment by cpockrandt** [comment]
@rrahn Done. But mails going now to support@seqan require moderation on the mailing list ...

**Comment by rrahn** [comment]
@marehr can you do that, and btw, add me and @h-2 to the maintainer of the list.
thanks

**Comment by marehr** [comment]
I'm already moderating the list. Btw, @h-2 and @rrahn are admins on the list, so you should be able to add yourself as a moderator.
