### ISSUE TITLE
SeqIO incorrectly assumes support for .bam

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#2018]
... although gzip is not available.

In:
https://github.com/seqan/seqan/blob/master/include/seqan/seq_io/sequence_file.h#L86
the Bam extension should be macro-guarded by zlib presence, like in bam_io:
https://github.com/seqan/seqan/blob/master/include/seqan/bam_io/bam_file.h#L122

@temehi can you fix it this week? Should be very easy to do...
Thanks!

**Comment by rrahn** [comment]
@temehi ping
