### ISSUE TITLE
Dead links in ReadTheDocs

### ISSUE THREAD

**Issue by cbielow** [seqan/seqan#2032]
When reading
http://seqan.readthedocs.io/en/master/Tutorial/GettingStarted/BackgroundAndMotivation.html

there are several dead links, e.g. to [template subclassing](http://seqan.readthedocs.io/en/master/Tutorial/GettingStarted/tutorial-getting-started-template-subclassing) or [ the section “From OOP to SeqAn” in the First Steps Tutorial.](http://seqan.readthedocs.io/en/master/Tutorial/GettingStarted/tutorial-getting-started-first-steps-in-seqan).
There might be more.

**Comment by h-2** [comment]
Should these prodcue errors  in our sphinx build? @xenigmax can you check this?

**Comment by martinjvickers** [comment]
@xenigmax @h-2 Regarding the `template subclassing` link, I'm not sure where this should point to. If anyone knows let me know and I can correct it.

**Comment by h-2** [comment]
what is the status here?

**Comment by rrahn** [comment]
Someone should check it and fix it accordingly.
@joergi-w Can you have a look. I think you have right now no further issues?
