### ISSUE TITLE
Compiling with TBB -ltbb flag with cmake

### ISSUE THREAD

**Issue by martinjvickers** [seqan/seqan#2034]
I'm trying to use the threading building blocks library within a program I'm writing and I can't seem to get it to compile. The library is installed on my ubuntu machine (`apt-get install libtbb-dev`) and a simple hello world (non-seqan/cmake) program compiles and runs fine;

`g++ hello.cpp -ltbb -std=gnu++11`

So I don't think there is an issue with tbb on my machine.

To add tbb into my seqan program I added -ltbb to make CMakeList.txt file alongside -lpthread but I get;

```
/usr/bin/ld: cannot find -ltbb
collect2: error: ld returned 1 exit status
make[2]: *** [tbb_test] Error 1
make[1]: *** [CMakeFiles/tbb_test.dir/all] Error 2
make: *** [all] Error 2
```

Is there another way to add the `-ltbb` flag or anyone know how to use the tbb within a seqan project?

**Comment by h-2** [comment]
@jtroehr can you respond to this? You are using TBB, right?

**Comment by martinjvickers** [comment]
Thanks for the reply @h-2 @jtroehr. I've found what the issue is but I'm not sure how to solve it. It's because in my CMakeList.txt file I have the following;

```set (CMAKE_CXX_FLAGS  "-${CMAKE_CXX_FLAGS} ${SEQAN_CXX_FLAGS} -ltbb")```

which creates the following in the link.txt file.

```/usr/bin/c++ -std=c++14 -ltbb -O3 -DNDEBUG   CMakeFiles/tbb_test.dir/tbb_test.cpp.o  -o tbb_test -rdynamic -lrt -lpthread -lz```

The issue is that I need -ltbb at the end. Can I do this from the CMakeLists.txt file?

**Comment by h-2** [comment]
> Can I do this from the CMakeLists.txt file?

Yes, instead of adding `-ltbb` to your CXX_FLAGS, instead add `tbb` to your `target_link_libraries`. In case that you are including `SEQAN_LIBRARIES` at that point anyway, you can just add it to `SEQAN_LIBRARIES`.

**Comment by martinjvickers** [comment]
@h-2 that's great, it works perfectly!
