### ISSUE TITLE
Replace getValue(it) with *it in tutorials

### ISSUE THREAD

**Issue by eldariont** [seqan/seqan#2042]
getValue(it) is deprecated but used in tutorials. Replace with operator*.

Deprecated: http://docs.seqan.de/seqan/develop/concept_IteratorAssociatedTypesConcept.html#IteratorAssociatedTypesConcept%23getValue

Tutorial example: http://seqan.readthedocs.io/en/master/Tutorial/DataStructures/Sequence/StringsAndSegments.html#assignment-5

**Comment by h-2** [comment]
Can you make a pull request?
