### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by alexanderwhatley** [seqan/seqan#2048]
I'm running razers3 on a 28GB BAM file using 32GB of RAM on a HPC cluster, and it is crashing as the memory limit is being exceeded. Do you have any recommendations on what to do when the input file sizes are large? Thanks.

**Comment by rrahn** [comment]
You could try out yara (https://www.seqan.de/apps/yara/). It also has an exact mode, while using much less memory.
If you really need razers3 for any reasons, then the only option that comes to my mind is to split the bam file and run the job in batches. So you can then also distribute over the nodes of your HPC if possible.

**Comment by h-2** [comment]
Closed because inactivity.
