### ISSUE TITLE
read bam error on mac, sam right

### ISSUE THREAD

**Issue by zengfengbo** [seqan/seqan#2056]
# code
```c++
    // error
    CharString bamFileName = "demos/tutorial/sam_and_bam_io/example.bam";
    // right
    CharString bamFileName = "demos/tutorial/sam_and_bam_io/example.sam";
    
    // Open input file, BamFileIn can read SAM and BAM files.
    BamFileIn bamFileIn;
    if (!open(bamFileIn, toCString(bamFileName)))
    {
        std::cerr << "ERROR: Could not open " << bamFileName << std::endl;
        return 1;
    }
```

# ERROR: 
Could not open /Users/fb/src/seqan-src/demos/tutorial/sam_and_bam_io/example.bam
Program ended with exit code: 1

**Comment by rrahn** [comment]
Hi that's strange. We don't see this in our nightly builds. But demos are tested as well. Can you please check that the macro ```SEQAN_HAS_ZLIB``` is set?

**Comment by zengfengbo** [comment]
I installed using brew.
`brew install  --HEAD homebrew/science/seqan`
and added the include path `/usr/local/Cellar/seqan/HEAD-d80e19a/include`.
how to check the macro `SEQAN_HAS_ZLIB` ?

**Comment by rrahn** [comment]
In your source file add a line in your main with something like:
```cpp
#if SEQAN_HAS_ZLIB
    std::cout << "zlib found" << std::endl;
#endif
```
or you can call
```
make -n your_main.cpp
```
which shows you what make would do. There should be the definition ```-DSEQAN_HAS_ZLIB``` listed.
Here is the [link](http://seqan.readthedocs.io/en/master/Infrastructure/Use/index.html) to some documentation of installing and using SeqAn in cmake-based projects or when you use your own build system.

**Comment by zengfengbo** [comment]
the macro `SEQAN_HAS_ZLIB` not found.
```c++
#if SEQAN_HAS_ZLIB
    std::cout << "zlib found" << std::endl;
#endif
```
Nothing happened.

**Comment by rrahn** [comment]
Ok, so this means that you did not link against zlib properly.

1.  make sure zlib is installed on your system.
2. make sure that libz.a is in your library path (should be the case, if installed via macports or homebrew)
3. in your build command add: ```g++ -I${prefix}/seqan/include -DSEQAN_HAS_ZLIB  ... main.cpp -lz```

That should make reading bam files to work.
If you use cmake then please read this [docu](http://seqan.readthedocs.io/en/master/Infrastructure/Use/FindSeqAnCMake.html) for more information on building your application with SeqAn.

**Comment by zengfengbo** [comment]
Thanks, @rrahn , It works.
```bash
clang++ -I/usr/local/Cellar/seqan/HEAD-d80e19a/include -DSEQAN_HAS_ZLIB -std=c++14 main.cpp -lz && a.out
```
