### ISSUE TITLE
Writing alignment objects to file (aligned FASTA, CLUSTALW etc)

### ISSUE THREAD

**Issue by skptic** [seqan/seqan#2060]
I have been unable to find any documentation/examples for writing out alignments to file. 

Ideally I'm wanting to output aligned FASTA or CLUSTALW type MSA files.

The only reference I can find is to the deprecated, old-style I/O `write()` function.

I assume there must be a way of doing it with `writeRecord`?

**Comment by h-2** [comment]
@joergi-w Can you help?

**Comment by joergi-w** [comment]
Sure. You need to use the AlignmentGraph and the [write](http://docs.seqan.de/seqan/master/class_Graph.html#Graph%23write) function there, which is not deprecated. It allows you to print to a file or to std::cout in any format listed here:
[http://docs.seqan.de/seqan/master/group_AlignmentGraphFormatTags.html](url)

I give you some example code:
```
#include <iostream>
#include <seqan/align.h>

using namespace seqan;

int main()
{
    typedef StringSet<DnaString, Dependent<> > TStringSet;
    typedef Graph<Alignment<TStringSet, void> > TAlignmentGraph;

    DnaString seq1 = "atcgaatgcgga";
    DnaString seq2 = "actcgttgca";
    TStringSet stringSet;
    appendValue(stringSet, seq1);
    appendValue(stringSet, seq2);
    TAlignmentGraph alignmentGraph(stringSet);
    
    StringSet<CharString> names;
    appendValue(names, "first");
    appendValue(names, "second");

    Score<int> scoringScheme(0, -1, -1, -2);
    int score = globalAlignment(alignmentGraph, scoringScheme, Gotoh());
    
    write(std::cout, alignmentGraph, names, MsfFormat());  // write in MsfFormat
    return 0;
}
```

**Comment by joergi-w** [comment]
@skptic : Was my answer helpful and can we close this issue?

**Comment by skptic** [comment]
Absolutely, thank you very much.

The confusion stems from the comment for write here claiming it to be deprecated.

http://docs.seqan.de/seqan/2.3.2/

**Comment by h-2** [comment]
@skptic Yes, the interface with a pure write function was deprecated for most of the IO which switched to new interfaces for SeqAn2, but for IO of Graphs it is not deprecated:
http://docs.seqan.de/seqan/2.3.2/class_Graph.html#Graph#write
Or did you see it makred as deprecated somewhere else?
