### ISSUE TITLE
FASTA writeRecord line length

### ISSUE THREAD

**Issue by LakeMendoza** [seqan/seqan#2061]
Is it possible to adjust FASTA output line length? Currently the following line produces a FASTA file with lines of 70 bp, but I would like to be able to adjust this if it's at all possible. I found SequenceOutputOptions in the docs.seqan.de but I don't know how I should use this. Any help would be much appreciated.

```
while (!atEnd(seqFileIn)) 
{
	readRecord(id, seq, seqFileIn);
	writeRecord(seqFileOut, id, seq);
}
```

**Comment by temehi** [comment]
Hello,
Yes it is possible. You can assign your `SequenceOutputOptions` object  to the context of `seqFileOut`.

```
   ...
   int lineLength = 100;
   SequenceOutputOptions write_options = SequenceOutputOptions(lineLength);
   context(seqFileOut).options = write_options;
   ...
```

**Comment by LakeMendoza** [comment]
Great, many thanks! It worked!

**Comment by temehi** [comment]
@LakeMendoza One more thing, 

- if lineLength = -1 (default) ---> lines will be of length 70
- if lineLength = 0 it means no line-wrapping at all.
