### ISSUE TITLE
Fragment Store loadContigs cannot handle 'M' in the contigs. 

### ISSUE THREAD

**Issue by roger-liu-bina** [seqan/seqan#2062]
If the reference, for example human hs37ds, contains letter M, seqan fails immediately.

**Comment by h-2** [comment]
This depends on which alphabet you use. Dna handles A,C,G,T, Dna5 handles A,C,G,T,N and Iupac handles all of the 16 Iupac characters. Did you try with Iupac, and if yes, can you post a more complete example?

**Comment by martinjvickers** [comment]
When using Dna5String it should convert anything other than an AGCT to an N. 
http://docs.seqan.de/seqan/master/?p=Dna5
```
An object that has a value not in {'A', 'C', 'G', 'T'} is converted to 'N'.
```
According to the docs for Dna, anything other than an AGCT is converted to an A?
http://docs.seqan.de/seqan/master/?p=Dna
```
An object that has a value not in {'A', 'C', 'G', 'T'} is converted to 'A'.
```

**Comment by h-2** [comment]
> So even if Dna is being used, it shouldn't fail right?

That depends. When doing an assignment this is true, but when doing IO SeqAn is "strict" by default. This is to prevent wrong data from just being re-interpreted, like an amino acid fasta file just being converted to lots of Ns without diagnostic.

**Comment by martinjvickers** [comment]
That makes sense, thanks for the clarification.

**Comment by h-2** [comment]
@roger-liu-bina does this answer your question, solve your problem?

**Comment by rrahn** [comment]
please reopen if the issue is not solved yet.
