### ISSUE TITLE
compiler crash with g++-5 and g++-6

### ISSUE THREAD

**Issue by joergi-w** [seqan/seqan#2065]
The target test_align_simd_sse4 make the compilers crash: http://cdash.seqan.de/viewBuildError.php?buildid=222160

EDIT: cdash points to this build https://travis-ci.org/seqan/seqan/builds/228898434

**Comment by marehr** [comment]
I'm on it! #2064 fixes some of those issues.

But, the errors described in this issue are due to travis, which has some different problems.
My pull request did run successfully on travis :roll_eyes:

**Comment by marehr** [comment]
@h-2 I would suggest to gradually and iteratively fix all remaining bugs by multiple pr and see after each nightly build what remains. Could you review #2064 and merge it? I try to find a solution for the out-of-nowhere failing travis and the failing darwin builds.

**Comment by rrahn** [comment]
Have a final check on the status

**Comment by marehr** [comment]
Should be fixed. For new problems let's open new issue.
