### ISSUE TITLE
goDown on empty string breaks iterator

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan#2072]
typedef Index<DnaString, FMIndex<> > TIndex;
    typedef Iter<TIndex, VSTree<TopDown<> > > TIter;

    DnaString text("GCCTC");
    TIndex index(text);
    TIter it(index);

    goDown(it, "C");    cout << representative(it) << endl; // outputs C
    goDown(it);         cout << representative(it) << endl; // outputs CC
    //goDown(it, "");     cout << representative(it) << endl; // outputs CC
    goRight(it);        cout << representative(it) << endl; // outputs GC
    goRight(it);        cout << representative(it) << endl; // outputs TC

When you comment in the line above, ``TC`` is not found anymore when calling goRight from ``GC``.

This might also happen with other index types. Going down an empty string should not touch the iterator at all.

**Comment by h-2** [comment]
well, then please fix it :)
