### ISSUE TITLE
read_vcf not up to date

### ISSUE THREAD

**Issue by sarahet** [seqan/seqan#2075]
The functions for reading a vcf file (vcf_io/read_vcf.h) are not matching the current vcf specification as they require 9 mandatory fields to be present in a file. In vcf specification 4.2 is stated that only 8 fields are mandatory (the FORMAT field is not required). In particular the readHeader function fails if less than 9 fields are present.

**Comment by h-2** [comment]
Thanks for pointing this out! Do you want to make a PR? 😄

**Comment by temehi** [comment]
I am not really a fan of the new format.  An optional column in the middle is a bit tricky. Anyways I will create a PR, that enables reading the new format. When it comes to writing we will use the old format with the "FORMAT" column present but empty.
