### ISSUE TITLE
bandedChainAlignment get position of first match

### ISSUE THREAD

**Issue by nevergonefan** [seqan/seqan#2077]
I use the bandedChainAlignment method to align two sequences. Actually, the seq2 is part of the seq1, so the beginning part of the alignment are all gaps and I want to get the position of the first match, what should I do?
I know that there is a method in LocalAlignment.

**Comment by smehringer** [comment]
Hi @nevergonefan,

You might want to look at our Tutorial for [Overlap Alignments](https://seqan.readthedocs.io/en/master/Tutorial/Algorithms/Alignment/PairwiseSequenceAlignment.html#overlap-alignments).

If I understand you correctly, you still want a full global alignment between two sequences but you want to allow initial gaps at the beginning (and end?) of seq1. In SeqAn you can do this by passing an `AlignConfig` object that specifies where to allow free initial gaps.

for example:
```
int score = bandedChainAlignment(align_obj, score_obj, AlignConfig<true, false, false, true>());
```
`true` means you allow gaps at this position. Visualizing the DP matrix the order is `<Top, Left, Right, Down>`.
But again, take a look at the [Tutorial](https://seqan.readthedocs.io/en/master/Tutorial/Algorithms/Alignment/PairwiseSequenceAlignment.html#overlap-alignments). It's better explained there anyway.

I hope that's what you need.

**Comment by smehringer** [comment]
@nevergonefan How's your problem? Did my suggestion provide any help?

**Comment by nevergonefan** [comment]
@smehringer I used the AlignConfig<true,true,true,true> when I called bandedChainAlignment method, but what I really want to know is the offset position of the first "not gap". Now I used a for loop to check the alignment result and it works though a little clumsy!
I have another problem! I found the bandedChainAlignment method is really slow, will seqan cooperate with NVBIO to accelerate in the future?

**Comment by smehringer** [comment]
I'm sorry, seems I was to rush reading your question that I missed the main point.
The function [```countLeadingGaps()```](http://docs.seqan.de/seqan/master/class_Gaps.html#Gaps#countLeadingGaps) might be what you were looking for?

**Comment by rrahn** [comment]
@nevergonefan first what you need is independent of the alignment algorithm but part of the `Gap` data structure. There you can us the function to [toViewPosition](http://docs.seqan.de/seqan/develop/class_Gaps.html#Gaps%23toViewPosition) on one of the rows.
```cpp
seqan::Gaps<DnaString> gapH;
seqan::Gaps<DnaString> gapV;
// ... assign source and call alignment ...
auto offset = toViewPosition(gapV, 0);
```
Second, we are really interested in optimising the alignment parts. I know for some benchmarks that the bandedChainAlignment has some performance bottlenecks. Though, there was not yet a use case for which to optimise it really. So if you say you need more performance here, and if you could provide some sample data and maybe some expected runtimes, we can work on the code to optimise it.

**Comment by rrahn** [comment]
@nevergonefan I will close the issue now. If it is not resolved for you, please reopen.
