### ISSUE TITLE
Accessing Name from nameStoreCache by id

### ISSUE THREAD

**Issue by martinjvickers** [seqan/seqan#2078]
How do I go about accessing the Name (string/CharString?) from a nameStoreCache if I have the id but not the string name? 

I can't find a method of doing the opposite of `getIdByName(idx, cache, name)`.

**Comment by h-2** [comment]
@smehringer since you worked on this recently, can you help?

**Comment by martinjvickers** [comment]
Hi @smehringer and @h-2 

I managed to get something working by adding a `getNameById` function to `name_store_cache.h`. It's probably not the best way but as it stands I don't understand enough of the inner-workings of SeqAn to do much better. But it works and it might provide a basis for me to understand how this is supposed to work.

```
// ----------------------------------------------------------------------------
// By Martin
// Function getNameById(name,context,idx)
// ----------------------------------------------------------------------------
template <typename TCNameStore, typename TCName, typename TName, typename TPos>
inline bool
getNameById(TName & name, NameStoreCache<TCNameStore, TCName> const & context, TPos const & pos)
{
    typedef typename Position<TCNameStore const>::Type TId;
    typedef NameStoreCache<TCNameStore, TCName> const TNameStoreCache;
    typedef typename TNameStoreCache::TSet TSet;

    int num = 0;
    for( auto i : host(context) )
    {
        if(num == pos)
        {
                name = i;
                return true;
        }
        num++;
    }    

    return false;
}

// deprecated.
template<typename TNameStore, typename TName, typename TCName, typename TCNameStore, typename TPos>
inline bool
getNameById(TNameStore const & /*nameStore*/, TName & name, TPos const & pos, NameStoreCache<TCNameStore, TCName> const & context)
{
    return getNameById(name, context, pos);
}
// end of Martin meddling
```

**Comment by smehringer** [comment]
Hi @martinjvickers,

could you supply me with an example of what you are trying to do?

The way I see it so far is that `NameStoreCashe` is an efficient way to query for a position of a name in a list of names. 
e.g. `names = ["Tom","Marten","Mark"]`
Which position is `"Marten"` -> create `NameStoreCashe` and query `getIdByName` for `"Marten"` -> `1` 

So now you have the id/position and you want to know the name.. since you store the `names` object anyway, why do you not query the names object directly?

`names[id]` -> `names[1] = "Marten"`

PS:
@h-2 When did I ever work on the `NameStoreCashe` :question:

**Comment by smehringer** [comment]
@martinjvickers Did this help with you problem?

**Comment by martinjvickers** [comment]
Hi @smehringer. Thanks for your reply. I've only just had chance to look at this.

I've found generally the BAM header very confusing. What I was working on was a small tool to give stats from a BAM/SAM file. Everything within code works fine with the rID until I wanted to say "Chr1 bla bla bla" where I had a rID = 0.

The final solution was to use something like this rather than editing the SeqAn library;

```
typedef FormattedFileContext<BamFileIn, void>::Type TBamContext;
TBamContext const & bamContext = context(inFile);
cout << contigNames(bamContext)[rID] << endl;
```
