### ISSUE TITLE
ReadTheDocs Sphinx setup for SeqAn manual

### ISSUE THREAD

**Issue by martinjvickers** [seqan/seqan#2080]
Is it worth having the information in the manual about how to setup Sphinx so that you can compile the SeqAn manual to check links etc locally?

My notes about getting this to work are here;

https://gist.github.com/martinjvickers/8f303c72c9ba999cfdfe868b07cdfd8a

If this is useful I'm happy to add this information somewhere within the manual if you let me know where might be an appropriate place.

**Comment by h-2** [comment]
Well, it should be the place:
http://seqan.readthedocs.io/en/master/Infrastructure/Manage/RepositoryStructure.html#manual
Do these instructions not work?

**Comment by martinjvickers** [comment]
You're right, I didn't quite catch that, that would of course work. :-)

From my point of view, I was simply trying to view the rst files locally to ensure a URLs worked while I do a bit of tidying up on a lazy document stuff Friday. It's a bit of a high barrier for entry if you don't use python much beyond the basic functionality, don't have virtualenv installed, don't have Sphinx and the dependencies installed etc. Obviously the main contributors to SeqAn already have this setup so I concede that those instructions in the manual are more than enough.
