### ISSUE TITLE
Unexpected results with chainSeedsGlobally

### ISSUE THREAD

**Issue by stevschmid** [seqan/seqan#2082]
In this scenario:
```

   /
  / /
   /
  /

 Y
 |
  ---> X
```

seed1 has length 3 and seed2 has length 2.  `chainSeedsGlobally` returns seed2, which is not the `optimal` solution.

This is the test case I added to `tests/seeds/test_seeds_global_chaining.cpp`:

```cpp
    {
        TSeedSet seedSet;

        addSeed(seedSet, TSeed(0, 0, 3), Single());
        addSeed(seedSet, TSeed(2, 3, 2), Single());

        TSeedChain result;
        chainSeedsGlobally(result, seedSet, SparseChaining());

        SEQAN_ASSERT_EQ(1u, length(result));
        SEQAN_ASSERT_EQ(TSeed(0, 0, 3), result[0]); /* fails, returns TSeed(2, 3, 2) */
    }
```

An extreme case:
```cpp
    {
        TSeedSet seedSet;

        addSeed(seedSet, TSeed(0, 0, 100), Single());
        addSeed(seedSet, TSeed(95, 95, 10), Single());

        TSeedChain result;
        chainSeedsGlobally(result, seedSet, SparseChaining());

        SEQAN_ASSERT_EQ(1u, length(result));
        SEQAN_ASSERT_EQ(TSeed(0, 0, 100), result[0]); /* fails, returns TSeed(95, 95, 10) */
    }
```

From what I can see in <em>Gusfield 1997</em>, the algorithm does not cover this case. The algorithm only discards solutions which are "higher up", and the author states that in the list `L` the last entry (i.e. the highest rectangle) contains the best score, which is not the case here. That could explain the unexpected output of `chainSeedsGlobally`. Maybe I am missing something?

**Comment by rrahn** [comment]
@stevschmid is now fixed in current develop and available in 2.4. Thanks for reporting.
