### ISSUE TITLE
FMIndex doesn't work with large StringSet

### ISSUE THREAD

**Issue by xhongyi** [seqan/seqan#2083]
Hi, Hongyi here.

I kept running into runtime I/O problems when generating a FM-Index with large StringSets (human genome v37 for example).

I kept getting this:

Asynchronous I/O operation failed (waitFor): "Bad file descriptor"
fildes:  a
buffer:  7fbf3d584000
offset:  344b0000
nbytes:  b0000
event:   1
Raddr:   0x1003b88
/usr0/local/include/seqan/file/file_page.h:816 FAILED!  (WRITING operation could not be completed: "Bad file descriptor")

I have been using the simplest FMIndex configs:

typedef FastFMIndexConfig<void, uint64_t> TConfig;
typedef Index<StringSet<String<Dna5> >, FMIndex<void, TConfig> > BWTIndex;
BWTIndex fmIndex(genomeSet);

Then query will fail with above async I/O exceptions.
Smaller string set works. The threshold StringSet size varies from machine to machine.
Is there a data race in the code? Did I do something wrong?

Also I find the Fibre concept hard to understand... Would be great if it is further elaborated in the manual.

**Comment by xhongyi** [comment]
If in the case that I do not have enough disk storage, I assume it is writing some intermediate data somewhere?

Is it writing to tmpfs or is it writing to my current folder?

**Comment by cpockrandt** [comment]
@xhongyi 

Hi Hongyi,

the index creation is using secondary memory. Yes, you're right: the error suggests that you don't have enough space left on your disk or the quota of your temp directory is exceeded. Try changing your temp directory (`export TMPDIR=/somewhere/else`)

If you have any further questions, feel free to ask!

**Comment by xhongyi** [comment]
Yep. Worked like wonders. Suggest putting this point into the tutorial. Some people have very small /tmp partition and it could be a potential problem in building larger indices.

**Comment by h-2** [comment]
@xhongyi true! @cpockrandt can you do this for the next release?

**Comment by cpockrandt** [comment]
@h-2 I made a PR for that.

@xhongyi If you have any further questions or suggestions, please feel free to open another issue. I'm closing this one now.
