### ISSUE TITLE
seqan (very) out-of-date in Ubuntu mirrors

### ISSUE THREAD

**Issue by Krannich479** [seqan/seqan#2084]
Hey,
is it perhaps possible to update seqAn in the Ubuntu source repository (e.g. xenial)?
Using your preferred first install option "Native package management of the operating system" I run into errors with undefined references while following your [Index Iterators](http://seqan.readthedocs.io/en/master/Tutorial/DataStructures/Indices/IndexIterators.html) tutorial, Assignment 1. According to the [Ubuntu Package Info](https://packages.ubuntu.com/xenial/seqan-dev) and the version.h it is still at build 1.4.1.

Thanks

**Comment by h-2** [comment]
We have an up-to-date version in ubuntu zesty and artful:
https://packages.ubuntu.com/search?keywords=seqan&searchon=names&suite=all&section=all
(the new package name is `libseqan2-dev`)

You can probably just use that package? I am not sure how backports work, but maybe that would work, too. All work in this regard is done by the debian-med team.

**Comment by h-2** [comment]
Otherwise you will have to use our library package which is also described in the documentation.

I hope this answers your questin, if not, please re-open this issue.
