### ISSUE TITLE
Timeouts for test_index_bifm

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan#2093]
There's a bug when compiled with OpenMP (and gcc). I narrowed it down to the method

`partialSum()` in `parallel/parallel_algorithms.h` which is used for creating the Count table used for the LF mapping. For some reason the program spends > 400s in `do_spin`.

Anyway, there shouldn't be done any parallelization at all (when called by the FMindex). We usually never build indices on alphabet sizes larger than 10 (which will lead to 9 summations).

**Comment by h-2** [comment]
Well apparently there is no Serial version of the algorithm and it defaults to parallel (although it claims otherwise in the documentation). Can you make a PR with a serial version and make it default?

**Comment by cpockrandt** [comment]
That's by far the easiest way, but maybe we should look into the parallel code as well? I don't know whether the 400s overhead for spawning is realistic or whether there is another bottleneck in the code that could affect other parts of our library as well?

**Comment by h-2** [comment]
Yes, that's a good idea, but please also add a Serial version in any case!

**Comment by rrahn** [comment]
partialSum without any parallel tag defaults to Serial: https://github.com/seqan/seqan/blame/master/include/seqan/parallel/parallel_algorithms.h#L201
Well, the parallel partialSum version is mainly used by the qGram Index creation. At least what I know.
But anyway, what is the state here?

**Comment by rrahn** [comment]
@cpockrandt was this only affecting travis?

**Comment by h-2** [comment]
@cpockrandt is this now resolved?
