### ISSUE TITLE
Navigating a bidirectional FM Index

### ISSUE THREAD

**Issue by xhongyi** [seqan/seqan#2096]
Are  here equivalent functions of goUp and goRight for bidirectional FM index iterators just like goDown(iter, Fwd()) ??

**Comment by xhongyi** [comment]
@cpockrandt

**Comment by xhongyi** [comment]
When I do "goRight(iter, Rev())", the code won't compile and throw out an error saying:

In file included from /usr0/local/include/seqan/index.h:172:0,
                 from /usr0/home/hxin/workspace/seqAn/my_project_test.cpp:3:
/usr0/local/include/seqan/index/index_fm_stree.h: In instantiation of ‘typename seqan::VertexDescriptor<seqan::Index<TText, seqan::FMIndex<TSpec, TConfig> > >::Type seqan::nodeUp(const seqan::Iter<seqan::Index<TText, seqan::FMIndex<TSpec, TConfig> >, seqan::VSTree<seqan::TopDown<seqan::ParentLinks<TSpec> > > >&) [with TText = seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<> > >; TOccSpec = void; TIndexSpec = seqan::FastFMIndexConfig<void, long unsigned int>; TSpec = seqan::Preorder; typename seqan::VertexDescriptor<seqan::Index<TText, seqan::FMIndex<TSpec, TConfig> > >::Type = seqan::VertexFM<long unsigned int, seqan::SimpleType<unsigned char, seqan::Dna5_> >]’:
/usr0/local/include/seqan/index/index_bifm_stree.h:70:40:   required from ‘void seqan::_updateOnGoRight(seqan::Iter<seqan::Index<TText, seqan::BidirectionalIndex<seqan::FMIndex<TSpec, TConfig> > >, seqan::VSTree<seqan::TopDown<TSpec> > >&, TDirection) [with TText = seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<> > >; TOccSpec = void; TIndexSpec = seqan::FastFMIndexConfig<void, long unsigned int>; TSpec = seqan::ParentLinks<>; TDirection = seqan::Tag<seqan::BidirectionalFwd_>]’
/usr0/local/include/seqan/index/index_bidirectional_stree.h:352:25:   required from ‘bool seqan::goRight(seqan::Iter<seqan::Index<TText, seqan::BidirectionalIndex<TIndexSpec> >, seqan::VSTree<seqan::TopDown<TSpec> > >&, seqan::Tag<TUsage>) [with TText = seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<> > >; TIndexSpec = seqan::FMIndex<void, seqan::FastFMIndexConfig<void, long unsigned int> >; TSpec = seqan::ParentLinks<>; TDirection = seqan::BidirectionalFwd_]’
/usr0/home/hxin/workspace/seqAn/my_project_test.cpp:95:29:   required from here
/usr0/local/include/seqan/index/index_fm_stree.h:469:16: error: no matching function for call to ‘seqan::VertexFM<long unsigned int, seqan::SimpleType<unsigned char, seqan::Dna5_> >::VertexFM(const seqan::Pair<long unsigned int, long unsigned int>&, const long unsigned int&, const seqan::SimpleType<unsigned char, seqan::Dna5_>&)’
         return TVertexDescriptor(back(it.history).range, back(it.history).repLen, back(it.history).lastChar);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr0/local/include/seqan/index.h:172:0,
                 from /usr0/home/hxin/workspace/seqAn/my_project_test.cpp:3:
/usr0/local/include/seqan/index/index_fm_stree.h:118:5: note: candidate: seqan::VertexFM<TSize, TAlphabet>::VertexFM(const seqan::VertexFM<TSize, TAlphabet>&) [with TSize = long unsigned int; TAlphabet = seqan::SimpleType<unsigned char, seqan::Dna5_>]
     VertexFM(VertexFM const & other) :
     ^~~~~~~~
/usr0/local/include/seqan/index/index_fm_stree.h:118:5: note:   candidate expects 1 argument, 3 provided
/usr0/local/include/seqan/index/index_fm_stree.h:110:5: note: candidate: seqan::VertexFM<TSize, TAlphabet>::VertexFM(seqan::Pair<TSize>, TSize, TSize, TAlphabet) [with TSize = long unsigned int; TAlphabet = seqan::SimpleType<unsigned char, seqan::Dna5_>]
     VertexFM(Pair<TSize> newCurrentRange, TSize newSmallerValue, TSize newRepLen, TAlphabet newChar) :
     ^~~~~~~~
/usr0/local/include/seqan/index/index_fm_stree.h:110:5: note:   candidate expects 4 arguments, 3 provided
/usr0/local/include/seqan/index/index_fm_stree.h:102:5: note: candidate: seqan::VertexFM<TSize, TAlphabet>::VertexFM(seqan::MinimalCtor) [with TSize = long unsigned int; TAlphabet = seqan::SimpleType<unsigned char, seqan::Dna5_>; seqan::MinimalCtor = seqan::Tag<seqan::MinimalCtor_>]
     VertexFM(MinimalCtor) :
     ^~~~~~~~
/usr0/local/include/seqan/index/index_fm_stree.h:102:5: note:   candidate expects 1 argument, 3 provided
/usr0/local/include/seqan/index/index_fm_stree.h:94:5: note: candidate: seqan::VertexFM<TSize, TAlphabet>::VertexFM() [with TSize = long unsigned int; TAlphabet = seqan::SimpleType<unsigned char, seqan::Dna5_>]
     VertexFM() :
     ^~~~~~~~
/usr0/local/include/seqan/index/index_fm_stree.h:94:5: note:   candidate expects 0 arguments, 3 provided
make[2]: *** [CMakeFiles/my_project_test.dir/my_project_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/my_project_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by xhongyi** [comment]
I saw a bug fix. Will try it out.

**Comment by cpockrandt** [comment]
@xhongyi Okay, let me know when you have further questions!

**Comment by xhongyi** [comment]
@cpockrandt Yes. The develop branch compiles and runs just fine! Closing the ticket!
