### ISSUE TITLE
Make SeqFileIn seek-able when index exists

### ISSUE THREAD

**Issue by Pbdas** [seqan/seqan#2100]
I couldn't find an API way of seeking a SeqFileIn opened from an indexed FASTA file. This would be great to have, as reading individual entries each from their offset (using the `readSequence(...)` and `sequenceName(...)`) seems to be somewhat slower than the standard.

I understand that the offset in the `.fai` points to the sequence itself, past the sequence name, so simply performing a seek on the underlying stream:
```
seqan::SeqFileIn file_;
seqan::FaiIndex index_;
size_t offset = 10; //some number of sequences to skip
...
const auto byte_offset = index_.indexEntryStore[offset].offset;
file_.stream.file.seekg(byte_offset);
```
is not sufficient, and probably not very safe.

Is there some reccomended way of doing this already?

**Comment by rrahn** [comment]
There is currently an interface that allows you to set the file to a specific position.
```
setPosition(file, offset)
```
Let me know if that works for you.

**Comment by Pbdas** [comment]
Yes! Thank you, that seems to be a viable replacement for seeking directly on the underlying file pointer of the stream (`seekg`).

For posterity: I solved the off-by-one issue when purely using `readRecord` after seeking by reading the first record using `readSequence` and `sequenceName`, then seeking using `setPosition` and continuing on with `readRecord` for the rest.

Code looks something like this:
```
seqan::SeqFileIn file;
seqan::FaiIndex index;
const size_t skip = 10; // some number of sequences to skip
...
// read the first record after the skip
CharString seq;
CharString id;
readSequence(seq, index, skip);
id = sequenceName(index, skip);

... // add seq and id to my data structure

// seek the file
auto byte_offset = index_.indexEntryStore[skip].offset;
setPosition(file, byte_offset);
// next readRecord will skip this sequence and go straight to the next header!

for (...) { // number of sequences I wanted to read, minus one
  readRecord(id, seq, file);
  ... // add both to my data structure
}
```
