### ISSUE TITLE
[boost] Use approximate matching algorithms in Boost.Algorithm

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [seqan/seqan#2102]
Hello.

I am Boost.Algorithm developer and currently i am working on approximate matching algorithms.

I found in seqan a lot of algorithms for approximate matching, so i must ask to you: can i use it in Boost.Algorithm under Boost license?

**Comment by h-2** [comment]
Can you not include it with our 3-Clause BSDL? Are they incompatible? It might be difficult to get a license change, but I can check around at the beginning of september

**Comment by ZaMaZaN4iK** [comment]
I can't inlude it with 3-Clause BSD, right. 

Thank you. I hope that you will check question about relicensing ASAP.

**Comment by h-2** [comment]
This seems to be more difficult here... do you need a copyright-waiver, or would you accept the BOOST license text with the current copyright holders (Knut Reinert and Freie Universität Berlin)?

**Comment by rrahn** [comment]
@ZaMaZaN4iK what is the state?

**Comment by h-2** [comment]
Closed because of inactivity.
