### ISSUE TITLE
Add library to Conan package mabager

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [seqan/seqan#2103]
Hello.

I think you know about modern package manager for C++ - Conan.

Can you please add your library to the package manager? It will be very useful for C++ developers.

**Comment by h-2** [comment]
There is a growing number of these OS agnostic package manager, but TBH packaging already consumes lots of resources.
If you are acquainted with Conan, can you add and maintain the SeqAn package?

**Comment by ZaMaZaN4iK** [comment]
I can try to package it.

P.S. Conan is the most popular package manager now in the C++ world.

**Comment by rrahn** [comment]
Currently we are developing strategies for continues deployment. If conan can be automated well we might add it in the future. Thanks for pointing this out.

**Comment by ZaMaZaN4iK** [comment]
Yes, it can be. You should just use simple python script for this and create your own repo on BinTray. After that you. If your package will be well-maintained, Conan maintainers will include your package to official conan-center repo (central official repo for Conan packages).

**Comment by h-2** [comment]
We have a TODO for SeqAn3, but for SeqAn2 this will only happen if someone else contributes this.
