### ISSUE TITLE
Citing packages (e.g. Yara)

### ISSUE THREAD

**Issue by klmr** [seqan/seqan#2105]
Hi, I’m using YARA (in conjunction with SLIMM) in my workflow. However, it doesn’t seem to be published separately. How should I cite it in our publication? Relatedly, how should I cite recent versions of SeqAn? The original publication is rather dated and doesn’t acknowledge any of the recent authors’ contributions.

**Comment by smehringer** [comment]
Hi @klmr, thanks for using SeqAn.

Unfortunately @esiragusa has not published YARA yet, so I think it's fine to reference to the GitHub page (https://github.com/seqan/seqan/tree/master/apps/yara) and cite SeqAn.
 
As you asked, we actually got accepted into the Journal of Biotechnology last month with the current state of our library.
Title: The SeqAb C++ template library for efficient sequence analysis: A resource for programmers
by Knut Reinert; Marcel  Ehrhardt; Hannes Hauswedell; Svenja Mehringer; René Rahn; Jongkyu Kim; Christopher Pockrandt; Jörg Winkler; Enrico Siragusa, Dr.; Gianvito Urgese; David Weese, Dr.; Temesgen Dadi
     SI: de.NBI
Journal of Biotechnology (accepted 2017)

I'm not sure when the article will be released but we will update the citation information on our website and on Github as soon as it is out.

**Comment by esiragusa** [comment]
Hey Konrad! As Svenja said, there is no journal article describing the latest Yara. However you can use one of these two references [here](https://github.com/seqan/seqan/tree/master/apps/yara#references): my dissertation describes the latest version of Yara, while the NAR paper describes an older version.

**Comment by klmr** [comment]
So, to clarify, the Masai paper describes an earlier version of Yara? Cool, didn’t know that.
