### ISSUE TITLE
building FM index fails

### ISSUE THREAD

**Issue by cbielow** [seqan/seqan#2110]
I'm currently trying to build an FM index using code written by a student in Seqan 2.
Basically using this code-base: https://github.com/jpalbrecht/OpenMS_PI2 (with slight modifications such that it actually compiles)
Test-System: redwood
Seqan: latest release

This is what I get when building the index for a 9 GB FASTA input file:
```
Building protein database...
Building protein database index...
Asynchronous I/O operation failed (waitFor): "Ungültiger Dateideskriptor"
fildes:  6
buffer:  7f170665e000
offset:  1e3228000
nbytes:  2058000
event:   1
Raddr:   0x1788a98
/buffer/ag_bsc/build/contrib_build/include/seqan/file/file_page.h:816 FAILED!  (WRITING operation could not be completed: "Ungültiger Dateideskriptor")

stack trace:
  0    [0x7f173430572e]  /buffer/ag_bsc/build/openms_build/lib/libOpenMS.so(+0x3b372e)
  1    [0x7f1734209965]  /buffer/ag_bsc/build/openms_build/lib/libOpenMS.so(+0x2b7965)
  2    [0x7f17347e9c68]  /buffer/ag_bsc/build/openms_build/lib/libOpenMS.so(+0x897c68)
  3    [0x7f17347ffa91]  /buffer/ag_bsc/build/openms_build/lib/libOpenMS.so(+0x8ada91)
  4    [0x7f1734812254]  /buffer/ag_bsc/build/openms_build/lib/libOpenMS.so(+0x8c0254)
  5    [0x7f1734813028]  /buffer/ag_bsc/build/openms_build/lib/libOpenMS.so(+0x8c1028)
  6    [0x7f17347c7eea]  /buffer/ag_bsc/build/openms_build/lib/libOpenMS.so(+0x875eea)
  7    [0x7f17347c92ed]  /buffer/ag_bsc/build/openms_build/lib/libOpenMS.so(+0x8772ed)
  8    [0x7f17347c9610]  OpenMS::BuildIndexing::build_index_(seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::AminoAcid_>, seqan::Alloc<void> >, seqan::Owner<seqan::Tag<seqan::Default_> > >&, seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::AminoAcid_>, seqan::Alloc<void> >, seqan::Owner<seqan::Tag<seqan::Default_> > >&, OpenMS::String, FMind) + 0x80
  9    [0x7f17347c9b2b]  OpenMS::BuildIndexing::run(OpenMS::String const&, OpenMS::String const&) + 0x3cb
 10          [0x40b004]  /buffer/ag_bsc/build/openms_build/bin/BuildIndex()
 11    [0x7f173421e36d]  OpenMS::TOPPBase::main(int, char const**) + 0x2cfd
 12          [0x402a68]  /buffer/ag_bsc/build/openms_build/bin/BuildIndex()
 13    [0x7f17314c8b45]  __libc_start_main + 0xf5
 14          [0x402e10]  /buffer/ag_bsc/build/openms_build/bin/BuildIndex()

Command terminated by signal 6
        Command being timed: "/buffer/ag_bsc/build/openms_build/bin/BuildIndex -fasta ../../160406_Uniprot_Proteome_Bacteria_+crap+MQ_FWBW.fasta -out bacteria/160406_Uniprot_Proteome_Bacteria_+crap+MQ_FWBW.txt -FM_index"
```

the output directory contains files like `160406_Uniprot_Proteome_Bacteria_+crap+MQ_FWBW.txt_AAA.txt.21841` ... and a lot of them: 

```...ex/FM/bacteria $ ls | wc
  32812   32812 2121756
```

Ideas anyone?

**Comment by cbielow** [comment]
the crash above occurs when writing the index to a network-mapped drive.
So I thought, the timeouts might be network related. But they are not. Trying the same using a local drive (for both reading the FASTA and writing the index), crashes at the exact same point, i.e. 32812 files are written, then it crashes.

**Comment by cbielow** [comment]
same error message and number of files written before the crash in Windows

**Comment by cbielow** [comment]
using another FASTA database (160MB instead of 9GB), the index creation succeeds, yielding 358k output files. Go figure ...

**Comment by h-2** [comment]
I assume with "network-mapped" you are referring to SAMBA? Have you tried setting the temporary directory to a local directory with sufficient space? Note that the space requirements for the index-construction with skew are around 30n.

**Comment by cbielow** [comment]
using a non-default TMPDIR (with 13 TB free space) seems to 'solve' the problem, but raises another (after 10h of index-building):
after creating 5611794 files in the output directory, it crashes again saying
`Open   failed on file   bacteria/160406_Uniprot_Proteome_Bacteria_+crap+MQ_FWBW.txt.txt.5578982:   "No space left on device"`

And indeed, 
`echo "bla" > bacteria/160406_Uniprot_Proteome_Bacteria_+crap+MQ_FWBW.txt.txt.5578982`
--> `bash: bacteria/160406_Uniprot_Proteome_Bacteria_+crap+MQ_FWBW.txt.txt.5578982: Auf dem Gerät ist kein Speicherplatz mehr verfügbar`

After checking `df -i` and `df -h` (which are both fine), I think the culprit is the filesystem: 
https://serverfault.com/questions/688637/getting-error-no-space-left-on-device-for-a-particular-filename 
Manually changing a single character in the filename will happily create the file on bash.
There seems to be a fix, but this will have performance drawbacks, so I'm throwing the towel at this point.

But to come back to the initial issue (out of curiosity): when I checked the tmpdir while the index was building, I could not see any files. Are they just created for very short periods? Maybe the error message could be improved. I would have never guessed tmpdir is the culprit (since it seems unaffected and there are not leftover files).

**Comment by cbielow** [comment]
`typedef seqan::StringSet<seqan::Peptide, seqan::Owner<seqan::ConcatDirect<> > > StringSetConcat;` solved the issue, creating only 78 files. thanks @h-2 :)
