### ISSUE TITLE
readRecords from GffFileIn with ending "###" line fails with "seqan::UnexpectedEnd"

### ISSUE THREAD

**Issue by okulev** [seqan/seqan#2112]
Using Debian seqan2-dev 2.3.1+dfsg-4 and genome annotations tutorial snippet:

```
FragmentStore<> store;
GffFileIn gffFile(toCString(annFilename));
readRecords(store, gffFile);
```

on uncompressed ftp://ftp.ensembl.org/pub/release-90/gff3/homo_sapiens/Homo_sapiens.GRCh38.90.gff3.gz fails with the following message:

```
terminate called after throwing an instance of 'seqan::UnexpectedEnd'
  what():  Unexpected end of input.
Aborted
```

After removing the last line `###` from the GFF3 file, it is parsed successfully.

**Comment by rrahn** [comment]
Mhmm, as far as I understand gff3 format, the `##` indicates a new section. 
Following this document here: http://gmod.org/wiki/GFF3
So if your file ends with these section indicator, the parser assumes more data. 
So in this case I wouldn't strictly say that the parser is wrong but the file format is not following the specifications.

**Comment by okulev** [comment]
The GMOD document talks about sections only in FASTA section explanation, for FASTA sequence that follows `##FASTA` line.

The [specification](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) talks about pragma directives:

> Lines beginning with '##' are directives (sometimes called pragmas or meta-data) and provide meta-information about the document as a whole.

The `###` used by Ensembl is specifically listed as such directive:

> This directive (three # signs in a row) indicates that all forward references to feature IDs that have been seen to this point have been resolved. After seeing this directive, a program that is processing the file serially can close off any open objects that it has created and return them, thereby allowing iterative access to the file. Otherwise, software cannot know that a feature has been fully populated by its subfeatures until the end of the file has been reached. It is recommended that complex features, such as the canonical gene, be terminated with the ### notation.

**Comment by rrahn** [comment]
Ok, thanks for pointing to this.
We'll take care of it.

**Comment by rrahn** [comment]
This should be fixed.
