### ISSUE TITLE
telling apart 'A' and 'N' for Dna5 during DP pattern matching.

### ISSUE THREAD

**Issue by xhongyi** [seqan/seqan#2117]
Hi,

I have been using `String<Dna5>` and it seems to me that during DP, 'N' is treated as 'A'. Is there a way that I treat 'N' as 'N' and get penalties when it is matched against any letter other than 'N' (for example, 'N' matched to 'A' is a counted as a mismatch)?

Thanks,

**Comment by xhongyi** [comment]
Hi can someone confirm that right now 'A' is matched to 'N'?

**Comment by rrahn** [comment]
Hi sorry for the late answer.
The [SimpleScore](http://docs.seqan.de/seqan/develop/) can only differentiate between mismatch and match. In this case 'N' against 'N' matches and 'N' against everything else will not match. 
You can, however, use a custom scoring matrix. Please follow the following tutorial http://seqan.readthedocs.io/en/master/Tutorial/HowTo/Recipes/WorkWithCustomScoreMatrices.html to learn how to create a scoring matrix for Dna5 alphabet.

**Comment by rrahn** [comment]
Mhmm, actually the SimpleScore class would not differentiate. It simply checks if two values are the same. If, however, someone overloaded the comparison for Dna5 than this could be possible. I will create a test case and check the scenario.

**Comment by rrahn** [comment]
@xhongyi can you verify, that you align a `Dna5` vs a `Dna` sequence? 
If both are `Dna5`, then the comparison is as I mentioned already. But if one of the alphabet types is `Dna`, then both types will be converted to the smaller alphabet type (`Dna` in this case) forcing the `N` to be converted to an `A` implicitly. That's why you might see the odd behaviour. 

```cpp
    Dna5{'N'} == Dna5{'N'};  // true
    Dna5{'N'} == Dna5{'A'};  // false
    Dna5{'N'} == Dna5{'C'};  // false
    Dna5{'N'} == Dna{'A'};   // true
    Dna5{'N'} == Dna{'C'};   // false
```

**Comment by xhongyi** [comment]
Hi,

I aligned 2 DNA5 strings.
I will give an example code when I reach office.

Hongyi

**Comment by xhongyi** [comment]
Just confirming 'A' and 'N' are different. Perhaps there were some errors in my earlier test... Sorry for the confusion. Good to have the confirmation!

I'm closing the issue. Thanks for answering the question!!!
