### ISSUE TITLE
Reading bgzip fastq files

### ISSUE THREAD

**Issue by tungufoss** [seqan/seqan#2119]
Is it possible to read bgzipped fastq files in seqan? Do I maybe need to rewrite the file ending beforehand? Because the automatic .gz ending of bgzip terminates with an instance of 'seqan::UnexpectedEnd' of input. Regular gzip files work fine, but I have a subsequent program that needs the file to be bgzipped instead of gzipped.

**Comment by temehi** [comment]
Hi,

1. Do you have BZip2 library installed?  If not, you can do so following the guidelines at:
http://seqan.readthedocs.io/en/master/Infrastructure/Use/InstallDependencies.html

2. are you using CMake? Was CMake able to locate the BZip2 package?

**Comment by tungufoss** [comment]
I'm using bgzip version 1.5, not bzip2. Is there support for that? Or do I need to use bzip2 instead?
Seqan is 'successful' opening the bgzip file, however, it's when I start reading the records it suddenly fails after processing a few reads. Probably because it thinks it's a gzip compression given the .gz file extension, and isn't actually opening it correctly. 
The easiest solution is simply to gunzip before running my seqan program. But I was hoping I didn't need that extra step.

**Comment by tungufoss** [comment]
It was easier to fix the subsequent program. Back to using regular gzip files instead of bgzip.

**Comment by h-2** [comment]
The file has to be named .bgzf since we detect format by extension!
