### ISSUE TITLE
Manipulation of the bit code of a DNA sequence

### ISSUE THREAD

**Issue by hh1985** [seqan/seqan#2128]
Hi,

I think the most compact way of encoding DNA is like: A --> 00,  C --> 01, G --> 10,   T --> 11.  I want to manipulate DNA sequence directly through bits (different bit operations).  Is there any easy way of getting std::bitset like object from DnaString object?

Thanks,

-Han

**Comment by rrahn** [comment]
We do have a packed string that does exactly what you want wrapping the SeqAn String interface.
http://docs.seqan.de/seqan/develop/?p=PackedString
Does this help?

**Comment by hh1985** [comment]
@rrahn Thanks a lot!  I will give it a try.

-Han
