### ISSUE TITLE
organize the third party Python code into a common directory

### ISSUE THREAD

**Issue by mr-c** [seqan/seqan#2132]
`util/py_lib/third_party` for example

**Comment by mr-c** [comment]
This would be helpful to packagers; thanks!

**Comment by h-2** [comment]
Yeh, sorry, that's a real mess. I think the only thing required for the (application) tests is `util/py_lib/seqan/app_tests.py`. I am not sure if that depends on anything else in there, but I think not. The rest is for building the documentation...

In general we are currently focusing our efforts on a last feature-release of SeqAn2 (possibly to be followed by 1-2 bugfix releases next year) and then on SeqAn3 which comes with a completely new and clean library-only repository without all this cruft.
This also means that for SeqAn2 we now try to avoid major structural re-organizations and clean-ups, I hope you understand.

**Comment by mr-c** [comment]
@h-2 That's fine, I just wanted to make sure this got recorded.
