### ISSUE TITLE
armel errors on pr #2142

### ISSUE THREAD

**Issue by mr-c** [seqan/seqan#2147]
```
/<<BUILDDIR>>/seqan2-2.3.2.000platform-issues1-66a8baf+dfsg/include/seqan/simd/simd_base_seqan_impl.h:52:4: warning: #warning "No supported platform for SIMD vectorization!" [-Wcpp]
/tmp/ccZDzoZ9.s: Assembler messages:
/tmp/ccZDzoZ9.s:16223: Error: selected processor does not support `yield' in ARM mode
```

https://buildd.debian.org/status/fetch.php?pkg=seqan2&arch=armel&ver=2.3.2.000platform-issues1-66a8baf%2Bdfsg-1&stamp=1508999772&raw=0

This isn't an architecture we normally build for, but this should either be fixed, skipped, or armel detected during build configuration and gracefully quit early (and the lack of support for armel documented)

**Comment by h-2** [comment]
moved to https://github.com/seqan/seqan/issues/2141#issuecomment-338704776
