### ISSUE TITLE
Is it possible to build RazerS 3.4 as standalone tool ?

### ISSUE THREAD

**Issue by samfux84** [seqan/seqan#2148]
I am trying to install the software OptiType, which depends on RazerS 3.4 and many other dependencies. I have built all other dependencies with GCC 4.8.5 (our standard toolchain for installing most applications and libraries is: GCC 4.8.5, OpenBLAS 0.2.19, OpenMPI 2.1.2).

Seqan requires GCC > 4.9, which breaks my entire toolchain that was use for all other dependencies.

Is it possible to compiler RazerS 3.4 with GCC 4.8.5 ?

**Comment by h-2** [comment]
> Is it possible to compiler RazerS 3.4 with GCC 4.8.5 ?

It may be possible, but we don't offer support for it. I strongly recommend you just use gcc-4.9, every currently supported linux distribution (https://linuxlifecycle.com/, except RHEL which was supposed to end-of-life this year) has gcc-4.9 (or newer) packages; it was released 3.5 years ago.

**Comment by h-2** [comment]
Also our static binary packages may "just work" for you.

**Comment by samfux84** [comment]
@h-2 : Thank you for your reply. I have installed razerS 3 from seqan 2.1. This version does not use c++ 14 and could therefore be compiled with GCC 4.8.5.

**Comment by h-2** [comment]
I really recommend you update your toolchain, because all the components, including SeqAn and RazerS have had many bugs fixed in the meantime.
But thats of course up to you.
