### ISSUE TITLE
Fiona - unable to run in Mac

### ISSUE THREAD

**Issue by aglorias** [seqan/seqan#2159]
I am trying to use Fiona using the pre-compiled versions provided here http://packages.seqan.de/fiona/ . I have a Mac  (10.12.6) and I tried both the 64bit and sse4 .zip and .dmg (v0.2.6). I also tried the linux version sse4 (v0.2.9) without success. When I tried running the fiona command, there is an error message noting that it  "cannot execute binary file".

Not sure what I am doing wrong, or if there is a problem with the software. I tired directly contacting the developers without success.

I would appreciate your help to get this software running.

Thanks

**Comment by h-2** [comment]
Can you copy'n'paste the complete command you ran on your terminal and the complete output?

@rrahn can you look at this or assign it to another mac developer?

**Comment by aglorias** [comment]
Dear Seqan team, I appreciate your quick response. I figured out what was wrong (on my side) and now the program is running.

Thank you for the support.

Best,
Andrea



On Nov 13, 2017, at 6:13 AM, Hannes Hauswedell <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you copy'n'paste the complete command you ran on your terminal and the complete output?

@rrahn<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rrahn&d=DwMCaQ&c=cjytLXgP8ixuoHflwc-poQ&r=SYYnihwldpV342yZfwQ9c5yk_UV1qH9kD3dNjW2HMOg&m=3P7MO4aERWkjIxbAXZ7zMbzUikA3oktCXkVuoQa14sg&s=L_Un63VxKu2SQkxRXmXNuW9h49LLZybcbRik49C-9pw&e=> can you look at this or assign it to another mac developer?
