### ISSUE TITLE
Rng<MersenneTwister>: use of undeclared identifier MersenneTwister/Rng

### ISSUE THREAD

**Issue by jimiranda** [seqan/seqan#2179]
I installed SeqAn version 2.3.2 with Homebrew. Works fine. BUT, even with the header <seqan/random.h> I am having the above error message.
And sometimes the compiler shows the message "undeclared identifier Rng"!
The code snippet provided is from SeqAn tutorial:

```cpp
#include <iostream>
#include <seqan/align.h>
#include <seqan/index.h>
#include <seqan/random.h>

using namespace seqan;

template <typename TStringSet, typename TIndexSpec>
void qgramCounting(TStringSet &set, TIndexSpec) {
  typedef Index<TStringSet, TIndexSpec> TIndex;
  typedef typename Fibre<TIndex, QGramCounts>::Type TCounts;
  typedef typename Fibre<TIndex, QGramCountsDir>::Type TCountsDir;
  typedef typename Value<TCountsDir>::Type TDirValue;
  typedef typename Iterator<TCounts, Standard>::Type TIterCounts;
  typedef typename Iterator<TCountsDir, Standard>::Type TIterCountsDir;
  ....etc.

// Assignment #2 Q-gram index
// Create and output a matrix M where M(i,j) is the number of common 
// ungapped 5-grams between sequence i and sequence j for 3 random
// Dna sequences, each not longer than 200 characters.
//
int main () {
  // For the sake of reproducibility
  Rng < MersenneTwister > rng;   // Error: Use of undeclared identifier MersenneTwister & Ring

}
```
By the way, I'm running SeqAn with Xcode and others tutorial examples run OK.

Thanks.

**Comment by jimiranda** [comment]
The line with error is INCOMPLETE in the code above. The correct is:
int main ()
{
  // For the sake of reproducibility
  Rng<MersenneTwister> rng;       // Error msg here: Use of undeclared identifier Rng &
                                                                                                                     MersenneTwister

**Comment by rrahn** [comment]
Hi now I remember.
We removed the random number generator from the library in favour of the STL's random generator library added with C++11. We only offer a beta-distribution in our random module which is not implemented in the STL's version.
See here: http://en.cppreference.com/w/cpp/numeric/random
