### ISSUE TITLE
update package install instructions in manual

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#2180]
Apparently when installing SeqAn via apt-get the `seqan-config.cmake` file is missing.
Second the shipped version is 1.4.1 which is very outdated. w
We need to check if the downstream package distributors can upgrade the package.

**Comment by h-2** [comment]
The package is now called `libseqan2-dev` is quite up to date actually:
https://packages.ubuntu.com/search?keywords=libseqan2-dev&searchon=names&suite=all&section=all

**Comment by rrahn** [comment]
Then please leave it open and we need to update the documentation in the reference manual
