### ISSUE TITLE
icpc-16 errors every build (platform.h is broken?)

### ISSUE THREAD

**Issue by marehr** [seqan/seqan#2203]
```terminal
> make test_basic_aggregate                                                                                                              

Built target seqan_library
Building CXX object tests/basic/CMakeFiles/test_basic_aggregate.dir/test_basic_aggregate.cpp.o
In file included from seqan-src/include/seqan/stream.h(89),
                 from seqan-src/tests/basic/test_basic_aggregate.cpp(39):
seqan-src/include/seqan/platform.h(500): error: a constexpr function must contain exactly one return statement
  {}
   ^

```

Offending code is:

https://github.com/seqan/seqan/blob/028fd79c6e02b7255c95d390b965d922aa874bb6/include/seqan/platform.h#L498-L500

This is icpc-16 exclusive.

**Comment by h-2** [comment]
We have dropped icpc-16 on all platforms, see also #2193 

We do need to get 17 and 18 properly supported, though.

**Comment by h-2** [comment]
I thought we also discussed this before Christmas? Maybe @rrahn and I called the shots in the last week because you were sick…

**Comment by marehr** [comment]
We occasionally talked about dropping it, but never did it. Great, one platform less to worry about! But, this bug should have been easy to fix. Just dropping the `constexpr`.
