### ISSUE TITLE
test failure on 32bit

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#2208]
@cpockrandt your PR broke our nightlies on all 32bit platforms. std::max between 32bit and 64bit it seems.

**Comment by cpockrandt** [comment]
there error on the range-based for loop is a possible bug of g++ 8

Filed here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83739

**Comment by h-2** [comment]
Since it has Bern confirmed as a bug we can close this issue here.
