### ISSUE TITLE
[Info] plot.awk and ps2pswLinks.gawk

### ISSUE THREAD

**Issue by sagitter** [seqan/seqan#2221]
Hi all.

Where should be installed the `.*awk` scripts?
Can they be executed as executable files or just used as input for `gawk`?

**Comment by h-2** [comment]
The FreeBSD package just installs them as executable files in $PREFIX/bin, the ubuntu packages apparently puts them im /usr/lib/seqan/bin for some reason: https://packages.ubuntu.com/artful/amd64/seqan-apps/filelist

**Comment by h-2** [comment]
Do you still have questions regarding these files or can I close this issue?
