### ISSUE TITLE
jumpToRegion has trouble finding a read

### ISSUE THREAD

**Issue by hannespetur** [seqan/seqan#2257]
Hello SeqAn team,

Thank you for all your hard work. I am writing this issue because I believe I have discovered a bug `seqan::jumpToRegion(...)` in the latest development files of SeqAn. To reproduce my problem, consider the following `test.sam` file with only one read at position 100:

```
@HD	VN:1.3	SO:coordinate
@SQ	SN:ref	LN:100000
schrodinger_read	0	ref	100	8	18M	=	31	40	CATCATCATCATCATCAT	*
```

Convert to BAM and index it:
```
samtools view test.sam -b -o test.bam
samtools index test.bam
```

I am using (a slightly modified version of the) [BAM indices tutorial](http://seqan.readthedocs.io/en/master/Tutorial/InputOutput/SamAndBamIO.html#using-bam-indices) which reads my `test.bam` and `test.bam.bai` files. By changing the `int beginPos = 9, endPos = 30;` to other positions revealed some strange behavior...
 * If `beginPos = 1, endPos = 99999` then `hasAlignments` is `false` and the file stream points to the end of the file. I expected `hasAlignments == true` and the file stream points to the read.
 * If `beginPos = 2, endPos = 99999` then `hasAlignments` is `false` and the file stream points to the end of the file. I expected `hasAlignments == true` and the file stream points to the read.
 * If `beginPos = 16384, endPos = 99999` then `hasAlignments` is `false` and the file stream points to the end of the file. This is expected.
 * If `beginPos = 16385, endPos = 99999` then `hasAlignments` is `false` **BUT** now the file stream points to the read. I expected it would have the same behavior as `beginPos = 16384`.

It seems that if a read is in the very first BAM index bin (which is of size 16384) then searching that bin does not work.

I might even have found another bug while investigating this, because if I move the read to position 20000, recreate the BAM+BAI and run again with the same regions then the file stream points correctly to the read in all scenarios but hasAlignments is always `false`. I expected `hasAlignments == true` in all cases.

All the best,
(Icelandic) Hannes

**Comment by rrahn** [comment]
Hi Hannes, 

many thanks for your thorough analysis. We'll investigate this.

**Comment by h-2** [comment]
@smehringer it looks like you "verschlimmbessert" the situation :laughing:
