### ISSUE TITLE
[APPS] Flexbar installation seems broken.

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan#2269]
`From the Mailing list:`

Dear Seqan team,

I am a Postdoc in Freiburg, Germany, trying to install flexbar since
days.

Unfortunately the installation of flexabr-3.0.3 doesn't work.
cmake . works
but make creates various errors
1. tbb not found - could be resolved by sudo apt install libtbb-dev
2. seqan/basic.h not found creates various problems
but even if seqan 1.4.2 is installed like flexbar requires,
there are problems that functions have a argument too much or too less
...

conda install -c bioconda flexbar
gives dependency problems since seqan 1.4.2 is not in bioconda

sudo apt search seqan (from ubuntu 16.04)

gives only seqan library version 1.4.1
as possibility

so your source of flexbar 3.0.3 is simply not installable ...

could it be that you use in the source a seqan version more updated
than 1.4.2 but in makefile etc stating you use 1.4.2?

I encountered same problem in our bwUniCluster which uses Red Hat
(~Fedora) Linux.

Me and a friend in Heidelberg - both Bioinformatic postdocs - would
love to use Flexbar but cannot use it because of this problems.

ubuntu's
sudo apt install flexbar install version 2.5
which has not -qf and especially no -qt flag/function.
But I would love to use quality trimming.

We would be grateful, if you could help us out.

Best,
Gwang-Jin Kim

**Comment by h-2** [comment]
Flexbar is not maintained by us, by @jtroehr . I have replied via e-mail and am closing this here (if it is still an issue, it can be opened at https://github.com/seqan/flexbar
