### ISSUE TITLE
unix manual page generation errors

### ISSUE THREAD

**Issue by mr-c** [seqan/seqan#2279]
<pre>
W: seqan-apps: manpage-has-errors-from-man usr/share/man/man1/micro_razers.1.gz 47: warning: macro `N'' not defined
N: 
N:    This man page provokes warnings or errors from man.
[…]
N:    Other warnings are often formatting typos, like missing quotes around a
N:    string argument to .IP. These are likely to result in lost or malformed
N:    output. See the groff_man (or groff_mdoc if using mdoc) man page for
N:    information on macros.
N:    
N:    This test uses man's --warnings option to enable groff warnings that
N:    catch common mistakes, such as putting . or ' characters at the start of
N:    a line when they are intended as literal text rather than groff
N:    commands. This can be fixed either by reformatting the paragraph so that
N:    these characters are not at the start of a line, or by adding a
N:    zero-width space (\&) immediately before them.
N:    
N:    At worst, warning messages can be disabled with the .warn directive, see
N:    "Debugging" in the groff manual.
N:    
N:    Lintian also stricter in regards to declaring manpage preprocessors.
N:    
N:    To test this for yourself you can use the following command:
N:     LC_ALL=en_US.UTF-8 MANROFFSEQ='' MANWIDTH=80 \
N:            man --warnings -E UTF-8 -l -Tutf8 -Z <file> >/dev/null
N:    
N:    Refer to the groff_man(7) manual page and the groff_mdoc(7) manual page
N:    for details.
N:    
N:    Severity: normal, Certainty: certain
N:    
N:    Check: manpages, Type: binary
N: 
W: seqan-apps: manpage-has-errors-from-man usr/share/man/man1/razers.1.gz 128: warning: macro `razers' not defined (possibly missing space after `ra')
W: seqan-apps: manpage-has-errors-from-man usr/share/man/man1/razers3.1.gz 167: warning: macro `razers' not defined (possibly missing space after `ra')
N: 1 tag overridden (1 error)
</pre>

**Comment by h-2** [comment]
@smehringer Since you have some experience with the man pages, can you have a look?

**Comment by mr-c** [comment]
Fixed in #2284 Thanks, y'all!
