### ISSUE TITLE
bad_alloc when using iterator with Index<String<int>, IndexWotd<>>

### ISSUE THREAD

**Issue by trig-ger** [seqan/seqan#2297]
I'm trying to work with int strings (not char), so the max value for unsigned int is >4 billion.
Iterator is created OK with `Index<String<int>, IndexEsa<>>`, but triggers **bad_alloc** with `Index<String<int>, IndexWotd<>>` trying to allocate >4e9 elements. How to iterate `String<int>` suffix tree index then?

Here is an example code:

    #include "seqan/index.h"

    #include <iostream>
    
    using namespace std;
    using namespace seqan;
    
    template <typename TIndexSpec>
    void constrainedDFS()
    {
        typedef Index<String<int>, TIndexSpec> TIndex;
        TIndex index(std::vector<int>{1, 2, 3, 4, 5, 3, 4, 7});
        typename Iterator<TIndex, TopDown<ParentLinks<> > >::Type it(index);
    
        do {
            std::cout << representative(it) << std::endl;
            if (!goDown(it) || repLength(it) > 3)
            {
                do {
                    if (!goRight(it))
                    {
                        while (goUp(it) && !goRight(it))
                            ;
                    }
                } while (repLength(it) > 3);
            }
        } while (!isRoot(it));
    
        std::cout << std::endl;
    }
    
    int main()
    {
        constrainedDFS<IndexEsa<>>();
        constrainedDFS<IndexWotd<>>();
        return 0;
    }

System: Kubuntu 16.04 64 bit, gcc 5.4.0.

**Comment by rrahn** [comment]
Thanks for reporting. We just came back from a retreat, so we will investigate this next week.

**Comment by cpockrandt** [comment]
Hi @trig-ger,

build a Wotd on 32bit integers requires about 32 GB of main memory. Your bad_alloc error means that you're running out of memory. I'm afraid there is currently no way to index such large alphabets in SeqAn since our indices are optimized for small alphabet sizes. You can find a number of indices for large alphabets in the [SDSL](https://github.com/simongog/sdsl-lite)

**Comment by trig-ger** [comment]
Hi, 
maybe `std::unordered_map` can help (if the matter is in ~O(N) access to each alphabet letter)?

Btw I'm currently trying to construct the SDSL suffix tree structure `cst_sct3<csa_bitcompressed<int_alphabet<>>> tree;` but without success: it gives an error on `construct_im(tree, vec)` where `int_vector<32> vec(size)` is filled at runtime. 
Have yout ever tried to use big alphabets (int) in SDSL?

**Comment by cpockrandt** [comment]
> maybe std::unordered_map can help (if the matter is in ~O(N) access to each alphabet letter)?

You mean in the implementation of our Wotd index? We just released our last (major) release for SeqAn2. I doubt that we will make any design/implementation changes to our data structures in SeqAn2

Could you post your code with the error message?

**Comment by trig-ger** [comment]
I get the same output only if I use std::ostringstream:

        std::ostringstream ss;

        for (size_t i = 0; i != vec.size(); ++i) {
            ss << vec[i];
            if (i + 1 < vec.size())
                ss << " ";
        }
    
        construct_im(cst, ss.str().c_str(), 'd');

Maybe we have different versions of sdsl-lite? Last commit of my version is 8f5245ff (2017-12-11). Kubuntu 16.04, 64 bit, gcc 5.4.0.

**Comment by cpockrandt** [comment]
Yes, you're right. I was using the unstable version. I couldn't get it working quickly with the stable release. You can open an issue there or you use the unstable release: [xxsds/sdsl-lite](https://github.com/xxsds/sdsl-lite)

**Comment by cpockrandt** [comment]
If you have any further question, feel free to reopen this issue or create a new one!
