### ISSUE TITLE
writeRecords(..., DotDrawing) is called write() in the docs

### ISSUE THREAD

**Issue by wtwhite** [seqan/seqan#2303]
[The tutorial](http://seqan.readthedocs.io/en/master/Tutorial/DataStructures/Graphs.html#graph-basics) indicates that a `Graph` can be written out in the Dot format with, for example:

    writeRecords(dotFile, g, DotDrawing());

This does work, but searching the docs for a function named `writeRecords()` that applies to graphs produces nothing.  This seems to be because the documentation (beginning on line 459 of graph_types/graph_drawing.h) names the function `write()` instead.

I would have submitted a patch, but I'm not sure which should be changed (the docs or the real function name) and which should stay the same.

**Comment by smehringer** [comment]
Hi @wtwhite,

sorry for coming back to you so late and thanks for spotting this. In SeqAn2 the documentation is not automatically generated from the code so the docs itself needs a patch. I will take care of it.

**Comment by wtwhite** [comment]
Thanks :)
