### ISSUE TITLE
Invalid quality read from fastq files

### ISSUE THREAD

**Issue by Chushuhuch** [seqan/seqan#2306]
The call `seqan::readRecords(meta, seqs, quals, file);` on a fastq file places into `quals` strings of only `ACGT` characters replacing everything else with `A`. I'm expecting a full range of Phred score with correct correspondence between characters and ords.

I am testing this on an old 2.1.1 version but there seem to be no related changes in the newer ones.

Also the documentation for `DnaQ` contains the following controversial points:
* The ValueSize of DnaQ is 4. The nucleotides are enumerated this way: 'A' = 0, 'C' = 1, 'G' = 2, 'T' = 3.
* Note that the default quality value is set to 60.

**Comment by h-2** [comment]
We haven't seen anything like this, FastQ is in regular use by many apps and we have nightly tests...

Can you provide a minimal test and an example file that reproduce this behaviour?

**Comment by Chushuhuch** [comment]
Sure. My full code snippet:
```
seqan::SeqFileIn file("sequence_io_test_data.fastq");
std::vector<seqan::CharString> meta;
std::vector<seqan::Dna5String> seqs;
std::vector<seqan::DnaQString> quals;
seqan::readRecords(meta, seqs, quals, file);
std::cout << quals[0] << std::endl;
```
"sequence_io_test_data.fastq" file contents:
```
@meta
ACGTACGTACGTACGTACGTA
+
ACGT!"#$%&xyz{|}~ghij
```
The code outputs `ACGTAAAAAAAAAAAAAGAAA`.

**Comment by Chushuhuch** [comment]
Thank you! This works.
