### ISSUE TITLE
Is there a way to use toSourcePosition() and toViewPosition() without loading a large reference sequence into memory?

### ISSUE THREAD

**Issue by wtwhite** [seqan/seqan#2307]
I'm dealing with BAM files containing many reads mapped to a single long reference sequence (the human genome).  I would like to use the nice SeqAn functions `toSourcePosition()` and `toViewPosition()` to convert between positions in the read and positions in the reference, *without* having to load the reference sequence into memory, but I can't find a way to do this (aside from rolling my own solution).  `bamRecordToAlignment()` nearly does what I want, but it necessitates loading the reference sequence -- even though none of this data is actually needed to do "alignment arithmetic".

To make matters slightly worse, `bamRecordToAlignment()` requires the reference sequence to be passed as a non-const reference, meaning I either need to pass non-const references to it up and down the call stack, or use `const_cast<TReference&>`.

Any ideas?  Thanks in advance.

**Comment by h-2** [comment]
> bamRecordToAlignment() nearly does what I want, but it necessitates loading the reference sequence -- even though none of this data is actually needed to do "alignment arithmetic".

Your assessment is correct, *in theory* it would not be needed, but in practice it is :(
You might be able to hack around it, but it's probably not easier than rolling your own. Something that might work is to use an external string for the genome, that at least guarantees that it won't be kept in memory. However, `bamRecordToAlignment()` might still want to parse it whichi would incur a strong run-time penalty.

> To make matters slightly worse, bamRecordToAlignment() requires the reference sequence to be passed as a non-const reference,

This looks like a bug.

**Comment by smehringer** [comment]
Hi @wtwhite,

if I understand correctly, you want to Gaps object for the read sequence, without getting the complete alignment?
A quick fix I could think of is in my [local branch](https://github.com/smehringer/seqan/tree/feature_bamRecordToGappedSequence) and looks like this:

```cpp
template <typename TSequence, typename TGapAnchors>
void
bamRecordToAnchorGaps(Gaps<TSequence, AnchorGaps<TGapAnchors>> & result, BamAlignmentRecord const & record)
{
    assignSource(result, record.seq);
    cigarToGapAnchorRead(result, record.cigar);
}
``` 

Do you care to check out if it works as you would like? (or if you are still interested in this?)
