### ISSUE TITLE
Help on enabling SIMD vectorization

### ISSUE THREAD

**Issue by hannespetur** [seqan/seqan#2308]
Hello SeqAn team,

I am interested in benchmarking sequence alignment in SeqAn and comparing it to my own and other implementations. The plan is to run several pairwise alignment algorithms using different SIMD processor extensions and compare CPU time and memory usage. But I am having some issues enabling SIMD vectorisation in SeqAn. I am not seeing the expected improvements of using SIMD extensions, so I must be doing something wrong. Here is my attempt:

**main.cpp**
```cpp
#include <iostream>

#include <seqan/align.h>


int
main()
{
  using TSequence = seqan::String<seqan::Dna>;
  using TAlign = seqan::Align<TSequence, seqan::ArrayGaps>;

  // dummy sequences
  std::string str1;
  str1.append(10000, 'A');
  std::string str2;
  str2.append(10000, 'A');
  TSequence seq1 = str1.c_str();
  TSequence seq2 = str2.c_str();

  TAlign align;
  seqan::resize(seqan::rows(align), 2);
  seqan::assignSource(row(align, 0), seq1);
  seqan::assignSource(row(align, 1), seq2);

  int score = seqan::globalAlignment(align, seqan::Score<int16_t, seqan::Simple>(1, -2, -1, -4));
  std::cout << "Score: " << score << "\n";
  return EXIT_SUCCESS;
}
```

I compiled and ran the program using
```
g++ -Iseqan/include -O3 -std=c++14 -DNDEBUG -m64 -W -Wall -Wextra -pedantic main.cpp -o seqan_sw-null
g++ -msse2 -Iseqan/include -O3 -std=c++14 -DNDEBUG -m64 -W -Wall -Wextra -pedantic main.cpp -o seqan_sw-sse2
g++ -msse4 -Iseqan/include -O3 -std=c++14 -DNDEBUG -m64 -W -Wall -Wextra -pedantic main.cpp -o seqan_sw-sse4
g++ -mavx -Iseqan/include -O3 -std=c++14 -DNDEBUG -m64 -W -Wall -Wextra -pedantic main.cpp -o seqan_sw-avx
g++ -mavx2 -Iseqan/include -O3 -std=c++14 -DNDEBUG -m64 -W -Wall -Wextra -pedantic main.cpp -o seqan_sw-avx2
$ time ./seqan_sw-null
Score: 10000
./seqan_sw-null  0,43s user 0,02s system 99% cpu 0,451 total
$ time ./seqan_sw-sse2
Score: 10000
./seqan_sw-sse2  0,44s user 0,02s system 99% cpu 0,458 total
$ time ./seqan_sw-sse4
Score: 10000
./seqan_sw-sse4  0,40s user 0,05s system 99% cpu 0,448 total
$ time ./seqan_sw-avx2
Score: 10000
./seqan_sw-avx2  0,41s user 0,04s system 99% cpu 0,444 total
```

I am using the SeqAn 2.4.0 headers and compiling with GCC 7.3.0. Any help is appreciated.

All the best,
Hannes

**Comment by h-2** [comment]
@marehr Can you help?

**Comment by marehr** [comment]
I can try to help :)

I think @rrahn didn't document how to use the interface, yet. 

First a couple of questions/remarks:
* You want to compute ONE big alignment? And not a dozen alignments?
* Why are you setting `-m64`? This might disable SIMD vectorization. Your compiler reads the flags from left to right and your most specific flag e.g. `-msse4` might overwrite `-m64` which could disable SIMD altogether. 
* We don't support SSE2; We support SSE4.2 and upwards. Including `-mavx512f -mavx512cd -mavx512bw -mavx512dq -mavx512vl` for Skylake.
* `globalAlignment` will compute the score AND the traceback. Our SIMD implementation is (currently) not accelerated for tracebacks. Use `globalAlignmentScore` to compute only the score.

To enable SIMD vectorization and threading, you have to use a special execution policy (see our test cases as reference):

https://github.com/seqan/seqan/blob/584ae4fbff8312cfe31b3e0aea651edfb1b580ef/tests/align_parallel/test_align_parallel_interface.h#L96-L130

This should be your code in spirit, but using threading (in this case single-threaded) and SIMD:
```c++
#include <iostream>

#include <seqan/align.h>
#include <seqan/align_parallel.h>

int
main()
{
  using TSequence = seqan::String<seqan::Dna>;
  using TAlign = seqan::Align<TSequence, seqan::ArrayGaps>;
  using TThreadModel = seqan::WavefrontAlignment<seqan::BlockOffsetOptimization>;
  using TVectorSpec = seqan::Vectorial;
  using TExecPolicy = seqan::ExecutionPolicy<TThreadModel, TVectorSpec>;

  // dummy sequences
  std::string str1;
  std::string str2;
  str1.append(10000, 'A');
  str2.append(10000, 'A');

  seqan::StringSet<TSequence> seqs1;
  seqan::StringSet<TSequence> seqs2;

  appendValue(seqs1, TSequence{str1.c_str()});
  appendValue(seqs2, TSequence{str2.c_str()});

  TExecPolicy execPolicy;
  setNumThreads(execPolicy, 1);

  seqan::Score<int16_t, seqan::Simple> scoreAffine(1, -2, -1, -4);

  seqan::String<int16_t> scores = seqan::globalAlignmentScore(execPolicy, seqs1, seqs2, scoreAffine);
  std::cout << "Score: " << scores[0] << "\n";
  return EXIT_SUCCESS;
}
```

**Comment by hannespetur** [comment]
> You want to compute ONE big alignment? And not a dozen alignments?

Yes, one. I am doing more than one alignments but I want to measure the time of each pair-wise alignment in several different scenarios. 

 > Why are you setting -m64? This might disable SIMD vectorization. Your compiler reads the flags from left to right and your most specific flag e.g. -msse4 might be overwritten by -m64 which could disable SIMD altogether.

I will remove the m64 flag but in my experience it does not overwrite the SIMD vectorization flags.

> We don't support SSE2; We support SSE4.2 and upwards. Including -mavx512f -mavx512cd -mavx512bw -mavx512dq -mavx512vl for Skylake.

Ok, good to know. I wish I had an avx512 processor but unfortunately I am not that lucky :sweat_smile: 

> globalAlignment will compute the score AND the traceback. Our SIMD implementation is (currently) not accelerated for tracebacks. 

Yes I used globalAlignment intentionally because I am interested in the tracebacks. I didn't realize only globalAlignmentScore could be vectorized currently. That clears it up for me.

> Use globalAlignmentScore to compute only the score. To enable SIMD vectorization and threading, you have to use a special execution policy (see our test cases as reference)

After I changed my function to the one you posted I can see clear improvements in calculating the score, now SSE4 is ~89.3 ms and AVX2 ~68.7 ms.


Thank you very much for the help,
Hannes
