### ISSUE TITLE
Canonical hash of a DNA sequence

### ISSUE THREAD

**Issue by standage** [seqan/seqan#2310]
Greetings!

I'm curious if there is any convenient way of computing the canonical hash of a DNA sequence (such that the sequence and its reverse complement hash to the same value)? Or is this left as an exercise to the user?  :-) Such as by hashing the lexicographically smaller of the two.

Thanks!

**Comment by cpockrandt** [comment]
Hi @standage

As far as I know we don't have this in SeqAn. Maybe @eseiler is aware of such a hash function in SeqAn? I guess the easiest way, as you suggested, is to check the lexicographical using a ReverseComplement-ModifiedString and then compute the hash value on the smaller one.

**Comment by standage** [comment]
Thanks!
