### ISSUE TITLE
Reading BAM on stdin and writing SAM to stdout with sync_with_stdio(false) produces nondeterministic errors

### ISSUE THREAD

**Issue by wtwhite** [seqan/seqan#2317]
Hi,

I found to my surprise that adding `sync_with_stdio(false);` to the start of a program that reads a BAM file from stdin using SeqAn's `BamFileIn` and writes a SAM file to stdout using `BamFileOut` produces *nondeterministic* corruption in the output file.  The MRE attached below simply copies stdin to stdout using `BamFileIn` and `BamFileOut` objects.  Running it 5 times with a large enough input file (I used a 250Mb BAM file, and kept just the first 1000 lines of output using `head`) reliably produces 5 different output files.  Using SAM input, or commenting out the `sync_with_stdio(false);` line, or creating a separate `ifstream` object and then initialising the `BamFileIn` object with that instead of with `cin` causes the problem to go away.

Some background: A while back I discovered the magic of [`sync_with_stdio(false);`](https://en.cppreference.com/w/cpp/io/ios_base/sync_with_stdio), which improves iostreams I/O speed dramatically (about 6-10 *times* on my system).  AFAICT, if you don't call this, then every character read or written using iostreams produces a *separate OS kernel call*, while calling it turns on a sane amount of buffering.  The downside of calling it is that interleaving iostreams and "old-style" C streams (`printf()`, etc.) could produce erroneous output (e.g., `cout << 1; putchar('2'); cout << 3;` could output `213` or `132`.), but I never (consciously...) mix these two kinds of I/O in programs I write.

So I suspect the cause of the nondeterminism is that internally SeqAn is mixing these two kinds of access.  I think adding some `flush()` calls in the right places would fix things.

[test_bam_sync_with_stdio_bug.zip](https://github.com/seqan/seqan/files/2134725/test_bam_sync_with_stdio_bug.zip)

**Comment by marehr** [comment]
Hi @wtwhite,

we read your issue, but it is unfortunately really vague and hard to pinpoint.

I imagine that we intermixed `printf` and `cout` calls multiple times in the library and I imagine that this would be a HUGE code restructure.

On the other side is `6x` quite substantial; @h-2 should we make this a requirement for seqan3?

**Comment by marehr** [comment]
Okay some tracing:

This is the primitive to write out BAM files:
https://github.com/seqan/seqan/blob/584ae4fbff8312cfe31b3e0aea651edfb1b580ef/include/seqan/bam_io/write_bam.h#L51-L96

It seems to not use `print`, but it might in some of the `write` operations.

On the other hand writing out a SAM file uses `appendNumber` which uses `snprintf`:

https://github.com/seqan/seqan/blob/e165bafd1d817ac2e8c75f1868b659aaa30290e2/include/seqan/bam_io/write_sam.h#L82-L119

https://github.com/seqan/seqan/blob/e165bafd1d817ac2e8c75f1868b659aaa30290e2/include/seqan/basic/basic_stream.h#L1111-L1125

But this prints not into the iostream. It seems that this is coming from reading and not from writing out.

@wtwhite Could you check this? By reenabling `sync_with_stdio(true);` before writing the files?

**Comment by h-2** [comment]
> @h-2 should we make this a requirement for seqan3?

Absolutely. 

For SeqAn2:
If someone figures this out and provides a patch I am would be very willing to accept it, but I don't have time to look at it myself.

**Comment by h-2** [comment]
Closing this. We will definitely track this for SeqAn3. Re-open in SeqAn2 only with a PR, please.
