### ISSUE TITLE
Yara: accept interleaved FASTQ or unaligned BAM on stdin

### ISSUE THREAD

**Issue by heuermh** [seqan/seqan#2329]
Hello,

As a feature request for `yara_mapper`, could support for specifying paired end reads as a single stream in interleaved FASTQ and/or unaligned BAM formats be added?  E.g.

```bash
# single end reads
$ cat READS.fastq.gz | yara_mapper REF.index -o READS.bam

# paired end reads
$ cat READS.interleaved.fastq.gz | yara_mapper REF.index -o READS.bam
$ cat READS.unaligned.bam | yara_mapper REF.index -o READS.bam
```

Perhaps an `--input-format { fastq, interleaved-fastq, unaligned-bam }` option might be necessary.

Thanks in advance!

**Comment by smehringer** [comment]
Hi @heuermh ,

thank you for using our mapper Yara. Right now we unfortunately don't work on feature requests for SeqAn2 as we currently put a lot of effort into the new SeqAn3 to be soon released.

Your suggestions are interesting to consider and reading raw sequences from an analigned BAM file should be fairly easy to implement as part of our `SeqFileIn` class. But it is also easily bash scripted (on linux): 
```
samtools view READS.unaligned.bam | cut -f 1,10 | awk '{print ">"$1"\n"$2}' | yara_mapper REF.index -o READS.bam
```

Interleaved FASTQ reads would be application specific and as the developer of Yara (@esiragusa ) is not part of our current team any more, this depends on him.

**Comment by h-2** [comment]
Unaligned BAM should work, we added that to SeqAn sequence file before the last release: https://github.com/seqan/seqan/blob/master/CHANGELOG.rst#release-230

**Comment by heuermh** [comment]
@smehringer  Thank you for the quick reply.

Our use case is a little odd, in that we'd be piping to Yara from Apache Spark

http://adam.readthedocs.io/en/latest/api/pipes
https://github.com/bigdatagenomics/cannoli

We can only populate one stream from Spark, so we need to be able to provide paired end reads in a single stream as either interleaved FASTQ and/or unaligned BAM formats.  I assume your scripted example is treated as single end reads by Yara?

@h-2 Are you saying that `cat READS.unaligned.bam | yara_mapper REF.index -o READS.bam` will work for paired end reads with the latest release?  If so, then we have all we need.

**Comment by smehringer** [comment]
Hi @heuermh,

sorry for answering so late. I just checked the yara command line interface and if only one file (stream) is provided, yara assumes you work with single-end reads, no matter the file format.
Unfortunately, we do not plan to extend yara in the recent future as the app developer (@esiragusa ) is not working here anymore.  We are sorry that we cannot help you with this any further for the time being.
