### ISSUE TITLE
problem with writing alignmentStore into a sam file

### ISSUE THREAD

**Issue by ztayyebi-wcm** [seqan/seqan#2333]
Hi.
I did not find any relevant issues, sorry if this has already been discussed.

I am trying to write the alignment store of a fragment store into a sam file with:
`std::ofstream samFile("address", std::ios_base::out);
write(samFile, fragStore, Sam());`
which I saw in one of the tutorials.
However, I get "no matching function for call to 'write'".

I have just pulled seqan from git so I think it is the latest version.

**Comment by ztayyebi-wcm** [comment]
it was in [simple read mapper](http://seqan.readthedocs.io/en/seqan-v1.4.2/Tutorial/SimpleReadMapping.html).

**Comment by smehringer** [comment]
The tutorial you pointed to is from the very outdated manual of SeqAn 1.4.2
 Please use the [current 2.4.0 version](https://seqan.readthedocs.io/en/seqan-v2.4.0/).

Did the  `readRecords()` function help to solve your issue?

**Comment by ztayyebi-wcm** [comment]
sorry I didn't realize that it was old.
that worked. thank you very much.
