### ISSUE TITLE
siRNA off target prediction

### ISSUE THREAD

**Issue by juulluu21** [seqan/seqan#2336]
I was wondering if it is possible to predict siRNA off-terget using STELLAR. What I want to do is: I have a query fasta sequence (a gene), and I want to align it against a genome. I want to see if as small as 21 Nt regions from the query gene gives me any hit in the genome. 

Can I do that?
Thanks.

**Comment by smehringer** [comment]
Hi @juulluu21 ,

sorry for coming back to you so late. 
Do you have ONE specific 21 nt region in the query gene, or do you want to search for every 21-nt-long-hit between the whole query and the genome? (I am not familiar with off-target prediction)

I think the latter problem can be solved with STELLAR, as it will `report all local alignments of a given minimal length and maximal error rate` (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-12-S9-S15). 

If you only have one specific region, that you want to search for in the genome I would recommend to rather use a read mapper like [Yara](https://www.seqan.de/apps/yara/) to find all matches of a query sequence with a maximum error rate in a reference genome.

**Comment by smehringer** [comment]
Feel free to reopen if not solved
