### ISSUE TITLE
foina does not build - build should abort, dependency should be indicated by cmake

### ISSUE THREAD

**Issue by cmeesters** [seqan/seqan#2339]
Hi,

My build log show

-- Configuring apps/fiona
--   Boost or OpenMP not found, not building fiona

That's fine. Yet, than Boost (best with a min. version) should be indicated to cmake, such that the build aborts, when attempting to build without Boost. 

Also, the OpenMP dependency resolution is depending on the compiler version. A recent compiler indicates, whether or not OpenMP is present.

Best regards,
Christian

**Comment by rrahn** [comment]
Currently all apps are part of the SeqAn library, that is why the build is not aborted when building it but just informing about the issue. 
You can use 
```console
cmake ... -DSEQAN_BUILD_SYSTEM=APP:fiona 
```
and it would only configure fiona and not the other tools. 

But sure a more informative error message would be great in general.
Currently, we are porting a lot of the SeqAn library to a new API interface, which consumes a lot of resources. So not sure, when we can get to it. 
But thanks a lot for reporting!

**Comment by cmeesters** [comment]
Yep, 

> Currently, we are porting a lot of the SeqAn library to a new API interface, ...

 is understood after last week (being at your workshop).
Apart from that, I am going to fix the easyconfig-file for easybuild. And I think, the issue itself, can be closed: If apps are going to be ported, the issue will resolve itself, 'cause of the different dependencies which have to be resolved.
