### ISSUE TITLE
<seqan/bed_io.h> issues with parsing BED12 file

### ISSUE THREAD

**Issue by go9kata** [seqan/seqan#2346]
### parsing BED12 line, without extra data in it ('\n' vs '\t\n' line delimiter)

- [x] when reading a BED12 line, the parser fails if the line finishes with '\n' character after the blockBegins comma separated list. If in the test script one changes the following line: https://github.com/seqan/seqan/blob/584ae4fbff8312cfe31b3e0aea651edfb1b580ef/tests/bed_io/test_bed_io.cpp#L167

to:

```String<char> test = "I\t123\t456\tNAME\t3\t-\t33\t66\t255,0,0\t3\t10,11,12\t1,2,3\n";```

execution fails with UnexpectedEnd, where the following line is working fine:

```String<char> test = "I\t123\t456\tNAME\t3\t-\t33\t66\t255,0,0\t3\t10,11,12\t1,2,3\t\n";```

There is no need to introduce an empty 13th field in the BED12 file in order to progress normally.

### compatibility with the UCSC BED12 files, downloaded via the TableBrowser
- [x] if itemRgb value is missing, it is often substituted with '0'. The parser only accepts 3 integers delimited by a comma, e.g.: '0,0,0'. Maybe a detection of '0' might default to '0,0,0', instead of throwing an error. 

To test:
```String<char> test = "I\t123\t456\tNAME\t3\t-\t33\t66\t0\t3\t10,11,12\t1,2,3\t\n";```
throws an exception for BadLexicalCast.

- [x] the blockSizes and blockBegins lists might finish with a comma, e.g.:
 a file can contain a list like: 1,2,3,
the parser only works with: 1,2,3 (without trailing comma)

To test:
```String<char> test = "I\t123\t456\tNAME\t3\t-\t33\t66\t0,0,0\t3\t10,11,12,\t1,2,3,\t\n";```
throws an exception for BadLexicalCast.

**Comment by smehringer** [comment]
Ho @go9kata,

thanks for reporting this and for the detailed description!

Looks like some incompatibility issue because our BED parsing is not up to date.
Our resources are mostly given to our new SeqAn3 library release so I don't know when we will have time to fix this. 
@joergi-w can you maybe have a look?

**Comment by smehringer** [comment]
@joergi-w ping

**Comment by smehringer** [comment]
Thanks @joergi-w  for fixing this.
@go9kata Check out the current develop branch and see if everything works fine now for your data.

**Comment by go9kata** [comment]
Thanks guys for the fast fix! Looks good! Keep up the nice work! Cheers! ;)
