### ISSUE TITLE
Unable to compile flexbar -- issue with numeric limits

### ISSUE THREAD

**Issue by cmeesters** [seqan/seqan#2347]
Hi,

this is a seqan issue, though I am not sure, whether it better placed here or in the flexbar project. However, it may show up elsewhere, so:

When compiling flexbar 3.4.0 sources in an attempt to create an easyconfig file with the following tools and version - CMake 3.11.4, GCC 7.3.0, tbb 2018.2.199, seqan 2.4.0 - I stumbled over this error:

<snip>

> In file included from /cluster/easybuild/nehalem/software/devel/seqan/2.4.0/include/seqan/basic/basic_alphabet.h:62:0,
>                  from /cluster/easybuild/nehalem/software/devel/seqan/2.4.0/include/seqan/basic/basic_container.h:47,
>                  from /cluster/easybuild/nehalem/software/devel/seqan/2.4.0/include/seqan/basic.h:71,
>                  from /gpfs/fs1/cluster/easybuild/nehalem/software/bio/flexbar/3.4.0/flexbar-3.4.0/src/Flexbar.h:19,
>                  from /gpfs/fs1/cluster/easybuild/nehalem/software/bio/flexbar/3.4.0/flexbar-3.4.0/src/Flexbar.cpp:24:
> /cluster/easybuild/nehalem/software/devel/seqan/2.4.0/include/seqan/basic/alphabet_math.h:80:44: error: ‘FLT_MAX’ was not declared in this scope
>  const float MaximumValueFloat_<T>::VALUE = FLT_MAX;
>                                             ^~~~~~~
> /cluster/easybuild/nehalem/software/devel/seqan/2.4.0/include/seqan/basic/alphabet_math.h:80:44: note: suggested alternative: ‘INT_MAX’
>  const float MaximumValueFloat_<T>::VALUE = FLT_MAX;
>                                             ^~~~~~~
>                                             INT_MAX
> /cluster/easybuild/nehalem/software/devel/seqan/2.4.0/include/seqan/basic/alphabet_math.h:82:46: error: ‘DBL_MAX’ was not declared in this scope
>  const double MaximumValueDouble_<T>::VALUE = DBL_MAX;
>                                               ^~~~~~~
> /cluster/easybuild/nehalem/software/devel/seqan/2.4.0/include/seqan/basic/alphabet_math.h:82:46: note: suggested alternative: ‘NL_NMAX’
>  const double MaximumValueDouble_<T>::VALUE = DBL_MAX;
>                                               ^~~~~~~
>                                               NL_NMAX
> /cluster/easybuild/nehalem/software/devel/seqan/2.4.0/include/seqan/basic/alphabet_math.h:138:45: error: ‘FLT_MAX’ was not declared in this scope
>  const float MinimumValueFloat_<T>::VALUE = -FLT_MAX;
>                                              ^~~~~~~
> /cluster/easybuild/nehalem/software/devel/seqan/2.4.0/include/seqan/basic/alphabet_math.h:138:45: note: suggested alternative: ‘INT_MAX’
>  const float MinimumValueFloat_<T>::VALUE = -FLT_MAX;
>                                              ^~~~~~~
>                                              INT_MAX
> /cluster/easybuild/nehalem/software/devel/seqan/2.4.0/include/seqan/basic/alphabet_math.h:140:47: error: ‘DBL_MAX’ was not declared in this scope
>  const double MinimumValueDouble_<T>::VALUE = -DBL_MAX;
>                                                ^~~~~~~
> /cluster/easybuild/nehalem/software/devel/seqan/2.4.0/include/seqan/basic/alphabet_math.h:140:47: note: suggested alternative: ‘NL_NMAX’
>  const double MinimumValueDouble_<T>::VALUE = -DBL_MAX;
>                                                ^~~~~~~
>                                                NL_NMAX
> make[2]: *** [src/CMakeFiles/flexbar.dir/Flexbar.cpp.o] Error 1

</snip>

Now, these are constants defined in the C++ std-library "limits" and as such are part of numeric limits. In  alphabet_math.h "climits" and "float" are included. I tried to path by including "limits" to no avail. When changing lines like

const float MaximumValueFloat_<T>::VALUE = FLT_MAX;

to

const float MaximumValueFloat_<T>::VALUE = numeric_limits<float>::max(); 

flexbar successfully compiled. 

Well, this ain't kosher - dropping a float to a generic T, yet, so is +/-FLT_MAX. 

What is your opinion on this? Is this a bug turning up, which is not revealed in certain build setups? Is the fix worth considering? Would it be a good idea to create a pull request on this?

Best,
Christian

**Comment by smehringer** [comment]
Hi @cmeesters ,

thanks for reporting this. Can you also include the parts for flexbar of your easy config file? Right now I cannot reproduce your error.

In general, this looks like the includes got messed with.

> I tried to path by including "limits" to no avail. 

FLT_MAX is included via <float.h>

> Well, this ain't kosher - dropping a float to a generic T, yet, so is +/-FLT_MAX.

Yes! But, you can specialize numeric limits via `numeric_limits<float>::max()`, which is a synonym for FLT_MAX.

I don't know why this didn't occur anywhere else so far but it is a quick fix (numeric_limits should be used in such cases anyway).

Could you make a PR with the following substitutions?:

```
FLT_MAX <=> std::numeric_limits<float>::max()
DBL_MAX <=> std::numeric_limits<double>::max()

-FLT_MIN <=> std::numeric_limits<double>::lowest()
-DBL_MIN <=> std::numeric_limits<double>::lowest()
```
Note that it is **lowest()** and **NOT min()**.

**Comment by cmeesters** [comment]
Hi Svenja,

Sorry, I have to leave, so no PR before tomorrow, but yes, I will gladly do that.

> Can you also include the parts for flexbar of your easy config file?

What would that be? I could attach the entire build log, yet the relevant part is already there. Or the easyconfig itself.

Best,
Christian

**Comment by smehringer** [comment]
Hi Christian,

> Sorry, I have to leave, so no PR before tomorrow, but yes, I will gladly do that.

Thank you that would be great! 

> What would that be? I could attach the entire build log, yet the relevant part is already there. Or the easyconfig itself.

Never mind. I just double checked and saw that we do not use the respective code parts in the entire Seqan2 repo so the code is not tested. We switched to numeric_limits for many cases already so your PR would help to modernize the library even if I could not reproduce your error.

**Comment by h-2** [comment]
fixed
