### ISSUE TITLE
getAbsolutePath and BAM IO example

### ISSUE THREAD

**Issue by AntoineHo** [seqan/seqan#2358]
Hello,
When I copy the solution of `Assignment 1` in https://seqan.readthedocs.io/en/master/Tutorial/InputOutput/SamAndBamIO.html#tutorial-io-sam-bam-io I get the could not open error. My input file path was **"./toy.bam"**
When I then try to print `bamFileName` I get: **"/usr/./toy.bam"** which is not the right file path.
When I try to put the aboluste path directly as `bamFileName` I still cannot open the file.

Can you help me?

Thank you very much.

AH

**Comment by smehringer** [comment]
Hi @AntoineHo,

thanks for trying SeqAn. 

The function `getAbsolutePath(...)` pre-pends the current directory of your SeqAn repository before the filename. So I guess your seqan repo is in `/usr/` and then you give it the path `./toy.bam` which results in `/usr/./toy.bam`. This is not the way to go in your case (We should drop a note about this in the tutorial such that this is clear so thanks for asking).

It should work with an absolute path directly given to `bamFileName` though. Can you list the follwing information:
- path where you execute the program: 
- path of the file you want to open
and then paste the code you are trying to execute.

sometimes it is only a typo :)

**Comment by AntoineHo** [comment]
Hello,
I execute the program in:
`/home/antoine/Dropbox/seqanTest/`
The path to the bamfile is:
`/home/antoine/Dropbox/seqanTest/toy.bam`

Here is the code:
``` c++
#include <seqan/bam_io.h>

using namespace seqan;

int main(int argc, char* argv[]) {
  CharString bamFileName = "/home/antoine/Dropbox/seqanTest/toy.bam";
  BamFileIn bamFileIn;
  std::cout << bamFileName << std::endl;

  if (! open(bamFileIn, toCString(bamFileName))) {
    std::cerr << "ERROR: Could not open " << bamFileName << std::endl;
    return 1;
  }
  BamFileOut bamFileOut(context(bamFileIn), std::cout, Sam());

  try {
    BamHeader header;
    readHeader(header, bamFileIn);
    writeHeader(bamFileOut, header);

    BamAlignmentRecord record;
    while (!atEnd(bamFileIn)) {
      readRecord(record, bamFileIn);
      writeRecord(bamFileOut, record);
    }
  }
  catch (Exception const & e) {
    std::cout << "ERROR: " << e.what() << std::endl;
    return 1;
  }
  return 0;
}
```
The output is:
`ERROR: Could not open /home/antoine/Dropbox/seqanTest/toy.bam`

**Comment by smehringer** [comment]
This code should work so I think it is not a problem with seqan. You can verify this by including the following and see if it also does also fail:

```cpp
#include <fstream>
// ...
int main(int argc, char* argv[]) 
{
    CharString bamFileName = "/home/antoine/Dropbox/seqanTest/toy.bam";
    std::fstream standard_file(toCString(bamFileName);

    if (!standard_file.is_open()) 
    {
        std::cout << "failed to open " << bamFileName << '\n';
    }

// the rest ...
``` 
If so there is a problem with your file, the rights to access the file or something else.

**Comment by AntoineHo** [comment]
I checked and it raises no error:
``` c++
#include <fstream>
#include <seqan/bam_io.h>
using namespace seqan;
int main(int argc, char* argv[]) {
  // Creates a seqan string for storing .bam filename
  CharString bamFileName = "/home/antoine/Development/seqanTest/toy.bam";
  std::fstream standard_file(toCString(bamFileName));
  if (!standard_file.is_open()) {
    std::cout << "failed to open " << bamFileName << '\n';
  } else {
    std::cout << "This worked fine!" << std::endl;
  }
  BamFileIn bamFileIn;
// ...
```
OUT:
```
This worked fine!
ERROR: ERROR: Could not open /home/antoine/Development/seqanTest/toy.bam
```
Actually I found that when using toy.sam it works but with toy.bam it does not, I will try with another .bam file and close the issue if it works.

Many thanks for your help!

**Comment by smehringer** [comment]
Ah I see, then you might have not installed the `zlib`. BAM file reading is only possible if `zlib` is installed

We mention this in the beginning of the tutorial

> Before you can read/write BAM files (bgzf compressed SAM files) you need to make sure that your program is linked against the zlib library. When you build your application within the SeqAn build infrastructure, the zlib library is automatically located by looking at the standard places for the library. Also have a look at Formatted Files to read more about support of compressed file I/O. If the macro SEQAN_HAS_ZLIB is set to 0 then reading/writing BAM file format is disabled. It is set to 1 if the zlib could be found and reading/writing of compressed files is enabled automatically. You can read Using SeqAn in CMake-based projects, Integration with your own Build System and Installing Dependencies for further notes about using the zlib and libbz2 in your build infrastructure.

**Comment by AntoineHo** [comment]
I checked that by adding the FindBZip2 to my project, I can compile fine and both zlib and bzip2 are found... Any idea ?
``` cmake
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/antoine/Development/seqanTest/tmp
Scanning dependencies of target seqanMYtest
[ 50%] Building CXX object CMakeFiles/seqanMYtest.dir/src/main.cpp.o
[100%] Linking CXX executable seqanMYtest
[100%] Built target seqanMYtest
```

**Comment by smehringer** [comment]
Can you attach the toy BAM file?

**Comment by AntoineHo** [comment]
I mainly tried with these two files (attached). I tested with other bam files as well I get the same error.
[mapt.NA12156.altex.bam.gz](https://github.com/seqan/seqan/files/2552112/mapt.NA12156.altex.bam.gz)
[toy.sorted.bam.gz](https://github.com/seqan/seqan/files/2552117/toy.sorted.bam.gz)

AH

**Comment by smehringer** [comment]
Please try gzipping your sam file and give that to the toy example. This will tell us if zlib works correctly.

Also, try the suggestion mentioned in #2056, including a macro to print if the zlib was actually found.

**Comment by AntoineHo** [comment]
You are right, it must that zlib is not found by seqan. The macro does not print anything and I cannot read .sam.gz files.

**Comment by smehringer** [comment]
Glad we could help! :tada:
