### ISSUE TITLE
extractTagValue hangs

### ISSUE THREAD

**Issue by JulianSpagnuolo** [seqan/seqan#2359]
This code snippet is making my script hang. I can retrieve one of either, but not both else it just stops and does nothing. Since this example is essentially the same as the one in the example tutorial then it should work without issue.

Is there another way I can access the tags directly and coerce to std::string?
```
BamTagsDict tags(record.tags);
buildIndex(tags);
seqan::CharString cellbc;
seqan::CharString umi;
for(unsigned uid = 0; uid < length(tags); uid++)
{
    if(findTagKey(uid, tags, "XC"))
    {
      extractTagValue(cellbc, tags, uid);
    }
    if(findTagKey(uid, tags, "XM"))
    {
        extractTagValue(umi, tags, uid);
    }
}
```

This works and prints out the bam/sam tags (twice with a tab-delimitation)
```
String<char, CStyle> some_tags;
some_tags = record.tags;
for(int uid = 0; uid < length(blah); uid++)
{
    std::cout << some_tags[uid];
}
std::cout << "\t" << some_tags << std::endl;
```

but this wont:
```
String<char, CStyle> some_tags;
some_tags = record.tags;
std::cout << some_tags << std::endl;
```

Since the first snippet doesn't do anything to `some_tags` there seems to me that there is no reason why the second (simpler) version wont work.

**Comment by JulianSpagnuolo** [comment]
Found the issue - I was looking at an older version of the documentation from which it wasn't clear that uid is an output value.... the latter issue still seems a bit wierd.

**Comment by smehringer** [comment]
Self-solving issues are my favourite :sparkles: 
Thanks for trying out SeqAn. If you have any other troubles come back again :bowtie:
