### ISSUE TITLE
Options of globalAlignmentScore

### ISSUE THREAD

**Issue by Lolasdasdasd** [seqan/seqan#2380]
I'm using the function globalAlignmentScore to align a huge amount sequences in parallel. When fiddling with the parameters, I could change gap costs via Score or AlignConfig. However, I fail to understand the function of lowerDiag, and upperDiag and its not documented as far as I can see...
More importantly, I want to apply a local alignment (SmithWaterman) combined with a scoring scheme but could not change the algorithm tag. What are the options for this? Is it even possible with the globalAlignmentScore function?

Here my code for aligning 2 sequences (actually I fill the StringSets with many more):
```

int main(int argc, char** argv){

    if (argc != 3){
        std::cout << "please provide <frag1> <frag2>" << std::endl;
        return -1;
    }
    std::string frag1 = argv[1]; std::string frag2 = argv[2];
    Score<int> NW1(100, 0, -10, -300);
    ExecutionPolicy<Parallel, Vectorial> exec{};
    setNumThreads(exec, 1);  // set the threads to the number of physical cores.

    StringSet<Peptide> block1; StringSet<Peptide> block2;
    resize(block1, 1); resize(block2, 1);
    assignValue(block1, 0, frag1); assignValue(block2, 0, frag2);

    auto scores = globalAlignmentScore(exec, block1, block2, NW1, AlignConfig<true,true,true,true>());
    std::cout << scores[0] << std::endl;

    return 1;
}
```

**Comment by rrahn** [comment]
Hi, 

>However, I fail to understand the function of lowerDiag, and upperDiag and its not documented as far as I can see...

these parameters are for the banded version of the algorithm. `lowerDiag` is the lower bound of the band and `upperDiag` is the upper bound. See http://docs.seqan.de/seqan/master/?p=globalAlignmentScore and https://seqan.readthedocs.io/en/master/Tutorial/Algorithms/Alignment/PairwiseSequenceAlignment.html#banded-alignments for the documentation.
 
> More importantly, I want to apply a local alignment (SmithWaterman) combined with a scoring scheme but could not change the algorithm tag. What are the options for this? Is it even possible with the globalAlignmentScore function?

For this there is the localAlignmentScore function, which computes the local alignment. It is the same interface without the AlignConfig object. 

I hope this helps.

**Comment by rrahn** [comment]
Pleas also note, that the banded vectorized version does not work yet for sequences with different length. This is a feature which will come with SeqAn3.

**Comment by rrahn** [comment]
@Lolasdasdasd many thanks for writing us. I hope we could help you in resolving your request. Please don't hesitate to reopen this ticket if it was not fully resolved.
