### ISSUE TITLE
BamFileIn#viewRecords does not show in the docs.

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#2388]
There is no entry in the user documentation for the function BamFileIn#viewRecords in develop, master or 2.4.0.

<img width="757" alt="Screenshot 2019-07-17 at 11 20 05" src="https://user-images.githubusercontent.com/1529364/61363808-e7d29d80-a884-11e9-9612-80bbbde3d84f.png">

**Comment by smehringer** [comment]
But the documentation is there  :( https://github.com/seqan/seqan/blob/develop/include/seqan/bam_io/bam_index_bai.h#L162
I have no clue why it is not included

**Comment by rrahn** [comment]
Well, first of all it is only relevant for the develop branch since it was not included for 2.4 and is not yet merged into master. 

For the other thing I am not sure why it does not pop up. The dox code seemed fine. Can you built it locally and check if it is present. If that is the case then the cronjob might be broken and is not building the docu anymore

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rrahn** [comment]
In case the Cron is not running, we should trigger it from Jenkins to get rid of the user dependency. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rrahn** [comment]
fixed by #2407
