### ISSUE TITLE
Controlling async IO threads

### ISSUE THREAD

**Issue by serosko** [seqan/seqan#2395]
Hi, 
I am using seqan BAM I/O for my project and when running the program lots of threads are spawned, which I imagine being due to the async I/O, because I did not implement any multi-threading. Is there a way to control the number of I/O threads?

**Comment by rrahn** [comment]
There is an environment variable called SEQAN_BGZF_NUM_THREADS which you can set before including before including seqan  headers. It defaults to 16 if not set otherwise.

**Comment by serosko** [comment]
Thank you for the answer. I included this in my preprocessing commands but this does not seem to change anything. The code now compiles with:
`
~/Development/PopDel$ make
g++ -I . -DSEQAN_HAS_ZLIB=1 -std=c++14 -DSEQAN_DISABLE_VERSION_CHECK -DSEQAN_BGZF_NUM_THREADS=1 -DDATE=\""on 2019-07-04"\" -DVERSION=\""1.1.0"\" -W -Wall -Wno-long-long -pedantic -Wno-variadic-macros -Wno-unused-result -O3 -DNDEBUG -DSEQAN_ENABLE_TESTING=0 -DSEQAN_ENABLE_DEBUG=0   -c -o popdel.o popdel.cpp
`
`
g++   popdel.o  -lz -lpthread -o popdel
`
but I still get 16 additional threads.

**Comment by serosko** [comment]
Ah, I just noticed that I seem to be using an old version of iostream_bgzf.h. The variable is not defined there and the number of threads hardcoded.

**Comment by serosko** [comment]
Changing this did the trick. Thank you for the advice.
