### ISSUE TITLE
Seqan Inter-Sequence Vectorization 

### ISSUE THREAD

**Issue by esaliya** [seqan/seqan#2401]
Hi,

I am trying to align a target sequence set, `S1`, against a query set, `S2`, where `|S1| = |S2|`. I see SeqAn supports vectorization for this pattern in the supplementary document pointed from [1]. 

However, I don't see how to do this programmatically. Is there a separate API to use or compiler flags to enable this?

Thank you,
Saliya

[1] https://academic.oup.com/bioinformatics/article/34/20/3437/4992147

**Comment by rrahn** [comment]
Hi @esaliya thanks for writing us. 

In general this vectorisation can be enabled by calling the aligmnent API with a set of sequences instead of passing each sequence pair separately:

```cpp
seqan::StringSet<seqan:DnaString> collection1{...};
seqan::StringSet<seqan:DnaString> collection2{...};

assert(seqan::length(collection1) == seqan::length(collection2));

seqan::String<int> scores =  seqan::globalAlignmentScore(collection1, collection2, ...);

assert(seqan::length(scores) == seqan::length(collection1));
```

In order to use the simd version of the alignment it should suffice to compile your program with `-msse4` for SSE4 or `-mavx2` for AVX2. If you use gcc, you can also use AVX512. There are several compiler flags for AVX512, which depend on the system you can use. [Here](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html) are some additional information on possible arch flags to the gcc compiler.  

If you are not cross-compiling you can simply use -march=native. But then only the instructions are picked from the system that the build is triggered on (so it might not run on another system due to illegal instructions or it is slower than expected because the platform you built on uses older instruction sets that not match the one used on the productive system). 

Also note, if your sequences are short (so you would expect no score overflow or underflow when aligning them, e.g. illumina reads) you can use for your scoring scheme a lower integer width:

```cpp
seqan::Score<int16_t, seqan::Simple> my_score{match, mismatch, gap, gap_open};
```
In this case the algorithm computes twice as many alignments as using the default int32_t score type. Note, that at the moment int16_t is the smallest integer that is supported at the moment.

The algorithm performs particular well when computing only the score but also alignment computation is supported. In this case you need to pass in a collection of seqan::Align objects (`seqan::StringSet<seqan::Align<seqan::DnaString>>`) or two sets of gapped sequences (seqan::StringSet<seqan::Gaps<seqan::DnaString>>) similar to the interface above when passing two collections. Also note that then you have to call the `globalAlignment` function.

I hope this helps, if not please let us know how we can further assist you.

Best regards,

the SeqAn team

**Comment by esaliya** [comment]
Thank you, @rrahn for the description of options and API. However, in a different thread (https://github.com/seqan/seqan/issues/2308) I see several execution policies related to vectorization. What are these and do I need them to enable this inter-sequence vectorization?

**Comment by rrahn** [comment]
Yes, you are right. I thought of the most simple version to activate vectorisation, that is also "kind of" documented. So basically everything that I said does work for merely vectorisation but if you want to also use parallelisation in combination you need to use the exception policy interface as described in the other thread. There you can also tweak the number of threads if you have too.
So it would be even better to use this interface because it is more expressive in what it does. 
Unfortunately, these interfaces are not yet documented but I make this an issue and add documentation for these interfaces soon.

This does not change the fact, that you have to compile with the respective flags to enable vectorisation for your platform.

```cpp

  using TThreadModel = seqan::Parallel;
  using TVectorSpec = seqan::Vectorial;
  using TExecPolicy = seqan::ExecutionPolicy<TThreadModel, TVectorSpec>;

  TExecPolicy execPolicy;
  setNumThreads(execPolicy, 4);
  seqan::Score<int16_t, seqan::Simple> scoreAffine(1, -2, -1, -4);
  auto results = seqan::globalAlignmentScore(execPolicy, seqs1, seqs2, scoreAffine);
```
This will call the inter-sequence vectorisation together with inter-sequence parallelisation (parallelised over the input sequences). The wavefront threading model can at the moment only be used to compute the scores and not the alignment. It is an intra-parallelisation model and does work well for large sequences. If this is your use case I can help you by providing more information.
So to find the optimal execution policy I'd like to ask you some questions about your data.

Are your sequences small or rather long (> 1Kbp). 
Do they have the same length or roughly the same or are they very heterogeneous in length? 
How many do you want to align? 
And do you want to compute the alignment or only the score? 
Are we talking about dna or amino acid sequences?

**Comment by esaliya** [comment]
Thank you, @rrahn. So if I understand correctly, given two sequence sets, `S1` and `S2` of equal length, say N, then in the parallel mode, it'll first partition these among threads. Is that correct?

Also, the chunk of `S1` and `S2` that a thread handles will use inter-sequence vectorization. Isn't that right?

About your questions:
1. Yes, these are short, about half of them are < 200 bp. 98% of them are < 700 bp
2. The lengths vary between 20-700 bp
3. About 70,000 sequences in each `S1` and `S2`
4. I want to compute the percent identity, which requires me to compute the alignment.
5. These are amino acid sequences.

So what are the constraints on the size of these sequence arrays? If I pass two large arrays like in my case with 70k sequences each, will seqan chunk these automatically during vectorization?

**Comment by rrahn** [comment]
> Thank you, @rrahn. So if I understand correctly, given two sequence sets, S1 and S2 of equal length, say N, then in the parallel mode, it'll first partition these among threads. Is that correct?
Also, the chunk of S1 and S2 that a thread handles will use inter-sequence vectorization. Isn't that right?

That is correct. It simply does a parallel for over the collection of sequences. Each thread than computes batches of sequences in parallel using vectorisation.

The suggested mode with parallel and vectorisation is the fastest. There is basically no constraint on the number of sequences, except the usual memory requirements for storing that many alignments and scores etc. But for 70k that is not a problem. It wold be worth trying out if sorting the sequences before, i.e. sequences of same length are grouped together, has an impact on the runtime. 

>will seqan chunk these automatically during vectorization?

Yes, with the parallel mode of the execution policy it will automatically chunk the collections.
There is nothing you need to parallelise in your code for the alignment step.

**Comment by esaliya** [comment]
Thank you, @rrahn. Could you also, show me a code sample on how to use the `globalAlignment` function with vectorization? I tried the following but it gives me an error.

```
seqan::StringSet<seqan::Align<seqan::DnaString>> ac;
for (int i = 0; i < 16; ++i) {
    std::string str1;
    std::string str2;
    str1.append(10000, 'A'+i); // Create first sequence string
    str2.append(10000, ('A'+i)-1); // Create the second sequence string
    seqan::Align<seqan::Peptide> align;
    resize(rows(align), 2);
    assignSource(row(align, 0), str1); // Assign first sequence to the align object
    assignSource(row(align, 1), str2); // Assign second sequence to the align object

    appendValue(ac, align); // Line 102, Error here.
  }
```

The long error message is below.

```
In file included from /Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/sequence.h:105,
                 from /Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/modifier.h:47,
                 from /Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/align.h:57,
                 from seqanvec.cpp:5:
/Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/sequence/string_base.h: In instantiation of 'static void seqan::AppendValueToString_<TExpand>::appendValue_(T&, TValue&&) [with T = seqan::String<seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> > >, seqan::Alloc<> >; TValue = const seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::AminoAcid_>, seqan::Alloc<> > >&; TExpand = seqan::Tag<seqan::TagGenerous_>]':
/Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/sequence/string_base.h:1366:54:   required from 'void seqan::appendValue(seqan::String<TValue, TSpec>&, TValue&&, seqan::Tag<TUsage>) [with TTargetValue = seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> > >; TTargetSpec = seqan::Alloc<>; TValue = const seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::AminoAcid_>, seqan::Alloc<> > >&; TExpand = seqan::TagGenerous_]'
/Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/sequence/string_set_owner.h:174:16:   required from 'void seqan::appendValue(seqan::StringSet<TString, seqan::Owner<> >&, const TString2&, seqan::Tag<TExpand>) [with TString = seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> > >; TString2 = seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::AminoAcid_>, seqan::Alloc<> > >; TExpand = seqan::TagGenerous_]'
/Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/sequence/sequence_interface.h:937:16:   required from 'void seqan::appendValue(TContainer&&, TSource&&) [with TContainer = seqan::StringSet<seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> > > >&; TSource = seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::AminoAcid_>, seqan::Alloc<> > >&]'
seqanvec.cpp:102:26:   required from here
/Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/sequence/string_base.h:1342:26: error: no matching function for call to 'seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> > >::Align(const seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::AminoAcid_>, seqan::Alloc<> > >&)'
 1342 |             TTargetValue temp_copy(std::forward<TValue>(_value)); //temp copy because resize could invalidate _value
      |                          ^~~~~~~~~
In file included from /Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/align.h:97,
                 from seqanvec.cpp:5:
/Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/align/align_base.h:99:5: note: candidate: 'template<class TString, class TStringsetSpec> seqan::Align<TSource, TSpec>::Align(seqan::StringSet<TOtherString, TOtherSpec>&)'
   99 |     Align(StringSet<TString, TStringsetSpec> & stringset)
      |     ^~~~~
/Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/align/align_base.h:99:5: note:   template argument deduction/substitution failed:
In file included from /Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/sequence.h:105,
                 from /Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/modifier.h:47,
                 from /Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/align.h:57,
                 from seqanvec.cpp:5:
/Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/sequence/string_base.h:1342:26: note:   types 'seqan::StringSet<TString, TSpec>' and 'const seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::AminoAcid_>, seqan::Alloc<> > >' have incompatible cv-qualifiers
 1342 |             TTargetValue temp_copy(std::forward<TValue>(_value)); //temp copy because resize could invalidate _value
      |                          ^~~~~~~~~
In file included from /Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/align.h:97,
                 from seqanvec.cpp:5:
/Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/align/align_base.h:96:5: note: candidate: 'seqan::Align<TSource, TSpec>::Align() [with TSource = seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> >; TSpec = seqan::Tag<seqan::ArrayGaps_>]'
   96 |     Align() {}
      |     ^~~~~
/Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/align/align_base.h:96:5: note:   candidate expects 0 arguments, 1 provided
/Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/align/align_base.h:87:7: note: candidate: 'seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> > >::Align(const seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> > >&)'
   87 | class Align
      |       ^~~~~
/Users/esaliya/sali/software/seqan-v2.4.0/include/seqan/align/align_base.h:87:7: note:   no known conversion for argument 1 from 'const seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::AminoAcid_>, seqan::Alloc<> > >' to 'const seqan::Align<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> > >&'

```

**Comment by rrahn** [comment]
This would be an example of how to use it passing two collections of Gaps objects. You can adapt it to also take a collection of Align objects. In this case you have to construct a StringSet over Align objects.

```cpp
#include <iostream>

#include <seqan/align_parallel.h>
#include <seqan/stream.h>  // for printint strings

int main()
{
    using TSequence = seqan::String<seqan::Dna>;
    using TAlignedSequence = seqan::Gaps<TSequence>;
    using TThreadModel = seqan::Parallel;
    using TVectorSpec = seqan::Vectorial;
    using TExecPolicy = seqan::ExecutionPolicy<TThreadModel, TVectorSpec>;

    // dummy sequences
    TSequence seqH = "CGATT";
    TSequence seqV = "CGAAATT";

    seqan::StringSet<TAlignedSequence> seqs1;
    seqan::StringSet<TAlignedSequence> seqs2;

    for (size_t i = 0; i < 100; ++i)
    {
        appendValue(seqs1, TAlignedSequence(seqH));
        appendValue(seqs2, TAlignedSequence(seqV));
    }

    TExecPolicy execPolicy;
    setNumThreads(execPolicy, 4);

    seqan::Score<int16_t, seqan::Simple> scoreAffine(2, -2, -1, -4);

    seqan::String<int16_t> scores = seqan::globalAlignment(execPolicy, seqs1, seqs2, scoreAffine);

    for (int16_t score : scores)
        std::cout << "Score: " << score << "\n";

    for (size_t pos = 0; pos < seqan::length(seqs1); ++pos)
    {
        std::cout << seqs1[pos] << "\n";
        std::cout << seqs2[pos] << "\n\n";
    }

    return EXIT_SUCCESS;
}
```

Does this work for you?

**Comment by esaliya** [comment]
Beautiful!
Can I pass `seqan::Blosum62` as the scoring mechanism?

**Comment by rrahn** [comment]
Yes you can do this with a scoring matrix:

```cpp
seqan::Score<int16_t, seqan::ScoreMatrix<seqan::AminoAcid, seqan::ScoreSpecBlosum62>> blosum62Affine{-1, -10};
```

Does this work?

**Comment by esaliya** [comment]
I tried it but I am running into an error. The compiler says it can't find a call to `globalAlignment` as in the example,

```
error: no matching function for call to 'globalAlignment(TExecPolicy&, seqan::StringSet<seqan::Gaps<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> >, seqan::Tag<seqan::ArrayGaps_> > >&, seqan::StringSet<seqan::Gaps<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> >, seqan::Tag<seqan::ArrayGaps_> > >&, seqan::Score<short int, seqan::Tag<seqan::Simple_> >&)'
  108 |   seqan::String<int16_t> scores = seqan::globalAlignment(execPolicy, seqs1, seqs2, scoreAffine);
```

**Comment by rrahn** [comment]
Ok, I’ll check this today

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rrahn** [comment]
Mhmmm, it compiles for me. Are you using the develop branch of SeqAn?
Can you output the entire compile output and add `VERBOSE=1` to the make command?

**Comment by rrahn** [comment]
So this is the snippet I compiled and run successfully.

```cpp
#include <iostream>

#include <seqan/align_parallel.h>
#include <seqan/stream.h>  // for printint strings

int main()
{
    using TSequence = seqan::String<seqan::AminoAcid>;
    using TThreadModel = seqan::Parallel;
    using TVectorSpec = seqan::Vectorial;
    using TExecPolicy = seqan::ExecutionPolicy<TThreadModel, TVectorSpec>;

    // dummy sequences
    TSequence seqH = "CGATT";
    TSequence seqV = "CGAAATT";

    seqan::StringSet<seqan::Gaps<TSequence>> seqs1;
    seqan::StringSet<seqan::Gaps<TSequence>> seqs2;

    for (size_t i = 0; i < 100; ++i)
    {
        appendValue(seqs1, seqan::Gaps<TSequence>(seqH));
        appendValue(seqs2, seqan::Gaps<TSequence>(seqV));
    }

    TExecPolicy execPolicy;
    setNumThreads(execPolicy, 4);

    seqan::Score<int16_t, seqan::ScoreMatrix<seqan::AminoAcid, seqan::ScoreSpecBlosum62>> scoreAffine(-1, -4);

    seqan::String<int16_t> scores = seqan::globalAlignment(execPolicy, seqs1, seqs2, scoreAffine);

    for (int16_t score : scores)
        std::cout << "Score: " << score << "\n";

    std::cout << "SeqH: " << seqs1[0] << "\n";
    std::cout << "SeqV: " << seqs2[0] << "\n";

    return EXIT_SUCCESS;
}

It also uses the amino acid alphabet and blosum62 scoring matrix
```

**Comment by esaliya** [comment]
I still get the same error message of no function overload for `globalAlignment()`. This is the build command I used with your example.

`g++-9 -mavx2 -I~/seqan-v2.4.0/include -std=c++14 ./example.cpp -o ex `

**Comment by rrahn** [comment]
Mhmm, some interfaces regarding the alignment and not just the score computation were added only after 2.4.0.. Can you check the current develop branch and see if this works? At least from your command I am guessing that you are using 2.4.0?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by esaliya** [comment]
Thank you, @rrahn, that fixed the issue. Yes, I was using seqan v2.4.0. Now I switched to the developer branch and got it working.

**Comment by rrahn** [comment]
Awesome! Glad we could help. Please let us know if something else pops up. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rrahn** [comment]
I am closing the issue now as it seems to be resolved? If you feel there are some things not clarified, please feel free to reopen the issue at any time.
