### ISSUE TITLE
external_split_merge.cpp:109 Assertion failed

### ISSUE THREAD

**Issue by Freequilibrium** [seqan/seqan#2424]
I try to simulate illumina short read from my own fasta but i get this
`mason_simulator -n 10000 -ir Final_FASTA.fasta --illumina-read-length 150 -o test.3.fastq`

> MASON SIMULATOR

>===============

> ____INITIALIZING______________________________________________________________

Opening reference and variants file ... OK
Initializing fragment-to-contig distribution ... OK
Initializing simulation threads ... OK
Opening output file 00.FASTQ/99.SimData/test.3.fastq ... OK

> ____READ SIMULATION___________________________________________________________

Distributing fragments to 6235 contigs (1 haplotypes each) .../home/osboxes/seqan/apps/mason2/external_split_merge.cpp:109 Assertion failed : files[i]->good() should be true but was 0

stack trace:
  0                      [0x41022c]
  1                      [0x4e3b7e]
  2                      [0x42a0fa]
  3                      [0x429150]
  4                      [0x40e728]
  5                      [0x5e063b]
  6                      [0x402901]

Aborted (core dumped)

>======

how do I correct this ?

thank you

**Comment by smehringer** [comment]
Hi @Freequilibrium,

I am not familiar with mason so this is just a guess:

From the assertion, it looks like some temporary files cannot be found. 
* Are you working on Linux or Windows?
* on a single computer or on a cluster?
* Are you using one of our packages or did you compile mason from source?

For once, you should make sure that you have write access in your temporary directory.

**Comment by Freequilibrium** [comment]
Thank You for Your response

I run simulator on my computer , so I'm sure i have full access

os
NAME="Linux Mint"
VERSION="19 (Tara)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19"

and  i installed mason by bioconda
(suppose to be whole mason?)

Thank you

**Comment by eseiler** [comment]
Hello,

can you try running `ulimit -n`?
This shows the maximum number of open files and I suspect it to be set to `1024` or similar.

If so, you can set it to a new limit (e.g. 8192) by running `ulimit -n 8192` and try running mason again?

I think mason2 is storing the contigs externally (=hard disk instead of memory). Since it has `6235` contigs and the limit is, e.g., `1024`, most of the file handles will be closed by the OS and the assertion is thrown.

**Comment by Freequilibrium** [comment]
Thank You @eseiler !!!
This Problem is solved !!
