### ISSUE TITLE
runtime_error: Illumina read is too long

### ISSUE THREAD

**Issue by Freequilibrium** [seqan/seqan#2425]
I have a question about short read simulation
I'm not simulate organism but a sequence library which are all 170bp
when I try to simulate fastq, i get a massage that "Illumina read is too long"
then I try do decrease read length to 50, still didn't work (actually I hope to simulate 100~150bp)

`mason_simulator -n 10000 -ir sim_Final_FASTA_3U.fasta --illumina-read-length 50 -o test.3.fastq`

MASON SIMULATOR
===============

____INITIALIZING______________________________________________________________

Opening reference and variants file ... OK
Initializing fragment-to-contig distribution ... OK
Initializing simulation threads ... OK
Opening output file 00.FASTQ/99.SimData/test.3.fastq ... OK

____READ SIMULATION___________________________________________________________

Distributing fragments to 6235 contigs (1 haplotypes each) ... OK

Simulating Reads:
 3M_1_1_chr1_100210692_r_Mut_1 (allele 1) WARNING: Tried 1000 times to sample fragment from contig of size 170.  Giving up.
WARNING: Tried 1000 times to sample fragment from contig of size 170.  Giving up.
WARNING: Tried 1000 times to sample fragment from contig of size 170.  Giving up.
/home/osboxes/seqan/include/seqan/basic/basic_exception.h:363 FAILED!  (Uncaught exception of type std::runtime_error: Illumina read is too long, increase fragment length)

so how do I solve this problem ?

thank you

**Comment by eseiler** [comment]
Hello,

if I understood you correctly, you have sequences of length 170 and you want to simulate reads of length 50?
If so, you need to set `--fragment-mean-size` and `--fragment-size-std-dev` so appropriate values.
The defaults are `300` and `30`, respectively.
So mason tries to create a fragment of length 300 from a sequence of length 170 - that's why the error.

I'm not very experienced with the fragment/library length you would aim for such an experiment; but it must be between `50` and `170`, so maybe `100`?

**Comment by Freequilibrium** [comment]
thank you @eseiler 

that's what i wish to do, 
i'm not sure how to set the parameter right to reach my goal,
so i randomly select a `50` ,  actually i hope final read should be `150 `

i simply try your suggestion `--fragment-mean-size 100` and it work for synthesize fragment

  3P_1_7_chr12_4917583_f_Mut_1 (allele 1) .. (2 fragments) OK
  3P_1_7_chr12_4917583_f_Ref_1 (allele 1) . (0 fragments) OK
  3M_1_7_chr10_53821299_r_Mut_1 (allele 1) .. (2 fragments) OK
  3M_1_7_chr10_53821299_r_Ref_1 (allele 1) .. (5 fragments) OK
  Done simulating reads.

Joining temporary files .../home/osboxes/seqan/apps/mason2/external_split_merge.cpp:109 Assertion failed : files[i]->good() should be true but was 0

stack trace:
  0                      [0x41022c]
  1                      [0x4e3b7e]


and then....fail on joining temporary files, so i don't really know the result

any suggestion to help me solve this problem?
(sorry for so many problem)

thank you

**Comment by eseiler** [comment]
Hey,

this looks like the first error, can you confirm that `ulimit -n` is high enough (mason should report the number of generated contigs somewhere). 
You can also just set it to a very high number, e.g. `ulimit -n  30000` and try again.

**Comment by Freequilibrium** [comment]
Thank you @eseiler 

I also notice that this problem is same my previous one, 
but i don't know if there is a maximum number in this parameter
according to your massage, it seems like there is no limit?
so i try `ulimit -n 204800` and it works

Thank Your again @eseiler 

Now I can start try change others parameter
