### ISSUE TITLE
maron simulator  --fragment-size-model uniform

### ISSUE THREAD

**Issue by Freequilibrium** [seqan/seqan#2426]
one more question, 
as i mention earlier, our library sequence are all 170bp length
and i want to simulate 150bp read ( which is same with read we got from illumina HiSeq)

although it worked when i set `--fragment-mean-length 170` 
but maximum `--illumina-read-length` can only be set to `113`

so i'm thinking perhaps i can reach this goal by make every fragment "exactly same length 150bp"
and then all these fragment can convert to 150bp reads

then i try this
`mason_simulator -n 100 -ir temp.3.fa --fragment-size-model uniform --fragment-max-size 150 --fragment-min-size 150 --seq-strands forward  -o test.3.fastq`

and illumina read too long again

3M_1_1_chr1_100210692_r_Mut_1 (allele 1) /home/osboxes/seqan/include/seqan/basic/basic_exception.h:363 FAILED!  (Uncaught exception of type std::runtime_error: Illumina read is too long, increase fragment length)

so, can this goal be reached?

i try to calculate maximum length, seem like maximum read length has to be  smaller than 66% longest fragment length (mean + 3sd) ?

thank you

**Comment by Freequilibrium** [comment]
well, i think extend by my library by using adapter sequence possibly is the easiest
way to solve this problem (and "trim" them before use)

thank you very much
and sorry for annoying

**Comment by smehringer** [comment]
No worries :) Questions are always welcome.

Your solution seems adequate since we canot easily drop this restriction on mason.
