### ISSUE TITLE
Errors with tutorial on reading BAM files - does not compile

### ISSUE THREAD

**Issue by aleighbrown** [seqan/seqan#2427]
Have copy pasted exactly the tutorial on reading BAM files

https://seqan.readthedocs.io/en/latest/Tutorial/InputOutput/SamAndBamIO.html#accessing-the-records-tags

Have only changed the files of the demo bams to one on my machine

`g++ --std=c++14 testseqanbam.cpp -o modify_string
testseqanbam.cpp:22:12: error: no member named 'BamIndex' in namespace 'seqan'
    seqan::BamIndex<Bai> baiIndex;
    ~~~~~~~^
testseqanbam.cpp:22:21: error: use of undeclared identifier 'Bai'
    seqan::BamIndex<Bai> baiIndex;
                    ^
testseqanbam.cpp:22:26: error: use of undeclared identifier 'baiIndex'
    seqan::BamIndex<Bai> baiIndex;
                         ^
testseqanbam.cpp:23:15: error: use of undeclared identifier 'baiIndex'
    if (!open(baiIndex, toCString(baiFileName)))
              ^
testseqanbam.cpp:53:69: error: use of undeclared identifier 'baiIndex'
    if (!jumpToRegion(inFile, hasAlignments, rID, beginPos, endPos, baiIndex))
                                                                    ^
5 errors generated.
`

**Comment by smehringer** [comment]
Hi @aleighbrown,

The `BamIndex` is only available if you have the zlib installed and linked when building with SeqAn.
Make sure you have the zlib installed and then add the following to you g++ call:
`-lz` (which links to the zlib library) and `-DSEQAN_HAS_ZLIB=1` (which enables zlib support).

If you would switch to a cmake based project this would be detected and set automatically btw.

Are you new to SeqAn? Note that we are only supporting major bug fixes in seqan 2.x and most of our resources are going into our new library version [seqan 3.x](https://github.com/seqan/seqan3). Unfortunately, we are far from feature complete but we encourage everyone starting on SeqAn to use the new library. You can have a look at our [tutorials](http://docs.seqan.de/seqan/3-master-user/tutorial_alignment_file.html) for SeqAn 3.

**Comment by aleighbrown** [comment]
"are you new to seqan" lol yep. Yep, since I have nothing deeply into seqan I'll switch over now

compilling with the provided g++ didn't work on my machine, final fix was
```clang++ --std=c++14 -I/usr/local/include/ -DSEQAN_HAS_ZLIB testseqanbam.cpp -o modify_string -lz
```
