### ISSUE TITLE
Efficiency of vectorization in local alignment

### ISSUE THREAD

**Issue by roguzsel** [seqan/seqan#2429]
Hi,

I am trying to use the parallel interface in the develop branch. Specifically, I am trying to get some improvement in my local alignments by using vectorization. However, my alignments run at the same speed whether I switch on or off the vectorization.

```c++
#include <iostream>
#include <seqan/align_parallel.h>
#include <seqan/stream.h>

int main()
{
    using T_Sequence = seqan::String<seqan::AminoAcid>;
    using T_ThreadModel = seqan::Serial;
    using T_VectorSpec = seqan::Vectorial;
    using T_ExecPolicy = seqan::ExecutionPolicy<T_ThreadModel, T_VectorSpec>;

    T_Sequence seqH = "ddsrytkfltqhhdakpkgrddrycermmkrrsltspckdvntfihgnksnika"
        "icgangspyrenlrmskspfqvttckhtggsprppcqyrasagfrhvviacenglpvhfdesff"
        "ddsrytkfltqhhdakpkgrddrycermmkrrsltspckdvntfihgnksnika"
        "icgangspyrenlrmskspfqvttckhtggsprppcqyrasagfrhvviacenglpvhfdesff"
        "ddsrytkfltqhhdakpkgrddrycermmkrrsltspckdvntfihgnksnika"
        "icgangspyrenlrmskspfqvttckhtggsprppcqyrasagfrhvviacenglpvhfdesff"
        "ddsrytkfltqhhdakpkgrddrycermmkrrsltspckdvntfihgnksnika"
        "icgangspyrenlrmskspfqvttckhtggsprppcqyrasagfrhvviacenglpvhfdesff"
        "ddsrytkfltqhhdakpkgrddrycermmkrrsltspckdvntfihgnksnika"
        "icgangspyrenlrmskspfqvttckhtggsprppcqyrasagfrhvviacenglpvhfdesff";


    T_Sequence seqV = "qdrmyqrflrqhvdpdatggndaycnlmmqrrkmtshyckrfntfihediwnir"
        "sicstsniqckngqmnchegvvkvtacretgssrapncryramastrrvviacegnpevpvhfdk"
        "qdrmyqrflrqhvdpdatggndaycnlmmqrrkmtshyckrfntfihediwnir"
        "sicstsniqckngqmnchegvvkvtacretgssrapncryramastrrvviacegnpevpvhfdk"
        "qdrmyqrflrqhvdpdatggndaycnlmmqrrkmtshyckrfntfihediwnir"
        "sicstsniqckngqmnchegvvkvtacretgssrapncryramastrrvviacegnpevpvhfdk"
        "qdrmyqrflrqhvdpdatggndaycnlmmqrrkmtshyckrfntfihediwnir"
        "sicstsniqckngqmnchegvvkvtacretgssrapncryramastrrvviacegnpevpvhfdk"
        "qdrmyqrflrqhvdpdatggndaycnlmmqrrkmtshyckrfntfihediwnir"
        "sicstsniqckngqmnchegvvkvtacretgssrapncryramastrrvviacegnpevpvhfdk"
        "qdrmyqrflrqhvdpdatggndaycnlmmqrrkmtshyckrfntfihediwnir"
        "sicstsniqckngqmnchegvvkvtacretgssrapncryramastrrvviacegnpevpvhfdk";


    seqan::StringSet<seqan::Gaps<T_Sequence>> seqs1;
    seqan::StringSet<seqan::Gaps<T_Sequence>> seqs2;

    int n = 1e4;
    for (size_t i = 0; i < n; ++i)
    {   
        appendValue(seqs1, seqan::Gaps<T_Sequence>(seqH));
        appendValue(seqs2, seqan::Gaps<T_Sequence>(seqV));
    }

    seqan::Blosum62 blosum62(-2, -11);
    T_ExecPolicy execPolicy;

    seqan::String<int16_t> scores =
        localAlignment(execPolicy, seqs1, seqs2, blosum62);
    int32_t tmp = 0;
    for (auto x : scores)
        tmp += x;
    std::cout << tmp << std::endl;

    return EXIT_SUCCESS;
}
```

I compile with: ` g++ -O3 -mavx2 -I../include -std=c++14 test.cpp -o test` on an Intel Haswell CPU, so it should enable vectorization.

I have several issues:

1. The above code that does local alignment, whether the vectorization is turned on or off, takes around 50 seconds.
2. When I run the same program by changing localAlignment to globalAlignment, the unvectorized version takes 45 seconds while the vectorized version takes 8 seconds. So the globalAlignment can actually take advantage of vectorization while the localAlignment cannot. Is this expected? What is the reason behind this?
3. In the local alignment, when I try to use DynamicGaps() as the last parameter to the function call, the vectorized version fails to compile.
4. When I use multiple threads, the execution times goes down expectedly for both the local and the global alignment. But adding vectorization to the local alignment does not improve the execution time (i.e., same problem as in (1) but with multiple threads).

Thanks in advance.

**Comment by rrahn** [comment]
@roguzsel thanks for writing us. I will look into this.

**Comment by rrahn** [comment]
Ok, I thought that was an easy fix, like the wrong branch is taken or something, but I must admit I am not entirely sure what's going on. The generated code contains the proper avx2 instructions but is in fact 8 times slower than the sequential version. Hence you see the same runtimes. If you compute instead only the score everything works as expected. Do you need the alignments at the moment?
Otherwise using `localAlignmentScore` will add the expected performance improvement. Note that you have to adapt the sequence collections to not use gap structures. 

In the mean time I will spent more time profiling the performance differences.

**Comment by rrahn** [comment]
Well, the huge difference between gloabal and local is kind of strange. So I expect some bad memory layout which is kind of related to the local alignment. I'll look into it.

**Comment by rrahn** [comment]
@roguzsel I fixed the issue in #2431. Can you check this out and test if this works in your regular case?

**Comment by roguzsel** [comment]
I checked the develop branch again and it does not seem to change anything. The interesting thing is that, I also compiled the code in the below repo
https://github.com/rrahn/align_bench

and then put 500 of the sequences in the above example in two distinct files and fed them into `align_bench_seq` and `align_bench_seq_trace` with and without the -v flag. My runtimes are as follows:

`./bin/align_bench_seq -a aa -d local --alignment-mode pair synt01.fa synt02.fa`: 56.1895 sec
`./bin/align_bench_seq -a aa -d local --alignment-mode pair synt01.fa synt02.fa -v` -> 6.10126 sec
`./bin/align_bench_seq_trace -a aa -d local --alignment-mode pair synt01.fa synt02.fa` -> 54.697 sec
`./bin/align_bench_seq_trace -a aa -d local --alignment-mode pair synt01.fa synt02.fa -v` -> 17.653 sec

So it seems to be utilizing the vectorization. There is something strange going on here. I made sure up to a point that the example code above and the sequential alignment in the `align_bench` repo follow the same path. These sequential binaries in the `align_bench` repo seems to be making the same function calls for the local alignment.

**Comment by rrahn** [comment]
> I checked the develop branch again and it does not seem to change anything. 

That is correct. The PR is not merged yet into develop. You would need to checkout my branch from #2431 to see the effects.

**Comment by roguzsel** [comment]
Thanks, now it is faster. I get 
47.623s with `seqan::ExecutionPolicy<Serial, Serial>`
10.447s with `seqan::ExecutionPolicy<Serial, Vectorial>`
6.685s with `seqan::ExecutionPolicy<Parallel, Serial>` (8 threads) 
1.853s with `seqan::ExecutionPolicy<Parallel, Vectorial>` (8 threads)

Another question though, why do these runtimes get worse when I call localAlignmentScore in the above code? I only change the call to localAlignmentScore and it is substantially slower. I got
3m51.115s with `seqan::ExecutionPolicy<Serial, Serial>`
when I call the score version of local alignment.

**Comment by rrahn** [comment]
> Thanks, now it is faster. I get

Great!

>Another question though, why do these runtimes get worse when I call localAlignmentScore in the above code? I only change the call to localAlignmentScore and it is substantially slower.

Mhmm, not sure entirely. Can you try if chaning the following lines to construct the sets also lead to the same problem?

```cpp
    seqan::StringSet<T_Sequence> seqs1;
    seqan::StringSet<T_Sequence> seqs2;

    int n = 1e4;
    for (size_t i = 0; i < n; ++i)
    {   
        appendValue(seqs1, seqH);
        appendValue(seqs2, seqV);
    }
```

**Comment by roguzsel** [comment]
Yes that did it. Now it is faster than the alignment with trace back.

Thanks!

**Comment by rrahn** [comment]
This is now in develop. Please let us know if there is anything else.
