### ISSUE TITLE
character conversion to dna4 is misbehaving

### ISSUE THREAD

**Issue by alphahmed** [seqan/seqan#2432]
When using `assign_char_to` and `assign_char` to assign a char to dna4, the normal behavior should result in implicit conversion of any character other than 'C', 'G', 'T' into 'A'; however, it is not really behaving as expected for all characters.

For example, the 'S' character is converted into 'C'... NOT 'A'

**Comment by marehr** [comment]
Closing this, because the correct repository would be: https://github.com/seqan/seqan3/issues/1864
