### ISSUE TITLE
Latest RazerS build fails, new gcc version not accepted

### ISSUE THREAD

**Issue by jbsysadmin** [seqan/seqan#2451]
Greetings.

How does one get around this error below? Build command was: 

cmake3 .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS:STRING="-march=native -std=c++14." The cmake3 version, 3.14.6. The gcc version, 9.3.

```
- Initializing SeqAn Build System...
-- Scanning dependencies once in DEVELOP mode...
-- Boost version: 1.68.0
CMake Warning (dev) at util/cmake/seqan-config.cmake:157 (message):
  GCC version (4.8.5) should be at least 4.9! Anything below is untested.
Call Stack (most recent call first):
  util/cmake/SeqAnBuildSystem.cmake:360 (find_package)
  CMakeLists.txt:123 (seqan_build_system_init)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at util/cmake/seqan-config.cmake:202 (message):
  SeqAn requires C++14 since v2.2.0, but your compiler does not support it.
Call Stack (most recent call first):
  util/cmake/SeqAnBuildSystem.cmake:360 (find_package)
  CMakeLists.txt:123 (seqan_build_system_init)

-- Configuring incomplete, errors occurred!
```

**Comment by rrahn** [comment]
Hi there, 
it seems as if you didn't configure with g++9. I guess, gcc 4.8 is your default compiler on your system? Then you should be able to add `-DCMAKE_CXX_COMPILER=path/to/g++-9`, or simply `-DCMAKE_CXX_COMPILER=g++-9`, if the binary can be found in your path environment, to your cmake command. Make sure you deleted the CMakeCache file before rerunning cmake.

**Comment by jbsysadmin** [comment]
Thanks! Build succeeded. Please close ticket.

**Comment by rrahn** [comment]
Sure, I am glad it helped.
cheers
