### ISSUE TITLE
mason_genome ignores --seed option

### ISSUE THREAD

**Issue by Felix-Droop** [seqan/seqan#2452]
The program `mason_genome` has a command line option `--seed` to set the seed for the internal random generator. Extraction from the help:
```
-s, --seed INTEGER
      The seed to use for the random number generator. Default: 0.
```
Internally, this option is ignored and the seed is set to a hardcoded value instead.
From [simulate_genome.cpp](https://github.com/seqan/seqan/blob/master/apps/mason2/simulate_genome.cpp), lines 48-51:
```cpp
// Initialize std generator and distribution
std::mt19937 generator(42); // seed 100
std::uniform_real_distribution<double> distribution(0, 1);
auto randomNumber = std::bind ( distribution, generator );
```
The program produces the exact same sequences everytime it is called. The `--seed` option is misleading, because a different seed is expected to lead to a different result.

**Comment by smehringer** [comment]
Hi @Felix-Droop,

good catch! Let's see if my fix works, then you can try mason again.

**Comment by marehr** [comment]
@eseiler I think this is fixed, right?

**Comment by eseiler** [comment]
Yes, #2454 promised to close this issue, but did not :(
