### ISSUE TITLE
Incorrect number reported in "XS:i:", when using mason_simulate to simulate variants and reads.

### ISSUE THREAD

**Issue by Lilu-guo** [seqan/seqan#2486]
Hi, 
I want to generate a series of variants with GRCh38.fa, following the command:
```
mason_variator -ir ../genome.fa -ov genome.test.vcf
```

Then, I use this variants file and GRCh38.fa to simulate 10k reads, the command is:
```
mason_simulator -ir ../genome.fa -iv genome.test.vcf -n 10000 -o mason_test_10k.fa -oa gold_test_10k.sam
```

I check the sam file, and find "XS:i:" is incorrect. Provide an example:
```
simulated.30    0       8       100774111       255     100M    *       0       0       GGCATGAGCCACTGCGCCTGGCCTCTGTTGCTGATT
TCTAGAAGATTTTTATATGTTAAGGAAATTAATTCCTTGTGTTATACAGTACAAATGCCTTTTT    IHHIHIHHHHHIHIHFIIIIIIIHIIHIIIDIHIIBGIIIGIIIICHIICI@F@II
;IAIIEII@AIGIII?IIFEI@DH6HIIDIII@IIIDBAIGIDI    NM:i:1  MD:Z:94A5       oR:Z:8  oH:i:1  oP:i:100782921  oS:A:F  XE:i:1  XS:i:1  XI:i:0
```

Actually, there is only one sequcing error (XE:i:1), no snp (but XS:i:1 reported). And i  check the vcf file generated, there is no snp covering thoes interval chr8  100774111:100774211. What is the reason for this issue? is there a bug?

BTW, I also find the "XS:i:" is right only in the first contig, i.e. chr1. Other contig or chromesone is incorrect. Maybe this phenomenon can help you to find the issue source. Look forward to your reply, Thanks.

**Comment by SGSSGene** [comment]
I think there is a misunderstanding on how mason simulator works.
mason simulator takes the genome (with applied vcf data if given) and then simulates reads. The gold_test_10k.sam gives you the ground truth (normally this woudn't be known).

Depending on what you want to do, you might want to set `--illumina-prob-insert`, `----illumina-prob-deletion` and `--illumina-prob-mismatch` to `0`. This will create reads with no errors.

**Comment by Lilu-guo** [comment]
Yes, using --illumina-prob-* parameters can set the probability of SNP and INDEL.
The questions is I need a certain vcf file to record the variations added (guarantee variations position is known), So I use "mason_variator" to generate vcf file firstly, and then simulate reads according to the known vcf data.
However, the gold_sam file is inconsist with vcf_file in the field of "XS:i:". You can see detail in the example, happy to discuss more.

**Comment by SGSSGene** [comment]
From my understanding you have a genome and a vcf file.
You would like to create reads from your genome, that follow the error occurrences as described in the vcf. Additional to the simulated reads, you would like to have a sam file describing how these reads differ between the genome and the vcf file?

Could explain again what you are trying to do? I am slightly confused :-)

**Comment by Lilu-guo** [comment]
Okey, I would like to explain again.
1. The vcf file is generated by Mason with command "mason_variator -ir ../genome.fa -ov genome.test.vcf".
2. Using above vcf file as given vcf data, to generate reads. In this way, I can know where SNP or INDEL occurs clearly.
3. At last, I check the gold_sam and find the "XS:i:" is not correctly reporting the SNP numbers in the read. Because I have the pregenerated vcf file and genome, I can check the result.

Please see the example again, it shows MD:Z:94A5, but give XE:i:1  XS:i:1.
My confusion is there is No SNP covering the interval of this reads by checking vcf file.

**Comment by SGSSGene** [comment]
The generated gold_sam file does not annotate the errors between genome.fa and genome.test.vcf.
The parameters in mason are slightly confusing here.
Masons output is equalivalent to first calling `cat genome.fa | vcf-consensus genome.test.vcf > genome_somehaplotype.fa`
and than running mason on `genome_somehaplotype.fa`.
mason_simulator introduces new errors that are independent of the vcf file.
Your use case doesn't seem to be coverd by mason.

What you could do is:
1. `mason_variator -ir ../genome.fa -ov genome.test.vcf`
2. `mason_simulator --illumina-prob-insertion 0 --illumina-prob-deletion 0 --illumina-prob-mismatch 0 -ir ../genome.fa -iv genome.test.vcf -n 10000 -o mason_test_10k.fa -oa gold_test_10k.sam`
3. # some custom tool, that does a local alignment of gold_test_10k.sam against `genome.fa`

Maybe a tool for the 3. step already exists, I don't know. But the result of the 3. step should give you the data you want.
It might not work if the vcf simulates long sequences of deletions/insertions, because then it wouldn't align at all.

**Comment by Lilu-guo** [comment]
@SGSSGene  Thanks for your patient answer, I got it more clearly.
But still have slight confusion. For the simulator, which location to generate SNP or INDEL, and how to change is known and controlled by itself. So why does the simulator need to do the local alignment to find the gold position, PS: in my mind, the position/location of SNP or INDEL is known before simulation.

**Comment by SGSSGene** [comment]
@Lilu-guo: It is a complicated topic, and the pipelines/workflows arn't that obvious/easy to understand.

I think it is possible to imagine two different types of simulations:
1. simulation of nature, errors introduced while replication etc, This is what `mason_variator` does. This includes not only substituting, adding and removing single bases, but also duplicating whole regions of a sequence. Changes like this are tracked
   in files like .vcf/.bcf.
2. simulation of sequencing machines. Sequencing machine also introduce errors which usually are only substituting, adding or removing single bases. This is what `mason_simulator` does. These changes are much simpler and are represented by file like .sam/.bam. When running this simulation with `--*-prob-*=0` it is like having a perfect sequencing machine.

I think one confusing point is that `mason_simulator` is taking a genome plus a .vcf file. But this is only a shortcut to not have to call `vcf-consensus` to merge the two files.

The gold standard is meant to be used to use with [Rabema](https://www.seqan.de/apps/rabema.html) which allows evaluating the quality of a read mapper. So exactly to measure how well the files from a sequencing machine are being used and mapped back to a genome.

**Comment by Lilu-guo** [comment]
Thanks again; I have understood more better with your help.

**Comment by SGSSGene** [comment]
Great to hear :-)
If you have any other question, don't hesitate, and ask :+1:
