### ISSUE TITLE
Question: is it possible to create a psl like output from razers3 ?

### ISSUE THREAD

**Issue by Aphrix** [seqan/seqan#2489]
Hello,

I want to use L_RNA_scaffolder that requires a psl file of the alignment that I should obtain by using BLAT. BLAT being not under active development anymore (and not working for me), and links to razers3, I wanted to know is it's possible to generate a psl file using razers3. 

Thank you for your help!

**Comment by eseiler** [comment]
Hey @Aphrix,

razers3 does not support PSL:
https://github.com/seqan/seqan/blob/8c631c003de3ec96b5c12a7b1a1fd159c918dc14/apps/razers3/README#L377-L384

However, there is [sam2psl.py](https://github.com/ndaniel/fusioncatcher/blob/master/bin/sam2psl.py) for converting SAM to PSL. You can try using this tool with any readmapper you like (in SeqAn we have razers3 and yara).

**Comment by Aphrix** [comment]
Thank you so much for your quick answer! I will try this.
