### ISSUE TITLE
README.md with dead links

### ISSUE THREAD

**Issue by Austernpilz** [seqan/seqan#2499]
die ersten 4 Links sind dead.
Namely:
[Getting Started](https://seqan.readthedocs.io/en/main/Tutorial/GettingStarted)
[Manual](https://seqan.readthedocs.io/en/main)
[Tutorial](https://seqan.readthedocs.io/en/main/index.html#tutorials)
[How-Tos](https://seqan.readthedocs.io/en/main/Tutorial/HowTo)

![grafik](https://github.com/seqan/seqan/assets/87067941/358b7fa7-6416-4b7f-9110-eff772d40287)

**Comment by eseiler** [comment]
readthedocs now builds the main branch :)
