### ISSUE TITLE
Cannot use on cygwin

### ISSUE THREAD

**Issue by gusevfe** [seqan/seqan#250]
Hi. Thanks for your great work on seqan.

I am trying to use seqan on cygwin, but everythings fails to build because seqan/system.h includes aio.h, which is not available on cygwin.

Is there any way to make it work? Probably some macro to disable asynchronous IO?

Thanks in advance.

**Comment by cozaar6** [comment]
Hi, would the precompiled razers3 work for cygwin?

**Comment by holtgrewe** [comment]
@cozaar6 It should. We recommend using Visual Studio on Windows. Please open a new issue if this fails.
