### ISSUE TITLE
mason_simulator error: (Uncaught exception of type MasonIOException: Could not build FAI index.)

### ISSUE THREAD

**Issue by cwatt** [seqan/seqan#2505]
Hello,

I'm trying to simulate paired-end reads from a genome sequence, but when I run mason_simulator like so:
```
mason_simulator -ir genome.fa -o sim_1.fq -or sim_2.fq -oa sim_golden.sam -n 10 --fragment-mean-size 335 --fragment-size-std-dev 130 --seq-technology illumina --illumina-read-length 150 --illumina-prob-insert 0 --illumina-prob-deletion 0 --illumina-prob-mismatch 0 --illumina-quality-mean-begin 40 --illumina-quality-mean-end 40 --illumina-quality-stddev-begin 0 --illumina-quality-stddev-end 0 --seed 10 --num-threads 30
```
I receive the following error:
```
MASON SIMULATOR
===============

____INITIALIZING______________________________________________________________

Opening reference and variants file .../home/osboxes/seqan/include/seqan/basic/basic_exception.h:363 FAILED!  (Uncaught exception of type MasonIOException: Could not build FAI index.)

stack trace:
  0                      [0x4c401d]
  1                      [0x4c96a6]
  2                      [0x4c96f1]
  3                      [0x4d4c38]
  4                      [0x4bbfbf]
  5                      [0x468030]
  6                      [0x400b42]
  7                      [0x53c62b]
  8                      [0x405f51]

Aborted (core dumped)
```
This error also occurs when I try to run the example code from README.mason_simulator on the example data provided with mason:
```
mason_simulator -ir adeno_virus.fa -n 1000 --illumina-read-length 150 -o reads.fa -oa alignments.sam
```
I've already tried increasing `ulimit` to the maximum possible (1048576 in my case) which I've seen as a solution in other issues but did not make a difference here. Any insight you have into what might be causing this would be appreciated!

Version information:
```
mason_simulator version: 2.0.9 [e165baf]
SeqAn version: 2.4.0
```

**Comment by SGSSGene** [comment]
Hey @cwatt 

This is a very unclear error message :sweat_smile: . This should happen if the file 'genome.fa' is not readable or simply not at the specified location. The path to `genome.fa` must be relative from the current path (or an absolute path).
Could you please double check this.

If this doesn't help, where did you get the `mason_simulator` executable from? Did you compile it yourself?
And what is the origin of `adeno_virus.fa`? From the repository?

**Comment by eseiler** [comment]
It also works for me for 2.4.0.

However, if I remove write permissions for the directory containing `adeno_virus.fa`, I get the same exception as described.

Can you double-check that you have write permissions in whatever directory your reference is in?
mason wants to write the fasta index in the same directory the reference is in. So, if your reference is in, e.g., `reference/adeno_virus.fa`, it will create `reference/adeno_virus.fa.fai` and you will need write permissions in `reference` for that.

**Comment by eseiler** [comment]
> This should happen if the file 'genome.fa' is not readable or simply not at the specified location. The path to `genome.fa` must be relative from the current path (or an absolute path). Could you please double check this.

After some more investigation, this seems the only way to trigger that error message.
Another way to check is:

Let's say your command is
```bash
mason_simulator -ir adeno_virus.fa -n 1000 --illumina-read-length 150 -o reads.fa -oa alignments.sam
```

Running
```bash
ls adeno_virus.fa
```
should then just print the filename.
If the path is not valid, the output will be something like
```
ls: cannot access 'adeno_virus.fa': No such file or directory
```

**Comment by cwatt** [comment]
Hello, thank you for your quick replies!

> If this doesn't help, where did you get the mason_simulator executable from? Did you compile it yourself?
And what is the origin of adeno_virus.fa? From the repository?

[Here's](http://packages.seqan.de/mason2/) where I got the executable. The adeno_virus.fa file came with the download in a directory called examples.

> This should happen if the file 'genome.fa' is not readable or simply not at the specified location. The path to genome.fa must be relative from the current path (or an absolute path). Could you please double check this.

Yes, you're right! I can trigger this error if the file is in a directory I don't have permissions to write in or if the file doesn't exist in the path specified. I'm doing my analyses on a cloud computing platform, and the permissions were tripping me up in this case. Glad this had a simple solution!
