### ISSUE TITLE
(Uncaught exception of type std::runtime_error: Illumina read is too long, increase fragment length)

### ISSUE THREAD

**Issue by mariaelf97** [seqan/seqan#2516]
Hello, I am trying to simulate reads from a multi fasta file containing a config with length about 1000 bps but I get the following error.
Could you explain what the issue is?

` mason_simulator -ir ~/GCA_014899445.1_amplicon_0.fasta -n 20000 -o read_1.fq -or read_2.fq --fragment-mean-size 450 --fragment-size-std-dev 50 --illumina-read-length 500 --fragment-min-size 400 --fragment-max-size 500`

error:

WARNING: Tried 1000 times to sample fragment from contig of size 1019.  Giving up.
(Uncaught exception of type std::runtime_error: Illumina read is too long, increase fragment length)

This is the fasta file for your reference 
`
>CP041800.1_amplicon_0
CCGATCCCGTGCGCAGAAACTGCAGCATCATCGCCGGCAACTCCCAGTACGCCCGCAGTGCGGCAATCTGCCACTCGCCGGTAACCGGTCGTAGGTCATAGCGTAGGAAGGCGGGAATGAACACCGTCACAGCCGAGTCCATCGCGACCTCGAGTTCGAGATCGCGCAGCACCACCGTGCCGGAGACGATATCCAGATCGCGATGGAACGTGATATCCCGCGGCCCGATGAAGGTGTCGTAGAAGCGGCCGATGGCCTCATGCCCCACCTGCGGCTGCGAACCCACCGGGTCTTCGACCCGCGCGTCACCGGTGAACAACCCGACCCAGCCGGCGCGGTCGTGCGCGGCGGCCGCTTGCGGCGAGCGCTCCACCGCCGCCAACAGTTCATCCCGGTTCGGCGGTGCCATCAGGAGCTGCAAACCAACTCGACGCTGGCGGTGCGCATCTCCTCCAGCGCGGCGACGGTGGTATCGGCCGACACACCCGCTGTCAGGTCCACCAGCACCCTGGTGGCCAAGCCATTGCGTACCGCGTCCTCGGCCGTCTGGCGCACACAATGATCGGTGGCAATACCGACCACATCGACCTCATCGACGCCGCGTTGCCGCAGCCAATTCAGCAGTGGCGTGCCGTTCTCGTCGACTCCTTCGAAGCCGCTGTACGCTCCGGTGTAGGCACCCTTGTAGAACACCGCCTCGATTGCCGACGTGTCCAGACTGGGATGGAAGTCCGCGCCGGGAGTACCGCTGACGCAATGCGGTGGCCACGACGAGGAATAGTCCGGTGTGCCGGAGAAGTGGTCACCCGGGTCGATGTGGAAGTCCTTGGTTGCCACGACGTGATGGTAGTCCGCCGCTTCGGCCAGGTAGTCGCTGATGGCGCGGGCCAGCGCGGCGCCACCGGTTACCGCCAGCGAGCCACCCTCGCAGAAGTCGTTCTGCACGTCGACGATGATCAACGCCCGCATACGTCCACCATACGTTCGGGCGACTGCCCGGGCAGTTTGCCTACCGACGC

`

**Comment by smehringer** [comment]
Hi @mariaelf97,

thanks for reaching out. The error message basically tells you whats going wrong.

You are trying to simulate paired-end sequencing data with reads of length 500 but your fragment size is `<= 500`. 

See this:
![image](https://github.com/seqan/seqan/assets/7955878/934f7841-163d-477f-aece-92428a8fd459)
(Source https://images.app.goo.gl/Zm4aDLFdZGdhaSC98)

Or this:
![image](https://github.com/seqan/seqan/assets/7955878/f752c7a2-39f9-436b-99bf-b26a79845a0d)
(Source https://images.app.goo.gl/qZrQ8njVfYhiuvcb7)

Not sure myself if mason_simulator is including Adaptor length but you should still get the idea.

You need to increase your fragment size or lower the read length.

Best,
Svenja

**Comment by rrahn** [comment]
Hi @mariaelf97 if you feel this problem is not resolved please reopen this issue any time.
For now I would like to close it.
