### ISSUE TITLE
Job getting killed without a error message

### ISSUE THREAD

**Issue by vinegang** [seqan/seqan#2518]
I am running razer3 using the docker image fred2-optitype-release-v1.3.1.img from [docker hub](https://hub.docker.com/layers/fred2/optitype/release-v1.3.1/images/sha256-f36366701c91dd10c30801fa323a84581db67ebf1dbbc653c491a6ab617276e3?context=explore)
Here is my command line. I provided 200G mem, only 180G has been used and the job got killed. Can someone help me debug this?
Any help is appreciated. Thanks!

```
Singularity> razers3 -i 95 -tc 14  -m 1 -dr 0 -vv -o filtered_Sample1_HFT7YDSX3_R1.bam /usr/local/bin/OptiType/data/hla_reference_dna.fasta Sample1_HFT7YDSX3_R1.fastq
___SETTINGS____________
Genome file:                     	/usr/local/bin/OptiType/data/hla_reference_dna.fasta
Read file:                       	Sample1_HFT7YDSX3_R1.fastq
Compute forward matches:         	YES
Compute reverse matches:         	YES
Allow Indels:                    	YES
Error rate:                      	0.05
Pigeonhole mode with overlap:    	0
Shape:                           	11111111111
Repeat threshold:                	1000
Overabundance threshold:         	1
Program PID:                     	2912200

Killed

```

**Comment by SGSSGene** [comment]
hi Vinegang

1. any chance you can try to run it with mofe memory?
2. Any chance you can make the data (fastq/fasta files) available to us?

How long was it running before crashing?

**Comment by rrahn** [comment]
Hi, my guess is that the docker container has not enough disk space. 
Razers3 is trying to build the index using an algorithm that uses secondary memory.
The intermediate data is by default stored in the public TMP directory of the system which has in most scenarios enough space. However, this might not be the case with your docker container. 

Maybe it suffices to map the tmp directory of your docker container to the tmp directory of the host system, assuming that the host has enough disk space there (e.g. also check that if the host is an administered compute server that tmp has large enough quota).

**Comment by rrahn** [comment]
@vinegang I assume your problem could be fixed, so I am closing this ticket for now. Please feel free to reopen it any time if something still doesn't work out as expected. Thank you.
