### ISSUE TITLE
Add Affix Index Structure

### ISSUE THREAD

**Issue by CVroland** [seqan/seqan#262]
Dear SeqAn team

First, I want to thank you for this excellent library.

As part of an implementation of an approximate string matching algorithm by “Seed-And -Extend”, I am looking for an affix-index structure. Such structures should be great for extending a pattern in both ways.

In a naive solution, I could use 2 FM-Indexes, one of the text and the other on the reversed text . First of all, I would iterate my seed in the “backward” FM-Index and then with an iterator on each index, I would extend in a direction or the other. However, at each change of way, it would be necessary to iterate the entire new pattern in the opposite substring index.

This approach does not seem very efficient compared to what Schnattinger et al proposed in their article “Bidirectional Search in a String with Wavelet Trees”(2010). Indeed, at each iteration in a BWT, they update interval in the opposite BWT with a time complexity of O(log(σ)).

Moreover, the naive solution implies that we have two FibreText loaded in memory, which would be quite space consuming.

I think it would be a great opportunity to be able to use an affix index in SeqAn. I unfortunately do not have sufficient technical kwonledges of SeqAn and template programming to be able to implement new structures. I'm wondering if you're planning to implement (or maybe already implementing!) such a structure in the SeqAn library.

Best regards,

Christophe Vroland

**Comment by esiragusa** [comment]
Coming with #1071.

**Comment by cpockrandt** [comment]
I think we can close this issue.

Since last year we have a bidirectional FM index (already taking care of synchronizing its two indices) and since Seqan 2.2.0 an even faster bidirectional FM index with constant time running time. I don't see any need to implement other indices such as affix arrays since they take up much more space and will probably not be faster.
