### ISSUE TITLE
Scoring algorithm different from literature

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#355]
I'd like to revive http://trac.seqan.de/ticket/1091

I have some code in the pipeline that works around this, but I would have to add publicly documented functions that explain our behaviour. And I don't see why we shouldn't just change it.

**Comment by h-2** [comment]
@rrahn @marehr I would like to get this right from the beginning in SeqAn3!

**Comment by smehringer** [comment]
@marehr Is this being considered? I don't know if you are working on affine gap costs but this issue should maybe be referenced somewhere?

**Comment by rrahn** [comment]
This has already been resolved in SeqAn3
