### ISSUE TITLE
MMap String cannot open read-only files.

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#507]
Originally from Enrico on Trac.

This is a major issue encountered many times by many users - including ourselves. There should be a way to have read-only MMap Strings.

We could have specs Input, Output and Bidirectional, exposing consistent interfaces: e.g. value assignment should be provided only by Output capable specs. Then, `String<TValue, MMap<Input> >` would call mmap with PROT_READ only.

**Comment by h-2** [comment]
@esiragusa Could you have a look at this? I have people complaining that they offer Lambda indexes in ro-group directories to their users, but these shouldn't be required to be writeable.
Thanks!

**Comment by h-2** [comment]
fixed
