### ISSUE TITLE
Clean up MaximumValue and MinimumValue metafunctions

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#514]
Originally from Dave on Trac

The metafunction degradated over time and became boiler-plated. The following steps should be taken to cut and simplify the code:

remove the indermediate Min/MaxValue_ struct
replace Min/Max..Double and ..Short by specializing Min/MaxValue for short/double
remove the cumbersome TParent default 2nd template argument and use the default directly as base class

**Comment by h-2** [comment]
We can now use numeric_limits in develop! @smehringer, ca you make our (Meta)-functions call these: http://en.cppreference.com/w/cpp/types/numeric_limits/max

**Comment by rrahn** [comment]
@xenigmax I assigned this to you in case you like some other task than dox stuff :smile:

**Comment by xenigmax** [comment]
All right. Thank you for giving me a chance to work on "!dox issues". :clap:
However, I have a lecture on Monday (AlDaBi). 
If you think this must be done urgently, I recommand you to assign this to others. :smile: 
But thank you.

**Comment by h-2** [comment]
@smehringer will this be fixed with your deprecation PR?

**Comment by smehringer** [comment]
@h-2 I don't think so since I only replaced the usage at specific places to numeric_limits but did not touch the implementation of the meta function.

**Comment by h-2** [comment]
Is part of #1794 now
