### ISSUE TITLE
Inconsistent usage of seqan namespace

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#530]
As of 2013-06-13 the SeqAn / BioStore developers decided to not namespace example in the online documentation.

Namespaces make the code harder to read and understand the essence of the example.

All online documentation examples must be revised.

We should do a global replace from "seqan::" to "" and add "using namespace seqan" after the "#include ...".

**Comment by esiragusa** [comment]
It seems that tutorials were not updated.

Look here please: http://seqan.readthedocs.org/en/develop/Tutorial/Metafunctions.html#type-metafunctions

**Comment by esiragusa** [comment]
Fixed in 552b69c
