### ISSUE TITLE
ArgumentParser Improvements

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#533]
Martin Frith notes that there are some deficiencies with the current state of the argument parser:
1. It requires space between an option and its argument.
2. It doesn't allow "-" as a positional argument.  "-" is often used to
   indicate stdin and stdout.
3. It doesn't seem to allow a list of zero or more positional
   arguments.  (It does allow a list of one or more positional
   arguments.)  It's standard to allow a list of zero or more
   file-names, with zero meaning "read stdin".
4. It doesn't recognize "--" meaning "end of options (http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html).  This is useful to allow negative numbers as positional arguments.
5. It requires argv to be const, whereas, strictly speaking, argv
   should not be const (http://en.wikipedia.org/wiki/Main_function).
   And it's not possible to convert non-const argv to const
   (http://www.parashift.com/c++-faq/constptrptr-conversion.html).
6. (Minor): It's not possible to display a fake default value in the
   help message.  This might be useful if the default value is
   logically -INF, but as an implementation detail is actually INT_MIN.

**Comment by smehringer** [comment]
This feature request will not be included in seqan2 anymore so we can close this issue.
I will check, but the SeqAn3 argument parser already covers all of the above except 6.
