### ISSUE TITLE
Usage of hidden options is not consistent in seqan apps

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#536]
Originally from Stephan on Trac

The argument parser can hide options. This is used in two different ways

To hide developer-only/debug options
To hide advanced options
We should change this to hidden and advanced options. In this way way we could exclude the hidden options for the CTD export and tag the advanced options as advanced in the CTD.

**Comment by esiragusa** [comment]
@h-2 tadaa :tada:

**Comment by h-2** [comment]
Hm, I have worked around it for now, but I will have a look at it again, at a later point.

**Comment by h-2** [comment]
I believe my pull request solves all of these issues. @holtgrewe can you have a look?

**Comment by holtgrewe** [comment]
@h-2 I currently don't have the time to check about this, sorry. I only copied this ticket when shutting down our Trac instance. Close at will.

**Comment by h-2** [comment]
fixed by #1162
