### ISSUE TITLE
Test using SEQAN_PATH_TO_ROOT fail with CMake Ninja generator

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#537]
Originally reported by Stephan on Trac.

Test that use the SEQAN_PATH_TO_ROOT macro fail when seqan is compiled with the ninja generator of cmake. It seems that the returned PATH_TO_ROOT is not valid.

**Comment by temehi** [comment]
I couldn't reproduce the problem.  I checked a couple of tests and SEQAN_PATH_TO_ROOT() returns  the expected value. May be it is already fixed.

**Comment by esiragusa** [comment]
Okay... anyway SEQAN_PATH_TO_ROOT is really embarrassing... :-1:
