### ISSUE TITLE
merge order

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#539]
Originally from Fabian on Trac

I found that the seed merging depends on the order of the merge. For example:

```
SeedSet< int, SimpleSeed,  DefaultNoScore , void > seedset(100, 0);bool 
yep = addSeed(seedset, Seed<int,SimpleSeed>(1, 1, 4),Single());
::std::cout << yep << " " << length(seedset) << " " << 
leftDim0(*begin(seedset)) << "-" << rightDim0(*begin(seedset)) << 
::std::endl;
yep = addSeed(seedset, Seed<int,SimpleSeed>(0, 0, 4), 0, Merge());
::std::cout << yep << " " << length(seedset) << " " << 
leftDim0(*begin(seedset)) << "-" << rightDim0(*begin(seedset)) << 
::std::endl;
```

 
results in:
```
1 1 1-4
0 1 1-4
```

the seed containing a preceding location is not added.
On the other hand adding the seeds in reverse order, i.e.:

```
SeedSet< int, SimpleSeed,  DefaultNoScore , void > seedset(100, 0);bool 
yep = addSeed(seedset, Seed<int,SimpleSeed>(0, 0, 4),Single());
::std::cout << yep << " " << length(seedset) << " " << 
leftDim0(*begin(seedset)) << "-" << rightDim0(*begin(seedset)) << 
::std::endl;
yep = addSeed(seedset, Seed<int,SimpleSeed>(1, 1, 4), 0, Merge());
::std::cout << yep << " " << length(seedset) << " " << 
leftDim0(*begin(seedset)) << "-" << rightDim0(*begin(seedset)) << 
::std::endl;
```

gives what one expects:

```
1 1 0-3
1 1 0-4
```

Is this a feature or a bug? It should be annotated if it is the former.
It would also be nice to have an example for seed merging in demos 
(although I found some in tests).

**Comment by rrahn** [comment]
Ok I think this is a bug, because I don't see any reason, why the order of the seeds should play a role when adding to the SeedSet. 
So if there is no other strong opinion about it @esiragusa? @holtgrewe? I will fix it.

**Comment by rrahn** [comment]
@holtgrewe Where is the code snippet from.
We neither have a SeedSet definition like the one above, nor do we have the interfaces rightDim0 and leftDim0. In the current ```SeedSet<TSeed, Unordered>``` implementation, the added seed can be left or right of an existing one and there is already a test for this.
I close this issue, if you can specify the problem in more detail, then please feel free to reopen it again.

**Comment by esiragusa** [comment]
Maybe that's a very old trac ticket?
