### ISSUE TITLE
Myers Finder's clear() does not work as expected

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#551]
According to documentation the call of clear(finder) resets a finder object to search again from the beginning.

The following code does not follow that description

```
int main()
{
        seqan::String<char> haystack("HEREIAM");
        seqan::String<char> needle1("HERE");
        seqan::String<char> needle2("HERE");
 
        seqan::Finder<seqan::String<char> > finder(haystack);
        seqan::Pattern<seqan::String<char>, seqan::Myers<seqan::FindInfix> > pattern1(needle1);
        seqan::Pattern<seqan::String<char>, seqan::Myers<seqan::FindInfix> > pattern2(needle2);
 
       if(find(finder, pattern1, 0)){
                std::cout << "Found pattern 1\n";
        }
 
        if(seqan::find(finder, pattern2, 0)){
                std::cout << "Found pattern 2 (attempt 1)\n";
        }
 
        seqan::clear(finder);
        if(seqan::find(finder, pattern2, 0)){
                std::cout << "Found pattern 2 (attempt 2)\n";
        }
 
        {
                seqan::Finder<seqan::String<char> > finder(haystack);
                if(seqan::find(finder, pattern2, 0)){
                        std::cout << "Found pattern 2 (attempt 3)\n";
                }
        }
}
```

output:

```
>./tester
Found pattern 1
Found pattern 2 (attempt 3)
```

when replacing the Pattern with an exact hoorspool algorithm the behaviour is as described.

```
#!cpp
Found pattern 1
Found pattern 2 (attempt 2)
Found pattern 2 (attempt 3)
```

**Comment by xenigmax** [comment]
Hmm.. I found this.

"
....**Note that clear(finder) doesn't move the text iterator.** To start the search from the beginning or somewhere else in the text, use #fn()goBegin or #fn()setPosition.
"
- From the API document (http://docs.seqan.de/seqan/develop/class_Finder.html)

If you put "seqan::goBegin(finder);" before "seqan::clear(finder);".
It works as you expected.

```
kjk@giraffe:~/work/seqan/sandbox/fix_838$ ./a.out 
Found pattern 1
Found pattern 2 (attempt 2)
Found pattern 2 (attempt 3)
```
@esiragusa  @holtgrewe 
(1) If you think the document is correct, we can close this issue.
(2) If you wish me to change something, I think we have to consider other finder alternatives as well -which may takes some time. And.. I think I need more clear definition about "clear" in Finder.

```
void clear(finder);

Clear the Finder.
Parameters
finder	The Finder to clear.
```

**Comment by esiragusa** [comment]
@holtgrewe where the dox or the manual says that clear(finder) does also goBegin(finder)? The Horspool demo here http://docs.seqan.de/seqan/develop/demos/find/finder_online.cpp suggests that it doesn't.

@xenigmax it's not clear at all what clear(finder) should do... :scream: 

Anyway, the long term plan is to replace this crappy find module and unify it with the align module.

**Comment by holtgrewe** [comment]
@esiragusa the inconsistency of the finder interface is a long-standing problem that exists and is known for more than 5 years ... @weese might know more

**Comment by esiragusa** [comment]
The documentation is correct - I close the issue as discussed with @xenigmax.
