### ISSUE TITLE
More robust/verbose handling in case of out-of-memory situations.

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#555]
There currently is no robust handling of out-of-memory situations in SeqAn. While such errors are hard to handle on any level, at least the library should expose the errors to the outside.

For example, in string_alloc.h, we should check in _allocateStorage() whether the allocate() calls are successful and at least offer to print error messages if a SEQAN_MEMORY_VERBOSE or so preprocessor symbol is set to 1.

**Comment by esiragusa** [comment]
See std::bad_alloc.
