### ISSUE TITLE
GFF AnnotationTree bug

### ISSUE THREAD

**Issue by cfblaeb** [seqan/seqan#583]
When parsing a NCBI GFF file (I specifically am trying these ftp://ftp.ncbi.nlm.nih.gov/genomes/Cricetulus_griseus/GFF/) using AnnotationTree I noticed that the structure of the tree did not become root-->gene-->mRNA-->exons/cds, but rather root-->gene and root-->mRNA-->exons/cds
The gene and the mRNA have correct parent/id pairs, but if the mRNA line contains a transcript_id then that is used instead of id.
When I remove/rename transcript_id it works correctly.
According to the gff3 specifications, transcript_id should NOT hold any special meaning and only Id should be used in determining parent/child relations. http://www.sequenceontology.org/gff3.shtml

**Comment by esiragusa** [comment]
@cfblaeb This issue should be finally fixed :sweat_smile:
