### ISSUE TITLE
Improve disable-able exceptions in SeqAn

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#634]
If we decide to allow for disabling exceptions completely, here are two possibilities to do this.

In both cases, we need (we already have this) the following macros:

``` c++
#ifdef SEQAN_EXCEPTIONS

#define SEQAN_TRY           try
#define SEQAN_THROW(E)      throw E
#define SEQAN_RETHROW       throw

#else

#define SEQAN_TRY           if (true)
#define SEQAN_THROW(E)      SEQAN_FAIL(#E)
#define SEQAN_RETHROW

#endif // #ifdef SEQAN_EXCEPTIONS
```

The question is how to handle catching.
@esiragusa and @holtgrewe would prefer the first way.
## Define Handling Macros

Define `SEQAN_CATCH` as follows (maybe only one variant not both `VALUE` and `REF`):

``` c++
#ifdef SEQAN_EXCEPTIONS

#define SEQAN_CATCH_VALUE(E, e) catch(E e)
#define SEQAN_CATCH_REF(E, e) catch(E const & e)

#else  // #ifdef SEQAN_EXCEPTIONS

#define SEQAN_CATCH_VALUE(E, e) for (E e; false;)
#define SEQAN_CATCH_REF(E, e) for (E e; false;)
// Cannot have "E const & e" in second case since we cannot initialize it.

#endif  // #ifdef SEQAN_EXCEPTIONS
```
## Handle By `#ifdef`

As follows in code (very verbose, not so good).

``` c++
try { blah(); }
#ifdef SEQAN_EXCEPTIONS
catch (std::runtime_error const & e)
{
    // handle
}
#endif  // #ifdef SEQAN_EXCEPTIONS
```

**Comment by h-2** [comment]
@esiragusa what is the state of this? Don't we have everything already?
