### ISSUE TITLE
Update I/O dox

### ISSUE THREAD

**Issue by esiragusa** [seqan/seqan#680]
At this point, the only functions to be documented should be `read`, `write`, etc. Maybe tokenization?

**Comment by esiragusa** [comment]
#768 adds documentation for formatted I/O. The low-level I/O will be documented before 2.1.0.

**Comment by esiragusa** [comment]
See #682 before working on this.

**Comment by xenigmax** [comment]
This issue is dependent on #682.
However, the milestone of #682 was changed to 3.0.0 on Jan 27.
So I think this should be changed to 3.0.0, too.

Please feel free to say anything if you have an opinion about this change :)

**Comment by temehi** [comment]
@rrahn could you please close this issue as its milestone is 3.0.0 and doesn't make sense to have it in this repo. (SeqAn  2.x.x)?

**Comment by h-2** [comment]
No, please don't close the issues for 3.0.
We need to have an overview over the open issues  when working on Seqan3. When we end-of-life seqan2 we can then iterate over the issues and decide which ones to move to seqan3 and which to close.
