### ISSUE TITLE
Missing Output of MaxRepeatsIterator

### ISSUE THREAD

**Issue by serosko** [seqan/seqan#701]
Quite the oposite of the duplicate problem, but code is basically the same.
Example Code
-------------------
```
typedef StringSet<Dna5String> TText;
    typedef Index<TText, IndexEsa<> > TMyIndex;
    typedef Iter<TMyIndex, VSTree< BottomUp<MaxRepeats> > > TMyRepIter;
    TText universe;
    resize(universe, 5);
    universe[0] = "GAATAAAGAA";
    universe[1] = "CGCCCCCAAAAAAAGAAAAAGAAT";
    TMyIndex idx(universe);    
    TMyRepIter repIter(idx, 3);
     while (!atEnd(repIter))
    {
        std::cout << representative(repIter) << "; ";
        std::cout << getOccurrences(repIter) << std::endl;
        ++repIter;
     }
```
Output
---------
```
AAAAAA; 1718
AAAAAGAA; 19115
AAAAA; 171819115
AAAA; 171819115110116
AAAGAA; 04111
AAAGAA; 04111117
AAA; 17181911511011604111117
CCCC; 1312
CCC; 141312
```
Problem
-----------
The repeats "GAAT" and "GAA" are missing. If I add a character different from 'A' in front of the first String, the two missing repeats magically appear in the output. (If an 'A' is added, output is still wrong, since now "AGAA" and "AGAAT" are missing and "GAAT" + "GAA" are still not there). Interestingly, adding any character ad the end of sequence 2, also lets "GAAT" and "GAA" appear in the output.

**Comment by h-2** [comment]
closed due to bitrot
