### ISSUE TITLE
Support g++ 4.9

### ISSUE THREAD

**Issue by sagitter** [seqan/seqan#702]
These errors stop SeqAn-1.4.2 build on my Fedora 21:

```
In file included from /builddir/build/BUILD/seqan-1.4.2/core/include/seqan/graph_align.h:51:0,
                 from /builddir/build/BUILD/seqan-1.4.2/core/include/seqan/align.h:54,
                 from /builddir/build/BUILD/seqan-1.4.2/extras/apps/breakpoint_calculator/parse_alignment.h:27,
                 from /builddir/build/BUILD/seqan-1.4.2/extras/apps/breakpoint_calculator/breakpoint_calculator.h:34,
                 from /builddir/build/BUILD/seqan-1.4.2/extras/apps/breakpoint_calculator/breakpoint_calculator.cpp:25:
/builddir/build/BUILD/seqan-1.4.2/core/include/seqan/graph_align/graph_impl_align.h: In function 'void seqan::write(TFile&, const seqan::Graph<seqan::Alignment<TStringSet, TCargo, TSpec> >&, const TIDString&, seqan::Raw)':
/builddir/build/BUILD/seqan-1.4.2/core/include/seqan/graph_align/graph_impl_align.h:845:94: error: there are no arguments to 'floor' that depend on a template parameter, so a declaration of 'floor' must be available [-fpermissive]
    if (baseCount != 0) offset = (unsigned int) floor(log((double)baseCount) / log((double)10));
```
I have not idea what causes these errors and if they are the reason of compilation failure.
Here a full log: https://kojipkgs.fedoraproject.org//work/tasks/7571/8187571/build.log

Thanks.

**Comment by h-2** [comment]
I have added `gcc-4.9.2`, `clang-3.5.1` and a snapshot of `gcc-5`. I have disabled `gcc-4.6` and moved the memcheck and coverage checks to `gcc-4.7` (from 4.6). I have also adapted the memcheck to work with our new folder hierarchy.
Unfortunately cdash is down again and before we also didn't reports for master (only develop). The mac builds seemto be completely down, so I will keep this issue open until all build-infrastructure related things are working again.

**Comment by h-2** [comment]
The installed `gcc-4.9.2` had some weird issues (including apparent lack of omp). I have reinstalled it and verified that it now builds razers3. 
Unfortunately there still seem to be some issues: yesterday we have only develop-branch, but both architectures, today we had master with -m32 and develop with 64bit, but always without the other.

Let's see how things fare tonight.
