### ISSUE TITLE
SeqAn libraries installation

### ISSUE THREAD

**Issue by sagitter** [seqan/seqan#706]
Hi all.

mason2 and seqan_flexbar compilation provides two private libraries named libseqan_flexlib.so and libmason_sim.so . I think they must be present in same directory of binary files in order to be used.

If I install both libraries in a private seqan sub-directory, mason and seqan_flexbar tests fail.
Can I link the binaries to the libraries if located in a different path?

**Comment by esiragusa** [comment]
Does setting ```BUILD_SHARED_LIBS=OFF``` by default solve this issue?

**Comment by esiragusa** [comment]
Or, stated differently, why do we need ```BUILD_SHARED_LIBS=ON```? We have only app-specific shared objects...

**Comment by h-2** [comment]
Should be fixed by #1329 
If not, please reopen.
