### ISSUE TITLE
SequenceStream / readRecord doesn't support sequential only files (named pipes, /dev/stdin, et cetera)

### ISSUE THREAD

**Issue by mr-c** [seqan/seqan#707]
The khmer project really appreciate SeqAn & the new SequenceStream API. I noticed that the lower level 
API supports sequential-only files; could this be added to the SequenceStream class?

Thanks.

(Our discussion about this issue is at https://github.com/ged-lab/khmer/issues/654 )

**Comment by mr-c** [comment]
@holtgrewe I don't think the issue with the suggested workaround was ever fixed: https://github.com/seqan/seqan/issues/866

**Comment by h-2** [comment]
@mr-c What are you referring to exactly? readRecord+std::string or multi-threaded IO?

**Comment by mr-c** [comment]
readRecord+std::string

**Comment by rrahn** [comment]
@mr-c you are right. #866 is not fixed and probably won't be fixed for SeqAn 2.x.
Though, we will have a working version of that for a new SeqAn 3 cycle. That however is on our mid-term/long-term roadmaps and won't be available before the next year.
