### ISSUE TITLE
A BamFile is a SeqFile

### ISSUE THREAD

**Issue by mr-c** [seqan/seqan#712]
BAM files can be an alternative to FASTQ that has unambiguous quality score representation, built-in compression, and expandable metadata.

https://www.biostars.org/p/13583/

**Comment by mr-c** [comment]
Any progress here?

**Comment by h-2** [comment]
@mr-c The current thoughts here are that we want to have a Generic SequenceFile and a generic AlignmentFile in the future. We might add the option to treat certain AlignmentFils as SequenceFiles, as well, but it won't be done in the short term.

**Comment by mr-c** [comment]
Okay. Thanks for the update.

**Comment by h-2** [comment]
@temehi this would be nice to have, maybe you could do it with a student as a PMSB proejct?

**Comment by h-2** [comment]
@temehi can you have a look at #1699  and discuss this also with the students so that we can merge this before 2.2.0?
I discussed with @rrahn that we do want this to be part of the SeqFile interface and not of BamFile. However write support is not required for the PR, only read (so there are not that many changes).

**Comment by esiragusa** [comment]
@h-2 @rrahn We want this to be part of the SeqFile interface, but not the current one. Right now SeqFile lacks the concept of record, this fact is the root of many problems. If SeqFile works on records, BamFile could subclass it.

**Comment by h-2** [comment]
@esiragusa I agree in the long run, however, we won't change this interface before SeqAn-3.0.0

Since we have a PR now, we decided on merging it with the current interface, so you can do the following:
```c++

SeqFileIn myFile{"/tmp/test.bam"};
StringSet<String<char>> ids;
StringSet<String<Dna>, Owner<ConcatDirect>>> seqs;

readRecords(ids, seqs, myFile);
```
