### ISSUE TITLE
Dox does not support switching between version.

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#724]
@holtgrewe @bkahlert:
Please add functionality to switch between the versions of the documentation as is done for the readthedocs documentation.
There you can select another version for the current page (See lower left corner at the side bar, there is a small drop down menu). 
Who is gonna responsible for such things?

**Comment by esiragusa** [comment]
@rrahn Do you know how to do this quickly? Otherwise let's postpone it.

**Comment by holtgrewe** [comment]
I would say we should postpone this.

**Comment by rrahn** [comment]
Mhmm, I guess I would have to play around a lot. 
So preferably I'd like to postpone it.

**Comment by xenigmax** [comment]
@rrahn  , @h-2 
1) Who maintains this page? - http://docs.seqan.de/
2) Is this OK to get the list of versions from above ?

If you agree, I will add some python codes to "/util/py_lib/seqan/dox/"
It will extract available versions from 1).

**Comment by xenigmax** [comment]
@rrahn, Would you check below?
http://docs.seqan.de/seqan/master_version_test/

The version selector is on a fixed layer as you requested.
If you like it, I will make another PR.

Please feel free to say anything :)

**Comment by rrahn** [comment]
That looks very good :+1: 
Could you align the label and box to the right side of the sidebar. 
I think it looks a little bit better. :nail_care: I know

**Comment by xenigmax** [comment]
@rrahn , I did. Would you check again?
Any other comments?

**Comment by rrahn** [comment]
Can you center the text and the drop down menu on the vertical axis?
You can then make PR.

**Comment by xenigmax** [comment]
@rrahn  Again, it seems a SafraI specific problem as we discussed.
I will find a way for reproducing your situation. 
I can't see anything odd with Chrome / FireFox.
