### ISSUE TITLE
Repository in CDash log message links to trac browser

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#728]
In CDash, there is this row ''repository'' associated with every log message directing to the repository and revision of the source. Unfortunately, this redirects to the trac source browser, which obviously cannot work. 
Is there an easy way to adapt this to link to the actual source (in this case to the correct github repository?) or if not could we at least inactivate this?
A non-existing link is better than a broken one, although this is not urgent :).

**Comment by esiragusa** [comment]
Now it points to github.
