### ISSUE TITLE
Remove the random module

### ISSUE THREAD

**Issue by esiragusa** [seqan/seqan#751]
Reasons:
- The random module appears to simulate wrong distributions.
- No one is willing to maintain it.
- The whole module can be replaced by C++11's random (http://en.cppreference.com/w/cpp/numeric/random).

Issues:
- Apps and demos picking random numbers will require C++11.
- HMMs and Skiplists will require C++11.
- Some unit tests rely on picking random numbers, but they shouldn't.

**Comment by h-2** [comment]
* unit test that use random numbers should use hardcoded numbers instead
 * remove skiplists

**Comment by h-2** [comment]
Done via #1401
