### ISSUE TITLE
Dox matches result are confusing if the listed elements have the same name as the page header.

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#767]
When selecting a dox entry from the search bar, the resulting dox page starts with the "Detailed Description" section. 
It should rather start at the beginning, otherwise one is confused and takes a second to realise that the page ist the correct one. Second, one does not see the interface overviews, which is the first thing one would like to see.

**Comment by holtgrewe** [comment]
Hi, I will not have time to update this.

**Comment by xenigmax** [comment]
BamAlignmentReocrd seems not a proper example anymore.
So I tested it with "gapAnchor".
The first one is a Class, and second one is a member function (a constructor in this case.).
```
 > GapAnchor
   matches:
    > GapAnchor
```

Here are questions.

Who can decide the UI/UX kind of things?
@rrahn , probably?
