### ISSUE TITLE
/seqan-1.4.2/core/include/seqan/index/index_qgram_openaddressing.h:225:38: error: '_mm_crc32_u64' was not declared in this scope

### ISSUE THREAD

**Issue by mmokrejs** [seqan/seqan#772]
Hi,
  when compiling with gcc-4.8.3 I get an error. Also, somehow the xlib detection doe snot reveal I have zlib installed (Gentoo Linux):

>>> Working in BUILD_DIR: "/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2_build"
cmake --no-warn-unused-cli -C /mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_INSTALL_DO_STRIP=OFF -DCMAKE_USER_MAKE_RULES_OVERRIDE=/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2_build/gentoo_toolchain.cmake  /mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2

...

-- Zlib could not be found!

....

Scanning dependencies of target stellar
make[2]: Leaving directory '/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2_build'
make -f core/apps/stellar/CMakeFiles/stellar.dir/build.make core/apps/stellar/CMakeFiles/stellar.dir/build
make[2]: Entering directory '/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2_build'
/usr/bin/cmake -E cmake_progress_report /mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2_build/CMakeFiles 
[  0%] Building CXX object core/apps/stellar/CMakeFiles/stellar.dir/stellar.cpp.o
cd /mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2_build/core/apps/stellar && /usr/bin/x86_64-pc-linux-gnu-g++  -DSEQAN_ENABLE_TESTING=0 -DSEQAN_HAS_EXECINFO=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE  -I/usr/include/bam -DNDEBUG -O2 -pipe -maes -mpclmul -mpopcnt -mavx -march=native  -W -Wall -Wno-long-long -fstrict-aliasing -Wstrict-aliasing -pedantic -Wno-variadic-macros -I/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include    -o CMakeFiles/stellar.dir/stellar.cpp.o -c /mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/apps/stellar/stellar.cpp
In file included from /mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include/seqan/index.h:81:0,
                 from /mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/apps/stellar/stellar.cpp:24:
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include/seqan/index/index_qgram_openaddressing.h: In instantiation of 'TValue seqan::_hashFunction(const TBucketMap&, TValue) [with TBucketMap = seqan::BucketMap<long unsigned int>; TValue = long unsigned int]':
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include/seqan/index/index_qgram_openaddressing.h:288:58:   required from 'THashValue seqan::getBucket(const seqan::BucketMap<THashValue>&, THashValue2) [with THashValue = long unsigned int; THashValue2 = long unsigned int]'
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include/seqan/index/find_swift.h:1027:76:   required from 'bool seqan::_swiftMultiProcessQGram(TFinder&, seqan::Pattern<TIndex, seqan::Swift<TSwiftSpec> >&, THashValue) [with TFinder = seqan::Finder<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> >, seqan::Swift<seqan::Tag<seqan::SwiftLocal_> > >; TIndex = seqan::Index<seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> >, seqan::Dependent<seqan::Tag<seqan::TagInsist_> > >, seqan::IndexQGram<seqan::UngappedShape<0u>, seqan::Tag<seqan::OpenAddressing_> > >; TSpec = seqan::Tag<seqan::SwiftLocal_>; THashValue = long unsigned int]'
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include/seqan/index/find_swift.h:1882:109:   required from 'bool seqan::find(seqan::Finder<THaystack, seqan::Swift<TSwiftSpec> >&, seqan::Pattern<TIndex, seqan::Swift<TSwiftSpec> >&, double, TSize) [with THaystack = seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> >; TIndex = seqan::Index<seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> >, seqan::Dependent<seqan::Tag<seqan::TagInsist_> > >, seqan::IndexQGram<seqan::UngappedShape<0u>, seqan::Tag<seqan::OpenAddressing_> > >; TSpec = seqan::Tag<seqan::SwiftLocal_>; TSize = int]'
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/apps/stellar/stellar.h:685:49:   required from 'void stellar(seqan::Finder<TText, seqan::Swift<seqan::Tag<seqan::SwiftLocal_> > >&, seqan::Pattern<seqan::Index<seqan::StringSet<TString, TSpec>, TSpec>, seqan::Swift<seqan::Tag<seqan::SwiftLocal_> > >&, double, TSize, TDrop, TSize1, TSize1&, TSize1, TMode, TId&, bool, seqan::StringSet<QueryMatches<StellarMatch<TSource, TId> > >&, TTag) [with TText = seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> >; TStringSetSpec = seqan::Dependent<seqan::Tag<seqan::TagInsist_> >; TIndexSpec = seqan::IndexQGram<seqan::UngappedShape<0u>, seqan::Tag<seqan::OpenAddressing_> >; TSize = int; TDrop = double; TSize1 = unsigned int; TMode = bool; TSource = seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> >; TId = seqan::String<char, seqan::Alloc<> >; TTag = seqan::Tag<VerifyAllLocal_>]'
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/apps/stellar/stellar.cpp:56:64:   required from 'bool _stellarOnOne(TSequence&, TId&, TPattern&, bool, TMatches&, StellarOptions&) [with TSequence = seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> >; TId = seqan::String<char, seqan::Alloc<> >; TPattern = seqan::Pattern<seqan::Index<seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> >, seqan::Dependent<seqan::Tag<seqan::TagInsist_> > >, seqan::IndexQGram<seqan::UngappedShape<0u>, seqan::Tag<seqan::OpenAddressing_> > >, seqan::Swift<seqan::Tag<seqan::SwiftLocal_> > >; TMatches = seqan::StringSet<QueryMatches<StellarMatch<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> >, seqan::String<char, seqan::Alloc<> > > >, seqan::Owner<> >]'
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/apps/stellar/stellar.cpp:172:98:   required from 'bool _stellarOnAll(seqan::StringSet<TString, seqan::Owner<> >&, seqan::StringSet<TString, seqan::Owner<> >&, seqan::StringSet<TString, seqan::Owner<> >&, seqan::StringSet<TString, seqan::Owner<> >&, StellarOptions&) [with TSequence = seqan::String<seqan::SimpleType<unsigned char, seqan::Dna_>, seqan::Alloc<> >; TId = seqan::String<char, seqan::Alloc<> >]'
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/apps/stellar/stellar.cpp:688:74:   required from 'int mainWithOptions(TOptions&, seqan::String<TAlphabet>) [with TOptions = StellarOptions; TAlphabet = seqan::SimpleType<unsigned char, seqan::Dna_>]'
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/apps/stellar/stellar.cpp:718:47:   required from here
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include/seqan/index/index_qgram_openaddressing.h:225:38: error: '_mm_crc32_u64' was not declared in this scope
         return _mm_crc32_u64(0ul, val);
                                      ^
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include/seqan/index/index_qgram_openaddressing.h: In function 'TValue seqan::_hashFunction(const TBucketMap&, TValue) [with TBucketMap = seqan::BucketMap<long unsigned int>; TValue = long unsigned int]':
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include/seqan/index/index_qgram_openaddressing.h:229:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
In file included from /mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include/seqan/basic.h:52:0,
                 from /mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include/seqan/sequence.h:51,
                 from /mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include/seqan/index.h:39,
                 from /mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/apps/stellar/stellar.cpp:24:
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include/seqan/basic/basic_exception.h: At global scope:
/mnt/1TB/var/tmp/portage/sci-biology/seqan-1.4.2/work/seqan-1.4.2/core/include/seqan/basic/basic_exception.h:241:37: warning: 'seqan::_globalExceptionHandler' defined but not used [-Wunused-variable]
 static const std::terminate_handler _globalExceptionHandler = std::set_terminate(globalExceptionHandler);
                                     ^
core/apps/stellar/CMakeFiles/stellar.dir/build.make:57: recipe for target 'core/apps/stellar/CMakeFiles/stellar.dir/stellar.cpp.o' failed
make[2]: *** [core/apps/stellar/CMakeFiles/stellar.dir/stellar.cpp.o] Error 1

**Comment by temehi** [comment]
@mmokrejs Your cmake is producing different commands. Could you please try the following:
1. checkout seqan-1.4.2 using 'git checkout seqan-v1.4.2' from your local SeqAn source repository.
2. run cmake from your build directory.  something like '../../seqan -DCMAKE_BUILD_TYPE=Debug' make sure you have a clean directory when you do this.
3. post the result of 'make -n stellar'
Thanks

**Comment by esiragusa** [comment]
Please try on seqan-v2.0.0 instead of seqan-v1.4.2. There are chances that this issue has been solved.

**Comment by mmokrejs** [comment]
So I tried the following OUTSIDE the Gentoo Linux compiling/packaging system. It runs cmake on its own and I would first need to figure out how to modify what it executes.

Is the below what you wanted me to do?
<pre>
git clone --branch seqan-v2.0.0 https://github.com/seqan/seqan.git
mkdir obj
cd obj
cmake ../seqan -DCMAKE_BUILD_TYPE=Debug 1>cmake.log 2>&1
make -n stellar 1>make.log 2>&1
</pre>

<pre>
$ cat make.log 
/usr/bin/cmake -H/mnt/external/tmp/seqan -B/mnt/external/tmp/obj --check-build-system CMakeFiles/Makefile.cmake 0
make -f CMakeFiles/Makefile2 stellar
/usr/bin/cmake -H/mnt/external/tmp/seqan -B/mnt/external/tmp/obj --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /mnt/external/tmp/obj/CMakeFiles 0
make -f CMakeFiles/Makefile2 apps/stellar/CMakeFiles/stellar.dir/all
make -f CMakeFiles/seqan_library.dir/build.make CMakeFiles/seqan_library.dir/depend
cd /mnt/external/tmp/obj && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /mnt/external/tmp/seqan /mnt/external/tmp/seqan /mnt/external/tmp/obj /mnt/external/tmp/obj /mnt/external/tmp/obj/CMakeFiles/seqan_library.dir/DependInfo.cmake --color=
make -f CMakeFiles/seqan_library.dir/build.make CMakeFiles/seqan_library.dir/build
/usr/bin/cmake -E cmake_progress_report /mnt/external/tmp/obj/CMakeFiles 
echo "Built target seqan_library"
make -f apps/stellar/CMakeFiles/stellar.dir/build.make apps/stellar/CMakeFiles/stellar.dir/depend
cd /mnt/external/tmp/obj && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /mnt/external/tmp/seqan /mnt/external/tmp/seqan/apps/stellar /mnt/external/tmp/obj /mnt/external/tmp/obj/apps/stellar /mnt/external/tmp/obj/apps/stellar/CMakeFiles/stellar.dir/DependInfo.cmake --color=
make -f apps/stellar/CMakeFiles/stellar.dir/build.make apps/stellar/CMakeFiles/stellar.dir/build
/usr/bin/cmake -E cmake_progress_report /mnt/external/tmp/obj/CMakeFiles 
/usr/bin/cmake -E cmake_echo_color --switch= --green "Building CXX object apps/stellar/CMakeFiles/stellar.dir/stellar.cpp.o"
cd /mnt/external/tmp/obj/apps/stellar && /usr/bin/c++   -DSEQAN_APP_VERSION=\"1.4.2\" -DSEQAN_DATE="\"2015-02-11 14:58:35 +0100\"" -DSEQAN_ENABLE_TESTING=0 -DSEQAN_HAS_EXECINFO=1 -DSEQAN_REVISION=\"b0826a7\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -W -Wall -Wno-long-long -fstrict-aliasing -Wstrict-aliasing -pedantic -Wno-variadic-macros  -fno-omit-frame-pointer -g -DSEQAN_ENABLE_DEBUG=1 -I/mnt/external/tmp/seqan/include    -o CMakeFiles/stellar.dir/stellar.cpp.o -c /mnt/external/tmp/seqan/apps/stellar/stellar.cpp
/usr/bin/cmake -E cmake_echo_color --switch= --red --bold "Linking CXX executable ../../bin/stellar"
cd /mnt/external/tmp/obj/apps/stellar && /usr/bin/cmake -E cmake_link_script CMakeFiles/stellar.dir/link.txt --verbose=
/usr/bin/cmake -E cmake_progress_report /mnt/external/tmp/obj/CMakeFiles 
echo "Built target stellar"
/usr/bin/cmake -E cmake_progress_start /mnt/external/tmp/obj/CMakeFiles 0
$
</pre>

**Comment by temehi** [comment]
Yes that was almost what I wanted to see, but with SeqAn 1.4.2. You did it with SeqAn 2.0.0, which is a good thing. Have you also tried to build stellar from the new version of SeqAn? I mean without the -n flag?

**Comment by mmokrejs** [comment]
I continued with the obj/ dir contents:

<pre>
$ make stellar 1>make.log2 2>&1
$ cat make.log2
Built target seqan_library
Scanning dependencies of target stellar
Building CXX object apps/stellar/CMakeFiles/stellar.dir/stellar.cpp.o
Linking CXX executable ../../bin/stellar
Built target stellar
$ ls -latr bin
total 191424
-rwx------  1 mmokrejs mmokrejs  2655977 Mar  5 21:36 test_graph_algorithms
-rwx------  1 mmokrejs mmokrejs   861642 Mar  5 21:36 test_score
-rwx------  1 mmokrejs mmokrejs  7392055 Mar  5 21:37 test_realign
-rwx------  1 mmokrejs mmokrejs  7662044 Mar  5 21:37 test_find_backtracking
-rwx------  1 mmokrejs mmokrejs 20974066 Mar  5 21:38 test_index_base
-rwx------  1 mmokrejs mmokrejs 15229411 Mar  5 21:39 test_index_creation
-rwx------  1 mmokrejs mmokrejs  7154026 Mar  5 21:39 test_index_crosscompare_char
-rwx------  1 mmokrejs mmokrejs   937770 Mar  5 21:39 test_index_crosscompare_char_dfi
-rwx------  1 mmokrejs mmokrejs 12457689 Mar  5 21:40 test_index_crosscompare_dna
-rwx------  1 mmokrejs mmokrejs  1056861 Mar  5 21:40 test_index_crosscompare_dna_dfi
-rwx------  1 mmokrejs mmokrejs   564713 Mar  5 21:40 test_index_drawing
-rwx------  1 mmokrejs mmokrejs 20755125 Mar  5 21:41 test_index_finder
-rwx------  1 mmokrejs mmokrejs 15816485 Mar  5 21:42 test_index_fm
-rwx------  1 mmokrejs mmokrejs  2721887 Mar  5 21:42 test_index_fm_rank_dictionary
-rwx------  1 mmokrejs mmokrejs   288358 Mar  5 21:42 test_index_fm_sparse_string
-rwx------  1 mmokrejs mmokrejs  1853103 Mar  5 21:43 test_index_qgram
-rwx------  1 mmokrejs mmokrejs   414634 Mar  5 21:43 test_index_repeats
-rwx------  1 mmokrejs mmokrejs  1362311 Mar  5 21:43 test_index_sa_bwtwalk
-rwx------  1 mmokrejs mmokrejs   480634 Mar  5 21:43 test_index_shapes
-rwx------  1 mmokrejs mmokrejs 15296228 Mar  5 21:44 test_index_stree_iterators
-rwx------  1 mmokrejs mmokrejs   918137 Mar  5 21:44 test_index_swift
-rwx------  1 mmokrejs mmokrejs   711816 Mar  5 21:44 test_index_view
-rwx------  1 mmokrejs mmokrejs 18839619 Mar  5 21:45 test_index_vstree
-rwx------  1 mmokrejs mmokrejs  3744551 Mar  5 21:45 test_translation
-rwx------  1 mmokrejs mmokrejs   866243 Mar  5 21:45 test_graph_types_derived
-rwx------  1 mmokrejs mmokrejs  1725866 Mar  5 21:46 test_graph_types_iterators
-rwx------  1 mmokrejs mmokrejs   834821 Mar  5 21:46 test_graph_types_property_map
-rwx------  1 mmokrejs mmokrejs  2317727 Mar  5 21:46 test_graph_types_types
-rwx------  1 mmokrejs mmokrejs  1427901 Mar  5 21:46 test_graph_types_utils
-rwx------  1 mmokrejs mmokrejs   787785 Mar  5 21:46 test_journaled_set
-rwx------  1 mmokrejs mmokrejs  2901069 Mar  5 21:46 test_modifier
-rwx------  1 mmokrejs mmokrejs  1580801 Mar  5 21:46 test_vcf_io
-rwx------  1 mmokrejs mmokrejs  3112351 Mar  5 21:47 test_align_split
-rwx------  1 mmokrejs mmokrejs  1005285 Mar  5 21:47 test_ucsc_io
-rwx------  1 mmokrejs mmokrejs   827407 Mar  5 21:47 test_roi_io
-rwx------  1 mmokrejs mmokrejs   724946 Mar  5 21:47 test_modifier_cyclic_shape
drwx------ 10 mmokrejs mmokrejs     4096 Mar  5 23:06 ..
drwx------  2 mmokrejs mmokrejs     4096 Mar  5 23:07 .
-rwx------  1 mmokrejs mmokrejs 17672490 Mar  5 23:07 stellar
$
</pre>

So, that works?

I am for the first time "using" SeqAn, please send me commands you want me to run. ;-)

After you know what is wrongly called by the cmake from Gentoo portage eclasses, please tell me what is the build system supposed to call and how, exactly the commands. Thank you.

**Comment by temehi** [comment]
Great! 
Perhaps this could help, 
http://seqan.readthedocs.org/en/master/Tutorial/GettingStarted.html#tutorial-getting-started

**Comment by esiragusa** [comment]
@mmokrejs 

To reproduce your compile flags, I did:
```
$ cmake ../seqan -DCMAKE_CXX_FLAGS="-maes -mpclmul -mpopcnt -mavx -march=native"
$ make stellar VERBOSE=1
```
and it works for me.

Unfortunately I don't have any Gentoo close at hand. Does the latest portage (http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/sci-biology/seqan/seqan-2.0.0.ebuild) work for you?

**Comment by mmokrejs** [comment]
OK, I see Justin picked up the old ebuild I wrote in the past and his seqan-2.0.0.ebuild works for me now.

BTW, have you realized "-DBoost_NO_BOOST_CMAKE=ON" in it? ;-)
