### ISSUE TITLE
convenience function for writing arbitrary types

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#774]
in the old IO-code there was `streamPut(stream, foo)` where arbitrary foo was supported, i.e. integers, floats, sequences...
This would be really nice to have  again, especially when dealing with unkown types, e.g. I have a function that recursively prints its variadically templated arguments.

The wrapper I currently use that seems to emulate the old behaviour fully is:
```c++
template <typename TStream>
inline int
streamPut(TStream & s, char const c)
{
    writeValue(s, c);
    return 0;
}

template <typename TStream,
          typename TIn,
          typename std::enable_if<std::numeric_limits<TIn>::is_integer &&
                         !std::is_same<TIn, char>::value &&
                         !std::is_same<TIn, signed char>::value &&
                         !std::is_same<TIn, unsigned char>::value, int>::type = 0>
inline int
streamPut(TStream & s, TIn const c)
{
    appendNumber(s, c);
    return 0;
}

template <typename TStream,
          typename TIn,
          typename std::enable_if<IsSequence<TIn>::VALUE, int>::type = 0>
inline int
streamPut(TStream & s, TIn const & c)
{
    write(s, c);
    return 0;
}
```

In the new interface we should maybe agree on using just `write()` for this, so the first two functions could  be adapted for that.

@esiragusa what are your thoughts on this?

**Comment by h-2** [comment]
ah, the desired behaviour actually is the current behaviour of `write()`.

This is however not yet documented (or maybe it is in a branch of @esiragusa ?)

**Comment by esiragusa** [comment]
Refer to #680.
