### ISSUE TITLE
changes to style-guide

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#776]
I propose changes to the style-guide. I know these things get religious, but IMHO it is very inconsistent to have different rules for function calls and function definitions (called function argument lists in our tutorials). I propose using "all arguments in one line" if they fit, and "each argument in its own line" if they don't fit [current rules for function definitions] and use this for function calls and template argument lists, as well. This also increases readability greatly, especially when trying to figure out which function call will trigger which function definition.
I would even go further and define "each argument in its own line" to always be legal, even if arguments don't exceed maximum line length. This has the advantage of improved readability, when e.g. you have multiple function definitions and/or calls where some exceed the maximum line length and others don't.

What do you think?

**Comment by esiragusa** [comment]
I think nobody remembers that rule :trollface: Just do it as you prefer :+1:
