### ISSUE TITLE
SeqAn style guide not up to date

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#777]
It contains statements like:
```
Exceptions
Currently, the SeqAn code does not use any exceptions and is not exception safe. Do not use any exceptions yourself, instead use return codes.
```
which is obviously out of date. Is there any doc on the exceptions at all?

**Comment by esiragusa** [comment]
I'd suggest to remove that paragraph...

**Comment by mr-c** [comment]
Yeah, I just got hit by this

```
third-party/seqan-library-2.0.0/include/seqan/basic/basic_exception.h:368 FAILED!  (Uncaught exception of type seqan::UnexpectedEnd: Unexpected end of input.)
```

(To reproduce run `make test` with https://github.com/ged-lab/khmer/commit/f4a1fff561f309b156f708757a1c5040f50ea662 )
