### ISSUE TITLE
zip file is xml file

### ISSUE THREAD

**Issue by aerval** [seqan/seqan#779]
The file [workflow_plugin_dir.zip](https://github.com/seqan/seqan/blob/develop/manual/source/HowTo/workflow_plugin_dir.zip) is not a zip file (and does not contain the folder it is supposed to).

I found this ussue on the [SeqAn tutorial](http://seqan.readthedocs.org/en/latest/HowTo/GenerateKnimeNodesExternalTools.html#how-to-generate-knime-nodes-for-external-tools-anatomy-of-a-plugin-directory) pages and had to figure out how to generate generic knime node content myself. Is there any other information (especially regarding a complete command list) for GenericKnimeNodes besides the various (Github) sources which are btw in no way linked to each other? (Gerne auch auf Deutsch)

Cheers from RKI

**Comment by esiragusa** [comment]
Fixed in #895, #897.
