### ISSUE TITLE
enum in dox not sorted numerically...

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#780]
... but alphabetically instead. This is really confusing as the order of the enum values is important to the user.

**Comment by esiragusa** [comment]
:+1:

**Comment by rrahn** [comment]
Fixed by #788

**Comment by esiragusa** [comment]
Hey is there any other place where we should disable lex sorting? Function calls, template arguments, etc?

**Comment by rrahn** [comment]
As far as I could see, the order of the function parameters is in the same order as listed in the signature.
But I just saw this here: http://docs.seqan.de/seqan/develop/?p=String#String%23resizeSpace
Here the order of beginPos and endPos is changed in the parameter description compared to the parameter list in the signature.
I'll will have a look if I figure out why.
