### ISSUE TITLE
AminoAcid Leucine/Isoleucine not present

### ISSUE THREAD

**Issue by cbielow** [seqan/seqan#782]
From what I can see, Seqan's AminoAcid class 
http://docs.seqan.de/seqan/1.4.1/SPEC_Amino_Acid.html
is not aware of the AA code "J" (Leucin/Isoleucin) [http://www.ddbj.nig.ac.jp/sub/ref2-e.html]

This leads to a nasty silent behaviour when reading sequences which contain a "J", i.e.
these positions get silently converted to "X". Ouch.

I've come across this in OpenMS' code and worked around it, but in general I think a fix in Seqan would be better.

**Comment by esiragusa** [comment]
Hi Chris. Thanks for reporting this issue. It has been already fixed in develop - see https://github.com/seqan/seqan/issues/666.
