### ISSUE TITLE
Consistent README naming scheme.

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#783]
Currently there are some apps using the new markdown version for READMES with the *.rst extension and the greater part of apps uses the plain README file. 
All Readmes need to be updated to the markdown version, such that the integration of the READMEs by the CPACK_PACKAGE_DESCRIPTION_FILE, can be done centrally without setting the correct variables for each app explicitly.

**Comment by h-2** [comment]
we should discuss using .md everywhere.
