### ISSUE TITLE
Documentation for BamFileIn Context is missing

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#791]
This is required for finding out how to access contig/chromosome names.

**Comment by esiragusa** [comment]
Here is the BAM tutorial: http://seqan.readthedocs.org/en/develop/Tutorial/SamBamIO.html#accessing-the-header.

So, feel free to add the dox and to improve the manual as well.

**Comment by esiragusa** [comment]
Already documented. See http://docs.seqan.de/seqan/develop/class_BamIOContext.html
