### ISSUE TITLE
Bump all apps versions

### ISSUE THREAD

**Issue by esiragusa** [seqan/seqan#807]
This implies tagging them together with seqan-v2.0.0

**Comment by esiragusa** [comment]
@rrahn @h-2 see  #819.

**Comment by h-2** [comment]
I will take apps alf ... ngs_roi

**Comment by esiragusa** [comment]
@h-2 @rrahn can you recycle this issue for 2.1.0?

Please **do not to bump yara version**. I just bumped it to 0.9.5 on develop but did not tag it yet. I am waiting for the seqan-v2.1.0 tag. Thanks.

**Comment by rrahn** [comment]
Ok yara is already bumped.

**Comment by h-2** [comment]
via #1464 (yara not bumped)
