### ISSUE TITLE
SeqFile .txt extension is harmful on Illumina FastQ files

### ISSUE THREAD

**Issue by esiragusa** [seqan/seqan#839]
Bernd Jagla reported that all Illumina FastQ files come with the .txt extension, so they are interpreted as raw sequence files.

**Comment by esiragusa** [comment]
@xenigmax We should figure out what's the best solution...

We could change the extension for raw sequence files from .txt to e.g. .raw. In this way .txt would be an unrecognized extension, at least. But I would not add .txt to the list of fastq extensions.

@weese Are these raw sequence files used anywhere? What do you think?

**Comment by esiragusa** [comment]
@xenigmax please note that #838 is somewhat related...

**Comment by xenigmax** [comment]
OK, I'm gonna listen your suggestions for a while.

**Comment by xenigmax** [comment]
I have checked this one.
Unfortunately, I can't find proper information about Illumina's output extensions about fastq with ".txt".
I found older version of Illumina softwares uses **"_qseq.txt"**  which is **comparable** to fastq but **different** file format.
http://support.illumina.com/content/dam/illumina-support/documents/myillumina/a557afc4-bf0e-4dad-9e59-9c740dd1e751/casava_userguide_15011196d.pdf
http://allaboutbioinfo.blogspot.de/2011/08/qseq-and-export-file-format-of-illumina.html

So I would like to make sure that whether ".txt" extensions with fastq files are Illumina's policy or user's preference.

**Comment by mr-c** [comment]
FYI: I have never heard of Casava delivering FASTQ files as '.txt'. But user's problem deserves investigation regardless.
