### ISSUE TITLE
Manual v2.0.0, master, develop link to dox develop

### ISSUE THREAD

**Issue by esiragusa** [seqan/seqan#854]
E.g. click on the link "Strings" in the first paragraph of the tutorial http://seqan.readthedocs.org/en/master/Tutorial/SequencesInDepth.html#tutorial-sequences-in-depth

**Comment by rrahn** [comment]
Still waiting for Read The Docs guys to merge the PR: https://github.com/rtfd/readthedocs.org/pull/1570

**Comment by h-2** [comment]
why was this closed? upstream hasn't merged yet...

**Comment by rrahn** [comment]
Probably to fast yesterday :tired_face:

**Comment by rrahn** [comment]
Upstream is merged and deployed. This is now done!
