### ISSUE TITLE
readUntil and skipUntil don't throw if atEnd()

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#855]
the should throw UnexpectedEnd() if the end is reached before the termination criterion.

**Comment by weese** [comment]
It's not that simple. Imagine an implementation of readLine() or a file format parser that reads until a newline. They should work even if the file doesn't end with newline. 
For cases where you want to parse until the next tab and the format demands a tab there, you use ```skipOne(iter, IsTab())```which throws an UnexpectedEnd if at the end.

**Comment by weese** [comment]
Can you specify your use case, please.

**Comment by h-2** [comment]
> It's not that simple. Imagine an implementation of readLine() or a file format parser that reads until a newline. They should work even if the file doesn't end with newline. 

I understand the rationale, but if the programmer says "readUntil X" and the code never reaches X that is a reason for giving an error IMHO. Reading lines is a bit of a special case, because you also don't stop on the Newline-character, but behind it. So one could of course easily define `readLine()` to be `readUntilNewlinePlusOneOrEof()`, but I still think the regular `readUntil()` should behave stricter.

> Can you specify your use case, please.

It's just something that I realised when reading the code. Of course I can work around it, or fix it myself, but I wanted to know the reasoning first and if it needs fixing...

**Comment by esiragusa** [comment]
@h-2 please close this issue if it's not relevant anymore, otherwise let's continue the discussion.

**Comment by h-2** [comment]
@esiragusa : I think we agreed that it should throw, but I don't know if @weese is convinced yet ;)

**Comment by weese** [comment]
@h-2: Can you specify a use case where you cannot live with skipOne after readUntil.

**Comment by h-2** [comment]
@weese I can live with almost everything, I was just told to use the new IO and give input on stuff. An example of where I think skipOne is not very handy, is whenever you want to read multiple characters after having skipped multiple characters:

Lets say you have a table that is not tab-separated but instead separated by a variable number of spaces (not too uncommen if the columns are aligned for humans):
```
foo    bar  bax
foobar bax  bat
```
The most intuitive way of reading the fields would be 
```c++
readUntil(var1, it, IsWhiteSpace());
skipUntil(it, IsGraph());
readUntil(var2, it, IsWhiteSpace());
skipUntil(it, IsGraph());
readUntil(var3, it, IsWhiteSpace());
```
None of these functions throw() if EOF is reached. Yes, you can probably `skipOne()` whitespace before doing `skipUntil()`, but I don't think it is very straightforward, nor do I see the drawback of making `*Until()` also throw, since its free if it doesn't happen.

That having been said, I don't need this code functionality right now and if you don't agree with the points you can just close this.

**Comment by esiragusa** [comment]
Moved to 2.1.0 as it would probably require an API change.
