### ISSUE TITLE
new IO buggy and/or poorly documented

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#857]
I am trying to read something from an fstream since over an hour now and it just won't work :rage: This was super easy before...

Things I have tried:
  * just using e.g. `skipLine()` on an fstream: doesn't work, but used to in the old code
  * `StreamIterator<std::fstream, Bidirectional> it(fstream);` according to the dox, this should exist, but in reality doesn't
  * `StreamIterator<Bidirectional> it(fstream);` exists but cant be initialized with an fstream
  * `auto it = begin(fstream)` [I am starting to get desperate]
  * `auto it = directionIterator(fstream, Bidirectional());` ...

Examples in the code seem to use:
  * `Iterator<CharString, Rooted>::Type it = begin(string);` but that also doesn't work if I replace the CharString with std::fstream and string with my fstream.

...

**Comment by weese** [comment]
Although I don't like the tone of your non-constructive criticism / general rant (?), I'm curious what you mean with super easy before (the record reader?) and why your are so desperately trying to use Bidirectional.
Similar to the STL, the documentation mentions only Input and Output Stream Iterators and there are lots of demos showing how to use them, e.g. demos/tutorial/custom_io/
I think the new I/O is super easy, makes error handling way easier (and compared to the former I/O even possible) and provides efficient and unified support for containers and STL streams.

Hannes, please be more constructive and feel free to improve the documentation at places where you think it is necessary.

**Comment by esiragusa** [comment]
:+1:

**Comment by esiragusa** [comment]
@h-2 please ask in the chat instead, probably somebody can help you...

**Comment by h-2** [comment]
@wesse sorry for the rage post, yesterday, maybe it was not adequate.

However I still believe the current situation is not very clear, and obviously I cannot improve the documentation, if I don't understand it myself :expressionless: The reason for using bidirectional  iterators was that it seem the most intuitive choice for writing tests: I write a string to a file, seek back to the beginning and then try to parse it.

Thanks for pointing me to  `demos/tutorial/custom_io/` (is this referenced else where?). So apparently the only thing I did wrong was using Bidirectional, I will try that out later.

**Comment by weese** [comment]
To complete this thread: 

Just like in the STL you would use a single fstream (Bidirectional) or two separate streams (ifstream/ofstream which are Input/Ouput streams). For parsing you instantiate an Input or Output iterator dependent on the direction (via directionIterator() and DirectionIterator<>). Seeking is not necessary in your case as both start from the beginning of a file and some compression streams don't support seeking.

I don't know if demos/tutorial/custom_io wasn't referenced before or if the tutorial went lost in the migration from Trac to ReadTheDocs. However, we should have a nice and crispy tutorial that only explains the parsing layer, i.e. how to parse custom formats with iterators, the readXX/skipXX functions, functors and how a custom high level formatted file could look like.
