### ISSUE TITLE
Move all cpp code blocks from the manual into files

### ISSUE THREAD

**Issue by esiragusa** [seqan/seqan#858]
Many tutorials contain cpp code blocks (directive .. code-block:: cpp) rather than external compilable files (directive .. includefrags:: file.cpp).

Such code blocks are not built in nightly/ci and potentially broken.

See e.g. https://github.com/seqan/seqan/blob/master/manual/source/Tutorial/Indices.rst#assignment-1 or https://github.com/seqan/seqan/blob/master/manual/source/Tutorial/Sequences.rst.

**Comment by rrahn** [comment]
@smehringer Can we close this?

**Comment by smehringer** [comment]
@rrahn Not yet. I was busy otherwise and there are several code snippets that need to be looked at  carefully because they do not resemble an actual function or program. I think Hannes suggested to always  have a "basic.cpp"-file where all snippets are listed in main().

**Comment by rrahn** [comment]
Ah great. Yes, something I also suggest.

**Comment by smehringer** [comment]
Then I'll do that.

**Comment by rrahn** [comment]
Maybe wait with this until next Monday.
We are basically restructuring the layout of the tutorials and the manual page.
We can then discuss the details about this.
