### ISSUE TITLE
Add .gitignore and .gitattributes for app repositories as well

### ISSUE THREAD

**Issue by holtgrewe** [seqan/seqan#860]
It is wonderful that all the apps have gone to their own repository. Here comes the obligatory ungrateful nit-picking. ;)

We should have a standardized `.gitattributes` and `.gitignore` files for each repository. The first ensures that we have normalized line endings (I think we all remember the pain this caused for the seqan/seqan repository). The second makes life easier for whomever updates the app but is less important.

**Comment by esiragusa** [comment]
Should I copy these two files from the seqan repo?

Note that I didn't finish migrating the apps! I copied them in separate repos but they are still in seqan/apps.

**Comment by holtgrewe** [comment]
I think the `.gitattributes` file is fine as it is. I am not sure what exactly to put into the `.gitignore` but the usual backup stuff, e.g.

```
*~
*.sw?
```

**Comment by esiragusa** [comment]
Done.
