### ISSUE TITLE
BAM example does not mention SEQAN_HAS_ZLIB

### ISSUE THREAD

**Issue by pmelsted** [seqan/seqan#871]
When running this example from the http://seqan.readthedocs.org/en/seqan-v2.0.0/Tutorial/SamBamIO.html#accessing-the-header

The program exits with 

    ../include/seqan/basic/basic_exception.h:368 FAILED!  (Uncaught exception of type seqan::UnknownExtensionError: Unknown file extension of example.bam: unspecified iostream_category error)

unless you specify SEQAN_HAS_ZLIB in your build. I just wasted too much time tracking down this bug/mistake. So it would be a good idea to mention this in the doc.

**Comment by rrahn** [comment]
Thank you very much for reporting this. 
I will change it immediately.

Sorry, for the inconvenience.

**Comment by rrahn** [comment]
Fixed by #872.
