### ISSUE TITLE
Impossible to read GFF with comments or directives with GffFileIn (seqan 2.0.0.0)

### ISSUE THREAD

**Issue by CVroland** [seqan/seqan#898]
Trying to read Gff with comment (a line begin with '#' char according to http://www.sequenceontology.org/gff3.shtml) or directives (begin with "##") throws an error : 
```
Unexpected character '\n' found.
```

You can use the Gff_IO demo code (gff_stream_read.cpp) : 
``` c++
#include <seqan/basic.h>
#include <seqan/gff_io.h>

using namespace seqan;

// USAGE: gff_stream_read IN.gff
//
// Read GFF file and print the positions (reference, position) to stdout.

int main(int argc, char ** argv)
{
    if (argc != 2)
    {
        std::cerr << "USAGE: " << argv[0] << " IN.gff\n";
        return 1;
    }

    try
    {
        GffFileIn gffIn(argv[1]);
        GffRecord record;
        while (!atEnd(gffIn))
        {
            readRecord(record, gffIn);

            // Note that we print the position 1-based since we use text output
            // whereas it is 0-based in the GffRecord.
            std::cout << record.ref << "\t" << (record.beginPos + 1) << "\n";
        }
    }
    catch (Exception & e)
    {
        std::cerr << e.what() << std::endl;
        return 1;
    }

    return 0;
}
```

with a GFF3 file with comment (or directive in this case) : 
```
##gff-version 3
ctg123	.	mRNA	1300	9000	.	+	.	ID=mrna0001;Name="sonichedgehog;hehe"
ctg123	.	exon	1300	1500	.	+	.	ID=exon00001;Parent=mrn a0001;Name
ctg123	.	exon	1050	1500	.	+	.	ID=exon00002;Name;Parent=mrna0001
```
I am not sure but I think the problem is in gff_io_base.h in function `readRecord`, at line 354  
``` c++
skipUntil(iter, NotFunctor<OrFunctor<EqualsChar<'#'>, IsWhitespace> >());  //skip commments and empty lines
```

In the case of a comment (or directive), it just skip '#' chars without going to the next line and so the next part of the function try to parse the comment as an GFF entry.

**Comment by xenigmax** [comment]
Thank you for reporting this.
I will take this issue.
The lines starting with “#” will be passed.

And..  I would like to mention two things.

(1)
@CVroland 
Please make sure that all columns are separated by tabs only. Whitespaces are not allowed as delimiters. If it’s the case, you will see “unexpected character \n” again and it’s not a bug.

```
.. Note that unescaped spaces are allowed within fields, meaning that parsers must split on tabs, not spaces… 
```


(2)
@esiragusa 
It seems current implementation assumes valid pair of  “ in attribute columns.
https://github.com/seqan/seqan/blob/master/include/seqan/gff_io/gff_io_base.h#L281-L290

However, it’s not guaranteed by the format definition. 
 it's not a requirement although it looks weird.

```
.. The quotes should be included as part of the value by parsers and not stripped...
```

For example, if we  use chr1 of bovine genome from http://bovinegenome.org/drupal/bovine/sites/genomes.arc.georgetown.edu.drupal.bovine/files/data/dump_gff_data_by_chromosomes/Chr1.gff3
There is a line containing unpaired **“** in the line 4086

Chr1.68	NCBI_transcript	gene	67486	72711	.	-	.	ID=613812_1;Dbxref="NCBI_Gene:NM_001076289.1";**Note="name:RNF168 ring finger protein 1**

It will produce “unexpected character \n” error.
However, I will not touch this now - And I don't think it's a serious problem.

Just for your information.

**Comment by CVroland** [comment]
Thanks a lot.
For whitespaces, github change tab by whitespace in my final comment. My files is well tabulate, I just modify the demo file https://github.com/seqan/seqan/blob/master/tests/gff_io/example.gff by adding `##gff-version 3` at the beginning.
