### ISSUE TITLE
Fix SIMD Vector

### ISSUE THREAD

**Issue by esiragusa** [seqan/seqan#903]
#892 introduced compile errors on platforms which are not under CI - see e.g. http://cdash.seqan.de/viewBuildError.php?buildid=123258 or http://cdash.seqan.de/viewBuildError.php?buildid=123260

@weese do you know what could it be?

**Comment by h-2** [comment]
@marehr  you are the new SIMD-guy, right? ^^

**Comment by rrahn** [comment]
@marehr We can have a look at it together. 
I need this as well for merging the SIMD align code from the master's thesis (see #1338)

**Comment by marehr** [comment]
@rrahn at least one is nice to me :D

**Comment by rrahn** [comment]
Fixed by #1379.
