### ISSUE TITLE
 bool open(file, fileName) (fileFormat): doesn't compile if fileName is a `char*` type

### ISSUE THREAD

**Issue by CVroland** [seqan/seqan#904]
In seqan 2.0.0, the function open(file, fileName) from FormattedFile doesn't compile if fileName  is a `char*` type. It need a `const char*` type. 
however, in seqan 1.4.1 open function for SequenceStream worked fine with a `char*` type.

**Comment by rrahn** [comment]
Fixed by #913 #914
