### ISSUE TITLE
"Custom Score Matrices" tutorial needs updating

### ISSUE THREAD

**Issue by hendrikweisser** [seqan/seqan#909]
The tutorial "Working With Custom Score Matrices" (http://seqan.readthedocs.org/en/master/HowTo/WorkWithCustomScoreMatrices.html#how-to-work-with-custom-score-matrices) still uses the "old" amino acid alphabet (class AminoAcid), from before the alphabet was changed in merge #762.

The current mismatch between the tutorial and the API docs is confusing, so the tutorial should be updated. (Although perhaps you might want to wait until issue #864 gets fixed, so you don't have to update it twice.)

**Comment by esiragusa** [comment]
@hendrikweisser thanks for reporting.
@h-2 could you please do it after #864?

**Comment by esiragusa** [comment]
Fixed in #1211, #1221.
