### ISSUE TITLE
cant join StringSet<DnaString> to another StringSet<DnaString> using AppendValue()

### ISSUE THREAD

**Issue by fari-99** [seqan/seqan#919]
is it appendValue thread safe? 

i'm using OpenMP parallel for sequencing. but i kinda stuck in appendValue for stored my sequence. it's always say "segmentation fault". So i tried to parting my variable for storing into 4 part (ex: spectrumLocal[thread] with thread = 4). but i can't join them using appendValue() (ex: appendValue(spectrumGlobal, spectrumLocal[id]). 

can someone give solution or alternative code? 

thanks.
best regards.

fadhlan.

note: 
i already using appendValue(spectrumGlobal, value), but its critical, so the performance slow down, if not critical then the program will crash because segmentation fault. 

i already use ConcurrentQueue for using it, it's very good, but i cant store the value, btw the value is string not a number (ex: "ACGT").

**Comment by h-2** [comment]
To concatenate two sequences, please use `append()` and not `appendValue()`.

`append()` is used to append a sequence to a sequence
`append()` is used to append a value to a sequence

PS: no types are thread safe ;)

**Comment by fari-99** [comment]
Hey, thanks for replying so fast.

yeah, i tried to use append() for it (like this: append(spectrumGlobal,
spectrumLocal[id_thread])). but i get an error like this.

/usr/include/seqan/sequence/sequence_interface.h|957|error:
no matching function for call to
‘append(seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char,
seqan::Dna_>, seqan::Alloc<> > >&,
seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char,
seqan::Dna_>, seqan::Alloc<> > >&,
seqan::DefaultOverflowImplicit<seqan::StringSet<seqan::String<seqan::SimpleType<unsigned
char, seqan::Dna_>, seqan::Alloc<> > > >::Type)’|

i dont understand with that error. can you help me?

thanks.

best regards.

2015-03-27 15:04 GMT+07:00 Hannes Hauswedell <notifications@github.com>:

**Comment by h-2** [comment]
Hm, that's strange. Can you give me a more complete error log?

**Comment by fari-99** [comment]
i'm sorry maybe i'm making you confusing with my explanation earlier.

so my program looks like this (not exactly like this but i made it simpler
though).

int main()
{
    StringSet<DnaString> pool;
    StringSet<DnaString> sekuens;

    //no parallel
    for(int i = 0; i < 12; i++)
    {
        appendValue(pool, "ACGT");
        appendValue(sekuens, "ACGT");
    }

    //parallel critical
    #pragma omp parallel
    {
        #pragma omp for
        for(int i = 0; i < 12; i++)
        {
            #pragma omp critical
            {
                appendValue(pool, "ACGT");
                appendValue(sekuens, "ACGT");
            }
        }
    }

    //parallel without critical
    StringSet<DnaString> poolLocal[4];
    StringSet<DnaString> sekuensLocal[4];
    int id;
    #pragma omp parallel num_threads(4) private(id)
    {
        id = omp_get_thread_num();
        int subTotal, start, finish;
        subTotal = 3;
        start = id * subTotal;
        finish = (id + 1) * subTotal;

        for(int i = start; i < finish; i++)
        {
            appendValue(poolLocal[id], "ACGT");
            appendValue(sekuensLocal[id], "ACGT");
        }
    }

    for(int j = 0; j < 4; j++)
    {
        /* join the data
        appendValue or append? //the problem is here.
        appendValue(pool3, poolLocal[i]);
        append(pool3,poolLocal[i]);
        //*/
    }

    return 0;
}


i can using critical parallel, but because the overhead waiting thread to
release, the sequential much better. so i tried using with non critical,
but i can't join them in the last. i want the result not like a sequence
(if using append).

thanks

best regards.





2015-03-30 17:54 GMT+07:00 Hannes Hauswedell <notifications@github.com>:

**Comment by h-2** [comment]
I have created a fix in SeqAn, see above. If you cannot wait for it to be merged, you can also locally merge the fix from the branch specified above.

**Comment by fari-99** [comment]
thanks for your fast response hannes, it's help a lot.

thanks again.

best regards.

2015-03-31 17:01 GMT+07:00 Hannes Hauswedell <notifications@github.com>:
