### ISSUE TITLE
ArgumentParser : Error in "arg_parse/tool_doc.h" file

### ISSUE THREAD

**Issue by CVroland** [seqan/seqan#921]
By using the ArgumentParser of seqan 2.0.0, I have got this kind of compilation errors : 
```text
/usr/local/include/seqan/arg_parse/tool_doc.h: In member function ‘void seqan::TextToolDocPrinter_::_printSection(std::ostream&, const seqan::ToolDocSection_&)’:
/usr/local/include/seqan/arg_parse/tool_doc.h:362:80: error: no matching function for call to ‘transform(seqan::IteratorDefaultImp_<const seqan::String<char, seqan::Alloc<> >, const seqan::Tag<seqan::Rooted_> >::Type, seqan::IteratorDefaultImp_<const seqan::String<char, seqan::Alloc<> >, const seqan::Tag<seqan::Rooted_> >::Type, std::ostream_iterator<char>&, <unresolved overloaded function type>)’
         std::transform(begin(section._title), end(section._title), out, toupper);
```
It seems that g++ does not recognized `toupper` in this case.
To solve this, it only need to change `toupper` by `::toupper` at lines 362, 1293 and 1322 and change `tolower` by `::tolower` at line 1295 in the file "arg_parse/tool_doc.h" as it is done in the example given there http://en.cppreference.com/w/cpp/algorithm/transform

**Comment by temehi** [comment]
Thanks @CVroland for your suggestions. Fixed by #940
