### ISSUE TITLE
Removing SeqAn from public headers speeds up compilation

### ISSUE THREAD

**Issue by mr-c** [seqan/seqan#924]
We were able to cut our compile times in half by moving our seqan usage out of public headers by using an [opaque pointer](http://en.wikipedia.org/wiki/Opaque_pointer).

https://github.com/ged-lab/khmer/commit/6a93d766009ba0f3bf7a5c7e58d0c490b3064450

Your other users may benefit from having this technique documented.

**Comment by h-2** [comment]
Hm, maybe we should make a HowTo for this.

**Comment by h-2** [comment]
will be resolved by #1477

**Comment by mr-c** [comment]
Yay!

On Wed, Feb 17, 2016 at 4:08 PM Hannes Hauswedell <notifications@github.com>
wrote:

> will be resolved by #1477 <https://github.com/seqan/seqan/issues/1477>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seqan/seqan/issues/924#issuecomment-185244419>.
>
-- 
Michael R. Crusoe     CWL Community Engineer     crusoe@ucdavis.edu
<mcrusoe@msu.edu>
Common Workflow Language project    University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe
