### ISSUE TITLE
wrong deletion handling in MD tag of mason sam reference output

### ISSUE THREAD

**Issue by frankho** [seqan/seqan#933]
Deletions should be marked with ^ in the MD flag

Here is a example.
The current output is:

    reads/illumina_chr1_100_100_rc_quality_mp.fa.000000033  99      chr1    17675648        255    95M1D5M =       17676556        1008    CGTTGGGGCGAACCAGCCAGCTGCTACCGTGACTTTGCCCTCTTTCTGCTGCTTTCAGTCCTGCCTGGTTCAGTGGCTGTGTCTACTTTGATGCCCAAG    HIHHIHHHHIIIHHGIIIFGIIIIIHIHIFGIGEIDIICFGGFIFIIIHGIICDEIIBIDIHDIIFIIIHHI@FIIIIIEIIIDBIIIIIIIIIHIFIII    NM:i:0 MD:Z:95T5       XE:i:1  XS:i:0  XI:i:0

but it should be:

    reads/illumina_chr1_100_100_rc_quality_mp.fa.000000033  99      chr1    17675648        255    95M1D5M =       17676556        1008    CGTTGGGGCGAACCAGCCAGCTGCTACCGTGACTTTGCCCTCTTTCTGCTGCTTTCAGTCCTGCCTGGTTCAGTGGCTGTGTCTACTTTGATGCCCAAG    HIHHIHHHHIIIHHGIIIFGIIIIIHIHIFGIGEIDIICFGGFIFIIIHGIICDEIIBIDIHDIIFIIIHHI@FIIIIIEIIIDBIIIIIIIIIHIFIII    NM:i:0 MD:Z:95^T5       XE:i:1  XS:i:0  XI:i:0

I observed this behavior in the generation of the SAM reference by mason.

    mason illumina -n 100 -N 100 -sq -mp -o reads/illumina_chr1_100_100_rc_quality_mp.fa fa/chr1.fa

**Comment by holtgrewe** [comment]
@weese I think I am just using your functions here. This is probably affecting core seqan code as well.

I will look at this later however.

**Comment by esiragusa** [comment]
@holtgrewe Hey, the problem is only affecting your own copy (https://github.com/seqan/seqan/blob/master/apps/mason2/mason_simulator.cpp#L1280) of seqan::getMDString() (https://github.com/seqan/seqan/blob/master/include/seqan/bam_io/cigar.h#L174). Would you please have a look at PR #1123, #1124?
