### ISSUE TITLE
seqan-2.0.0: Does not install libs and headers

### ISSUE THREAD

**Issue by mmokrejs** [seqan/seqan#954]
Please help us to find why seqan-2.0.0.ebuild from https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/sci-biology/seqan/ did NOT install header and libs.

Please answer at https://bugs.gentoo.org/show_bug.cgi?id=545154 if possible (or ask Justin Lecher who is more able to poke through the guts of cmake than me).

**Comment by esiragusa** [comment]
I think you need to call cmake with ```-DSEQAN_BUILD_SYSTEM=SEQAN_RELEASE_LIBRARY``` to install *only* the library headers, otherwise it will compile and install *only* the binaries.
See http://seqan.readthedocs.org/en/master/BuildManual/UsingTheSeqAnBuildSystem.html#user-library-installation. Please note that we do not maintain gentoo ebuilds nor have gentoo at hand.

**Comment by mmokrejs** [comment]
I don't understand.

I want "cmake install" to install everything, that is shared binaries, libs, headers, docs. I believe this is a common assumption. Please alter your defaults.

**Comment by h-2** [comment]
> I don't understand.

There are two kinds of people, those that wan't to develop software with SeqAn (*developers*) and those that want to run a SeqAn-based application to gain some knowledge from their data (*users*). Usually this doesn't overlap, so there is no point in providing a default that appeals to no-one, except packagers ;)

In the future the apps will be completely unbundled from the library and maintained in different repos.

**Comment by h-2** [comment]
Also, there are no shared libs and the headers do not interface the apps in anyway, so they really are unrelated from a technical point of view.
Debian packages are also seperate and have been for a long while.

**Comment by h-2** [comment]
Thanks for porting SeqAn to Gentoo and I hope I could convince you that the method used right now make sense for our case.
If you have issues with installing the header library with the above mentioned parameter, please reopen.

**Comment by esiragusa** [comment]
To sum it up, there should be two ebuild packages: seqan-lib and seqan-apps. Right @h-2 ?

**Comment by h-2** [comment]
@esiragusa yes, although I don't know the conventions for naming in gentoo, debian uses -dev for header only packages, but usually that refers to the header package of another app or shared lib package. Like I pointed out before in our case seqan-dev are not the headers for interfacing seqan-apps.

I will use biology/seqan in FreeBSD for the library and biology/seqan-apps for the applications, as "SeqAn" (without suffices) refers to the header library and nothing else.

**Comment by mmokrejs** [comment]
We cannot (I think) call twice cmake to create the makefiles.



Therefore I call cmake in the install() phase which is ugly. Still it does not work because somehow the makefiles write directly into /usr/local/ instead of respecting "${D}" variable (aka  $(DESTDIR) in Makefile itself).

src_prepare() {
    rm -f \
        util/cmake/FindZLIB.cmake \
        || die
    cmake-utils_src_prepare
}

src_configure() {
    local mycmakeargs=(
        -DBoost_NO_BOOST_CMAKE=ON
    )
    cmake-utils_src_configure
}

src_install() {
    cmake -DSEQAN_BUILD_SYSTEM=SEQAN_RELEASE_LIBRARY -DCMAKE_INSTALL_PREFIX="${D}"|| die
    make doc
    make install
    mkdir -p "${BUILD_DIR}"/docs/html || die
    cmake-utils_src_install
    chmod 755 "${ED}"/usr/bin/*sh || die
}


Because makefiles do not respect $(DESTDIR) the make process places files directly into target directory, which is not allowed.

make: *** No rule to make target 'docs'.  Stop.
Install the project...
-- Install configuration: "Release"
 * ACCESS DENIED:  mkdir:        /usr/local/share
CMake Error at cmake_install.cmake:36 (file):
  file cannot create directory: /usr/local/share/doc/seqan.  Maybe need
  administrative privileges.


Makefile:86: recipe for target 'install' failed



I don't have time to study Gentoo cmake eclasses to figure out via what argument or environment values it passes "${D}" down to the cmake call.

**Comment by esiragusa** [comment]
@mmokrejs we suggested you to have two ebuilds...

**Comment by mmokrejs** [comment]
> I will use biology/seqan in FreeBSD for the library and biology/seqan-apps for the applications, as "SeqAn"
> (without suffices) refers to the header library and nothing else.

So where will the headers be? If biology/seqan install libs and headers it is fine. Then seqan-apps is also ok.

> we suggested you to have two ebuilds...
You are right but it should have worked while ugly. I still think the real problem is that you use for example  ${PREFIX}/bin instead of ${DESTDIR}/${PREFIX}/bin , at least in UsingTheSeqAnBuildSystem.html manual.

**Comment by mmokrejs** [comment]
I got a bit further with 

cmake -DSEQAN_BUILD_SYSTEM=SEQAN_RELEASE_LIBRARY -DCMAKE_INSTALL_PREFIX="${D}" || die
make install

but that fails here:

CMake Error at dox/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/mnt/1TB/var/tmp/portage/sci-biology/seqan-2.0.0-r1/work/seqan-seqan-v2.0.0/dox/html".
Call Stack (most recent call first):
  cmake_install.cmake:2642 (include)


Makefile:86: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by h-2** [comment]
> So where will the headers be?

which headers do you mean? The library or the apps' headers?

> If biology/seqan install libs and headers it is fine

Yes, the main seqan build should install anything but the apps, i.e. the header library (no .so!), demos, documentation and tests. If you don't specify the above parameter, you instead get all the apps. You can use this behaviour to make two packages.

**Comment by h-2** [comment]
@mmokrejs you are right, there is a bug in the build procedure for installing the library. I have opened another ticket for it.

**Comment by mmokrejs** [comment]
@h-2: Please also check that 'make doc' or 'make docs' do what they are supposed to do. I think 'make doc' dies elsewhere because there is no 'docs' target defined (or vice versa?). And your HTML install docs to match the reality.

**Comment by esiragusa** [comment]
isn't it ```make dox``` now?

**Comment by h-2** [comment]
> isn't it make dox now?

yes. I think we should stick with ``make docs``, though because thats standard.  And I don't understand why its supposed to be impossible to have cmake call this before installing.
