### ISSUE TITLE
Make install target depends on make dox target (to be run manually)

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#958]
see https://github.com/seqan/seqan/issues/954#issuecomment-93676138

this should be fixed for the next release!

**Comment by h-2** [comment]
- [ ]  ``make docs`` should build the documentation, not ``make dox``
  - [ ]  ``make install`` should include ``make docs`` ``if (${SEQAN_BUILD_SYSTEM} MATCHES "LIBRARY")``

**Comment by temehi** [comment]
I changed the misleading documentation. `make docs` is now changed to `make dox`. 

We can not have `make install` to call dependancies because of an open bug ins cmake (http://public.kitware.com/Bug/view.php?id=8438) and this is documented in seqan.

**Comment by esiragusa** [comment]
Partially fixed in #1095 #1096.

**Comment by h-2** [comment]
fixed in #1316
