### ISSUE TITLE
Using SeqFileOut and WriteRecord for I/O

### ISSUE THREAD

**Issue by fari-99** [seqan/seqan#972]
hello, i just can't get enough demo to using `SeqFileOut` and `WriteRecord`. 
i have the data like this in my StringSet<DnaString> sequence

ACGTTTACT
AGTCTTTAA

and i want the output file ex: file_output.fa

>seq1
ACGTTTACT
>seq2
AGTCTTTA

can you tell me what should i do? should i just `WriteRecord(file, "chr1", sequence)`? 
or looping for WriteRecord?

thanks,
best regards.

**Comment by h-2** [comment]
you can loop over `writeRecord(file, id, sequence)` or call `writeRecords(file, ids, sequences)`. In the second case the function expects stringsets for the ids and sequences.

**Comment by h-2** [comment]
If you still cannot make it work, please re-open with a full code example.
