### ISSUE TITLE
DOX copy button in frame dialog not working.

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#974]
When pressing the copy button one gets redirected to the main page of the dox, and nothing has been copied to the the clipboard.

![screen shot 2015-04-21 at 11 33 23](https://cloud.githubusercontent.com/assets/1529364/7249391/471963da-e81a-11e4-90c6-b404b11b8afa.png)

Browser: Safari Version 8.0.5 (10600.5.17)
OS: Mac OS 10.10.3

**Comment by xenigmax** [comment]
It seems Safari specific bug.
It was not reproduced in Chrome.

**Comment by rrahn** [comment]
Ok I'll have a check later.
