### ISSUE TITLE
unused typedefs and unused variable warnings on c++11

### ISSUE THREAD

**Issue by h-2** [seqan/seqan#985]
gcc5, clang36 and clang37 now default to c++11 resulting in a bunch of warnings.

Unused variable warnings (related to exceptions handling):
http://cdash.seqan.de/viewBuildError.php?type=1&buildid=128257

Unused typedef warnings (realted to concepts):
http://cdash.seqan.de/viewBuildError.php?type=1&buildid=128226

**Comment by esiragusa** [comment]
That's on our yet unsupported FreeBSD builds.

**Comment by h-2** [comment]
Its not related to FreeBSD but to different compiler default behaviour in gcc5 and clang36, please see these up-to-date links:
http://cdash.seqan.de/viewBuildError.php?type=1&buildid=143926
http://cdash.seqan.de/viewBuildError.php?type=1&buildid=143900

**Comment by h-2** [comment]
fixed by #1207

**Comment by esiragusa** [comment]
Hey @h-2 there are a couple of GCC 5.0 warnings left. See here: http://cdash.seqan.de/viewBuildError.php?type=1&buildid=147347

**Comment by h-2** [comment]
@esiragusa those are unrerelated to GCC5 (as you can see they are present on all other compilers on FreeBSD). They stem from deficiencies in FreeBSD's cmath and can't be fixed by us.

clang-3.7 however does still have warnings and errors which are related to OpenMP:
http://cdash.seqan.de/viewBuildError.php?buildid=147329
I will investigate those, although some are simple due to OpenMP being broken with 3.7.0 and SeqAn :(

**Comment by esiragusa** [comment]
Ah sorry I clicked on the wrong line, I thought it was Linux/GCC5 :+1:

**Comment by h-2** [comment]
keep open, because of:

> clang-3.7 however does still have warnings and errors which are related to OpenMP

If I can't get this fixed within the next hour, I will deactivate openmp on clang for now.

**Comment by esiragusa** [comment]
OpenMP deactivated for Clang 3.7.0 in #1219 #1220.
