### ISSUE TITLE
seqan-2.0.0/micro_razers: crash at seqan::end<char, void> (me=...) at seqan-seqan-v2.0.0/include/seqan/sequence/string_alloc.h:299

### ISSUE THREAD

**Issue by mmokrejs** [seqan/seqan#988]
<pre>
$ micro_razers -sL 16  /tmp/query.fasta /tmp/db.fasta
Segmentation fault (core dumped)
$ gdb /usr/bin/micro_razers /var/dumps/core.micro_razers.20226 
GNU gdb (Gentoo 7.9 vanilla) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/micro_razers...done.
[New LWP 20226]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `micro_razers -sL 16 /tmp/query.fasta /tmp/db.fasta'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000005896f9 in seqan::end<char, void> (me=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_alloc.h:299
299     /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_alloc.h: No such file or directory.
(gdb) where
#0  0x00000000005896f9 in seqan::end<char, void> (me=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_alloc.h:299
#1  0x00000000005895c8 in seqan::empty<char, seqan::Alloc<void> > (me=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_base.h:462
#2  0x00000000005adcfe in seqan::AssignString_<seqan::Tag<seqan::TagGenerous_> >::assign_<seqan::String<char, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > const> (target=..., source=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_base.h:985
#3  0x00000000005a1e8b in seqan::assign<char, seqan::Alloc<void>, seqan::String<char, seqan::Alloc<void> >, seqan::TagGenerous_> (target=..., source=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_base.h:1035
#4  0x0000000000593090 in seqan::assign<char, seqan::Alloc<void>, seqan::String<char, seqan::Alloc<void> > > (target=..., source=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_base.h:971
#5  0x000000000058b2c7 in seqan::String<char, seqan::Alloc<void> >::operator= (this=0x7ffe49484a20, source=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_alloc.h:180
#6  0x0000000000575cb4 in main (argc=5, argv=0x7ffe494851e8) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/micro_razers/micro_razers.cpp:323
(gdb) bt full
#0  0x00000000005896f9 in seqan::end<char, void> (me=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_alloc.h:299
No locals.
#1  0x00000000005895c8 in seqan::empty<char, seqan::Alloc<void> > (me=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_base.h:462
No locals.
#2  0x00000000005adcfe in seqan::AssignString_<seqan::Tag<seqan::TagGenerous_> >::assign_<seqan::String<char, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > const> (target=..., source=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_base.h:985
No locals.
#3  0x00000000005a1e8b in seqan::assign<char, seqan::Alloc<void>, seqan::String<char, seqan::Alloc<void> >, seqan::TagGenerous_> (target=..., source=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_base.h:1035
No locals.
#4  0x0000000000593090 in seqan::assign<char, seqan::Alloc<void>, seqan::String<char, seqan::Alloc<void> > > (target=..., source=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_base.h:971
No locals.
#5  0x000000000058b2c7 in seqan::String<char, seqan::Alloc<void> >::operator= (this=0x7ffe49484a20, source=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/sequence/string_alloc.h:180
No locals.
#6  0x0000000000575cb4 in main (argc=5, argv=0x7ffe494851e8) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/micro_razers/micro_razers.cpp:323
        pm_options = {minThreshold = 1, maxWeight = 14, chooseOneGappedOnly = false, chooseUngappedOnly = false, useDefaultShapes = true, totalN = 32, totalK = 2, optionLossRate = 0, chosenLossRate = 0, optionErrorRate = 0.050000000000000003, optionHammingOnly = false, extrapolate = false, extrapolN = 65, 
          extrapolK = 4, maxComputedEditN = 59, maxComputedHammingN = 75, optionProbINSERT = 0, optionProbDELETE = 0, fparams = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, fgparams = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, fnameCount0 = false, fnameCount1 = false, prefixCount = false, 
          fname = {0x6b6353 "", 0x6b6353 ""}, fprefix = {0x6b6353 ""}, paramFolderPath = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, paramFolder = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, shapeFile = 0x6b6353 "", qualityCutoff = 20, solexaQual = true, appendToPrevious = false, 
          verbose = true}
        paramChoosing = true
        genomeFileNames = {strings = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, limits = {data_begin = 0x17391c0, data_end = 0x17391c8, data_capacity = 32}, limitsValid = true, concat = {set = 0x0}}
        readLength = 0
        options = {spec = {<No data fields>}, forward = false, reverse = false, errorRate = 0.080000000000000002, maxHits = 100, distanceRange = 0, purgeAmbiguous = false, output = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, _debugLevel = 0, printVersion = false, hammingOnly = true, trimLength = 0, 
          outputFormat = 0, dumpAlignment = false, genomeNaming = 0, readNaming = 0, sortOrder = 0, positionFormat = 0, runID = 0x6b76d0 "s", shape = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0x1739028 '1' <repeats 11 times>}}, threshold = 1, tabooLength = 1, repeatLength = 1000, abundanceCut = 1, libraryLength = 220, libraryError = 50, nextMatePairId = 1, matchN = false, compMask = "\001\002\004\b", FP = 3749312, TP = 21312, timeCompactMatches = 1.9395040993143974e-319, 
          timeMaskDuplicates = 1.0361307573072619e-317, timeLoadFiles = 1.2731974746779765e-313, timeMapReads = 8.2308965082051636e-318, timeDumpResults = 1.8592204081277782e-317, timeBuildQGramIndex = 1.8592204081277782e-317, microRNA = true, rnaSeedLength = 16, exactSeed = true, lowMemory = false, 
          fastaIdQual = false, minClippedLen = 0, compactThresh = 1024, verifications = {data_begin = 0x0, data_end = 0x0, mapping = {fileSize = 0, file = {<seqan::File<seqan::Sync<void> >> = {_vptr.File = 0x6b9b90 <vtable for seqan::File<seqan::Async<void> >+16>, handle = -1}, handleAsync = -1}, openMode = 3, 
              ownFile = false, temporary = true}, advise = seqan::MAP_NORMAL}, readFile = {stream = {<std::basic_istream<char, std::char_traits<char> >> = {<No data fields>}, file = <incomplete type>, bufferedStream = warning: RTTI symbol not found for class 'seqan::BufferedStream<std::istream, seqan::Tag<seqan::Input_> >'
{<std::basic_istream<char, std::char_traits<char> >> = {<No data fields>}, 
                buf = {<std::basic_streambuf<char, std::char_traits<char> >> = {<No data fields>}, static defaultBufferSize = 1024, static defaultPutbackSize = 256, buffer = {<std::_Vector_base<char, std::allocator<char> >> = {
                      _M_impl = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}, bufferSize = 1024, putbackSize = 256, streamBufPtr = 0x0}}, streamBuf = 0x0, context = 0x0, 
              format = {<seqan::TagSelector<void>> = {tagId = -1}, <No data fields>}}, iter = {streamBuf = 0x0}, 
            format = {<seqan::TagSelector<seqan::TagList<seqan::Tag<seqan::TagFasta_>, seqan::TagList<seqan::Tag<seqan::Embl_>, seqan::TagList<seqan::Tag<seqan::GenBank_>, seqan::TagList<seqan::Tag<seqan::Raw_>, void> > > > >> = {<seqan::TagSelector<seqan::TagList<seqan::Tag<seqan::Embl_>, seqan::TagList<seqan::Tag<seqan::GenBank_>, seqan::TagList<seqan::Tag<seqan::Raw_>, void> > > >> = {<seqan::TagSelector<seqan::TagList<seqan::Tag<seqan::GenBank_>, seqan::TagList<seqan::Tag<seqan::Raw_>, void> > >> = {<seqan::TagSelector<seqan::TagList<seqan::Tag<seqan::Raw_>, void> >> = {<seqan::TagSelector<void>> = {
                        tagId = -1}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, data_context = {buffer = {i = {{data_begin = 0x0, data_end = 0x0, data_capacity = 0}, {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, {data_begin = 0x0, data_end = 0x0, 
                    data_capacity = 0}}}, hybrid = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}}, context = {buffer = {i = {{data_begin = 0x0, data_end = 0x0, data_capacity = 0}, {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, {data_begin = 0x0, data_end = 0x0, data_capacity = 0}}}, hybrid = {
                data_begin = 0x0, data_end = 0x0, data_capacity = 0}}}}
        readFileNames = {strings = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, limits = {data_begin = 0x17392d0, data_end = 0x17392d8, data_capacity = 32}, limitsValid = true, concat = {set = 0x0}}
        result = 0
        seedError = false
        stop = false
        tmp = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}
        success = false
        paramChoosingError = false
        errorPrbFileName = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}
        parser = {shortNameMap = {_M_t = {
              _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {
                  _M_color = std::_S_red, _M_parent = 0x173b280, _M_left = 0x173be90, _M_right = 0x173bdb0}, _M_node_count = 20}}}, longNameMap = {_M_t = {
              _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {
                  _M_color = std::_S_red, _M_parent = 0x173a230, _M_left = 0x173e470, _M_right = 0x17397c0}, _M_node_count = 27}}}, optionMap = {<std::_Vector_base<seqan::ArgParseOption, std::allocator<seqan::ArgParseOption> >> = {
              _M_impl = {<std::allocator<seqan::ArgParseOption>> = {<__gnu_cxx::new_allocator<seqan::ArgParseOption>> = {<No data fields>}, <No data fields>}, _M_start = 0x173c6b0, _M_finish = 0x173ddf0, _M_end_of_storage = 0x173deb0}}, <No data fields>}, 
          argumentList = {<std::_Vector_base<seqan::ArgParseArgument, std::allocator<seqan::ArgParseArgument> >> = {_M_impl = {<std::allocator<seqan::ArgParseArgument>> = {<__gnu_cxx::new_allocator<seqan::ArgParseArgument>> = {<No data fields>}, <No data fields>}, _M_start = 0x173a8e0, _M_finish = 0x173aa30, 
                _M_end_of_storage = 0x173aa30}}, <No data fields>}, _toolDoc = {_name = {data_begin = 0x1739440 "micro_razers", data_end = 0x173944c "", data_capacity = 32}, _shortDescription = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, _date = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, 
            _version = {data_begin = 0x173a010 "1.0.2 [tarball]", data_end = 0x173a01f "", data_capacity = 32}, _manTitle = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, _category = {data_begin = 0x1739d20 "Read Mapping", data_end = 0x1739d2c "", data_capacity = 32}, _manSection = 1, _entries = {
              data_begin = 0x0, data_end = 0x0, data_capacity = 0}}, _description = {<std::_Vector_base<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {
              _M_impl = {<std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<__gnu_cxx::new_allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<No data fields>}, <No data fields>}, _M_start = 0x17393e0, _M_finish = 0x17393f8, 
                _M_end_of_storage = 0x1739400}}, <No data fields>}, _usageText = {<std::_Vector_base<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {
              _M_impl = {<std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<__gnu_cxx::new_allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<No data fields>}, <No data fields>}, _M_start = 0x17394d0, _M_finish = 0x17394d8, 
                _M_end_of_storage = 0x17394d8}}, <No data fields>}}
        res = seqan::ArgumentParser::PARSE_OK
(gdb)
</pre>

**Comment by rrahn** [comment]
is this still a problem?
