### ISSUE TITLE
seqan-2.0.0/stellar: crash at seqan::ClassTest::fail () at seqan-seqan-v2.0.0/include/seqan/basic/debug_test_system.h:1715

### ISSUE THREAD

**Issue by mmokrejs** [seqan/seqan#989]
<pre>
$ stellar -e 0.025 -l 8 -a dna5 -k 4 -vs bandedGlobal /tmp/db.fasta /tmp/query.fasta
I/O options:
  database file   : /tmp/db.fasta
  query file      : /tmp/query.fasta
  alphabet        : dna5
  output file     : stellar.gff
  output format   : gff

User specified parameters:
  minimal match length             : 8
  maximal error rate (epsilon)     : 0.025
  maximal x-drop                   : 5
  k-mer (q-gram) length            : 4
  search forward strand            : yes
  search reverse complement        : yes

  verification strategy            : bandedGlobal
  maximal number of matches        : 50
  duplicate removal every          : 500

Calculated parameters:
  s^min        : 8
  threshold    : 5
  distance cut : 8
  delta        : 16
  overlap      : 0

Loaded 1 query sequence.
Loaded 1 database sequence.

All matches matches resulting from your search have an E-value of: 
        0.272407 or smaller  (match score = 1, error penalty = -2)

Constructing index...

Aligning all query sequences to database sequence...
  rcMINT2_PlugOligo_1_uncleaved_RsaI/var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.h:471 FAILED!  (TODO(bkehr): Adapt to new clipping interface!)

stack trace:
  0          [0x6ff3d9]  seqan::ClassTest::fail() + 0xe
  1          [0x75c28e]  void verifySwiftHit<seqan::Segment<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::InfixSegment>, double, int, unsigned int, double, unsigned int, seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > >(seqan::Segment<seqan::Segment<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::InfixSegment>, seqan::InfixSegment> const&, seqan::Segment<seqan::Segment<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::InfixSegment>, seqan::InfixSegment> const&, double, int, double, unsigned int, unsigned int, unsigned int&, unsigned int, seqan::String<char, seqan::Alloc<void> >&, bool, QueryMatches<StellarMatch<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > > >&, seqan::Tag<VerifyBandedGlobal_>) + 0x405
  2          [0x7400a6]  void stellar<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Dependent<seqan::Tag<seqan::TagInsist_> >, seqan::IndexQGram<seqan::UngappedShape<0u>, seqan::Tag<seqan::OpenAddressing_> >, int, double, unsigned int, bool, seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> >, seqan::Tag<VerifyBandedGlobal_> >(seqan::Finder<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Swift<seqan::Tag<seqan::SwiftLocal_> > >&, seqan::Pattern<seqan::Index<seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Dependent<seqan::Tag<seqan::TagInsist_> > >, seqan::IndexQGram<seqan::UngappedShape<0u>, seqan::Tag<seqan::OpenAddressing_> > >, seqan::Swift<seqan::Tag<seqan::SwiftLocal_> > >&, double, int, double, unsigned int, unsigned int&, unsigned int, bool, seqan::String<char, seqan::Alloc<void> >&, bool, seqan::StringSet<QueryMatches<StellarMatch<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > > >, seqan::Owner<seqan::Tag<seqan::Default_> > >&, seqan::Tag<VerifyBandedGlobal_>) + 0x400
  3          [0x72d255]  bool _stellarOnOne<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> >, seqan::Pattern<seqan::Index<seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Dependent<seqan::Tag<seqan::TagInsist_> > >, seqan::IndexQGram<seqan::UngappedShape<0u>, seqan::Tag<seqan::OpenAddressing_> > >, seqan::Swift<seqan::Tag<seqan::SwiftLocal_> > >, seqan::StringSet<QueryMatches<StellarMatch<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > > >, seqan::Owner<seqan::Tag<seqan::Default_> > > >(seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >&, seqan::String<char, seqan::Alloc<void> >&, seqan::Pattern<seqan::Index<seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Dependent<seqan::Tag<seqan::TagInsist_> > >, seqan::IndexQGram<seqan::UngappedShape<0u>, seqan::Tag<seqan::OpenAddressing_> > >, seqan::Swift<seqan::Tag<seqan::SwiftLocal_> > >&, bool, seqan::StringSet<QueryMatches<StellarMatch<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > > >, seqan::Owner<seqan::Tag<seqan::Default_> > >&, StellarOptions&) + 0x369
  4          [0x721e30]  bool _stellarOnAll<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > >(seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Owner<seqan::Tag<seqan::Default_> > >&, seqan::StringSet<seqan::String<char, seqan::Alloc<void> >, seqan::Owner<seqan::Tag<seqan::Default_> > >&, seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Owner<seqan::Tag<seqan::Default_> > >&, seqan::StringSet<seqan::String<char, seqan::Alloc<void> >, seqan::Owner<seqan::Tag<seqan::Default_> > >&, StellarOptions&) + 0x1e4
  5          [0x71659a]  int mainWithOptions<StellarOptions, seqan::SimpleType<unsigned char, seqan::Dna5_> >(StellarOptions&, seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >) + 0x332
  6          [0x6fe3da]  main + 0x1c1
  7    [0x7ff687768fa0]  __libc_start_main + 0xf0
  8          [0x6f993e]  stellar()

Aborted (core dumped)
$ gdb /usr/bin/stellar /var/dumps/core.stellar.828 
GNU gdb (Gentoo 7.9 vanilla) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/stellar...done.
[New LWP 828]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `stellar -e 0.025 -l 8 -a dna5 -k 4 -vs bandedGlobal /tmp/db.fasta /tmp/query.fa'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007ff68777ca57 in raise () from /lib64/libc.so.6
(gdb) where
#0  0x00007ff68777ca57 in raise () from /lib64/libc.so.6
#1  0x00007ff68777ddea in abort () from /lib64/libc.so.6
#2  0x00000000006ff3de in seqan::ClassTest::fail () at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/basic/debug_test_system.h:1715
#3  0x000000000075c28e in verifySwiftHit<seqan::Segment<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::InfixSegment>, double, int, unsigned int, double, unsigned int, seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > > (infH=..., infV=..., eps=0.025000000000000001, minLength=8, delta=16, disableThresh=4294967295, compactThresh=@0x7ffdb21987a4: 500, numMatches=50, databaseId=..., dbStrand=true, matches=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.h:471
#4  0x00000000007400a6 in stellar<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Dependent<seqan::Tag<seqan::TagInsist_> >, seqan::IndexQGram<seqan::UngappedShape<0u>, seqan::Tag<seqan::OpenAddressing_> >, int, double, unsigned int, bool, seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> >, seqan::Tag<VerifyBandedGlobal_> > (finder=..., pattern=..., epsilon=0.025000000000000001, minLength=8, xDrop=5, disableThresh=4294967295, compactThresh=@0x7ffdb21987a4: 500, numMatches=50, verbose=false, databaseID=..., 
    dbStrand=true, matches=..., tag=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.h:705
#5  0x000000000072d255 in _stellarOnOne<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> >, seqan::Pattern<seqan::Index<seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Dependent<seqan::Tag<seqan::TagInsist_> > >, seqan::IndexQGram<seqan::UngappedShape<0u>, seqan::Tag<seqan::OpenAddressing_> > >, seqan::Swift<seqan::Tag<seqan::SwiftLocal_> > >, seqan::StringSet<QueryMatches<StellarMatch<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > > >, seqan::Owner<seqan::Tag<seqan::Default_> > > > (database=..., databaseID=..., swiftPattern=..., databaseStrand=true, matches=..., options=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.cpp:64
#6  0x0000000000721e30 in _stellarOnAll<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > > (databases=..., databaseIDs=..., queries=..., queryIDs=..., options=...)
    at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.cpp:174
#7  0x000000000071659a in mainWithOptions<StellarOptions, seqan::SimpleType<unsigned char, seqan::Dna5_> > (options=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.cpp:662
#8  0x00000000006fe3da in main (argc=13, argv=0x7ffdb2198a48) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.cpp:694
(gdb) bt full
#0  0x00007ff68777ca57 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ff68777ddea in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00000000006ff3de in seqan::ClassTest::fail () at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/include/seqan/basic/debug_test_system.h:1715
No locals.
#3  0x000000000075c28e in verifySwiftHit<seqan::Segment<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::InfixSegment>, double, int, unsigned int, double, unsigned int, seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > > (infH=..., infV=..., eps=0.025000000000000001, minLength=8, delta=16, disableThresh=4294967295, compactThresh=@0x7ffdb21987a4: 500, numMatches=50, databaseId=..., dbStrand=true, matches=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.h:471
        match = 1
        mismatchIndel = -30
        scoreMatrix = {data_match = 1, data_mismatch = -30, data_gap_extend = -30, data_gap_open = -30}
        upperDiag = 0
        m = {static INVALID_ID = {data_begin = 0x14ae170 '#' <repeats 11 times>, data_end = 0x14ae17b "", data_capacity = 32}, id = {data_begin = 0x14b8bd0 "\340\216K\001", data_end = 0x0, data_capacity = 529}, orientation = 202, begin1 = 2988014064, end1 = 21700408, row1 = {_source = {data_value = 0x7ffdb2197a00, 
              data_state = (unknown: 21728208)}, _array = {data_begin = 0x7ffdb2197a40, data_end = 0x7210ff <seqan::length<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >(seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> > const&)+70>, data_capacity = 6}, 
            _sourceBeginPos = 7475434, _sourceEndPos = 2988014160, _clippingBeginPos = 140727591467920, _clippingEndPos = 140727591467600}, begin2 = 7857170, end2 = 476, row2 = {_source = {data_value = 0x1b6, data_state = (unknown: 21728208)}, _array = {data_begin = 0x7ffdb2197e30, data_end = 0x7ffdb2197a90, 
              data_capacity = 8024576}, _sourceBeginPos = 140727591467684, _sourceEndPos = 140727591468936, _clippingBeginPos = 140727591467696, _clippingEndPos = 7829139}}
        lowerDiag = -16
        align = {data_rows = {data_begin = 0x14bcf50, data_end = 0x14bcfe0, data_capacity = 32}}
        bandedAlign = {data_rows = {data_begin = 0x14bc420, data_end = 0x14bc4b0, data_capacity = 32}}
#4  0x00000000007400a6 in stellar<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Dependent<seqan::Tag<seqan::TagInsist_> >, seqan::IndexQGram<seqan::UngappedShape<0u>, seqan::Tag<seqan::OpenAddressing_> >, int, double, unsigned int, bool, seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> >, seqan::Tag<VerifyBandedGlobal_> > (finder=..., pattern=..., epsilon=0.025000000000000001, minLength=8, xDrop=5, disableThresh=4294967295, compactThresh=@0x7ffdb21987a4: 500, numMatches=50, verbose=false, databaseID=..., 
    dbStrand=true, matches=..., tag=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.h:705
        finderSegment = {data_host = {data_host = 0x14b1fd0, data_begin_position = 0, data_end_position = 30}, data_begin_position = 6, data_end_position = 28}
        patternInfix = {data_host = 0x14b8bd0, data_begin_position = 438, data_end_position = 476}
        patternInfixSeq = {data_host = 0x14b8bd0, data_begin_position = 0, data_end_position = 529}
        finderInfix = {data_host = 0x14b1fd0, data_begin_position = 6, data_end_position = 28}
        finderInfixSeq = {data_host = 0x14b1fd0, data_begin_position = 0, data_end_position = 30}
        patternSeq = @0x14b8bd0: {data_begin = 0x14b8ee0, data_end = 0x14b90f1, data_capacity = 793}
        patternSegment = {data_host = {data_host = 0x14b8bd0, data_begin_position = 0, data_end_position = 529}, data_begin_position = 438, data_end_position = 476}
        numSwiftHits = 1
        maxLength = 22
        totalLength = 22
        it = {<seqan::Iter<unsigned long, seqan::CountingIteratorImpl_<void> >> = {data_position = 21700560}, data_container = 0x0}
        itEnd = {<seqan::Iter<unsigned long, seqan::CountingIteratorImpl_<void> >> = {data_position = 21728208}, data_container = 0x0}
#5  0x000000000072d255 in _stellarOnOne<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> >, seqan::Pattern<seqan::Index<seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Dependent<seqan::Tag<seqan::TagInsist_> > >, seqan::IndexQGram<seqan::UngappedShape<0u>, seqan::Tag<seqan::OpenAddressing_> > >, seqan::Swift<seqan::Tag<seqan::SwiftLocal_> > >, seqan::StringSet<QueryMatches<StellarMatch<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > > >, seqan::Owner<seqan::Tag<seqan::Default_> > > > (database=..., databaseID=..., swiftPattern=..., databaseStrand=true, matches=..., options=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.cpp:64
        swiftFinder = {data_iterator = {data_container = 0x14b1fd0, data_iterator = 0x14b22fb}, haystackEnd = {data_container = 0x14b1fd0, data_iterator = 0x14b22fb}, _needReinit = false, hits = {data_begin = 0x14b8720, data_end = 0x14b8740, data_capacity = 32}, curHit = 0x14b8720, endHit = 0x14b8740, startPos = 0, 
          curPos = 26, endPos = 30, windowStart = 0, dotPos = 100000, dotPos2 = 1000000, data_repeats = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, curRepeat = 0x0, endRepeat = 0x0}
#6  0x0000000000721e30 in _stellarOnAll<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::String<char, seqan::Alloc<void> > > (databases=..., databaseIDs=..., queries=..., queryIDs=..., options=...)
    at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.cpp:174
        i = 0
        qgramIndex = {static defaultAlpha = 1.6000000000000001, text = {data_value = 0x14b1f30, data_state = seqan::Holder<seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Dependent<seqan::Tag<seqan::TagInsist_> > >, seqan::Tag<seqan::Tristate_> >::OWNER}, 
          sa = {data_begin = 0x14b9210, data_end = 0x14bb2f0, data_capacity = 526}, dir = {data_begin = 0x14b6e70, data_end = 0x14b8200, data_capacity = 626}, counts = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, countsDir = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, shape = {span = 4, 
            hValue = 0, XValue = 0, leftFactor = 125, leftFactor2 = 156, leftChar = {value = 0 '\000'}}, cargo = {abundanceCut = 1}, bucketMap = {static EMPTY = 18446744073709551615, qgramCode = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}}, stepSize = 1, alpha = 1.6000000000000001}
        swiftPattern = {shape = {span = 4, hValue = 293, XValue = 0, leftFactor = 125, leftFactor2 = 156, leftChar = {value = 2 '\002'}}, buckets = {data_begin = 0x14bb810, data_end = 0x14bc010, data_capacity = 96}, bucketParams = {data_begin = 0x14bb300, data_end = 0x14bb328, data_capacity = 32}, verifyList = {
            data_begin = 0x14b1d90, data_end = 0x14b1d90, data_capacity = 32}, params = {minThreshold = 1, minLog2Delta = 4, tabooLength = 1, printDots = false, debug = false}, curSeqNo = 0, curBeginPos = 438, curEndPos = 476, finderPosOffset = 0, finderPosNextOffset = 31, finderLength = 31, maxPatternLength = 0, 
          _currentErrorRate = 0.025000000000000001, _currentMinLengthForAll = 8, data_host = {data_value = 0x7ffdb2197e70, 
            data_state = seqan::Holder<seqan::Index<seqan::StringSet<seqan::String<seqan::SimpleType<unsigned char, seqan::Dna5_>, seqan::Alloc<void> >, seqan::Dependent<seqan::Tag<seqan::TagInsist_> > >, seqan::IndexQGram<seqan::UngappedShape<0u>, seqan::Tag<seqan::OpenAddressing_> > >, seqan::Tag<seqan::Tristate_> >::DEPENDENT}}
        matches = {strings = {data_begin = 0x14b8210, data_end = 0x14b8238, data_capacity = 32}, limits = {data_begin = 0x14b1a20, data_end = 0x14b1a30, data_capacity = 32}, limitsValid = false, concat = {set = 0x0}}
#7  0x000000000071659a in mainWithOptions<StellarOptions, seqan::SimpleType<unsigned char, seqan::Dna5_> > (options=...) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.cpp:662
        queryIDs = {strings = {data_begin = 0x14b26a0, data_end = 0x14b26b8, data_capacity = 32}, limits = {data_begin = 0x14b1c80, data_end = 0x14b1c88, data_capacity = 32}, limitsValid = false, concat = {set = 0x0}}
        databaseIDs = {strings = {data_begin = 0x14b2310, data_end = 0x14b2328, data_capacity = 32}, limits = {data_begin = 0x14b2af0, data_end = 0x14b2af8, data_capacity = 32}, limitsValid = false, concat = {set = 0x0}}
        file = <incomplete type>
        startTime = 610448.00948634197
        queries = {strings = {data_begin = 0x14b8bd0, data_end = 0x14b8be8, data_capacity = 32}, limits = {data_begin = 0x14b1b70, data_end = 0x14b1b80, data_capacity = 32}, limitsValid = true, concat = {set = 0x7ffdb21980b0}}
        databases = {strings = {data_begin = 0x14b1fd0, data_end = 0x14b1fe8, data_capacity = 32}, limits = {data_begin = 0x14b29e0, data_end = 0x14b29e8, data_capacity = 32}, limitsValid = false, concat = {set = 0x0}}
#8  0x00000000006fe3da in main (argc=13, argv=0x7ffdb2198a48) at /var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.cpp:694
        scientificNotationNormalizer = {_oldExponentFormat = 0}
        parser = {shortNameMap = {_M_t = {
              _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, 
                  _M_parent = 0x14ae5b0, _M_left = 0x14b0cb0, _M_right = 0x14b0630}, _M_node_count = 19}}}, longNameMap = {_M_t = {
              _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> > >> = {<No data fields>}, <No data fields>}, _M_key_compare = {<std::binary_function<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, 
                  _M_parent = 0x14ae5f0, _M_left = 0x14b0300, _M_right = 0x14b0670}, _M_node_count = 27}}}, optionMap = {<std::_Vector_base<seqan::ArgParseOption, std::allocator<seqan::ArgParseOption> >> = {
              _M_impl = {<std::allocator<seqan::ArgParseOption>> = {<__gnu_cxx::new_allocator<seqan::ArgParseOption>> = {<No data fields>}, <No data fields>}, _M_start = 0x14b35b0, _M_finish = 0x14b4ff0, _M_end_of_storage = 0x14b65b0}}, <No data fields>}, 
          argumentList = {<std::_Vector_base<seqan::ArgParseArgument, std::allocator<seqan::ArgParseArgument> >> = {_M_impl = {<std::allocator<seqan::ArgParseArgument>> = {<__gnu_cxx::new_allocator<seqan::ArgParseArgument>> = {<No data fields>}, <No data fields>}, _M_start = 0x14af6a0, _M_finish = 0x14af7f0, 
                _M_end_of_storage = 0x14af7f0}}, <No data fields>}, _toolDoc = {_name = {data_begin = 0x14ae310 "stellar", data_end = 0x14ae317 "", data_capacity = 32}, _shortDescription = {data_begin = 0x14aeda0 "the SwifT Exact LocaL AligneR", data_end = 0x14aedbd "", data_capacity = 32}, _date = {
              data_begin = 0x0, data_end = 0x0, data_capacity = 0}, _version = {data_begin = 0x14aee00 "1.4.2 [tarball]", data_end = 0x14aee0f "", data_capacity = 32}, _manTitle = {data_begin = 0x0, data_end = 0x0, data_capacity = 0}, _category = {data_begin = 0x14ae8c0 "Local Alignment", data_end = 0x14ae8cf "", 
              data_capacity = 32}, _manSection = 1, _entries = {data_begin = 0x14b1780, data_end = 0x14b1790, data_capacity = 32}}, 
          _description = {<std::_Vector_base<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {
              _M_impl = {<std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<__gnu_cxx::new_allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<No data fields>}, <No data fields>}, _M_start = 0x14aed70, _M_finish = 0x14aed88, 
                _M_end_of_storage = 0x14aed90}}, <No data fields>}, _usageText = {<std::_Vector_base<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {
              _M_impl = {<std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<__gnu_cxx::new_allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<No data fields>}, <No data fields>}, _M_start = 0x14ae3a0, _M_finish = 0x14ae3a8, 
                _M_end_of_storage = 0x14ae3a8}}, <No data fields>}}
        options = {databaseFile = {data_begin = 0x14b19f0 "/tmp/db.fasta", data_end = 0x14b19fd "", data_capacity = 32}, queryFile = {data_begin = 0x14b1710 "/tmp/query.fasta", data_end = 0x14b1720 "", data_capacity = 32}, outputFile = {data_begin = 0x14ae260 "stellar.gff", data_end = 0x14ae26b "", 
            data_capacity = 32}, disabledQueriesFile = {data_begin = 0x14aebc0 "stellar.disabled.fasta", data_end = 0x14aebd6 "", data_capacity = 32}, outputFormat = {data_begin = 0x14aebf0 "gff\001", data_end = 0x14aebf3 "\001", data_capacity = 32}, alphabet = {data_begin = 0x14aec50 "dna5", 
            data_end = 0x14aec54 "", data_capacity = 32}, noRT = false, qGram = 4, epsilon = 0.025000000000000001, minLength = 8, xDrop = 5, forward = true, reverse = true, fastOption = {data_begin = 0x14aed00 "bandedGlobal", data_end = 0x14aed0c "", data_capacity = 32}, disableThresh = 4294967295, 
          compactThresh = 500, numMatches = 50, maxRepeatPeriod = 1, minRepeatLength = 1000, qgramAbundanceCut = 1, verbose = false}
        res = seqan::ArgumentParser::PARSE_OK
(gdb) 
</pre>

**Comment by rrahn** [comment]
Hi, seems there is a default assert when trying to clip alignments:
```
Aligning all query sequences to database sequence...
  rcMINT2_PlugOligo_1_uncleaved_RsaI/var/tmp/portage/sci-biology/seqan-2.0.0/work/seqan-seqan-v2.0.0/apps/stellar/stellar.h:471 FAILED!  (TODO(bkehr): Adapt to new clipping interface!)
```
We will have a look at this.

**Comment by rrahn** [comment]
The banded version is not fully implemented, yet.
Please don't use this option for now. We have to see, if someone can implement this option or what the original purpose of it was.

**Comment by esiragusa** [comment]
@rrahn Is the command line option```-vs bandedGlobal``` unsupported? Shouldn't we hide or disable it then?

**Comment by rrahn** [comment]
Actually I wrote Birte and she said something that we can have a look at it, but if we won't fix it we can disable it safely. She won't be able to fix it in the near feature. 
Maybe we disable it instead.

**Comment by rrahn** [comment]
If this is still a problem, please reopen.
