### ISSUE TITLE
Stellar does not support BLAST output

### ISSUE THREAD

**Issue by mmokrejs** [seqan/seqan#990]
Hi,
  I wanted to use some of the SeqAn apps but I realized that none output anything I could easily parse (except SAM and GFF but they are NOT rich enough for my purpose).

  I use NCBI TOOLS++ blastn's XML output (which is same as the one from legacy NCBI TOOLS), parse it via biopython. I need access to the HSP alignment string.

  Alternatively, I consume a lot EMBOSS' water output, it has it's own plaintext format but I wonder why at least Stellar does not output its plaintext results in something readily compatible with any existing tool. Compatibility with NCBI BLAST XML format would be the best (no matter I agree it is terribly inefficient format). ;-) However, it would be easy then to replace blast with stellar in external applications. Isn't that what you want? ;-)

  Of course, the traditional plaintext output from blast would be another good option. Oh, and definitely the TSV format which blast can output (user can even define which columns will be output and their ordering).

**Comment by mmokrejs** [comment]
Also, blast supports BTOP format output:

              btop means Blast traceback operations (BTOP)

See 'blastn -help' for details and http://www.ncbi.nlm.nih.gov/books/NBK279682/ (search for BTOP).

**Comment by josemduarte** [comment]
+1 for blast-style xml output. 

Note that blast+ is about to change their xml formatting: 

ftp://ftp.ncbi.nlm.nih.gov/blast/documents/NEWXML/xml2.pdf

**Comment by h-2** [comment]
There is a BLAST module currently in review (will be merged within the next weeks) that contains support for writing the default BLAST plaintext format and blast tabular formats (with and without headers). It also contains support for reading tabular formats.
Blast XML support might be added in the future. However it was already a real pain to implement the other formats, since they are not well described and "subject to unannounced and undocumented change" :sob:

**Comment by h-2** [comment]
> (user can even define which columns will be output and their ordering).

This is also supported by the new blast module.

**Comment by rrahn** [comment]
Blast module is now in develop see: #979.
I will keep this issue open, as the original problem might not be solved directly - that is BLAST output format for STELLAR results.

**Comment by h-2** [comment]
@mmokrejs @josemduarte  There is support for Blast Tabular, Blast Tabular with comments and Blast Pairwise formats in SeqAn develop (to be released as SeqAn-2.1.0 in January).

Stellar is currently in maintenance mode which means we are fixing severe issues and tracking SeqAn branches, but we are not adding features. If you would like to see support for the Blast formats, you are very welcome to create a pull request. The Blast Tutorial is very comprehensive:
http://seqan.readthedocs.org/en/develop/Tutorial/BlastIO.html

I have created a new long term feature request for Blast XML and BTOP in #1273.
