### ISSUE TITLE
Segments implement ContainerConcept but should not be resizable.

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan#991]
As far as I can see a segment should not be resizable, right? Which means appendValue and append should not work on an infix as it would lead to a modification of the base sequence, which can be very dangerous if many objects depend on the same base sequence. However, in the documentation it looks like as if those functions are implemented for segments since the SegmentableConcept implements the ContainerConcept.

We need a better concept design for this in the future. 
Although this might be just a documentation error.

**Comment by h-2** [comment]
I would propose modelling our concepts exactly like the stl concepts, with the only difference that we have global functions...

**Comment by esiragusa** [comment]
The STL has only loose concepts for sequential and associative containers (see http://www.cplusplus.com/reference/stl/). Boost has concepts like ours (see http://www.boost.org/doc/libs/1_58_0/libs/concept_check/reference.htm).

**Comment by esiragusa** [comment]
Update: see section 3.1 from http://www.sgi.com/tech/stl/table_of_contents.html

**Comment by h-2** [comment]
http://en.cppreference.com/w/cpp/concept
shows
  * Container
  * SequenceContainer
  * ContiguousContainer
...

**Comment by esiragusa** [comment]
Yeah cplusplus.com is not mentioning concepts :-1:

Those in http://www.sgi.com/tech/stl/table_of_contents.html are like in http://en.cppreference.com/w/cpp/concept.

**Comment by esiragusa** [comment]
The (pre C++11) hierarchy looks like: Container --> (SequenceContainer, AssociativeContainer, ReversibleContainer)
